# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-06-19 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0021_auto_20240313_1147'),
        ('schools', '0146_auto_20231017_1510'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adolescent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('education_status', models.CharField(blank=True, choices=[('', '----------'), ('Never registered in any formal school before', 'Never registered in any formal school before'), ("Was registered in formal school but didn't continue", "Was registered in formal school but didn't continue"), ('Was registered in non formal program and was referred to MSCC', 'Was registered in non formal program and was referred to MSCC'), ("Was registered in non formal program but didn't continue", "Was registered in non formal program but didn't continue"), ('Was enrolled in TVET Programs', 'Was enrolled in TVET Programs'), ('Was Registered in Formal Education but not attending', 'Was Registered in Formal Education but not attending'), ('Currently registered in Formal Education school', 'Currently registered in Formal Education school'), ('Currently registered in Formal Education school but not attending', 'Currently registered in Formal Education school but not attending'), ('No', 'No')], max_length=200, null=True, verbose_name="Child's educational level when registering for the round")),
                ('dropout_date', models.DateField(blank=True, null=True, verbose_name='Please Specify dropout date from school')),
                ('programs', models.CharField(blank=True, choices=[('BLN Level 1', 'BLN Level 1'), ('BLN Level 2', 'BLN Level 2'), ('BLN Level 3', 'BLN Level 3'), ('ABLN Level 1', 'ABLN Level 1'), ('ABLN Level 2', 'ABLN Level 2'), ('YBLN Level 1', 'YBLN Level 1'), ('YBLN Level 2', 'YBLN Level 2'), ('YFS Level 1', 'YFS Level 1'), ('YFS Level 2', 'YFS Level 2'), ('CBECE Level 1', 'CBECE Level 1'), ('CBECE Level 2', 'CBECE Level 2'), ('CBECE Level 3', 'CBECE Level 3'), ('RS Grade 7', 'RS Grade 7'), ('RS Grade 8', 'RS Grade 8'), ('RS Grade 9', 'RS Grade 9'), ('ECD', 'ECD')], max_length=200, null=True, verbose_name='Education Program')),
                ('class_section', models.CharField(blank=True, choices=[('', '----------'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=50, null=True, verbose_name='Class Section')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Date of registration in the round')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Date of completion in the round')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Enrolled Program',
                'verbose_name_plural': 'Enrolled Programs',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('child_outreach', models.IntegerField(blank=True, null=True)),
                ('student_old', models.IntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('adolescent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='adolescent.Adolescent', verbose_name='Child')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Center', verbose_name='Center')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.PartnerOrganization', verbose_name='Partner')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'YOUTH Registration',
                'verbose_name_plural': 'YOUTH Registrations',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('current_year', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Round',
            },
        ),
        migrations.CreateModel(
            name='YouthAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('undertake_post_diagnostic', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent undertake any Post Diagnotic tests?')),
                ('receive_passing_grade', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent receive a passing grade for the tests?')),
                ('complete_life_skills', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent complete the life skills package?')),
                ('participate_volunteering', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent participate in any volunteering opportunity during the course of the program?')),
                ('volunteering_opportunity', models.CharField(blank=True, choices=[('', '----------'), ('Outreach', 'Outreach'), ('Data entry', 'Data entry'), ('Admin work', 'Admin work'), ('Awareness raising sessions', 'Awareness raising sessions'), ('Empowerment and leadership', 'Empowerment and leadership'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Is yes, please specify the volunteering opportunity')),
                ('benefit_innovation_course', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent benefit from any social innovation/entrepreneurship course?')),
                ('compelete_yfs_course', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent complete the YFS course?')),
                ('training_material', models.CharField(blank=True, choices=[('', '----------'), ('Printed workbook', 'Printed workbook'), ('Tablets', 'Tablets'), ('Access to digital content (learning Passport)', 'Access to digital content (learning Passport)'), ('Other', 'Other')], max_length=50, null=True, verbose_name='What training material was provided?')),
                ('future_path', models.CharField(blank=True, choices=[('', '----------'), ('Transition to FE', 'Transition to FE'), ('Repeat the school year', 'Repeat the school year'), ('Refer to a UNICEF Youth Programme (skills tranining, CBT, GIL...)', 'Refer to a UNICEF Youth Programme (skills tranining, CBT, GIL...)'), ('Transition to TVET', 'Transition to TVET'), ('Internship or volunteering opportunity', 'Internship or volunteering opportunity')], max_length=200, null=True, verbose_name='What is the recommended future path for the adolescent?')),
                ('participate_community_initiatives', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent participate/come up in community based initiatives?')),
                ('attendance', models.CharField(blank=True, choices=[('', '----------'), ('Full attendance', 'Full attendance'), ('Absence for less than 5 days', 'Absence for less than 5 days'), ('Absence for more than 5 days', 'Absence for more than 5 days'), ('Dropout', 'Dropout')], max_length=50, null=True, verbose_name='Adolescent attendance')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Registration')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Youth Assessment',
                'verbose_name_plural': 'Youth Assessments',
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Round', verbose_name='Round'),
        ),
        migrations.AddField(
            model_name='enrolledprograms',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_service', to='youth.Registration'),
        ),
        migrations.AddField(
            model_name='enrolledprograms',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Round', verbose_name='Round'),
        ),
    ]
