# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-06-26 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0002_auto_20240625_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Program',
            },
        ),
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='youth.Program')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Sub Program',
            },
        ),
        migrations.RemoveField(
            model_name='enrolledprograms',
            name='programs',
        ),
        migrations.AlterField(
            model_name='enrolledprograms',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of completion'),
        ),
        migrations.AlterField(
            model_name='enrolledprograms',
            name='education_status',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Never registered in any formal school before', 'Never registered in any formal school before'), ("Was registered in formal school but didn't continue", "Was registered in formal school but didn't continue"), ('Was registered in non formal program and was referred to MSCC', 'Was registered in non formal program and was referred to MSCC'), ("Was registered in non formal program but didn't continue", "Was registered in non formal program but didn't continue"), ('Was enrolled in TVET Programs', 'Was enrolled in TVET Programs'), ('Was Registered in Formal Education but not attending', 'Was Registered in Formal Education but not attending'), ('Currently registered in Formal Education school', 'Currently registered in Formal Education school'), ('Currently registered in Formal Education school but not attending', 'Currently registered in Formal Education school but not attending'), ('No', 'No')], max_length=200, null=True, verbose_name="Child's educational level when registering"),
        ),
        migrations.AlterField(
            model_name='enrolledprograms',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of registration'),
        ),
        migrations.AddField(
            model_name='enrolledprograms',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Program'),
        ),
        migrations.AddField(
            model_name='enrolledprograms',
            name='sub_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.SubProgram'),
        ),
    ]
