# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0004_auto_20240628_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Donor',
            },
        ),
        migrations.AddField(
            model_name='enrolledprograms',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Donor'),
        ),
    ]
