# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-09 16:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0006_auto_20240701_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocalPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of Focal Point')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Focal Point Phone Number')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Focal Point Email')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Funded By')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Full Name')),
                ('short_name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Short Name')),
                ('monitoring_evaluation_focal_point_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Monitoring and Evaluation Focal Point Name')),
                ('monitoring_evaluation_focal_point_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Monitoring and Evaluation Focal Point Phone')),
                ('monitoring_evaluation_focal_point_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Monitoring and Evaluation Focal Point Email')),
                ('program_manager_focal_point_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Program Manager Focal Point Name')),
                ('program_manager_focal_point_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Program Manager Focal Point Phone')),
                ('program_manager_focal_point_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Program Manager Focal Point Email')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Plan')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PopulationGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Population Groups')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Project Type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sector')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='programdocument',
            options={'ordering': ['project_name'], 'verbose_name': 'Program Document'},
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='name',
        ),
        migrations.AddField(
            model_name='program',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='budget',
            field=models.FloatField(blank=True, null=True, verbose_name='Please add the Project Budget in USD'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='cash_assistance',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Does this Project have any Cash Assistance Component'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='governorates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Governorate of Coverage'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='implementing_partners',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Support of Public Institution'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='number_targeted_lebanese',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Targeted Lebanese'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='number_targeted_prl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Targeted PRL'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='number_targeted_prs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Targeted PRS'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='number_targeted_syrians',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Targeted Displaced Syrians'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='population_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Population Groups Targeted'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='programs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Population Groups Targeted'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='project_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Code'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='project_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='project_status',
            field=models.CharField(blank=True, choices=[('', '----------'), ('on going', 'On going'), ('closed', 'No')], max_length=100, null=True, verbose_name='Project Status'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='focal_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.FocalPoint', verbose_name='Focal Point'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='funded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.FundedBy', verbose_name='Funded By'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Partner', verbose_name='Organization Name'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Plan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.ProjectType', verbose_name='Type of Project'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='sectors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Sector', verbose_name='SELECT SECTORS TARGETED BY THIS PROJECT'),
        ),
    ]
