# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-10 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_auto_20240313_1147'),
        ('youth', '0007_auto_20240709_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdocument',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='governorates',
        ),
        migrations.AddField(
            model_name='programdocument',
            name='governorates',
            field=models.ManyToManyField(blank=True, to='locations.Location', verbose_name='Governorate of Coverage'),
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='population_groups',
        ),
        migrations.AddField(
            model_name='programdocument',
            name='population_groups',
            field=models.ManyToManyField(blank=True, to='youth.PopulationGroups', verbose_name='Population Groups Targeted'),
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='programs',
        ),
        migrations.AddField(
            model_name='programdocument',
            name='programs',
            field=models.ManyToManyField(blank=True, to='youth.Program', verbose_name='Programs'),
        ),
    ]
