# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-17 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0011_auto_20240711_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdocument',
            name='public_institution_support',
            field=models.CharField(blank=True, choices=[('', '----------'), ('No Support', 'No Support'), ('Support', 'Support')], max_length=100, null=True, verbose_name='Support of Public Institution'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='implementing_partners',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Key Implementing Partner(s)'),
        ),
    ]
