# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-22 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0012_auto_20240717_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='masterprogram',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='population_groups',
            field=models.ManyToManyField(blank=True, to='youth.PopulationGroups', verbose_name='Population Groups Targeted'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
