# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-25 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0013_auto_20240722_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprogram',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='masterprogram',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
