# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0014_auto_20240725_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterprogram',
            options={'ordering': ['name'], 'verbose_name': 'Master Program'},
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='governorates',
            field=models.ManyToManyField(blank=True, related_name='_programdocument_governorates_+', to='locations.Location', verbose_name='Governorate of Coverage'),
        ),
    ]
