# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-25 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0015_auto_20240725_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprogram',
            name='number',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='project_code',
            field=models.CharField(default='project_code', max_length=100, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='project_name',
            field=models.CharField(default='project_name', max_length=100, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='number',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
