# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-11-06 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0017_programdocument_donors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdocument',
            name='project_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='project_name',
            field=models.CharField(default='project_name', max_length=250, verbose_name='Project Name'),
        ),
    ]
