# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-11-07 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0020_auto_20241107_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprogram',
            name='program_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.ProgramTag', verbose_name='Program Tag'),
        ),
        migrations.AlterField(
            model_name='masterprogram',
            name='program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.ProgramType', verbose_name='Program Type'),
        ),
    ]
