# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-12-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0021_auto_20241107_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdocument',
            name='baseline1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='baseline2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='baseline3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='master_program1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_program1', to='youth.MasterProgram', verbose_name='Master Program 1'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='master_program2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_program2', to='youth.MasterProgram', verbose_name='Master Program 2'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='master_program3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_program3', to='youth.MasterProgram', verbose_name='Master Program 3'),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='target1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='target2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programdocument',
            name='target3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
