# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-06-03 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0022_auto_20241205_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDocumentIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('baseline', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('master_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_indicator', to='youth.MasterProgram', verbose_name='Master Indicator')),
                ('program_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='youth.ProgramDocument')),
            ],
            options={
                'verbose_name': 'Indicator',
                'ordering': ['master_indicator'],
            },
        ),
    ]
