# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-06-04 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0023_programdocumentindicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programdocument',
            name='baseline1',
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='baseline2',
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='baseline3',
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='master_program1',
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='master_program2',
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='master_program3',
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='master_programs',
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='target1',
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='target2',
        ),
        migrations.RemoveField(
            model_name='programdocument',
            name='target3',
        ),
    ]
