# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-06-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0025_auto_20250610_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.AlterField(
            model_name='registration',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.PartnerOrganization', verbose_name='Partner'),
        ),
    ]
