# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-06-25 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0027_programdocumentindicator_sub_indicator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programdocumentindicator',
            old_name='Sub_indicator',
            new_name='sub_indicator',
        ),
    ]
