# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-07-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0028_auto_20250625_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprogram',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
