# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-08-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0029_auto_20250710_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledprograms',
            name='education_status',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Never registered in any formal school before', 'Never registered in any formal school before'), ("Was registered in formal school but didn't continue", "Was registered in formal school but didn't continue"), ('Was registered in non formal program and was referred to MSCC', 'Was registered in non formal program and was referred to MSCC'), ("Was registered in non formal program but didn't continue", "Was registered in non formal program but didn't continue"), ('Was enrolled in TVET Programs', 'Was enrolled in TVET Programs'), ('Was Registered in Formal Education but not attending', 'Was Registered in Formal Education but not attending'), ('Currently registered in Formal Education school', 'Currently registered in Formal Education school'), ('Currently registered in Formal Education school but not attending', 'Currently registered in Formal Education school but not attending'), ('Completed university degree', 'Completed university degree'), ('No', 'No')], max_length=200, null=True, verbose_name="Child's educational level when registering"),
        ),
    ]
