# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-09-02 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0026_auto_20250701_1656'),
        ('youth', '0030_auto_20250801_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledprograms',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='Cadaster'),
        ),
        migrations.AddField(
            model_name='enrolledprograms',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='enrolledprograms',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='Governorate'),
        ),
        migrations.AddField(
            model_name='enrolledprograms',
            name='same_location',
            field=models.BooleanField(default=True),
        ),
    ]
