# -*- coding: utf-8 -*-
# Generated by ChatGPT
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0030_auto_20250801_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledprograms',
            name='same_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enrolledprograms',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, related_name='+', to='locations.Location', verbose_name='Governorate'),
        ),
        migrations.AddField(
            model_name='enrolledprograms',
            name='district',
            field=models.ForeignKey(blank=True, null=True, related_name='+', to='locations.Location', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='enrolledprograms',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, related_name='+', to='locations.Location', verbose_name='Cadaster'),
        ),
    ]
