# Generated by Django 5.2.3 on 2025-09-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescent', '0006_alter_adolescent_cadaster_and_more'),
        ('locations', '0027_alter_activityinfolocation_level_and_more'),
        ('schools', '0159_alter_alpassignmentmatrix_level_and_more'),
        ('youth', '0031_auto_20250902_1147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='enrolledprograms',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Cadaster'),
        ),
        migrations.AlterField(
            model_name='enrolledprograms',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='enrolledprograms',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.donor'),
        ),
        migrations.AlterField(
            model_name='enrolledprograms',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='enrolledprograms',
            name='master_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.masterprogram'),
        ),
        migrations.AlterField(
            model_name='enrolledprograms',
            name='program_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.programdocument'),
        ),
        migrations.AlterField(
            model_name='enrolledprograms',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_programs', to='youth.registration'),
        ),
        migrations.AlterField(
            model_name='enrolledprograms',
            name='sub_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.subprogram'),
        ),
        migrations.AlterField(
            model_name='fundedby',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='masterprogram',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='masterprogram',
            name='program_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.programtag', verbose_name='Program Tag'),
        ),
        migrations.AlterField(
            model_name='masterprogram',
            name='program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.programtype', verbose_name='Program Type'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='focal_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.focalpoint', verbose_name='UNICEF Focal Point'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='funded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.fundedby', verbose_name='Funded By'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='governorates',
            field=models.ManyToManyField(blank=True, related_name='+', to='locations.location', verbose_name='Governorate of Coverage'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.partnerorganization', verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.plan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='project_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.projectstatus', verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.projecttype', verbose_name='Type of Project'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='sectors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.sector', verbose_name='SELECT SECTORS TARGETED BY THIS PROJECT'),
        ),
        migrations.AlterField(
            model_name='programdocumentindicator',
            name='master_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_indicator', to='youth.masterprogram', verbose_name='Master Indicator'),
        ),
        migrations.AlterField(
            model_name='programdocumentindicator',
            name='program_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='youth.programdocument'),
        ),
        migrations.AlterField(
            model_name='programdocumentindicator',
            name='sub_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_indicator', to='youth.subprogram', verbose_name='Sub Indicator'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='adolescent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='adolescent.adolescent', verbose_name='adolescent'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.center', verbose_name='Center'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.round', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='current_year',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='sector',
            name='default',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='master_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_program', to='youth.masterprogram'),
        ),
        migrations.AlterField(
            model_name='youthassessment',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.registration'),
        ),
    ]
