# Generated by Django 5.2.3 on 2025-09-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0032_alter_donor_active_alter_enrolledprograms_cadaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('current_year', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
            },
        ),
        migrations.AddField(
            model_name='programdocument',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.year', verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='registration',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='youth.year', verbose_name='Year'),
        ),
    ]
