# Generated by Django 5.2.3 on 2025-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0034_alter_programdocument_unique_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdocument',
            name='project_code',
            field=models.CharField(max_length=100, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='project_name',
            field=models.CharField(max_length=250, verbose_name='Project Name'),
        ),
    ]
