# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45L)),
                ('p_code', models.CharField(blank=True, max_length=32L, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
