# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-20 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20160820_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mother_firstname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_lastname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
