# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20160820_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
