# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_classlevel_educationlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100L, unique=True)),
            ],
        ),
    ]
