# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
<<<<<<< HEAD
            field=models.CharField(blank=True, max_length=45L, null=True),
=======
            field=models.CharField(blank=True, max_length=45, null=True),
>>>>>>> 3b9073c012bcdfc49afcb1d105deb56123ab5be1
        ),
    ]
