# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20160518_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='number',
            field=models.CharField(default='', max_length=45L, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=555L),
        ),
    ]
