# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20160920_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='code',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
