# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20160520_1429'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='location',
            name='point',
        ),
    ]
