# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_nationality_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
