# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20160531_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='', max_length=225L),
            preserve_default=False,
        ),
    ]
