# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(blank=True, max_length=45L),
        ),
    ]
