# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20161020_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
