# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_phone_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idtype',
            options={'ordering': ['id']},
        ),
    ]
