# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20161027_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='old_id_number',
<<<<<<< HEAD
            field=models.CharField(blank=True, max_length=45L, null=True),
=======
            field=models.CharField(blank=True, max_length=45, null=True),
>>>>>>> 3b9073c012bcdfc49afcb1d105deb56123ab5be1
        ),
        migrations.AddField(
            model_name='student',
            name='old_id_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
