# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20160607_1631'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.School'),
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Location'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number',
            field=models.CharField(max_length=45L, unique=True),
        ),
    ]
