# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-05 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20161113_2338'),
        ('students', '0017_auto_20161115_1824'),
    ]

    operations = [
    ]
