# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20161115_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashing',
            name='number',
            field=models.CharField(blank=True, max_length=45L, null=True, unique=True),
        ),
    ]
