# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-30 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student')),
            ],
        ),
    ]
