# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-30 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_studentmatching'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number_part1',
<<<<<<< HEAD
            field=models.CharField(blank=True, max_length=45L, null=True),
=======
            field=models.CharField(blank=True, max_length=45, null=True),
>>>>>>> 3b9073c012bcdfc49afcb1d105deb56123ab5be1
        ),
        migrations.AddField(
            model_name='student',
            name='number_part2',
<<<<<<< HEAD
            field=models.CharField(blank=True, max_length=45L, null=True),
=======
            field=models.CharField(blank=True, max_length=45, null=True),
>>>>>>> 3b9073c012bcdfc49afcb1d105deb56123ab5be1
        ),
    ]
