# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-30 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_studentmatching'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number_part1',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='number_part2',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
