# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20160803_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationlevel',
            name='school',
        ),
    ]
