# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_idtype_inuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_number_duplicate',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
