# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0030_auto_20160817_2243'),
        ('students', '0022_auto_20160812_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassLevel',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='school',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='section',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='EducationLevel',
        ),
        migrations.DeleteModel(
            name='Governorate',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='location',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='location',
            name='parent',
        ),
        migrations.DeleteModel(
            name='PartnerOrganization',
        ),
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationType',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
