# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_student_id_number_duplicate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_number_duplicate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='old_id_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='old_id_type',
        ),
        migrations.AddField(
            model_name='student',
            name='registered_in_unhcr',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True),
        ),
    ]
