# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-22 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_student_id_number_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hh_barcode',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
