# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_auto_20170820_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labour',
            options={'ordering': ['id'], 'verbose_name': 'Labour'},
        ),
    ]
