# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-15 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_auto_20170915_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='family_status',
            field=models.CharField(blank=True, choices=[('married', '\u0645\u062a\u0632\u0648\u062c'), ('engaged', '\u0645\u0631\u062a\u0628\u0637'), ('divorced', '\u0645\u0637\u0644\u0642'), ('widower', '\u0627\u0631\u0645\u0644\u0629'), ('single', '\u0627\u0639\u0632\u0628')], max_length=50, null=True),
        ),
    ]
