# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-19 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0036_auto_20171018_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mother_fullname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0623\u0645 \u0648\u0634\u0647\u0631\u062a\u0647\u0627 '),
        ),
    ]
