# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-11 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0037_auto_20171019_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_prefix',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u0631\u0645\u0632 \u0631\u0642\u0645 \u0627\u0644\u0647\u0627\u062a\u0641 '),
        ),
    ]
