# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-19 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0026_auto_20171201_1705'),
        ('students', '0042_auto_20171201_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_on', models.CharField(blank=True, max_length=500, null=True)),
                ('pertinence', models.CharField(blank=True, max_length=1, null=True)),
                ('program_type', models.CharField(blank=True, max_length=100, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='outreach.Child')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student')),
            ],
        ),
    ]
