# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_crossmatching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossmatching',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched', to='students.Student'),
        ),
    ]
