# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student_registration.students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_student_std_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Financialsupport_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Financial Support Number'),
        ),
        # migrations.AddField(
        #     model_name='student',
        #     name='id_image',
        #     field=models.ImageField(blank=True, help_text='Identification picture', null=True, upload_to='profiles/ids', validators=[student_registration.students.models.validate_file_size]),
        # ),
        migrations.AddField(
            model_name='student',
            name='is_financialsupport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_justified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_specialneeds',
            field=models.BooleanField(default=False),
        ),
        # migrations.AlterField(
        #     model_name='student',
        #     name='std_image',
        #     field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='profiles', validators=[student_registration.students.models.validate_file_size], verbose_name='Profile Picture'),
        # ),
        migrations.AddField(
            model_name='student',
            name='financialsupport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financialsupport', to='students.FinancialSupport', verbose_name='Financial Support Program'),
        ),
        migrations.AddField(
            model_name='student',
            name='specialneeds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialneeds', to='students.SpecialNeeds', verbose_name='Types Special Needs'),
        ),
    ]
