# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_auto_20190912_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialNeedsDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('specialneeds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.SpecialNeeds', verbose_name='Detail Special Needs')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='specialneedsdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.SpecialNeedsDt', verbose_name='Details Special Needs'),
        ),
    ]
