# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-18 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import student_registration.students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0046_auto_20190912_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthdoc_image',
            field=models.ImageField(blank=True, help_text='Birth Document', null=True, upload_to='profiles/birthdoc', validators=[student_registration.students.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='student',
            name='unhcr_family',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='UNHCR Family Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='unhcr_image',
            field=models.ImageField(blank=True, help_text='UNHCR picture', null=True, upload_to='profiles/unhcr', validators=[student_registration.students.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='student',
            name='unhcr_personal',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='UNHCR Personal Number'),
        ),
    ]
