# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-17 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0051_auto_20191008_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='financialsupport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financialsupport', to='students.FinancialSupport', verbose_name='\u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0645\u0627\u0644\u064a'),
        ),
    ]
