# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-20 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student_registration.students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0052_auto_20200117_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth_DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Documents Type',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdoc_image',
            field=models.ImageField(blank=True, help_text='\u0648\u062b\u064a\u0642\u0629 \u0627\u0644\u0645\u064a\u0644\u0627\u062f', null=True, upload_to='profiles/birthdoc', validators=[student_registration.students.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_documenttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documenttype', to='students.Birth_DocumentType', verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u062e\u0627\u0635\u0629 \u0628\u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
    ]
