# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-03 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0053_auto_20200120_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_justified',
        ),
    ]
