# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0055_merge_20200320_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mother_fullname',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0623\u0645 \u0648 \u0634\u0647\u0631\u062a\u0647\u0627'),
        ),
    ]
