# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-17 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0062_auto_20220817_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='trainings',
            field=models.ManyToManyField(blank=True, null=True, related_name='_teacher_trainings_+', to='students.Training', verbose_name='Topics of teacher training'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_provided',
            field=models.CharField(blank=True, choices=[('arabic', '\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('math', '\u0627\u0644\u0631\u064a\u0627\u0636\u064a\u0627\u062a'), ('english', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629'), ('french', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629')], max_length=100, null=True, verbose_name='Subject provided'),
        ),
    ]
