# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0064_auto_20220817_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='trainings',
            field=models.ManyToManyField(blank=True, to='students.Training'),
        ),
    ]
