# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0066_auto_20220817_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Attachment Type',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_file_1',
            field=models.FileField(blank=True, null=True, upload_to='teacher_attachments', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_short_description_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Attachment Description'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_type_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.AttachmentType', verbose_name='Type'),
        ),
    ]
