# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0067_auto_20220819_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='attach_file_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='attach_short_description_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
