# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-19 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0068_auto_20220819_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='attach_file_2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/teacher', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_file_3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/teacher', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_file_4',
            field=models.FileField(blank=True, null=True, upload_to='uploads/teacher', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_file_5',
            field=models.FileField(blank=True, null=True, upload_to='uploads/teacher', verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_short_description_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_short_description_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_short_description_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_short_description_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='attach_type_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attach_type_1', to='students.AttachmentType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_type_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attach_type_2', to='students.AttachmentType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_type_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attach_type_3', to='students.AttachmentType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_type_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attach_type_4', to='students.AttachmentType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='attach_type_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attach_type_5', to='students.AttachmentType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='attach_file_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/teacher', verbose_name='Attachment'),
        ),
    ]
