# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-31 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0073_auto_20230331_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_assignment',
            field=models.CharField(blank=True, choices=[('full_time', 'Full time'), ('part_time_mix_private', 'Part time, Mix private'), ('part_time_sbp_only', 'Part time, SBP only')], max_length=100, null=True, verbose_name='Teacher Assignment'),
        ),
    ]
