# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0076_auto_20230428_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school_pss_counsellor',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Is the teacher considered as a school counsellor/PSS counsellor'),
        ),
    ]
