# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-09 16:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0077_teacher_school_pss_counsellor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school_pss_counsellor',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects_provided',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('arabic', 'Arabic'), ('math', 'Math'), ('english', 'English'), ('french', 'French'), ('PSS / Counsellor', 'PSS / Counsellor')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Subjects provided'),
        ),
    ]
