# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-01-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0080_auto_20230809_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unicef_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='unicef_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
