# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-02-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0082_auto_20250210_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='name_en',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
