# Generated by Django 5.2.3 on 2025-09-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0043_delete_outreachyear_alter_child_household_and_more'),
        ('schools', '0159_alter_alpassignmentmatrix_id_and_more'),
        ('students', '0087_auto_20250626_1644'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmenttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='birth_documenttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financialsupport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='idtype',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='idtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialneeds',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialneedsdt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialneedsdt',
            name='specialneeds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.specialneeds', verbose_name='Detail Special Needs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_documenttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenttype', to='students.birth_documenttype', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='financialsupport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financialsupport', to='students.financialsupport', verbose_name='Financial Support Program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.idtype', verbose_name='ID type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Mother nationality'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='student',
            name='outreach_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outreach.child'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialneeds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialneeds', to='students.specialneeds', verbose_name='Types Special Needs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialneedsdt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.specialneedsdt', verbose_name='Details Special Needs'),
        ),
        migrations.AlterField(
            model_name='studentmatching',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='attach_type_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attach_type_1', to='students.attachmenttype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='attach_type_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attach_type_2', to='students.attachmenttype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='attach_type_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attach_type_3', to='students.attachmenttype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='attach_type_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attach_type_4', to='students.attachmenttype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='attach_type_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attach_type_5', to='students.attachmenttype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.idtype', verbose_name='ID type'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mother_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Mother nationality'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clmround', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='training',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
