# Generated by Django 5.2.3 on 2026-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0088_alter_idtype_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unicef_id_backup',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Unicef ID Backup'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='unicef_id_backup',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Unicef ID Backup'),
        ),
    ]
