version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=student_registration

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
      args:
        - REQUIREMENTS_FILE=local.txt
    command: ./compose/django/start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=student_registration
      - DATABASE_URL=postgres://student_registration:postgres@postgres:5432/student_registration
      - USE_DOCKER=yes
    volumes:
      - .:/code
      - .:/home/LogFiles
    ports:
      - "8000:8000"


  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
      args:
        - REQUIREMENTS_FILE=local.txt
    command: ./compose/django/start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=student_registration
      - DATABASE_URL=postgres://student_registration:postgres@postgres:5432/student_registration
    volumes:
      - .:/code
      - .:/home/LogFiles



