version: "3.9"

x-domain-name: &domain_name compiler.uniceflebanon.org
x-certbot-email: &certbot_email jcranwellward@unicef.org

volumes:
  postgres_data:
  postgres_backup:

services:
  postgres:
    build: ./compose/postgres
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /gunicorn.sh
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    build: ./compose/nginx
    depends_on:
      django:
        condition: service_started
      certbot:
        condition: service_completed_successfully
    environment:
      MY_DOMAIN_NAME: *domain_name
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot:latest
    command: >-
      bash -c "sleep 6 &&
      certbot certonly -n --standalone -d ${DOMAIN_NAME:-*domain_name}
      --staging --agree-tos --email ${CERTBOT_EMAIL:-*certbot_email}
      --rsa-key-size 4096 --keep-until-expiring --preferred-challenges http-01"
    entrypoint: ""
    environment:
      DOMAIN_NAME: *domain_name
      CERTBOT_EMAIL: *certbot_email
      TERM: xterm
    ports:
      - "80"
      - "443"
    restart: on-failure
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: celery -A student_registration.taskapp worker -l INFO
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    restart: unless-stopped

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: celery -A student_registration.taskapp beat -l INFO
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    restart: unless-stopped
