version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    extends:
      file: local.yml
      service: postgres

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
      args:
        - REQUIREMENTS_FILE=test.txt
    image: app
    command: ./runtests.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=student_registration
      - DATABASE_URL=postgres://student_registration:postgres@postgres:5432/student_registration
      - USE_DOCKER=yes


