# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-20 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0035_auto_20180215_1432'),
        ('backends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('general', 'General'), ('helpdesk', 'Helpdesk')], max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('comments', models.TextField(blank=True, max_length=500, null=True)),
                ('ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School')),
                ('schools', models.ManyToManyField(blank=True, to='schools.School')),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
