# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
