# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0003_auto_20180326_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='school_type',
            field=models.CharField(blank=True, choices=[('2ndshift', '2nd-shift'), ('ALP', 'ALP')], max_length=50, null=True),
        ),
    ]
