# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-03-04 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backends', '0005_exporter_exported_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('export_type', models.CharField(blank=True, choices=[('', '----------'), ('Makani List', 'Makani List'), ('Makani Center', 'Makani Center'), ('Makani Teacher', 'Makani Teacher'), ('Makani Attendance', 'Makani Attendance')], max_length=100, null=True, verbose_name='Export Type')),
                ('partner_name', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='First name')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name_plural': 'Export History',
                'ordering': ['id'],
                'verbose_name': 'Export History',
            },
        ),
    ]
