# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-03-04 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0007_auto_20250304_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporthistory',
            name='partner_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Partner name'),
        ),
    ]
