# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-04-08 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0008_auto_20250304_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporthistory',
            name='export_type',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Makani List', 'Makani List'), ('Makani Raw Attendance', 'Makani Raw Attendance'), ('Makani Total Attendance', 'Makani Total Attendance'), ('Center List', 'Center List'), ('Bridging Absence Raw Data', 'Bridging Absence Raw Data'), ('Bridging Attendance Total', 'Bridging Attendance Total'), ('Bridging Absence Consecutive', 'Bridging Absence Consecutive'), ('Teacher List', 'Teacher List'), ('Bridging List', 'Bridging List'), ('School List - Bridging', 'School List - Bridging'), ('School List', 'School List')], max_length=100, null=True, verbose_name='Export Type'),
        ),
    ]
