# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-05-14 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0010_merge_20250506_1339'),
        ('backends', '0010_useractivity'),
    ]

    operations = [
    ]
