# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-07-01 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0011_merge_20250514_1937'),
        ('backends', '0012_adolescentupload_failed_file'),
    ]

    operations = [
    ]
