# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-07-02 14:07
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0013_merge_20250701_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescentupload',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='adolescentupload',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
