# Generated by Django 5.2.3 on 2025-09-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0016_useractivity_path_text'),
        ('schools', '0158_auto_20250820_1259'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exporthistory',
            options={'ordering': ['-created'], 'verbose_name': 'Export History', 'verbose_name_plural': 'Export History'},
        ),
        migrations.AlterField(
            model_name='adolescentupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
        migrations.AlterField(
            model_name='exporter',
            name='exported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Exported by'),
        ),
        migrations.AlterField(
            model_name='exporthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
