# Generated by Django 5.2.7 on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0017_alter_exporthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='method',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='username',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['username', '-timestamp'], name='user_activity_user_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['method', '-timestamp'], name='user_activity_method_ts_idx'),
        ),
    ]
