# Generated by Django 5.2.7 on 2025-10-09 13:13

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backends", "0017_alter_exporthistory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=120, unique=True)),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("sql_view", models.CharField(max_length=200)),
                ("value_column", models.CharField(max_length=120)),
                (
                    "allowed_breakdowns",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "allowed_filters",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        size=None,
                    ),
                ),
                ("default_time_column", models.CharField(max_length=50)),
                ("unit", models.CharField(default="count", max_length=50)),
                (
                    "decimals",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "min_sample_size",
                    models.IntegerField(
                        default=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("rounding", models.IntegerField(default=5)),
                ("owner_team", models.CharField(default="T4D/Unknown", max_length=120)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "freshness_sla_minutes",
                    models.IntegerField(
                        default=60,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sql_view"], name="backends_me_sql_vie_d1f7b2_idx"
                    ),
                    models.Index(
                        fields=["owner_team"], name="backends_me_owner_t_a31957_idx"
                    ),
                ],
            },
        ),
    ]
