# Generated by Django 5.2.7 on 2026-10-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("figures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiguresRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "targets",
                    models.JSONField(help_text="[[programme, year or null], ...]"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("requested_by", models.CharField(blank=True, max_length=150)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "counted",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[[programme, year, seconds], ...]",
                    ),
                ),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-requested_at",),
            },
        ),
    ]
