# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0002_jobs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffenroll',
            name='current_hourrate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hour Rate'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(default=' ', max_length=45, unique=True, verbose_name='Job description'),
        ),
    ]
