# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-28 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0003_auto_20190902_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['id'], 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['id'], 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='jobs',
            name='hourrate',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0642\u064a\u0645\u0629 \u0627\u0644\u062d\u0635\u0629'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(default=' ', max_length=45, unique=True, verbose_name='\u0648\u0635\u0641 \u0627\u0644\u0645\u0634\u0643\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='current_hourrate',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0642\u064a\u0645\u0629 \u0627\u0644\u062d\u0635\u0629'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffenroll.Jobs', verbose_name='\u0627\u0644\u0648\u0638\u064a\u0641\u0629'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staffenroll.Subjects', verbose_name='\u0627\u0644\u0645\u0627\u062f\u0629'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='weeklyhours',
            field=models.IntegerField(default=0, verbose_name='\u0639\u062f\u062f \u0627\u0644\u0633\u0627\u0639\u0627\u062a \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639'),
        ),
    ]
