# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-23 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0007_jobs_maxhoursperweek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffenroll',
            name='first_education_year',
        ),
        migrations.AddField(
            model_name='staffenroll',
            name='school_ispublic',
            field=models.BooleanField(default=False, verbose_name='is public'),
        ),
        migrations.AddField(
            model_name='staffenroll',
            name='shift',
            field=models.CharField(blank=True, choices=[('D', 'Day'), ('N', 'Night')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='staffenroll',
            name='work',
            field=models.CharField(blank=True, max_length=150, verbose_name='main work'),
        ),
    ]
