# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0008_auto_20191223_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffenroll',
            name='school_ismain',
            field=models.BooleanField(default=True, verbose_name='is public'),
        ),
    ]
