# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-05 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0009_staffenroll_school_ismain'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salarytype',
            field=models.CharField(blank=True, choices=[('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, null=True),
        ),
    ]
