# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-06 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0046_auto_20200106_0051'),
        ('staffs', '0016_auto_20191227_0102'),
        ('staffenroll', '0011_auto_20200106_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffattend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attenddate', models.DateField()),
                ('attendhours', models.IntegerField()),
                ('isattend', models.BooleanField(default=False)),
                ('attendremarks', models.CharField(blank=True, max_length=200, null=True)),
                ('education_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear', verbose_name='\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062f\u0631\u0627\u0633\u064a\u0629')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salarytype',
            field=models.CharField(blank=True, choices=[('H', 'Hourly'), ('D', 'Daily')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='staffattend',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staffenroll.Jobs', verbose_name='Job Type'),
        ),
        migrations.AddField(
            model_name='staffattend',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='\u0627\u0644\u0645\u062f\u0631\u0633\u0629'),
        ),
        migrations.AddField(
            model_name='staffattend',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staffs.Staffs', verbose_name='Staff'),
        ),
    ]
