# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-06 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0012_auto_20200106_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffattend',
            old_name='jobs',
            new_name='job',
        ),
    ]
