# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0014_auto_20200106_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattend',
            name='attendhours',
            field=models.IntegerField(default=0),
        ),
    ]
