# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-06 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0015_auto_20200106_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
