# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-07 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0016_jobs_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='with_additionalhour',
            field=models.BooleanField(default=False, verbose_name='with Hours no class'),
        ),
        migrations.AddField(
            model_name='staffenroll',
            name='weeklyhours_noclass',
            field=models.IntegerField(default=0, verbose_name='Weekly Nb of hours no class'),
        ),
    ]
