# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-11 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0046_auto_20200106_0051'),
        ('staffenroll', '0017_auto_20200107_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffenroll',
            name='school_am',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='\u0627\u0644\u0645\u062f\u0631\u0633\u0629'),
        ),
    ]
