# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-04-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import student_registration.staffenroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0020_auto_20200412_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffenroll',
            name='image',
            field=models.ImageField(blank=True, help_text='Form 5', null=True, upload_to='profiles', validators=[student_registration.staffenroll.models.validate_file_size], verbose_name='Form 5'),
        ),
        migrations.AddField(
            model_name='staffenroll',
            name='pic_commitment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Picture of the commitment'),
        ),
    ]
