# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-03 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0021_auto_20200428_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salarytype',
            field=models.CharField(blank=True, choices=[('H', 'Hourly'), ('D', '\u064a\u0648\u0645\u064a\u0627\u064b')], max_length=1, null=True),
        ),
    ]
