# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0022_auto_20200803_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salarytype',
            field=models.CharField(blank=True, choices=[('H', 'Hourly'), ('D', '\u064a\u0648\u0645\u064a\u064b\u0651\u0627')], max_length=1, null=True),
        ),
    ]
