# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-06 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffenroll', '0023_auto_20210212_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='hourrate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hour Rate'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(default=' ', max_length=45, unique=True, verbose_name='Job description'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salarytype',
            field=models.CharField(blank=True, choices=[('H', 'Hourly'), ('D', 'Daily')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='staffattend',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='staffattend',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staffenroll.Jobs', verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='staffattend',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='staffattend',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staffs.Staffs', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='Current Class'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='current_hourrate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hour Rate'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffenroll.Jobs', verbose_name='Jobs'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='schools.School', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='school_am',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section', verbose_name='Current Section'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='shift',
            field=models.CharField(blank=True, choices=[('D', 'Day'), ('N', 'Night')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staffenroll.Subjects', verbose_name='Subjects'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='weeklyhours',
            field=models.IntegerField(default=0, verbose_name='Weekly Nb of hours'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='weeklyhours_noclass',
            field=models.IntegerField(default=0, verbose_name='Weekly Nb of hours no class'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='work',
            field=models.CharField(blank=True, max_length=150, verbose_name='main work'),
        ),
        migrations.AlterField(
            model_name='statisticattend',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='statisticattend',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='statisticattend',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='School'),
        ),
    ]
