# Generated by Django 5.2.3 on 2025-09-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0159_alter_alpassignmentmatrix_level_and_more'),
        ('staffenroll', '0024_auto_20221206_1532'),
        ('staffs', '0027_alter_participantyear_staff_alter_staffs_bank_base1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffenroll',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='jobs',
            name='is_teacher',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='with_additionalhour',
            field=models.BooleanField(blank=True, default=False, verbose_name='with Hours no class'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='with_date_interval',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='staffattend',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationyear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='staffattend',
            name='isattend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='staffattend',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staffenroll.jobs', verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='staffattend',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='staffattend',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staffs.staffs', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classroom', verbose_name='Current Class'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationyear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, verbose_name='main record'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffenroll.jobs', verbose_name='Jobs'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school', to='schools.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='school_am',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='school_ismain',
            field=models.BooleanField(blank=True, default=True, verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='school_ispublic',
            field=models.BooleanField(blank=True, default=False, verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.section', verbose_name='Current Section'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_enrollment', to='staffs.staffs'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staffenroll.subjects', verbose_name='Subjects'),
        ),
        migrations.AlterField(
            model_name='staffenroll',
            name='worklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffenroll.worklist', verbose_name='List of work'),
        ),
        migrations.AlterField(
            model_name='statisticattend',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationyear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='statisticattend',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='statisticattend',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school', verbose_name='School'),
        ),
    ]
