# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-23 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=45, unique=True)),
                ('registration_status', models.CharField(blank=True, choices=[('registered', 'Registered'), ('recorded', 'Recorded'), ('unregistered', 'Unregistered')], max_length=45, null=True)),
                ('location_type', models.CharField(blank=True, choices=[('cs', 'CS'), ('is', 'IS')], max_length=45, null=True)),
                ('governorate', models.CharField(max_length=45)),
                ('district', models.CharField(max_length=45)),
                ('cadastral', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('total_children', models.IntegerField(max_length=5)),
                ('card_distributed', models.CharField(blank=True, choices=[('distributed', 'Distributed'), ('not_distributed', 'Not Distributed')], max_length=45, null=True)),
                ('card_loaded', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=45, null=True)),
            ],
            options={
                'ordering': ['case_number'],
                'verbose_name_plural': 'Beneficiaries',
            },
        ),
    ]
