# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-25 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='card_distributed',
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('Distributed', 'Distributed'), ('Not Distributed', 'Not Distributed')], max_length=45L, null=True),
=======
            field=models.CharField(blank=True, choices=[('Distributed', 'Distributed'), ('Not Distributed', 'Not Distributed')], max_length=45, null=True),
>>>>>>> 3b9073c012bcdfc49afcb1d105deb56123ab5be1
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='card_loaded',
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=45L, null=True),
=======
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=45, null=True),
>>>>>>> 3b9073c012bcdfc49afcb1d105deb56123ab5be1
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='location_type',
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('CS', 'CS'), ('IS', 'IS')], max_length=45L, null=True),
=======
            field=models.CharField(blank=True, choices=[('CS', 'CS'), ('IS', 'IS')], max_length=45, null=True),
>>>>>>> 3b9073c012bcdfc49afcb1d105deb56123ab5be1
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='registration_status',
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Recorded', 'Recorded'), ('Unregistered', 'Unregistered')], max_length=45L, null=True),
=======
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Recorded', 'Recorded'), ('Unregistered', 'Unregistered')], max_length=45, null=True),
>>>>>>> 3b9073c012bcdfc49afcb1d105deb56123ab5be1
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='total_children',
            field=models.IntegerField(),
        ),
    ]
