# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-06 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0002_auto_20170125_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='id',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='case_number',
<<<<<<< HEAD
            field=models.CharField(max_length=45L, primary_key=True, serialize=False, unique=True),
=======
            field=models.CharField(max_length=45, primary_key=True, serialize=False, unique=True),
>>>>>>> 3b9073c012bcdfc49afcb1d105deb56123ab5be1
        ),
    ]
