# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 15:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0003_auto_20170206_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('_id', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('_rev', models.CharField(blank=True, max_length=45, null=True)),
                ('assistance_type', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('barcode_num', models.CharField(blank=True, max_length=45, null=True)),
                ('channels', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('child_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.CharField(blank=True, max_length=45, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=45, null=True)),
                ('criticality', models.CharField(blank=True, max_length=45, null=True)),
                ('disabilities', models.CharField(blank=True, max_length=45, null=True)),
                ('dob', models.CharField(blank=True, max_length=45, null=True)),
                ('family_count', models.CharField(blank=True, max_length=45, null=True)),
                ('family_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('family_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('history', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id_type', models.CharField(blank=True, max_length=45, null=True)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('location_distribution', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=45, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('moving_location', models.CharField(blank=True, max_length=45, null=True)),
                ('new_cadastral', models.CharField(blank=True, max_length=45, null=True)),
                ('new_district', models.CharField(blank=True, max_length=45, null=True)),
                ('official_id', models.CharField(blank=True, max_length=45, null=True)),
                ('over18', models.CharField(blank=True, max_length=45, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_owner', models.CharField(blank=True, max_length=45, null=True)),
                ('principal_applicant', models.CharField(blank=True, max_length=45, null=True)),
                ('relationship_type', models.CharField(blank=True, max_length=45, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('registration_status', models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Recorded', 'Recorded'), ('Unregistered', 'Unregistered')], max_length=45, null=True)),
                ('location_type', models.CharField(blank=True, max_length=45, null=True)),
                ('governorate', models.CharField(blank=True, max_length=45, null=True)),
                ('district', models.CharField(blank=True, max_length=45, null=True)),
                ('cadastral', models.CharField(blank=True, max_length=45, null=True)),
                ('latitude', models.CharField(blank=True, max_length=45, null=True)),
                ('longitude', models.CharField(blank=True, max_length=45, null=True)),
                ('p_code', models.CharField(blank=True, max_length=45, null=True)),
                ('p_code_name', models.CharField(blank=True, max_length=45, null=True)),
                ('site_type', models.CharField(blank=True, max_length=45, null=True)),
                ('total_children', models.IntegerField(blank=True, null=True)),
                ('card_distributed', models.CharField(blank=True, choices=[('Distributed', 'Distributed'), ('Not Distributed', 'Not Distributed')], max_length=45, null=True)),
                ('card_loaded', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=45, null=True)),
            ],
            options={
                'ordering': ['id_type'],
                'verbose_name_plural': 'Assessments',
            },
        ),
    ]
