# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-06 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0004_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='_0_to_3_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_10_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_11_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_12_months_kit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_12_months_kit_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_12_years_kit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_12_years_kit_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_12_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_13_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_14_years_kit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_14_years_kit_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_14_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_1_year_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_2_years_kit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_2_years_kit_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_2_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_3_months_kit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_3_months_kit_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_3_to_12_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_3_years_kit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_3_years_kit_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_3_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_4_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_5_years_kit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_5_years_kit_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_5_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_6_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_7_years_kit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_7_years_kit_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_7_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_8_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_9_years_kit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_9_years_kit_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='_9_years_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='male',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
