# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0005_auto_20171031_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='barcode',
            new_name='barcode_num',
        ),
    ]
