# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-12 12:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0005_auto_20171106_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
