# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0006_auto_20171031_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
