# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0007_beneficiary__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='id_type',
            field=models.CharField(default=None, max_length=45, primary_key=True, unique=True),
            preserve_default=False,
        ),
    ]
