# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0009_auto_20171031_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='total_children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
