# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0012_auto_20171031_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='_id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='id_type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
