# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0013_auto_20171031_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='location_type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
