# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 10:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0014_auto_20171031_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='assistance_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
