# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 10:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0016_auto_20171031_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='assistance_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=45), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
