# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0018_auto_20171031_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='assistance_type',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='channels',
        ),
    ]
