# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 11:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winterization', '0019_auto_20171031_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='assistance_type',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='channels',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
