# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 15:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0003_auto_20170828_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bln',
            name='referral',
            field=models.ManyToManyField(blank=True, related_name='_bln_referral_+', to='clm.Referral'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referral',
            field=models.ManyToManyField(blank=True, related_name='_cbece_referral_+', to='clm.Referral'),
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='referral_reasons',
        ),
        migrations.AddField(
            model_name='cbece',
            name='referral_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('academic', 'Academic'), ('absence', 'Absence')], max_length=100, null=True), blank=True, null=True, size=None),
        ),
    ]
