# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0005_auto_20170829_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='assessment',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
