# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0006_auto_20170908_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['name']},
        ),
    ]
