# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0007_auto_20170908_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['order']},
        ),
    ]
