# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0008_auto_20170908_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['form_order']},
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='order',
            new_name='form_order',
        ),
        migrations.AddField(
            model_name='assessment',
            name='test_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
