# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 08:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_auto_20171009_1542'),
        ('clm', '0008_selfperceptiongrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='rs',
            name='registered_in_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School'),
        ),
        migrations.AddField(
            model_name='rs',
            name='type',
            field=models.CharField(blank=True, choices=[('homework_support', 'Homework Support'), ('remedial_support', 'Remedial Support')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bln',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('weather', '\u0627\u0644\u0637\u0642\u0633'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='bln',
            name='have_labour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', '\u0643\u0644\u0627'), ('yes_morning', '\u0646\u0639\u0645 - \u0642\u0628\u0644 \u0627\u0644\u0638\u0647\u0631'), ('yes_afternoon', '\u0646\u0639\u0645 - \u0628\u0639\u062f \u0627\u0644\u0638\u0647\u0631')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='bln',
            name='labours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', '\u0627\u0644\u0632\u0631\u0627\u0639\u0629'), ('building', '\u0627\u0644\u0628\u0646\u0627\u0621'), ('manufacturing', '\u0627\u0644\u062a\u0635\u0646\u064a\u0639'), ('retail_store', '\u0627\u0644\u0628\u064a\u0639 \u0628\u0627\u0644\u0645\u0641\u0631\u0642 / \u0645\u062d\u0644'), ('begging', '\u062a\u0633\u0648\u0644'), ('other_many_other', '\u063a\u064a\u0631 \u0630\u0644\u0643 (\u0641\u0646\u062f\u0642\u060c \u0645\u0637\u0639\u0645\u060c \u0646\u0642\u0644\u060c \u062e\u062f\u0645\u0627\u062a \u0634\u062e\u0635\u064a\u0629 \u0645\u062b\u0644 \u0627\u0644\u062a\u0646\u0638\u064a\u0641\u060c \u0627\u0644\u0639\u0646\u0627\u064a\u0629 \u0628\u0627\u0644\u0634\u0639\u0631\u060c \u0627\u0644\u0637\u0628\u062e \u0648\u0627\u0644\u0625\u0639\u062a\u0646\u0627\u0621 \u0628\u0627\u0644\u0623\u0637\u0641\u0627\u0644)'), ('other', '\u0622\u062e\u0631')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='bln',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('english_arabic', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('french_arabic', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='bln',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('graduated_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('graduated_to_formal_kg', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0631\u0648\u0636\u0629'), ('graduated_to_formal_level1', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0635\u0641 \u0627\u0644\u0623\u0648\u0644'), ('referred_to_another_program', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0622\u062e\u0631 \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0631\u0627\u0633\u0629')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bln',
            name='participation',
            field=models.CharField(blank=True, choices=[('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_15days', '\u0623\u0643\u062b\u0631 \u0645\u0646 15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referral',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('from_same_ngo', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0627\u0644\u062c\u0645\u0639\u064a\u0629 \u0630\u0627\u062a\u0647\u0627'), ('from_other_ngo', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u063a\u064a\u0631\u062c\u0645\u0639\u064a\u0629'), ('form_official_reference', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0645\u0631\u062c\u0639 \u0631\u0633\u0645\u064a (\u0645\u062e\u062a\u0627\u0631\u060c \u0628\u0644\u062f\u064a\u0629\u060c \u0645\u062f\u064a\u0631 \u0645\u062f\u0631\u0633\u0629\u060c \u0625\u0644\u062e ..)'), ('from_host_community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0627\u0644\u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0645\u0636\u064a\u0641'), ('from_displaced_community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0646\u0627\u0632\u062d\u064a\u0646')], max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('weather', '\u0627\u0644\u0637\u0642\u0633'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='have_labour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', '\u0643\u0644\u0627'), ('yes_morning', '\u0646\u0639\u0645 - \u0642\u0628\u0644 \u0627\u0644\u0638\u0647\u0631'), ('yes_afternoon', '\u0646\u0639\u0645 - \u0628\u0639\u062f \u0627\u0644\u0638\u0647\u0631')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='labours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', '\u0627\u0644\u0632\u0631\u0627\u0639\u0629'), ('building', '\u0627\u0644\u0628\u0646\u0627\u0621'), ('manufacturing', '\u0627\u0644\u062a\u0635\u0646\u064a\u0639'), ('retail_store', '\u0627\u0644\u0628\u064a\u0639 \u0628\u0627\u0644\u0645\u0641\u0631\u0642 / \u0645\u062d\u0644'), ('begging', '\u062a\u0633\u0648\u0644'), ('other_many_other', '\u063a\u064a\u0631 \u0630\u0644\u0643 (\u0641\u0646\u062f\u0642\u060c \u0645\u0637\u0639\u0645\u060c \u0646\u0642\u0644\u060c \u062e\u062f\u0645\u0627\u062a \u0634\u062e\u0635\u064a\u0629 \u0645\u062b\u0644 \u0627\u0644\u062a\u0646\u0638\u064a\u0641\u060c \u0627\u0644\u0639\u0646\u0627\u064a\u0629 \u0628\u0627\u0644\u0634\u0639\u0631\u060c \u0627\u0644\u0637\u0628\u062e \u0648\u0627\u0644\u0625\u0639\u062a\u0646\u0627\u0621 \u0628\u0627\u0644\u0623\u0637\u0641\u0627\u0644)'), ('other', '\u0622\u062e\u0631')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('english_arabic', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('french_arabic', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('graduated_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('graduated_to_formal_kg', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0631\u0648\u0636\u0629'), ('graduated_to_formal_level1', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0635\u0641 \u0627\u0644\u0623\u0648\u0644'), ('referred_to_another_program', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0622\u062e\u0631 \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0631\u0627\u0633\u0629')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='participation',
            field=models.CharField(blank=True, choices=[('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_15days', '\u0623\u0643\u062b\u0631 \u0645\u0646 15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referral',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('from_same_ngo', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0627\u0644\u062c\u0645\u0639\u064a\u0629 \u0630\u0627\u062a\u0647\u0627'), ('from_other_ngo', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u063a\u064a\u0631\u062c\u0645\u0639\u064a\u0629'), ('form_official_reference', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0645\u0631\u062c\u0639 \u0631\u0633\u0645\u064a (\u0645\u062e\u062a\u0627\u0631\u060c \u0628\u0644\u062f\u064a\u0629\u060c \u0645\u062f\u064a\u0631 \u0645\u062f\u0631\u0633\u0629\u060c \u0625\u0644\u062e ..)'), ('from_host_community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0627\u0644\u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0645\u0636\u064a\u0641'), ('from_displaced_community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0646\u0627\u0632\u062d\u064a\u0646')], max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='site',
            field=models.CharField(blank=True, choices=[('in_school', 'Inside the school'), ('out_school', 'Outside the school')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rs',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('weather', '\u0627\u0644\u0637\u0642\u0633'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rs',
            name='have_labour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', '\u0643\u0644\u0627'), ('yes_morning', '\u0646\u0639\u0645 - \u0642\u0628\u0644 \u0627\u0644\u0638\u0647\u0631'), ('yes_afternoon', '\u0646\u0639\u0645 - \u0628\u0639\u062f \u0627\u0644\u0638\u0647\u0631')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rs',
            name='labours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', '\u0627\u0644\u0632\u0631\u0627\u0639\u0629'), ('building', '\u0627\u0644\u0628\u0646\u0627\u0621'), ('manufacturing', '\u0627\u0644\u062a\u0635\u0646\u064a\u0639'), ('retail_store', '\u0627\u0644\u0628\u064a\u0639 \u0628\u0627\u0644\u0645\u0641\u0631\u0642 / \u0645\u062d\u0644'), ('begging', '\u062a\u0633\u0648\u0644'), ('other_many_other', '\u063a\u064a\u0631 \u0630\u0644\u0643 (\u0641\u0646\u062f\u0642\u060c \u0645\u0637\u0639\u0645\u060c \u0646\u0642\u0644\u060c \u062e\u062f\u0645\u0627\u062a \u0634\u062e\u0635\u064a\u0629 \u0645\u062b\u0644 \u0627\u0644\u062a\u0646\u0638\u064a\u0641\u060c \u0627\u0644\u0639\u0646\u0627\u064a\u0629 \u0628\u0627\u0644\u0634\u0639\u0631\u060c \u0627\u0644\u0637\u0628\u062e \u0648\u0627\u0644\u0625\u0639\u062a\u0646\u0627\u0621 \u0628\u0627\u0644\u0623\u0637\u0641\u0627\u0644)'), ('other', '\u0622\u062e\u0631')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rs',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('english_arabic', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('french_arabic', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rs',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('graduated_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('graduated_to_formal_kg', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0631\u0648\u0636\u0629'), ('graduated_to_formal_level1', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0635\u0641 \u0627\u0644\u0623\u0648\u0644'), ('referred_to_another_program', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0622\u062e\u0631 \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0631\u0627\u0633\u0629')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rs',
            name='participation',
            field=models.CharField(blank=True, choices=[('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_15days', '\u0623\u0643\u062b\u0631 \u0645\u0646 15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rs',
            name='site',
            field=models.CharField(blank=True, choices=[('in_school', 'Inside the school'), ('out_school', 'Outside the school')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selfperceptiongrades',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.RS'),
        ),
    ]
