# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0009_auto_20170908_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['test_order']},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='form_order',
        ),
    ]
