# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0010_auto_20171018_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbece',
            name='child_muac',
            field=models.CharField(blank=True, choices=[('1', '<11.5 \u0633\u0645 (\u0633\u0648\u0621 \u0627\u0644\u062a\u063a\u0630\u064a\u0629 \u0627\u0644\u062d\u0627\u062f)'), ('2', '<12.5 \u0633\u0645 (\u0633\u0648\u0621 \u0627\u0644\u062a\u063a\u0630\u064a\u0629 \u0627\u0644\u0645\u0639\u062a\u062f\u0644)')], max_length=50, null=True),
        ),
    ]
