# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-19 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0013_auto_20171018_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bln',
            options={'ordering': ['id'], 'verbose_name': 'BLN', 'verbose_name_plural': 'BLN'},
        ),
        migrations.AlterModelOptions(
            name='cbece',
            options={'ordering': ['id'], 'verbose_name': 'CB-ECE', 'verbose_name_plural': 'CB-ECE'},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['name'], 'verbose_name': 'Program cycle', 'verbose_name_plural': 'Program cycles'},
        ),
        migrations.AlterModelOptions(
            name='disability',
            options={'ordering': ['name'], 'verbose_name': 'Disability', 'verbose_name_plural': 'Disabilities'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['name'], 'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AlterModelOptions(
            name='rs',
            options={'ordering': ['id'], 'verbose_name': 'RS', 'verbose_name_plural': 'RS'},
        ),
        migrations.AlterModelOptions(
            name='selfperceptiongrades',
            options={'ordering': ['id'], 'verbose_name': 'Child perception grade', 'verbose_name_plural': 'Child perception grades'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name'], 'verbose_name': 'Program site', 'verbose_name_plural': 'Program sites'},
        ),
    ]
