# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-19 07:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0014_auto_20171019_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbece',
            name='referral_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('academic', '\u0623\u0643\u0627\u062f\u064a\u0645\u064a'), ('absence', '\u063a\u064a\u0627\u0628')], max_length=100, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_arabic',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_language',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_math',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_science',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_arabic',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_language',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_math',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_science',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rs',
            name='type',
            field=models.CharField(blank=True, choices=[('homework_support', 'Homework Support'), ('remedial_support', 'Remedial Support')], max_length=50, null=True),
        ),
    ]
