# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_auto_20171009_1542'),
        ('clm', '0017_auto_20171019_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='bln',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.PartnerOrganization', verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.PartnerOrganization', verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='rs',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.PartnerOrganization', verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
    ]
