# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 07:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0018_auto_20171025_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbece',
            name='referral',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('academic', '\u0623\u0643\u0627\u062f\u064a\u0645\u064a'), ('absence', '\u063a\u064a\u0627\u0628')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0633\u0628\u0628 \u0627\u0644\u0625\u062d\u0627\u0644\u0629 '),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referral',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('academic', '\u0623\u0643\u0627\u062f\u064a\u0645\u064a'), ('absence', '\u063a\u064a\u0627\u0628')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0633\u0628\u0628 \u0627\u0644\u0625\u062d\u0627\u0644\u0629 '),
        ),
    ]
