# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0020_auto_20171102_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='bln',
            name='post_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Pre-test score'),
        ),
        migrations.AddField(
            model_name='bln',
            name='pre_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Pre-test score'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='post_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Pre-test score'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='pre_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Pre-test score'),
        ),
        migrations.AddField(
            model_name='rs',
            name='post_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Pre-test score'),
        ),
        migrations.AddField(
            model_name='rs',
            name='pre_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Pre-test score'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0627\u0644\u0645\u0648\u0642\u0639/\u0645\u0631\u0643\u0632'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0627\u0644\u0645\u0648\u0642\u0639/\u0645\u0631\u0643\u0632'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0627\u0644\u0645\u0648\u0642\u0639/\u0645\u0631\u0643\u0632'),
        ),
    ]
