# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0021_auto_20171103_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bln',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('graduated_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('graduated_to_formal_kg', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0631\u0648\u0636\u0629'), ('graduated_to_formal_level1', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0635\u0641 \u0627\u0644\u0623\u0648\u0644'), ('referred_to_another_program', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0622\u062e\u0631 \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0631\u0627\u0633\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='participation',
            field=models.CharField(blank=True, choices=[('', '\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '), ('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_15days', '\u0623\u0643\u062b\u0631 \u0645\u0646 15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
        migrations.AlterField(
            model_name='bln',
            name='post_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=' \u0627\u0644\u062a\u0642\u064a\u064a\u0645 \u0641\u064a \u0622\u062e\u0631 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='pre_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='\u0627\u0644\u062a\u0642\u064a\u064a\u0645 \u0639\u0646\u062f \u0627\u0644\u062f\u062e\u0648\u0644 \u0627\u0644\u0649 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='child_muac',
            field=models.CharField(blank=True, choices=[('', 'MUAC'), ('1', '<11.5 \u0633\u0645 (\u0633\u0648\u0621 \u0627\u0644\u062a\u063a\u0630\u064a\u0629 \u0627\u0644\u062d\u0627\u062f)'), ('2', '<12.5 \u0633\u0645 (\u0633\u0648\u0621 \u0627\u0644\u062a\u063a\u0630\u064a\u0629 \u0627\u0644\u0645\u0639\u062a\u062f\u0644)')], max_length=50, null=True, verbose_name='Child MUAC'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('graduated_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('graduated_to_formal_kg', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0631\u0648\u0636\u0629'), ('graduated_to_formal_level1', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0635\u0641 \u0627\u0644\u0623\u0648\u0644'), ('referred_to_another_program', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0622\u062e\u0631 \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0631\u0627\u0633\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='participation',
            field=models.CharField(blank=True, choices=[('', '\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '), ('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_15days', '\u0623\u0643\u062b\u0631 \u0645\u0646 15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='post_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=' \u0627\u0644\u062a\u0642\u064a\u064a\u0645 \u0641\u064a \u0622\u062e\u0631 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='pre_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='\u0627\u0644\u062a\u0642\u064a\u064a\u0645 \u0639\u0646\u062f \u0627\u0644\u062f\u062e\u0648\u0644 \u0627\u0644\u0649 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='site',
            field=models.CharField(blank=True, choices=[('', '\u0645\u0648\u0642\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'), ('in_school', ' \u062f\u0627\u062e\u0644 \u0627\u0644\u0645\u062f\u0631\u0633\u0629'), ('out_school', '\u062e\u0627\u0631\u062c \u0627\u0644\u0645\u062f\u0631\u0633\u0629')], max_length=50, null=True, verbose_name='\u0645\u0648\u0642\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('graduated_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('graduated_to_formal_kg', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0631\u0648\u0636\u0629'), ('graduated_to_formal_level1', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0635\u0641 \u0627\u0644\u0623\u0648\u0644'), ('referred_to_another_program', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0622\u062e\u0631 \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0631\u0627\u0633\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='participation',
            field=models.CharField(blank=True, choices=[('', '\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '), ('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_15days', '\u0623\u0643\u062b\u0631 \u0645\u0646 15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name=' \u0627\u0644\u062a\u0642\u064a\u064a\u0645 \u0641\u064a \u0622\u062e\u0631 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='\u0627\u0644\u062a\u0642\u064a\u064a\u0645 \u0639\u0646\u062f \u0627\u0644\u062f\u062e\u0648\u0644 \u0627\u0644\u0649 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='shift',
            field=models.CharField(blank=True, choices=[('', '\u062f\u0648\u0627\u0645 \u0627\u0644\u062a\u0639\u0644\u064a\u0645'), ('first', '\u062f\u0648\u0627\u0645 \u0635\u0628\u0627\u062d\u064a'), ('second', '\u062f\u0648\u0627\u0645 \u0628\u0639\u062f \u0627\u0644\u0638\u0647\u0631')], max_length=50, null=True, verbose_name='\u062f\u0648\u0627\u0645 \u0627\u0644\u062a\u0639\u0644\u064a\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='site',
            field=models.CharField(blank=True, choices=[('', '\u0645\u0648\u0642\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'), ('in_school', ' \u062f\u0627\u062e\u0644 \u0627\u0644\u0645\u062f\u0631\u0633\u0629'), ('out_school', '\u062e\u0627\u0631\u062c \u0627\u0644\u0645\u062f\u0631\u0633\u0629')], max_length=50, null=True, verbose_name='\u0645\u0648\u0642\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='type',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'), ('homework_support', 'Homework Support'), ('remedial_support', 'Remedial Support')], max_length=50, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
    ]
