# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-06 14:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0023_auto_20171105_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbece',
            name='referral',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('from_same_ngo', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0627\u0644\u062c\u0645\u0639\u064a\u0629 \u0630\u0627\u062a\u0647\u0627'), ('from_other_ngo', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u063a\u064a\u0631\u062c\u0645\u0639\u064a\u0629'), ('form_official_reference', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0645\u0631\u062c\u0639 \u0631\u0633\u0645\u064a (\u0645\u062e\u062a\u0627\u0631\u060c \u0628\u0644\u062f\u064a\u0629\u060c \u0645\u062f\u064a\u0631 \u0645\u062f\u0631\u0633\u0629\u060c \u0625\u0644\u062e ..)'), ('from_host_community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0627\u0644\u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0645\u0636\u064a\u0641'), ('from_displaced_community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0646\u0627\u0632\u062d\u064a\u0646')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0633\u0628\u0628 \u0627\u0644\u0625\u062d\u0627\u0644\u0629 '),
        ),
    ]
