# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-14 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0028_auto_20171111_1831'),
        ('clm', '0029_auto_20171111_0204'),
    ]

    operations = [
    ]
