# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0031_auto_20171114_1609'),
        ('clm', '0029_auto_20171114_1100'),
    ]

    operations = [
    ]
