# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-17 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_auto_20171114_1609'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clm', '0032_merge_20171115_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='bln',
            name='internal_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal number'),
        ),
        migrations.AddField(
            model_name='bln',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u062e\u0631 \u062a\u0639\u062f\u064a\u0644 \u0645\u0646 \u0642\u0628\u0644'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='internal_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal number'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u062e\u0631 \u062a\u0639\u062f\u064a\u0644 \u0645\u0646 \u0642\u0628\u0644'),
        ),
        migrations.AddField(
            model_name='rs',
            name='internal_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal number'),
        ),
        migrations.AddField(
            model_name='rs',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u062e\u0631 \u062a\u0639\u062f\u064a\u0644 \u0645\u0646 \u0642\u0628\u0644'),
        ),
        migrations.AddField(
            model_name='rs',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section', verbose_name='\u0627\u0644\u0634\u0639\u0628\u0629'),
        ),
    ]
