# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-21 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0033_auto_20171117_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bln',
            name='internal_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0631\u0642\u0645 \u062a\u0633\u0644\u0633\u0644\u064a \u062e\u0627\u0635 \u0628\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='internal_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0631\u0642\u0645 \u062a\u0633\u0644\u0633\u0644\u064a \u062e\u0627\u0635 \u0628\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='internal_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0631\u0642\u0645 \u062a\u0633\u0644\u0633\u0644\u064a \u062e\u0627\u0635 \u0628\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
    ]
