# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-21 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0034_auto_20171121_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bln',
            name='language',
            field=models.CharField(blank=True, choices=[('english_arabic', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('french_arabic', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=100, null=True, verbose_name='\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0645\u0639\u062a\u0645\u062f\u0629 \u0641\u064a \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='language',
            field=models.CharField(blank=True, choices=[('english_arabic', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('french_arabic', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=100, null=True, verbose_name='\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0645\u0639\u062a\u0645\u062f\u0629 \u0641\u064a \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='language',
            field=models.CharField(blank=True, choices=[('english_arabic', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('french_arabic', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=100, null=True, verbose_name='\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0645\u0639\u062a\u0645\u062f\u0629 \u0641\u064a \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
    ]
