# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-23 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0035_auto_20171121_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='bln',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0627\u062a'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0627\u062a'),
        ),
        migrations.AddField(
            model_name='rs',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0627\u062a'),
        ),
    ]
