# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-12 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0036_auto_20171123_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bln',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('repeat_level', '\u0625\u0639\u0627\u062f\u0629 \u0627\u0644\u0635\u0641'), ('attended_public_school', '\u0645\u0644\u062a\u062d\u0642 \u0628\u0645\u062f\u0631\u0633\u0629 \u0631\u0633\u0645\u064a\u0629'), ('referred_to_alp', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ALP'), ('ready_to_alp_but_not_possible', '\u062c\u0627\u0647\u0632 \u0644\u0628\u0631\u0646\u0627\u0645\u062c ALP \u0648\u0644\u0643\u0646 \u0627\u0644\u0625\u062d\u0627\u0644\u0629 \u0644\u064a\u0633\u062a \u0645\u0645\u0643\u0646\u0629'), ('reenrolled_in_alp', '\u0625\u0639\u0627\u062f\u0629 \u062a\u0633\u062c\u064a\u0644 \u0641\u064a \u062c\u0648\u0644\u0629 \u0623\u062e\u0631\u0649 \u0645\u0646 BLN'), ('not_enrolled_any_program', '\u063a\u064a\u0631 \u0645\u0644\u062a\u062d\u0642 \u0628\u0623\u064a \u0628\u0631\u0646\u0627\u0645\u062c \u062a\u0639\u0644\u064a\u0645\u064a')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('repeat_level', '\u0625\u0639\u0627\u062f\u0629 \u0627\u0644\u0635\u0641'), ('graduated_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('graduated_to_formal_kg', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0631\u0648\u0636\u0629'), ('graduated_to_formal_level1', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0635\u0641 \u0627\u0644\u0623\u0648\u0644'), ('referred_to_another_program', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0622\u062e\u0631 \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('repeat_level', '\u0625\u0639\u0627\u062f\u0629 \u0627\u0644\u0635\u0641'), ('graduated_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_arabic',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_language',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name=' \u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0623\u062c\u0646\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_math',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0627\u0644\u0631\u064a\u0627\u0636\u064a\u0627\u062a'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_science',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0627\u0644\u0639\u0644\u0648\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_arabic',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_language',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name=' \u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0623\u062c\u0646\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_math',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0627\u0644\u0631\u064a\u0627\u0636\u064a\u0627\u062a'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_science',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0627\u0644\u0639\u0644\u0648\u0645'),
        ),
    ]
