# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-12 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0038_auto_20171224_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bln',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bln_enrollment', to='students.Student', verbose_name='\u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbece_enrollment', to='students.Student', verbose_name='\u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rs_enrollment', to='students.Student', verbose_name='\u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
    ]
