# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-24 18:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0039_auto_20180323_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='rs',
            name='post_reading',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rs',
            name='post_reading_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Arabic reading - Post'),
        ),
        migrations.AddField(
            model_name='rs',
            name='pre_reading',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rs',
            name='pre_reading_score',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Arabic reading - Pre'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='unsuccessful_posttest_reason',
            field=models.CharField(blank=True, choices=[('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Post-test'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='unsuccessful_posttest_reason',
            field=models.CharField(blank=True, choices=[('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Post-test'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='unsuccessful_posttest_reason',
            field=models.CharField(blank=True, choices=[('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Post-test'),
        ),
    ]
