# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0040_auto_20180324_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbece',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='/80', max_digits=4, null=True),
        ),
    ]
