# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0042_auto_20180326_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbece',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
