# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-14 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0044_auto_20180405_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='disability',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
