# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-14 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0045_disability_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bln',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='unsuccessful pre test reason'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='unsuccessful pre test reason'),
        ),
        migrations.AddField(
            model_name='rs',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='unsuccessful pre test reason'),
        ),
    ]
