# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-21 10:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0049_auto_20190403_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bln',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('weather', '\u0627\u0644\u0637\u0642\u0633'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', 'Moved back to Syria'), ('Enrolled in formal education', 'Enrolled in formal education'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '\u0628\u0644\u0637\u062c\u0629/\u0639\u0646\u0641'), ('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='unsuccessful_posttest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Post-test'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('enrolled in formal', 'Enrolled in formal education'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Pre-test'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('weather', '\u0627\u0644\u0637\u0642\u0633'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', 'Moved back to Syria'), ('Enrolled in formal education', 'Enrolled in formal education'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '\u0628\u0644\u0637\u062c\u0629/\u0639\u0646\u0641'), ('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='unsuccessful_posttest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Post-test'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('enrolled in formal', 'Enrolled in formal education'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Pre-test'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('weather', '\u0627\u0644\u0637\u0642\u0633'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', 'Moved back to Syria'), ('Enrolled in formal education', 'Enrolled in formal education'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '\u0628\u0644\u0637\u062c\u0629/\u0639\u0646\u0641'), ('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='unsuccessful_posttest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Post-test'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('enrolled in formal', 'Enrolled in formal education'), ('uncompleted_participation', '\u0644\u0645 \u064a\u0645\u0643\u0644 \u0627\u0644\u0646\u0633\u0628\u0629 \u0627\u0644\u0645\u0631\u062c\u0648\u0629 \u0645\u0646 \u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629  ')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Pre-test'),
        ),
    ]
