# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0051_auto_20190521_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bln',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('repeat_level', '\u0625\u0639\u0627\u062f\u0629 \u0627\u0644\u0645\u0633\u062a\u0648\u0649'), ('attended_public_school', '\u0627\u062d\u064a\u0644 \u0627\u0644\u0649 \u0645\u062f\u0631\u0633\u0629 \u0631\u0633\u0645\u064a\u0629'), ('referred_to_alp', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ALP'), ('referred_to_tvet', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c TVET'), ('ready_to_alp_but_not_possible', '\u062c\u0627\u0647\u0632 \u0644\u0628\u0631\u0646\u0627\u0645\u062c ALP \u0648\u0644\u0643\u0646 \u0627\u0644\u0625\u062d\u0627\u0644\u0629 \u0644\u064a\u0633\u062a \u0645\u0645\u0643\u0646\u0629'), ('reenrolled_in_alp', '\u0625\u0639\u0627\u062f\u0629 \u062a\u0633\u062c\u064a\u0644 \u0641\u064a \u062c\u0648\u0644\u0629 \u0623\u062e\u0631\u0649 \u0645\u0646 BLN'), ('not_enrolled_any_program', '\u063a\u064a\u0631 \u0645\u0644\u062a\u062d\u0642 \u0628\u0623\u064a \u0628\u0631\u0646\u0627\u0645\u062c \u062a\u0639\u0644\u064a\u0645\u064a'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629\u060c \u0627\u062d\u0627\u0644\u0629 \u063a\u064a\u0631 \u0645\u0645\u0643\u0646\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
    ]
