# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-08 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_auto_20171201_1630'),
        ('clm', '0054_abln'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case number'),
        ),
        migrations.AddField(
            model_name='abln',
            name='case_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case number confirm'),
        ),
        migrations.AddField(
            model_name='abln',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.IDType', verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AddField(
            model_name='abln',
            name='individual_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Individual Case number'),
        ),
        migrations.AddField(
            model_name='abln',
            name='individual_case_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Individual Case number confirm'),
        ),
        migrations.AddField(
            model_name='abln',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian / Lebanese ID number '),
        ),
        migrations.AddField(
            model_name='abln',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian / Lebanese ID number confirm'),
        ),
        migrations.AddField(
            model_name='abln',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
        migrations.AddField(
            model_name='abln',
            name='phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number confirm'),
        ),
        migrations.AddField(
            model_name='abln',
            name='recorded_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recorded number'),
        ),
        migrations.AddField(
            model_name='abln',
            name='recorded_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recorded number confirm'),
        ),
        migrations.AddField(
            model_name='bln',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case number'),
        ),
        migrations.AddField(
            model_name='bln',
            name='case_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case number confirm'),
        ),
        migrations.AddField(
            model_name='bln',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.IDType', verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AddField(
            model_name='bln',
            name='individual_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Individual Case number'),
        ),
        migrations.AddField(
            model_name='bln',
            name='individual_case_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Individual Case number confirm'),
        ),
        migrations.AddField(
            model_name='bln',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian / Lebanese ID number '),
        ),
        migrations.AddField(
            model_name='bln',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian / Lebanese ID number confirm'),
        ),
        migrations.AddField(
            model_name='bln',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
        migrations.AddField(
            model_name='bln',
            name='phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number confirm'),
        ),
        migrations.AddField(
            model_name='bln',
            name='recorded_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recorded number'),
        ),
        migrations.AddField(
            model_name='bln',
            name='recorded_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recorded number confirm'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case number'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='case_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case number confirm'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.IDType', verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='individual_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Individual Case number'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='individual_case_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Individual Case number confirm'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian / Lebanese ID number '),
        ),
        migrations.AddField(
            model_name='cbece',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian / Lebanese ID number confirm'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number confirm'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='recorded_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recorded number'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='recorded_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recorded number confirm'),
        ),
        migrations.AddField(
            model_name='rs',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case number'),
        ),
        migrations.AddField(
            model_name='rs',
            name='case_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Case number confirm'),
        ),
        migrations.AddField(
            model_name='rs',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.IDType', verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AddField(
            model_name='rs',
            name='individual_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Individual Case number'),
        ),
        migrations.AddField(
            model_name='rs',
            name='individual_case_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Individual Case number confirm'),
        ),
        migrations.AddField(
            model_name='rs',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian / Lebanese ID number '),
        ),
        migrations.AddField(
            model_name='rs',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian / Lebanese ID number confirm'),
        ),
        migrations.AddField(
            model_name='rs',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
        migrations.AddField(
            model_name='rs',
            name='phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number confirm'),
        ),
        migrations.AddField(
            model_name='rs',
            name='recorded_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recorded number'),
        ),
        migrations.AddField(
            model_name='rs',
            name='recorded_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recorded number confirm'),
        ),
    ]
