# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-09 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0055_auto_20190708_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abln',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='bln',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='rs',
            name='id_type',
        ),
    ]
