# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-24 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0057_auto_20190709_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='referral_partner_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='abln',
            name='referral_partner_2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='abln',
            name='referral_partner_3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='abln',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
        migrations.AddField(
            model_name='abln',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
        migrations.AddField(
            model_name='abln',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
        migrations.AddField(
            model_name='bln',
            name='referral_partner_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='bln',
            name='referral_partner_2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='bln',
            name='referral_partner_3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='bln',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
        migrations.AddField(
            model_name='bln',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
        migrations.AddField(
            model_name='bln',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='referral_partner_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='referral_partner_2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='referral_partner_3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
        migrations.AddField(
            model_name='rs',
            name='referral_partner_1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='rs',
            name='referral_partner_2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='rs',
            name='referral_partner_3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='rs',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
        migrations.AddField(
            model_name='rs',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
        migrations.AddField(
            model_name='rs',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Programme Type'),
        ),
    ]
