# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0059_auto_20190724_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='followup_call_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='Call date'),
        ),
        migrations.AddField(
            model_name='abln',
            name='followup_call_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='Call date'),
        ),
        migrations.AddField(
            model_name='abln',
            name='followup_call_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='abln',
            name='followup_call_reason_2',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='abln',
            name='followup_call_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='abln',
            name='followup_call_result_2',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='abln',
            name='followup_visit_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='Visit date'),
        ),
        migrations.AddField(
            model_name='abln',
            name='followup_visit_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='abln',
            name='followup_visit_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_call_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='Call date'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_call_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='Call date'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_call_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_call_reason_2',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_call_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_call_result_2',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_visit_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='Visit date'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_visit_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_visit_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_call_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='Call date'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_call_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='Call date'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_call_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_call_reason_2',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_call_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_call_result_2',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_visit_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='Visit date'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_visit_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_visit_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_call_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='Call date'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_call_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='Call date'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_call_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_call_reason_2',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_call_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_call_result_2',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_visit_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='Visit date'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_visit_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_visit_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='Results'),
        ),
    ]
