# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-31 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0063_auto_20190730_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='parent_sop_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number '),
        ),
        migrations.AddField(
            model_name='abln',
            name='parent_sop_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number confirm'),
        ),
        migrations.AddField(
            model_name='abln',
            name='parent_syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number '),
        ),
        migrations.AddField(
            model_name='abln',
            name='parent_syrian_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number confirm'),
        ),
        migrations.AddField(
            model_name='abln',
            name='sop_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number '),
        ),
        migrations.AddField(
            model_name='abln',
            name='sop_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number confirm'),
        ),
        migrations.AddField(
            model_name='abln',
            name='syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number '),
        ),
        migrations.AddField(
            model_name='abln',
            name='syrian_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number confirm'),
        ),
        migrations.AddField(
            model_name='bln',
            name='parent_sop_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number '),
        ),
        migrations.AddField(
            model_name='bln',
            name='parent_sop_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number confirm'),
        ),
        migrations.AddField(
            model_name='bln',
            name='parent_syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number '),
        ),
        migrations.AddField(
            model_name='bln',
            name='parent_syrian_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number confirm'),
        ),
        migrations.AddField(
            model_name='bln',
            name='sop_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number '),
        ),
        migrations.AddField(
            model_name='bln',
            name='sop_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number confirm'),
        ),
        migrations.AddField(
            model_name='bln',
            name='syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number '),
        ),
        migrations.AddField(
            model_name='bln',
            name='syrian_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number confirm'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='parent_sop_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number '),
        ),
        migrations.AddField(
            model_name='cbece',
            name='parent_sop_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number confirm'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='parent_syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number '),
        ),
        migrations.AddField(
            model_name='cbece',
            name='parent_syrian_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number confirm'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='sop_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number '),
        ),
        migrations.AddField(
            model_name='cbece',
            name='sop_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number confirm'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number '),
        ),
        migrations.AddField(
            model_name='cbece',
            name='syrian_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number confirm'),
        ),
        migrations.AddField(
            model_name='rs',
            name='parent_sop_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number '),
        ),
        migrations.AddField(
            model_name='rs',
            name='parent_sop_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number confirm'),
        ),
        migrations.AddField(
            model_name='rs',
            name='parent_syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number '),
        ),
        migrations.AddField(
            model_name='rs',
            name='parent_syrian_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number confirm'),
        ),
        migrations.AddField(
            model_name='rs',
            name='sop_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number '),
        ),
        migrations.AddField(
            model_name='rs',
            name='sop_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Palestinian ID number confirm'),
        ),
        migrations.AddField(
            model_name='rs',
            name='syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number '),
        ),
        migrations.AddField(
            model_name='rs',
            name='syrian_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Syrian ID number confirm'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Child have no ID', 'Child have no ID')], max_length=100, null=True, verbose_name='Child ID type'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number '),
        ),
        migrations.AlterField(
            model_name='abln',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number confirm'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='parent_id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Parent have no ID', 'Parent have no ID')], max_length=100, null=True, verbose_name='Parent ID type'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='parent_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number '),
        ),
        migrations.AlterField(
            model_name='abln',
            name='parent_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number confirm'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Child have no ID', 'Child have no ID')], max_length=100, null=True, verbose_name='Child ID type'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number '),
        ),
        migrations.AlterField(
            model_name='bln',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number confirm'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='parent_id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Parent have no ID', 'Parent have no ID')], max_length=100, null=True, verbose_name='Parent ID type'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='parent_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number '),
        ),
        migrations.AlterField(
            model_name='bln',
            name='parent_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number confirm'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Child have no ID', 'Child have no ID')], max_length=100, null=True, verbose_name='Child ID type'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number '),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number confirm'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='parent_id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Parent have no ID', 'Parent have no ID')], max_length=100, null=True, verbose_name='Parent ID type'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='parent_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number '),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='parent_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number confirm'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Child have no ID', 'Child have no ID')], max_length=100, null=True, verbose_name='Child ID type'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number '),
        ),
        migrations.AlterField(
            model_name='rs',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number confirm'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='parent_id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Parent have no ID', 'Parent have no ID')], max_length=100, null=True, verbose_name='Parent ID type'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='parent_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number '),
        ),
        migrations.AlterField(
            model_name='rs',
            name='parent_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese ID number confirm'),
        ),
    ]
