# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-07-31 08:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0064_auto_20190731_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='other_nationality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Specify the nationality'),
        ),
        migrations.AddField(
            model_name='bln',
            name='other_nationality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Specify the nationality'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='other_nationality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Specify the nationality'),
        ),
        migrations.AddField(
            model_name='rs',
            name='other_nationality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Specify the nationality'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='labours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', '\u0627\u0644\u0632\u0631\u0627\u0639\u0629'), ('building', '\u0627\u0644\u0628\u0646\u0627\u0621'), ('manufacturing', '\u0627\u0644\u062a\u0635\u0646\u064a\u0639'), ('retail_store', '\u0627\u0644\u0628\u064a\u0639 \u0628\u0627\u0644\u0645\u0641\u0631\u0642 / \u0645\u062d\u0644'), ('begging', '\u062a\u0633\u0648\u0644'), ('other_many_other', '\u063a\u064a\u0631 \u0630\u0644\u0643 (\u0641\u0646\u062f\u0642\u060c \u0645\u0637\u0639\u0645\u060c \u0646\u0642\u0644\u060c \u062e\u062f\u0645\u0627\u062a \u0634\u062e\u0635\u064a\u0629 \u0645\u062b\u0644 \u0627\u0644\u062a\u0646\u0638\u064a\u0641\u060c \u0627\u0644\u0639\u0646\u0627\u064a\u0629 \u0628\u0627\u0644\u0634\u0639\u0631\u060c \u0627\u0644\u0637\u0628\u062e \u0648\u0627\u0644\u0625\u0639\u062a\u0646\u0627\u0621 \u0628\u0627\u0644\u0623\u0637\u0641\u0627\u0644)')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='\u0645\u0627 \u0647\u0648 \u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644 \u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='labours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', '\u0627\u0644\u0632\u0631\u0627\u0639\u0629'), ('building', '\u0627\u0644\u0628\u0646\u0627\u0621'), ('manufacturing', '\u0627\u0644\u062a\u0635\u0646\u064a\u0639'), ('retail_store', '\u0627\u0644\u0628\u064a\u0639 \u0628\u0627\u0644\u0645\u0641\u0631\u0642 / \u0645\u062d\u0644'), ('begging', '\u062a\u0633\u0648\u0644'), ('other_many_other', '\u063a\u064a\u0631 \u0630\u0644\u0643 (\u0641\u0646\u062f\u0642\u060c \u0645\u0637\u0639\u0645\u060c \u0646\u0642\u0644\u060c \u062e\u062f\u0645\u0627\u062a \u0634\u062e\u0635\u064a\u0629 \u0645\u062b\u0644 \u0627\u0644\u062a\u0646\u0638\u064a\u0641\u060c \u0627\u0644\u0639\u0646\u0627\u064a\u0629 \u0628\u0627\u0644\u0634\u0639\u0631\u060c \u0627\u0644\u0637\u0628\u062e \u0648\u0627\u0644\u0625\u0639\u062a\u0646\u0627\u0621 \u0628\u0627\u0644\u0623\u0637\u0641\u0627\u0644)')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='\u0645\u0627 \u0647\u0648 \u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644 \u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='labours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', '\u0627\u0644\u0632\u0631\u0627\u0639\u0629'), ('building', '\u0627\u0644\u0628\u0646\u0627\u0621'), ('manufacturing', '\u0627\u0644\u062a\u0635\u0646\u064a\u0639'), ('retail_store', '\u0627\u0644\u0628\u064a\u0639 \u0628\u0627\u0644\u0645\u0641\u0631\u0642 / \u0645\u062d\u0644'), ('begging', '\u062a\u0633\u0648\u0644'), ('other_many_other', '\u063a\u064a\u0631 \u0630\u0644\u0643 (\u0641\u0646\u062f\u0642\u060c \u0645\u0637\u0639\u0645\u060c \u0646\u0642\u0644\u060c \u062e\u062f\u0645\u0627\u062a \u0634\u062e\u0635\u064a\u0629 \u0645\u062b\u0644 \u0627\u0644\u062a\u0646\u0638\u064a\u0641\u060c \u0627\u0644\u0639\u0646\u0627\u064a\u0629 \u0628\u0627\u0644\u0634\u0639\u0631\u060c \u0627\u0644\u0637\u0628\u062e \u0648\u0627\u0644\u0625\u0639\u062a\u0646\u0627\u0621 \u0628\u0627\u0644\u0623\u0637\u0641\u0627\u0644)')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='\u0645\u0627 \u0647\u0648 \u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644 \u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='labours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', '\u0627\u0644\u0632\u0631\u0627\u0639\u0629'), ('building', '\u0627\u0644\u0628\u0646\u0627\u0621'), ('manufacturing', '\u0627\u0644\u062a\u0635\u0646\u064a\u0639'), ('retail_store', '\u0627\u0644\u0628\u064a\u0639 \u0628\u0627\u0644\u0645\u0641\u0631\u0642 / \u0645\u062d\u0644'), ('begging', '\u062a\u0633\u0648\u0644'), ('other_many_other', '\u063a\u064a\u0631 \u0630\u0644\u0643 (\u0641\u0646\u062f\u0642\u060c \u0645\u0637\u0639\u0645\u060c \u0646\u0642\u0644\u060c \u062e\u062f\u0645\u0627\u062a \u0634\u062e\u0635\u064a\u0629 \u0645\u062b\u0644 \u0627\u0644\u062a\u0646\u0638\u064a\u0641\u060c \u0627\u0644\u0639\u0646\u0627\u064a\u0629 \u0628\u0627\u0644\u0634\u0639\u0631\u060c \u0627\u0644\u0637\u0628\u062e \u0648\u0627\u0644\u0625\u0639\u062a\u0646\u0627\u0621 \u0628\u0627\u0644\u0623\u0637\u0641\u0627\u0644)')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='\u0645\u0627 \u0647\u0648 \u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644 \u061f'),
        ),
    ]
