# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0067_auto_20190805_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('graduated_to_abln_next_level', 'Graduated to the ABLN next level'), ('referred_to_bln', 'Referred to BLN'), ('referred_to_ybln', 'Referred to YBLN'), ('referred_to_alp', 'Referred to ALP'), ('referred_to_cbt', 'Referred to CBT'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629\u060c \u0627\u062d\u0627\u0644\u0629 \u063a\u064a\u0631 \u0645\u0645\u0643\u0646\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('enrolled and did not do the pre-test', 'Enrolled and did not do the pre-test'), ('enrolled in formal', 'Enrolled in formal education')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Pre-test'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('graduated_to_bln_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('referred_to_alp', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ALP'), ('referred_public_school', 'Referred to public school'), ('referred_to_tvet', 'Referred to TVET'), ('referred_to_ybln', 'Referred to YBLN'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629\u060c \u0627\u062d\u0627\u0644\u0629 \u063a\u064a\u0631 \u0645\u0645\u0643\u0646\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('enrolled and did not do the pre-test', 'Enrolled and did not do the pre-test'), ('enrolled in formal', 'Enrolled in formal education')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Pre-test'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('enrolled and did not do the pre-test', 'Enrolled and did not do the pre-test'), ('enrolled in formal', 'Enrolled in formal education')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Pre-test'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('enrolled and did not do the pre-test', 'Enrolled and did not do the pre-test'), ('enrolled in formal', 'Enrolled in formal education')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Pre-test'),
        ),
    ]
