# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-19 07:02
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0039_auto_20190619_1028'),
        ('clm', '0068_auto_20190805_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='What is the educational level of the father?'),
        ),
        migrations.AddField(
            model_name='bln',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='What is the educational level of the father?'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='What is the educational level of the father?'),
        ),
        migrations.AddField(
            model_name='rs',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='What is the educational level of the father?'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('weather', '\u0627\u0644\u0637\u0642\u0633'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 - \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0648 \u0639\u0644\u0649 \u0637\u0631\u064a\u0642\u0647 \u0627\u0644\u0649 \u0627\u0644\u0645\u0631\u0643\u0632 '), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='confirmation_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='confirmation_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='confirmation_date_3',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', 'Out of school'), ('enrolled in formal educarioh but did not continue', 'Enrolled in formal educarioh but did not continue')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='followup_call_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062a\u0635\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='followup_call_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062a\u0635\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='followup_call_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='followup_call_reason_2',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='followup_call_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='followup_call_result_2',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='followup_visit_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0632\u064a\u0627\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='followup_visit_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='followup_visit_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='hh_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='\u0645\u0627 \u0647\u0648 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0644\u0644\u0623\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Child have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642 ')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='labours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', '\u0627\u0644\u0632\u0631\u0627\u0639\u0629'), ('building', '\u0627\u0644\u0628\u0646\u0627\u0621'), ('manufacturing', '\u0627\u0644\u062a\u0635\u0646\u064a\u0639'), ('retail_store', '\u0627\u0644\u0628\u064a\u0639 \u0628\u0627\u0644\u0645\u0641\u0631\u0642 / \u0645\u062d\u0644'), ('begging', '\u062a\u0633\u0648\u0644'), ('other_many_other', ' \u062e\u062f\u0645\u0627\u062a \u0645\u062e\u062a\u0644\u0641\u0629 (\u0641\u0646\u062f\u0642\u060c \u0645\u0637\u0639\u0645\u060c \u0646\u0642\u0644\u060c \u062e\u062f\u0645\u0627\u062a \u0634\u062e\u0635\u064a\u0629 \u0645\u062b\u0644 \u0627\u0644\u062a\u0646\u0638\u064a\u0641\u060c \u0627\u0644\u0639\u0646\u0627\u064a\u0629 \u0628\u0627\u0644\u0634\u0639\u0631\u060c \u0627\u0644\u0637\u0628\u062e \u0648\u0627\u0644\u0625\u0639\u062a\u0646\u0627\u0621 \u0628\u0627\u0644\u0623\u0637\u0641\u0627\u0644)')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='\u0645\u0627 \u0647\u0648 \u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644 \u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='language',
            field=models.CharField(blank=True, choices=[('arabic', '\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('english_arabic', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('french_arabic', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=100, null=True, verbose_name='\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0645\u0639\u062a\u0645\u062f\u0629 \u0641\u064a \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('graduated_to_abln_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('referred_to_bln', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c BLN'), ('referred_to_ybln', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c YBLN'), ('referred_to_alp', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ALP'), ('referred_to_cbt', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c CBT'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629\u060c \u0627\u062d\u0627\u0644\u0629 \u063a\u064a\u0631 \u0645\u0645\u0643\u0646\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u062a\u0623\u0643\u064a\u062f \u0631\u0642\u0645 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='other_nationality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' \u062d\u062f\u062f \u0627\u0644\u062c\u0646\u0633\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='parent_id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Parent have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u062e\u0627\u0635\u0629 '),
        ),
        migrations.AlterField(
            model_name='abln',
            name='parent_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='parent_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u062a\u0623\u0643\u064a\u062f \u0631\u0642\u0645 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='parent_syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629\u0627\u0644\u0633\u0648\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='participation',
            field=models.CharField(blank=True, choices=[('less_than_3days', '\u0623\u0642\u0644 \u0645\u0646 3 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('3_7_days', '3-7 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('7_12_days', '7-12 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_12days', '\u0623\u0643\u062b\u0631 \u0645\u0646 12 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
        migrations.AlterField(
            model_name='abln',
            name='phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u062a\u0623\u0643\u064a\u062f \u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referral_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referral_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referral_date_3',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Referred by CP partner', 'Referred by CP partner'), ('Referred by youth partner', 'Referred by youth partner'), ('Family walked in to NGO', 'Family walked in to NGO'), ('Referral from another NGO', 'Referral from another NGO'), ('Referral from another Municipality', 'Referral from Municipality'), ('Direct outreach', 'Direct outreach'), ('List database', 'List database')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u0644\u062a\u0639\u0631\u0641 \u0639\u0644\u0649 \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629\u0627\u0644\u0633\u0648\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('enrolled and did not do the pre-test', 'Pre-test \u0645\u0633\u062c\u0644 \u0648\u0644\u0643\u0646 \u0644\u0645 \u064a\u0642\u0645 \u0628\u0627\u0644'), ('enrolled in formal', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Pre-test'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('weather', '\u0627\u0644\u0637\u0642\u0633'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 - \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0648 \u0639\u0644\u0649 \u0637\u0631\u064a\u0642\u0647 \u0627\u0644\u0649 \u0627\u0644\u0645\u0631\u0643\u0632 '), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='confirmation_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='confirmation_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='confirmation_date_3',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', 'Out of school'), ('enrolled in formal educarioh but did not continue', 'Enrolled in formal educarioh but did not continue')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='followup_call_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062a\u0635\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='followup_call_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062a\u0635\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='followup_call_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='followup_call_reason_2',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='followup_call_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='followup_call_result_2',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='followup_visit_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0632\u064a\u0627\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='followup_visit_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='followup_visit_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='hh_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='\u0645\u0627 \u0647\u0648 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0644\u0644\u0623\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Child have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642 ')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='labours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', '\u0627\u0644\u0632\u0631\u0627\u0639\u0629'), ('building', '\u0627\u0644\u0628\u0646\u0627\u0621'), ('manufacturing', '\u0627\u0644\u062a\u0635\u0646\u064a\u0639'), ('retail_store', '\u0627\u0644\u0628\u064a\u0639 \u0628\u0627\u0644\u0645\u0641\u0631\u0642 / \u0645\u062d\u0644'), ('begging', '\u062a\u0633\u0648\u0644'), ('other_many_other', ' \u062e\u062f\u0645\u0627\u062a \u0645\u062e\u062a\u0644\u0641\u0629 (\u0641\u0646\u062f\u0642\u060c \u0645\u0637\u0639\u0645\u060c \u0646\u0642\u0644\u060c \u062e\u062f\u0645\u0627\u062a \u0634\u062e\u0635\u064a\u0629 \u0645\u062b\u0644 \u0627\u0644\u062a\u0646\u0638\u064a\u0641\u060c \u0627\u0644\u0639\u0646\u0627\u064a\u0629 \u0628\u0627\u0644\u0634\u0639\u0631\u060c \u0627\u0644\u0637\u0628\u062e \u0648\u0627\u0644\u0625\u0639\u062a\u0646\u0627\u0621 \u0628\u0627\u0644\u0623\u0637\u0641\u0627\u0644)')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='\u0645\u0627 \u0647\u0648 \u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644 \u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='language',
            field=models.CharField(blank=True, choices=[('arabic', '\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('english_arabic', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('french_arabic', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=100, null=True, verbose_name='\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0645\u0639\u062a\u0645\u062f\u0629 \u0641\u064a \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('graduated_to_bln_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('referred_to_alp', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ALP'), ('referred_public_school', '\u0627\u062d\u064a\u0644 \u0627\u0644\u0649 \u0645\u062f\u0631\u0633\u0629 \u0631\u0633\u0645\u064a\u0629'), ('referred_to_tvet', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c TVET'), ('referred_to_ybln', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c YBLN'), ('dropout', '\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629\u060c \u0627\u062d\u0627\u0644\u0629 \u063a\u064a\u0631 \u0645\u0645\u0643\u0646\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u062a\u0623\u0643\u064a\u062f \u0631\u0642\u0645 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='other_nationality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' \u062d\u062f\u062f \u0627\u0644\u062c\u0646\u0633\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='parent_id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Parent have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u062e\u0627\u0635\u0629 '),
        ),
        migrations.AlterField(
            model_name='bln',
            name='parent_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='parent_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u062a\u0623\u0643\u064a\u062f \u0631\u0642\u0645 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='parent_syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629\u0627\u0644\u0633\u0648\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='participation',
            field=models.CharField(blank=True, choices=[('less_than_10days', '\u0623\u0642\u0644 \u0645\u0646 10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('15_20_days', '15-20 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_20days', '\u0623\u0643\u062b\u0631 \u0645\u0646 20 \u064a\u0648\u0645 \u063a\u064a\u0627\u0628')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
        migrations.AlterField(
            model_name='bln',
            name='phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u062a\u0623\u0643\u064a\u062f \u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referral_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referral_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referral_date_3',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Referred by CP partner', 'Referred by CP partner'), ('Referred by youth partner', 'Referred by youth partner'), ('Family walked in to NGO', 'Family walked in to NGO'), ('Referral from another NGO', 'Referral from another NGO'), ('Referral from another Municipality', 'Referral from Municipality'), ('Direct outreach', 'Direct outreach'), ('List database', 'List database')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u0644\u062a\u0639\u0631\u0641 \u0639\u0644\u0649 \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629\u0627\u0644\u0633\u0648\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('enrolled and did not do the pre-test', 'Pre-test \u0645\u0633\u062c\u0644 \u0648\u0644\u0643\u0646 \u0644\u0645 \u064a\u0642\u0645 \u0628\u0627\u0644'), ('enrolled in formal', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Pre-test'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('weather', '\u0627\u0644\u0637\u0642\u0633'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 - \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0648 \u0639\u0644\u0649 \u0637\u0631\u064a\u0642\u0647 \u0627\u0644\u0649 \u0627\u0644\u0645\u0631\u0643\u0632 '), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='confirmation_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='confirmation_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='confirmation_date_3',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', 'Out of school'), ('enrolled in formal educarioh but did not continue', 'Enrolled in formal educarioh but did not continue')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='followup_call_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062a\u0635\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='followup_call_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062a\u0635\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='followup_call_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='followup_call_reason_2',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='followup_call_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='followup_call_result_2',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='followup_visit_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0632\u064a\u0627\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='followup_visit_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='followup_visit_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='hh_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='\u0645\u0627 \u0647\u0648 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0644\u0644\u0623\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Child have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642 ')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='labours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', '\u0627\u0644\u0632\u0631\u0627\u0639\u0629'), ('building', '\u0627\u0644\u0628\u0646\u0627\u0621'), ('manufacturing', '\u0627\u0644\u062a\u0635\u0646\u064a\u0639'), ('retail_store', '\u0627\u0644\u0628\u064a\u0639 \u0628\u0627\u0644\u0645\u0641\u0631\u0642 / \u0645\u062d\u0644'), ('begging', '\u062a\u0633\u0648\u0644'), ('other_many_other', ' \u062e\u062f\u0645\u0627\u062a \u0645\u062e\u062a\u0644\u0641\u0629 (\u0641\u0646\u062f\u0642\u060c \u0645\u0637\u0639\u0645\u060c \u0646\u0642\u0644\u060c \u062e\u062f\u0645\u0627\u062a \u0634\u062e\u0635\u064a\u0629 \u0645\u062b\u0644 \u0627\u0644\u062a\u0646\u0638\u064a\u0641\u060c \u0627\u0644\u0639\u0646\u0627\u064a\u0629 \u0628\u0627\u0644\u0634\u0639\u0631\u060c \u0627\u0644\u0637\u0628\u062e \u0648\u0627\u0644\u0625\u0639\u062a\u0646\u0627\u0621 \u0628\u0627\u0644\u0623\u0637\u0641\u0627\u0644)')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='\u0645\u0627 \u0647\u0648 \u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644 \u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='language',
            field=models.CharField(blank=True, choices=[('arabic', '\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('english_arabic', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('french_arabic', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=100, null=True, verbose_name='\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0645\u0639\u062a\u0645\u062f\u0629 \u0641\u064a \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u062a\u0623\u0643\u064a\u062f \u0631\u0642\u0645 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='other_nationality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' \u062d\u062f\u062f \u0627\u0644\u062c\u0646\u0633\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='parent_id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Parent have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u062e\u0627\u0635\u0629 '),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='parent_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='parent_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u062a\u0623\u0643\u064a\u062f \u0631\u0642\u0645 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='parent_syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629\u0627\u0644\u0633\u0648\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u062a\u0623\u0643\u064a\u062f \u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referral_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referral_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referral_date_3',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Referred by CP partner', 'Referred by CP partner'), ('Referred by youth partner', 'Referred by youth partner'), ('Family walked in to NGO', 'Family walked in to NGO'), ('Referral from another NGO', 'Referral from another NGO'), ('Referral from another Municipality', 'Referral from Municipality'), ('Direct outreach', 'Direct outreach'), ('List database', 'List database')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u0644\u062a\u0639\u0631\u0641 \u0639\u0644\u0649 \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629\u0627\u0644\u0633\u0648\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('enrolled and did not do the pre-test', 'Pre-test \u0645\u0633\u062c\u0644 \u0648\u0644\u0643\u0646 \u0644\u0645 \u064a\u0642\u0645 \u0628\u0627\u0644'), ('enrolled in formal', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Pre-test'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('weather', '\u0627\u0644\u0637\u0642\u0633'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 - \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0648 \u0639\u0644\u0649 \u0637\u0631\u064a\u0642\u0647 \u0627\u0644\u0649 \u0627\u0644\u0645\u0631\u0643\u0632 '), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='confirmation_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='confirmation_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='confirmation_date_3',
            field=models.DateField(blank=True, null=True, verbose_name='\u0627\u0644\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0630\u064a \u062a\u0624\u0643\u062f \u0641\u064a\u0647 \u0627\u0644\u0645\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0642\u0628\u0644\u0629 \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062e\u062f\u0645\u0629 \u062a\u0644\u0642\u064a \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', 'Out of school'), ('enrolled in formal educarioh but did not continue', 'Enrolled in formal educarioh but did not continue')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='followup_call_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062a\u0635\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='followup_call_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062a\u0635\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='followup_call_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='followup_call_reason_2',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='followup_call_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='followup_call_result_2',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='followup_visit_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0632\u064a\u0627\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='followup_visit_reason_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='followup_visit_result_1',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u062a\u064a\u062c\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='hh_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='\u0645\u0627 \u0647\u0648 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0644\u0644\u0623\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Child have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642 ')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='labours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('agriculture', '\u0627\u0644\u0632\u0631\u0627\u0639\u0629'), ('building', '\u0627\u0644\u0628\u0646\u0627\u0621'), ('manufacturing', '\u0627\u0644\u062a\u0635\u0646\u064a\u0639'), ('retail_store', '\u0627\u0644\u0628\u064a\u0639 \u0628\u0627\u0644\u0645\u0641\u0631\u0642 / \u0645\u062d\u0644'), ('begging', '\u062a\u0633\u0648\u0644'), ('other_many_other', ' \u062e\u062f\u0645\u0627\u062a \u0645\u062e\u062a\u0644\u0641\u0629 (\u0641\u0646\u062f\u0642\u060c \u0645\u0637\u0639\u0645\u060c \u0646\u0642\u0644\u060c \u062e\u062f\u0645\u0627\u062a \u0634\u062e\u0635\u064a\u0629 \u0645\u062b\u0644 \u0627\u0644\u062a\u0646\u0638\u064a\u0641\u060c \u0627\u0644\u0639\u0646\u0627\u064a\u0629 \u0628\u0627\u0644\u0634\u0639\u0631\u060c \u0627\u0644\u0637\u0628\u062e \u0648\u0627\u0644\u0625\u0639\u062a\u0646\u0627\u0621 \u0628\u0627\u0644\u0623\u0637\u0641\u0627\u0644)')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='\u0645\u0627 \u0647\u0648 \u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644 \u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='language',
            field=models.CharField(blank=True, choices=[('arabic', '\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('english_arabic', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('french_arabic', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=100, null=True, verbose_name='\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0645\u0639\u062a\u0645\u062f\u0629 \u0641\u064a \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u062a\u0623\u0643\u064a\u062f \u0631\u0642\u0645 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='other_nationality',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=' \u062d\u062f\u062f \u0627\u0644\u062c\u0646\u0633\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='parent_id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Parent have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u062e\u0627\u0635\u0629 '),
        ),
        migrations.AlterField(
            model_name='rs',
            name='parent_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='parent_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u062a\u0623\u0643\u064a\u062f \u0631\u0642\u0645 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='parent_syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629\u0627\u0644\u0633\u0648\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u062a\u0623\u0643\u064a\u062f \u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referral_date_1',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referral_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referral_date_3',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u062d\u0627\u0644\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('Formal Education', 'Formal Education'), ('ALP', 'ALP'), ('BLN', 'BLN'), ('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Youth', 'Youth'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Referred by CP partner', 'Referred by CP partner'), ('Referred by youth partner', 'Referred by youth partner'), ('Family walked in to NGO', 'Family walked in to NGO'), ('Referral from another NGO', 'Referral from another NGO'), ('Referral from another Municipality', 'Referral from Municipality'), ('Direct outreach', 'Direct outreach'), ('List database', 'List database')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u0644\u062a\u0639\u0631\u0641 \u0639\u0644\u0649 \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0631\u0642\u0645 \u0627\u0644\u0628\u0637\u0627\u0642\u0629\u0627\u0644\u0633\u0648\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='unsuccessful_pretest_reason',
            field=models.CharField(blank=True, choices=[('disability', '\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u062e\u0627\u0635\u0629'), ('enrolled and did not do the pre-test', 'Pre-test \u0645\u0633\u062c\u0644 \u0648\u0644\u0643\u0646 \u0644\u0645 \u064a\u0642\u0645 \u0628\u0627\u0644'), ('enrolled in formal', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a')], max_length=100, null=True, verbose_name='\u0627\u0633\u0628\u0627\u0628 \u0639\u062f\u0645 \u0627\u0644\u0642\u064a\u0627\u0645 \u0628\u0627\u0644 Pre-test'),
        ),
    ]
