# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0069_auto_20190819_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='caretaker_first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker First Name'),
        ),
        migrations.AddField(
            model_name='abln',
            name='caretaker_last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Last Name'),
        ),
        migrations.AddField(
            model_name='abln',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Middle Name'),
        ),
        migrations.AddField(
            model_name='abln',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Mother Name'),
        ),
        migrations.AddField(
            model_name='bln',
            name='caretaker_first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker First Name'),
        ),
        migrations.AddField(
            model_name='bln',
            name='caretaker_last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Last Name'),
        ),
        migrations.AddField(
            model_name='bln',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Middle Name'),
        ),
        migrations.AddField(
            model_name='bln',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Mother Name'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='caretaker_first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker First Name'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='caretaker_last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Last Name'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Middle Name'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Mother Name'),
        ),
        migrations.AddField(
            model_name='rs',
            name='caretaker_first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker First Name'),
        ),
        migrations.AddField(
            model_name='rs',
            name='caretaker_last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Last Name'),
        ),
        migrations.AddField(
            model_name='rs',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Middle Name'),
        ),
        migrations.AddField(
            model_name='rs',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caretaker Mother Name'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', 'Out of school'), ('enrolled in formal education but did not continue', 'Enrolled in formal education but did not continue')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='\u0645\u0627 \u0647\u0648 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0644\u0644\u0623\u0628\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Referred by CP partner', 'Referred by CP partner'), ('Referred by youth partner', 'Referred by youth partner'), ('Family walked in to NGO', 'Family walked in to NGO'), ('Referral from another NGO', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u063a\u064a\u0631 \u062c\u0645\u0639\u064a\u0629'), ('Referral from another Municipality', 'Referral from Municipality'), ('Direct outreach', 'Direct outreach'), ('List database', 'List database')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u0644\u062a\u0639\u0631\u0641 \u0639\u0644\u0649 \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', 'Out of school'), ('enrolled in formal education but did not continue', 'Enrolled in formal education but did not continue')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='\u0645\u0627 \u0647\u0648 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0644\u0644\u0623\u0628\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Referred by CP partner', 'Referred by CP partner'), ('Referred by youth partner', 'Referred by youth partner'), ('Family walked in to NGO', 'Family walked in to NGO'), ('Referral from another NGO', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u063a\u064a\u0631 \u062c\u0645\u0639\u064a\u0629'), ('Referral from another Municipality', 'Referral from Municipality'), ('Direct outreach', 'Direct outreach'), ('List database', 'List database')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u0644\u062a\u0639\u0631\u0641 \u0639\u0644\u0649 \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', 'Out of school'), ('enrolled in formal education but did not continue', 'Enrolled in formal education but did not continue')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='\u0645\u0627 \u0647\u0648 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0644\u0644\u0623\u0628\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Referred by CP partner', 'Referred by CP partner'), ('Referred by youth partner', 'Referred by youth partner'), ('Family walked in to NGO', 'Family walked in to NGO'), ('Referral from another NGO', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u063a\u064a\u0631 \u062c\u0645\u0639\u064a\u0629'), ('Referral from another Municipality', 'Referral from Municipality'), ('Direct outreach', 'Direct outreach'), ('List database', 'List database')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u0644\u062a\u0639\u0631\u0641 \u0639\u0644\u0649 \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', 'Out of school'), ('enrolled in formal education but did not continue', 'Enrolled in formal education but did not continue')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationalLevel', verbose_name='\u0645\u0627 \u0647\u0648 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0644\u0644\u0623\u0628\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Referred by CP partner', 'Referred by CP partner'), ('Referred by youth partner', 'Referred by youth partner'), ('Family walked in to NGO', 'Family walked in to NGO'), ('Referral from another NGO', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u063a\u064a\u0631 \u062c\u0645\u0639\u064a\u0629'), ('Referral from another Municipality', 'Referral from Municipality'), ('Direct outreach', 'Direct outreach'), ('List database', 'List database')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u0644\u062a\u0639\u0631\u0641 \u0639\u0644\u0649 \u0627\u0644\u0637\u0641\u0644'),
        ),
    ]
