# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-08 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0073_auto_20191001_1015'),
        ('clm', '0072_auto_20190922_2321'),
    ]

    operations = [
    ]
