# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-11-14 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0075_auto_20191008_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abln',
            options={'ordering': ['-id'], 'verbose_name': 'ABLN', 'verbose_name_plural': 'ABLN'},
        ),
        migrations.AlterModelOptions(
            name='bln',
            options={'ordering': ['-id'], 'verbose_name': 'BLN', 'verbose_name_plural': 'BLN'},
        ),
        migrations.AlterModelOptions(
            name='cbece',
            options={'ordering': ['-id'], 'verbose_name': 'CB-ECE', 'verbose_name_plural': 'CB-ECE'},
        ),
        migrations.AlterModelOptions(
            name='rs',
            options={'ordering': ['-id'], 'verbose_name': 'RS', 'verbose_name_plural': 'RS'},
        ),
    ]
