# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-11-15 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0075_auto_20191008_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abln',
            options={'ordering': ['-id'], 'verbose_name': 'ABLN', 'verbose_name_plural': 'ABLN'},
        ),
        migrations.AlterModelOptions(
            name='bln',
            options={'ordering': ['-id'], 'verbose_name': 'BLN', 'verbose_name_plural': 'BLN'},
        ),
        migrations.AlterModelOptions(
            name='cbece',
            options={'ordering': ['-id'], 'verbose_name': 'CB-ECE', 'verbose_name_plural': 'CB-ECE'},
        ),
        migrations.AlterModelOptions(
            name='rs',
            options={'ordering': ['-id'], 'verbose_name': 'RS', 'verbose_name_plural': 'RS'},
        ),
        migrations.AddField(
            model_name='abln',
            name='first_attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='First attendance date'),
        ),
        migrations.AddField(
            model_name='bln',
            name='first_attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='First attendance date'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='first_attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='First attendance date'),
        ),
        migrations.AddField(
            model_name='rs',
            name='first_attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='First attendance date'),
        ),
    ]
