# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-11-26 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0076_auto_20191114_1123'),
        ('clm', '0076_auto_20191115_1532'),
    ]

    operations = [
    ]
