# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0078_auto_20191217_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='disability',
            name='name_en',
            field=models.CharField(blank=True, max_length=145, null=True),
        ),
    ]
