# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-20 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0080_auto_20200115_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='participation',
            field=models.CharField(blank=True, choices=[('less_than_3days', '\u0623\u0642\u0644 \u0645\u0646 3 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('3_7_days', '3-7 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('7_12_days', '7-12 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_12days', '\u0623\u0643\u062b\u0631 \u0645\u0646 12 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('no_absence', 'No Absence')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
        migrations.AlterField(
            model_name='bln',
            name='participation',
            field=models.CharField(blank=True, choices=[('less_than_10days', '\u0623\u0642\u0644 \u0645\u0646 10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('15_20_days', '15-20 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_20days', '\u0623\u0643\u062b\u0631 \u0645\u0646 20 \u064a\u0648\u0645 \u063a\u064a\u0627\u0628'), ('no_absence', 'No Absence')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='participation',
            field=models.CharField(blank=True, choices=[('', '\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '), ('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_15days', '\u0623\u0643\u062b\u0631 \u0645\u0646 15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('no_absence', 'No Absence')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
        migrations.AlterField(
            model_name='rs',
            name='participation',
            field=models.CharField(blank=True, choices=[('', '\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '), ('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('more_than_15days', '\u0623\u0643\u062b\u0631 \u0645\u0646 15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('no_absence', 'No Absence')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
    ]
