# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-09 10:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0083_auto_20200216_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0627\u0633\u0645 \u0648\u0627\u0644\u062f \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0627\u0633\u0645 \u0648\u0627\u0644\u062f\u0629 \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Cycle', verbose_name='\u0631\u0642\u0645'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', '\u0644\u0645 \u064a\u0633\u062c\u0644 \u0627\u0628\u062f\u0627 \u0641\u064a \u0627\u0644\u0645\u062f\u0631\u0633\u0629 \u0645\u0646 \u0642\u0628\u0644'), ('enrolled in formal education but did not continue', '\u0643\u0627\u0646 \u0645\u0633\u062c\u0644\u0627 \u0645\u062f\u0631\u0633\u0629 \u0646\u0636\u0627\u0645\u064a\u0647 \u0648\u0644\u0645 \u064a\u0643\u0645\u0644'), ('enrolled in ABLN', '\u0643\u0627\u0646 \u0645\u0633\u062c\u0644\u0627\u064b \u0641\u064a \u0645\u062f\u0631\u0633\u0629 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a\u0629 \u0648\u0644\u0645 \u064a\u0643\u0645\u0644')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a \u0644\u0644\u0637\u0641\u0644 \u0639\u0646\u062f \u0627\u0644\u062a\u0633\u062c\u064a\u0644 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='first_attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u062d\u0636\u0648\u0631 \u0627\u0644\u0637\u0641\u0644 \u0644\u0644\u0645\u0631\u0629 \u0627\u0644\u0623\u0648\u0644\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0623\u0648\u0644\u0649'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='labour_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0643\u0645 \u0633\u0627\u0639\u0629 \u064a\u0639\u0645\u0644 \u0647\u0630\u0627 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='new_registry',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u064a\u062a\u0645 \u062a\u0633\u062c\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0644\u0623\u0648\u0644 \u0645\u0631\u0629 \u0641\u064a \u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u062c\u0645\u0639\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.CLMRound', verbose_name='\u0631\u0642\u0645 \u0627\u0644\u062f\u0648\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Direct outreach', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u062d\u0645\u0644\u0627\u062a \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u0627\u0644\u062c\u0645\u0639\u064a\u0629'), ('List database', ' \u0627\u062d\u0644\u0629 \u0639\u0646 \u0637\u0631\u064a\u0642 Profiling Database'), ('Referral from another NGO', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u062c\u0645\u0639\u064a\u0629 \u0623\u062e\u0631\u0649'), ('Referred by CP partner', ' \u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0634\u0631\u0643\u0627\u0621 \u062d\u0645\u0627\u064a\u0629 \u0627\u0644\u0637\u0641\u0644 CP partner'), ('Referred by youth partner', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0634\u0631\u0643\u0627\u0621 \u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u0634\u0628\u0627\u0628 \u0648\u0627\u0644\u0645\u0631\u0627\u0647\u0642\u064a\u0646 youth'), ('Referral from another Municipality', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0627\u0644\u0628\u0644\u062f\u064a\u0629 / \u0645\u0631\u062c\u0639 \u0631\u0633\u0645\u064a'), ('Family walked in to NGO', '\u0645\u0646 \u0642\u0628\u0644 \u0627\u0647\u0644 \u0627\u0644\u0637\u0641\u0644 \u0645\u0628\u0627\u0634\u0631\u0629')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u062d\u0627\u0644\u0629 \u0627\u0644\u0637\u0641\u0644  \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ABLN'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0627\u0633\u0645 \u0648\u0627\u0644\u062f \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0627\u0633\u0645 \u0648\u0627\u0644\u062f\u0629 \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Cycle', verbose_name='\u0631\u0642\u0645'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', '\u0644\u0645 \u064a\u0633\u062c\u0644 \u0627\u0628\u062f\u0627 \u0641\u064a \u0627\u0644\u0645\u062f\u0631\u0633\u0629 \u0645\u0646 \u0642\u0628\u0644'), ('enrolled in formal education but did not continue', '\u0643\u0627\u0646 \u0645\u0633\u062c\u0644\u0627 \u0645\u062f\u0631\u0633\u0629 \u0646\u0636\u0627\u0645\u064a\u0647 \u0648\u0644\u0645 \u064a\u0643\u0645\u0644'), ('enrolled in ABLN', '\u0643\u0627\u0646 \u0645\u0633\u062c\u0644\u0627\u064b \u0641\u064a \u0645\u062f\u0631\u0633\u0629 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a\u0629 \u0648\u0644\u0645 \u064a\u0643\u0645\u0644')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a \u0644\u0644\u0637\u0641\u0644 \u0639\u0646\u062f \u0627\u0644\u062a\u0633\u062c\u064a\u0644 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='first_attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u062d\u0636\u0648\u0631 \u0627\u0644\u0637\u0641\u0644 \u0644\u0644\u0645\u0631\u0629 \u0627\u0644\u0623\u0648\u0644\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0623\u0648\u0644\u0649'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='labour_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0643\u0645 \u0633\u0627\u0639\u0629 \u064a\u0639\u0645\u0644 \u0647\u0630\u0627 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='new_registry',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u064a\u062a\u0645 \u062a\u0633\u062c\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0644\u0623\u0648\u0644 \u0645\u0631\u0629 \u0641\u064a \u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u062c\u0645\u0639\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.CLMRound', verbose_name='\u0631\u0642\u0645 \u0627\u0644\u062f\u0648\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Direct outreach', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u062d\u0645\u0644\u0627\u062a \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u0627\u0644\u062c\u0645\u0639\u064a\u0629'), ('List database', ' \u0627\u062d\u0644\u0629 \u0639\u0646 \u0637\u0631\u064a\u0642 Profiling Database'), ('Referral from another NGO', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u062c\u0645\u0639\u064a\u0629 \u0623\u062e\u0631\u0649'), ('Referred by CP partner', ' \u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0634\u0631\u0643\u0627\u0621 \u062d\u0645\u0627\u064a\u0629 \u0627\u0644\u0637\u0641\u0644 CP partner'), ('Referred by youth partner', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0634\u0631\u0643\u0627\u0621 \u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u0634\u0628\u0627\u0628 \u0648\u0627\u0644\u0645\u0631\u0627\u0647\u0642\u064a\u0646 youth'), ('Referral from another Municipality', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0627\u0644\u0628\u0644\u062f\u064a\u0629 / \u0645\u0631\u062c\u0639 \u0631\u0633\u0645\u064a'), ('Family walked in to NGO', '\u0645\u0646 \u0642\u0628\u0644 \u0627\u0647\u0644 \u0627\u0644\u0637\u0641\u0644 \u0645\u0628\u0627\u0634\u0631\u0629')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u062d\u0627\u0644\u0629 \u0627\u0644\u0637\u0641\u0644  \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ABLN'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0627\u0633\u0645 \u0648\u0627\u0644\u062f \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0627\u0633\u0645 \u0648\u0627\u0644\u062f\u0629 \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Cycle', verbose_name='\u0631\u0642\u0645'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', '\u0644\u0645 \u064a\u0633\u062c\u0644 \u0627\u0628\u062f\u0627 \u0641\u064a \u0627\u0644\u0645\u062f\u0631\u0633\u0629 \u0645\u0646 \u0642\u0628\u0644'), ('enrolled in formal education but did not continue', '\u0643\u0627\u0646 \u0645\u0633\u062c\u0644\u0627 \u0645\u062f\u0631\u0633\u0629 \u0646\u0636\u0627\u0645\u064a\u0647 \u0648\u0644\u0645 \u064a\u0643\u0645\u0644'), ('enrolled in ABLN', '\u0643\u0627\u0646 \u0645\u0633\u062c\u0644\u0627\u064b \u0641\u064a \u0645\u062f\u0631\u0633\u0629 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a\u0629 \u0648\u0644\u0645 \u064a\u0643\u0645\u0644')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a \u0644\u0644\u0637\u0641\u0644 \u0639\u0646\u062f \u0627\u0644\u062a\u0633\u062c\u064a\u0644 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='first_attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u062d\u0636\u0648\u0631 \u0627\u0644\u0637\u0641\u0644 \u0644\u0644\u0645\u0631\u0629 \u0627\u0644\u0623\u0648\u0644\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0623\u0648\u0644\u0649'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='labour_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0643\u0645 \u0633\u0627\u0639\u0629 \u064a\u0639\u0645\u0644 \u0647\u0630\u0627 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='new_registry',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u064a\u062a\u0645 \u062a\u0633\u062c\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0644\u0623\u0648\u0644 \u0645\u0631\u0629 \u0641\u064a \u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u062c\u0645\u0639\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.CLMRound', verbose_name='\u0631\u0642\u0645 \u0627\u0644\u062f\u0648\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Direct outreach', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u062d\u0645\u0644\u0627\u062a \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u0627\u0644\u062c\u0645\u0639\u064a\u0629'), ('List database', ' \u0627\u062d\u0644\u0629 \u0639\u0646 \u0637\u0631\u064a\u0642 Profiling Database'), ('Referral from another NGO', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u062c\u0645\u0639\u064a\u0629 \u0623\u062e\u0631\u0649'), ('Referred by CP partner', ' \u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0634\u0631\u0643\u0627\u0621 \u062d\u0645\u0627\u064a\u0629 \u0627\u0644\u0637\u0641\u0644 CP partner'), ('Referred by youth partner', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0634\u0631\u0643\u0627\u0621 \u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u0634\u0628\u0627\u0628 \u0648\u0627\u0644\u0645\u0631\u0627\u0647\u0642\u064a\u0646 youth'), ('Referral from another Municipality', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0627\u0644\u0628\u0644\u062f\u064a\u0629 / \u0645\u0631\u062c\u0639 \u0631\u0633\u0645\u064a'), ('Family walked in to NGO', '\u0645\u0646 \u0642\u0628\u0644 \u0627\u0647\u0644 \u0627\u0644\u0637\u0641\u0644 \u0645\u0628\u0627\u0634\u0631\u0629')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u062d\u0627\u0644\u0629 \u0627\u0644\u0637\u0641\u0644  \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ABLN'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0627\u0633\u0645 \u0648\u0627\u0644\u062f \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='\u0627\u0633\u0645 \u0648\u0627\u0644\u062f\u0629 \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='education_status',
            field=models.CharField(blank=True, choices=[('out of school', '\u0644\u0645 \u064a\u0633\u062c\u0644 \u0627\u0628\u062f\u0627 \u0641\u064a \u0627\u0644\u0645\u062f\u0631\u0633\u0629 \u0645\u0646 \u0642\u0628\u0644'), ('enrolled in formal education but did not continue', '\u0643\u0627\u0646 \u0645\u0633\u062c\u0644\u0627 \u0645\u062f\u0631\u0633\u0629 \u0646\u0636\u0627\u0645\u064a\u0647 \u0648\u0644\u0645 \u064a\u0643\u0645\u0644'), ('enrolled in ABLN', '\u0643\u0627\u0646 \u0645\u0633\u062c\u0644\u0627\u064b \u0641\u064a \u0645\u062f\u0631\u0633\u0629 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a\u0629 \u0648\u0644\u0645 \u064a\u0643\u0645\u0644')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a \u0644\u0644\u0637\u0641\u0644 \u0639\u0646\u062f \u0627\u0644\u062a\u0633\u062c\u064a\u0644 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='first_attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u062d\u0636\u0648\u0631 \u0627\u0644\u0637\u0641\u0644 \u0644\u0644\u0645\u0631\u0629 \u0627\u0644\u0623\u0648\u0644\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0623\u0648\u0644\u0649'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='labour_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0643\u0645 \u0633\u0627\u0639\u0629 \u064a\u0639\u0645\u0644 \u0647\u0630\u0627 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='new_registry',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u064a\u062a\u0645 \u062a\u0633\u062c\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0644\u0623\u0648\u0644 \u0645\u0631\u0629 \u0641\u064a \u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u062c\u0645\u0639\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referral_programme_type_1',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referral_programme_type_2',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referral_programme_type_3',
            field=models.CharField(blank=True, choices=[('CP (PSS and/or Case Management)', 'CP (PSS and/or Case Management)'), ('Health', 'Health'), ('WASH', 'WASH'), ('Specialized Services', 'Specialized Services'), ('Other', '\u0622\u062e\u0631'), ('No need', 'No need')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.CLMRound', verbose_name='\u0631\u0642\u0645 \u0627\u0644\u062f\u0648\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('Direct outreach', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u062d\u0645\u0644\u0627\u062a \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u0627\u0644\u062c\u0645\u0639\u064a\u0629'), ('List database', ' \u0627\u062d\u0644\u0629 \u0639\u0646 \u0637\u0631\u064a\u0642 Profiling Database'), ('Referral from another NGO', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u062c\u0645\u0639\u064a\u0629 \u0623\u062e\u0631\u0649'), ('Referred by CP partner', ' \u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0634\u0631\u0643\u0627\u0621 \u062d\u0645\u0627\u064a\u0629 \u0627\u0644\u0637\u0641\u0644 CP partner'), ('Referred by youth partner', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0634\u0631\u0643\u0627\u0621 \u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u0634\u0628\u0627\u0628 \u0648\u0627\u0644\u0645\u0631\u0627\u0647\u0642\u064a\u0646 youth'), ('Referral from another Municipality', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0627\u0644\u0628\u0644\u062f\u064a\u0629 / \u0645\u0631\u062c\u0639 \u0631\u0633\u0645\u064a'), ('Family walked in to NGO', '\u0645\u0646 \u0642\u0628\u0644 \u0627\u0647\u0644 \u0627\u0644\u0637\u0641\u0644 \u0645\u0628\u0627\u0634\u0631\u0629')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u062d\u0627\u0644\u0629 \u0627\u0644\u0637\u0641\u0644  \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ABLN'),
        ),
    ]
