# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-09 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0085_auto_20200309_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='source_of_transportation',
            field=models.CharField(blank=True, choices=[('Transportation provided by partner', 'Transportation provided by partner'), ('Walk', 'Walk'), ('private or parents', 'Private/Parents')], max_length=100, null=True, verbose_name='Source of transportation of the child'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='source_of_transportation',
            field=models.CharField(blank=True, choices=[('Transportation provided by partner', 'Transportation provided by partner'), ('Walk', 'Walk'), ('private or parents', 'Private/Parents')], max_length=100, null=True, verbose_name='Source of transportation of the child'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='source_of_transportation',
            field=models.CharField(blank=True, choices=[('Transportation provided by partner', 'Transportation provided by partner'), ('Walk', 'Walk'), ('private or parents', 'Private/Parents')], max_length=100, null=True, verbose_name='Source of transportation of the child'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='source_of_transportation',
            field=models.CharField(blank=True, choices=[('Transportation provided by partner', 'Transportation provided by partner'), ('Walk', 'Walk'), ('private or parents', 'Private/Parents')], max_length=100, null=True, verbose_name='Source of transportation of the child'),
        ),
    ]
