# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0098_auto_20200324_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='bln',
            name='round_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0628\u062f\u0627\u064a\u0629 \u0627\u0644\u062f\u0648\u0631\u0629 \u0641\u064a \u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='registration_level',
            field=models.CharField(blank=True, choices=[('', '----------'), ('level_one', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0623\u0648\u0644'), ('level_two', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062b\u0627\u0646\u064a')], max_length=100, null=True, verbose_name='\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0633\u062c\u064a\u0644'),
        ),
    ]
