# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-25 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0101_auto_20200325_1310'),
        ('clm', '0099_inclusion'),
    ]

    operations = [
    ]
