# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-25 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0101_merge_20200325_1234'),
        ('clm', '0103_bln_student_number_children'),
    ]

    operations = [
    ]
