# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-25 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0105_auto_20200325_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusion',
            name='main_caregiver',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0647\u0648 \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631 \u0627\u0644\u0631\u0626\u064a\u0633\u064a'),
        ),
    ]
