# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-25 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0106_inclusion_main_caregiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusion',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0627\u0644\u0645\u0648\u0642\u0639/\u0645\u0631\u0643\u0632'),
        ),
    ]
