# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-25 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0107_auto_20200326_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusion',
            name='barriers',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True, verbose_name='The main barriers affecting the daily attendance and performance'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('graduated_to_abln_next_round_same_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062c\u0648\u0644\u0629 \u0627\u0644\u062a\u0627\u0644\u064a\u0629 \u060c \u0646\u0641\u0633 \u0627\u0644\u0645\u0633\u062a\u0648\u0649'), ('graduated_to_abln_next_round_higher_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062c\u0648\u0644\u0629 \u0627\u0644\u062a\u0627\u0644\u064a\u0629 \u060c \u0645\u0633\u062a\u0648\u0649 \u0623\u0639\u0644\u0649'), ('referred_to_bln', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c BLN'), ('referred_to_ybln', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c YBLN'), ('referred_to_cbt', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c CBT')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
    ]
