# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-26 07:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0055_merge_20200320_2135'),
        ('schools', '0048_auto_20200117_1032'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0006_auto_20191219_1302'),
        ('clm', '0108_auto_20200326_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='main_caregiver',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0647\u0648 \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631 \u0627\u0644\u0631\u0626\u064a\u0633\u064a'),
        ),
        migrations.AddField(
            model_name='abln',
            name='round_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0628\u062f\u0627\u064a\u0629 \u0627\u0644\u062f\u0648\u0631\u0629 \u0641\u064a \u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
        migrations.AddField(
            model_name='abln',
            name='student_number_children',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True, verbose_name='\u062d\u062f\u062f \u0639\u062f\u062f \u0627\u0644\u0623\u0637\u0641\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='registration_level',
            field=models.CharField(blank=True, choices=[('', '----------'), ('level_one', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0623\u0648\u0644'), ('level_two', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062b\u0627\u0646\u064a')], max_length=100, null=True, verbose_name='\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0633\u062c\u064a\u0644'),
        ),
    ]
