# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0110_auto_20200408_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='phone_owner',
            field=models.CharField(blank=True, choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0627\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645'),
        ),
        migrations.AddField(
            model_name='bln',
            name='phone_owner',
            field=models.CharField(blank=True, choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0627\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645'),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='phone_owner',
            field=models.CharField(blank=True, choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0627\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0645\u0646\u0637\u0642\u0629 \u0639\u0642\u0627\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0642\u0636\u0627\u0621'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0645\u062d\u0627\u0641\u0638\u0629'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0645\u0648\u0642\u0639/\u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0645\u0646\u0637\u0642\u0629 \u0639\u0642\u0627\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0642\u0636\u0627\u0621'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0645\u062d\u0627\u0641\u0638\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0645\u0648\u0642\u0639/\u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0645\u0646\u0637\u0642\u0629 \u0639\u0642\u0627\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0642\u0636\u0627\u0621'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0645\u062d\u0627\u0641\u0638\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0645\u0648\u0642\u0639/\u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0645\u0646\u0637\u0642\u0629 \u0639\u0642\u0627\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0642\u0636\u0627\u0621'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0645\u062d\u0627\u0641\u0638\u0629'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0645\u0648\u0642\u0639/\u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0645\u0646\u0637\u0642\u0629 \u0639\u0642\u0627\u0631\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0642\u0636\u0627\u0621'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0645\u062d\u0627\u0641\u0638\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0645\u0648\u0642\u0639/\u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
    ]
