# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-14 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0056_auto_20200414_1021'),
        ('clm', '0111_auto_20200414_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='main_caregiver_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Nationality', verbose_name='Main Caregiver Nationality'),
        ),
        migrations.AddField(
            model_name='bln',
            name='main_caregiver_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Nationality', verbose_name='Main Caregiver Nationality'),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='main_caregiver_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Nationality', verbose_name='Main Caregiver Nationality'),
        ),
    ]
