# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-14 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0113_auto_20200414_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='other_caregiver_relationship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0645\u0627 \u0647\u064a \u0635\u0644\u0629 \u0627\u0644\u0642\u0631\u0627\u0628\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='other_caregiver_relationship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0645\u0627 \u0647\u064a \u0635\u0644\u0629 \u0627\u0644\u0642\u0631\u0627\u0628\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='other_caregiver_relationship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0645\u0627 \u0647\u064a \u0635\u0644\u0629 \u0627\u0644\u0642\u0631\u0627\u0628\u0629\u061f'),
        ),
    ]
