# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0114_auto_20200414_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Phone number'),
        ),
        migrations.AddField(
            model_name='abln',
            name='second_phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u062a\u0623\u0643\u064a\u062f \u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
        migrations.AddField(
            model_name='bln',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Phone number'),
        ),
        migrations.AddField(
            model_name='bln',
            name='second_phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u062a\u0623\u0643\u064a\u062f \u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Phone number'),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='second_phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u062a\u0623\u0643\u064a\u062f \u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
    ]
