# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-15 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0118_auto_20200415_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='second_phone_owner',
            field=models.CharField(blank=True, choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0627\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='Second Phone Owner'),
        ),
        migrations.AddField(
            model_name='bln',
            name='second_phone_owner',
            field=models.CharField(blank=True, choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0627\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='Second Phone Owner'),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='second_phone_owner',
            field=models.CharField(blank=True, choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0627\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='Second Phone Owner'),
        ),
    ]
