# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0123_auto_20200423_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Other nationality', '\u0645\u0646 \u062c\u0646\u0633\u064a\u0629 \u0623\u062e\u0631\u0649'), ('Child have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642 ')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Other nationality', '\u0645\u0646 \u062c\u0646\u0633\u064a\u0629 \u0623\u062e\u0631\u0649'), ('Child have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642 ')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Other nationality', '\u0645\u0646 \u062c\u0646\u0633\u064a\u0629 \u0623\u062e\u0631\u0649'), ('Child have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642 ')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Other nationality', '\u0645\u0646 \u062c\u0646\u0633\u064a\u0629 \u0623\u062e\u0631\u0649'), ('Child have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642 ')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0633\u0648\u0631\u064a\u0629'), ('Palestinian national ID', '\u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0641\u0644\u0633\u0637\u0646\u064a\u0629'), ('Lebanese national ID', '\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u0647\u0648\u064a\u0629 \u0627\u0644\u0644\u0628\u0646\u0627\u0646\u064a\u0629'), ('Other nationality', '\u0645\u0646 \u062c\u0646\u0633\u064a\u0629 \u0623\u062e\u0631\u0649'), ('Child have no ID', '\u0628\u062f\u0648\u0646 \u0627\u0648\u0631\u0627\u0642 ')], max_length=100, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
    ]
