# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-30 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0125_auto_20200424_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('thousand_or_less', '\u0661\u0660\u066b\u0660\u0660\u0660 \u0644.\u0644. \u0623\u0648 \u0623\u0642\u0644'), ('eleven_thousand_to_twenty_five', '\u0645\u0646 \u0661\u0661\u066c\u0660\u0660\u0660 \u0625\u0644\u0649 \u0662\u0665\u066c\u0660\u0660\u0660 \u0644.\u0644.'), ('twenty_six_thousand_to_fifty', '\u0645\u0646 \u0662\u0666\u066c\u0660\u0660\u0660 \u0625\u0644\u0649 \u0665\u0660\u066c\u0660\u0660\u0660 \u0644.\u0644.'), ('more_than_fifty', '\u0623\u0643\u062b\u0631 \u0645\u0646 \u0665\u0665\u066c\u0660\u0660\u0660 \u0644.\u0644.')], max_length=100, null=True, verbose_name='\u0643\u0645 \u064a\u062c\u0646\u064a \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0627\u0644\u0639\u0645\u0644 \u0641\u064a \u0627\u0644\u0627\u0633\u0628\u0648\u0639\u061f'),
        ),
        migrations.AddField(
            model_name='bln',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('thousand_or_less', '\u0661\u0660\u066b\u0660\u0660\u0660 \u0644.\u0644. \u0623\u0648 \u0623\u0642\u0644'), ('eleven_thousand_to_twenty_five', '\u0645\u0646 \u0661\u0661\u066c\u0660\u0660\u0660 \u0625\u0644\u0649 \u0662\u0665\u066c\u0660\u0660\u0660 \u0644.\u0644.'), ('twenty_six_thousand_to_fifty', '\u0645\u0646 \u0662\u0666\u066c\u0660\u0660\u0660 \u0625\u0644\u0649 \u0665\u0660\u066c\u0660\u0660\u0660 \u0644.\u0644.'), ('more_than_fifty', '\u0623\u0643\u062b\u0631 \u0645\u0646 \u0665\u0665\u066c\u0660\u0660\u0660 \u0644.\u0644.')], max_length=100, null=True, verbose_name='\u0643\u0645 \u064a\u062c\u0646\u064a \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0627\u0644\u0639\u0645\u0644 \u0641\u064a \u0627\u0644\u0627\u0633\u0628\u0648\u0639\u061f'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('thousand_or_less', '\u0661\u0660\u066b\u0660\u0660\u0660 \u0644.\u0644. \u0623\u0648 \u0623\u0642\u0644'), ('eleven_thousand_to_twenty_five', '\u0645\u0646 \u0661\u0661\u066c\u0660\u0660\u0660 \u0625\u0644\u0649 \u0662\u0665\u066c\u0660\u0660\u0660 \u0644.\u0644.'), ('twenty_six_thousand_to_fifty', '\u0645\u0646 \u0662\u0666\u066c\u0660\u0660\u0660 \u0625\u0644\u0649 \u0665\u0660\u066c\u0660\u0660\u0660 \u0644.\u0644.'), ('more_than_fifty', '\u0623\u0643\u062b\u0631 \u0645\u0646 \u0665\u0665\u066c\u0660\u0660\u0660 \u0644.\u0644.')], max_length=100, null=True, verbose_name='\u0643\u0645 \u064a\u062c\u0646\u064a \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0627\u0644\u0639\u0645\u0644 \u0641\u064a \u0627\u0644\u0627\u0633\u0628\u0648\u0639\u061f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('thousand_or_less', '\u0661\u0660\u066b\u0660\u0660\u0660 \u0644.\u0644. \u0623\u0648 \u0623\u0642\u0644'), ('eleven_thousand_to_twenty_five', '\u0645\u0646 \u0661\u0661\u066c\u0660\u0660\u0660 \u0625\u0644\u0649 \u0662\u0665\u066c\u0660\u0660\u0660 \u0644.\u0644.'), ('twenty_six_thousand_to_fifty', '\u0645\u0646 \u0662\u0666\u066c\u0660\u0660\u0660 \u0625\u0644\u0649 \u0665\u0660\u066c\u0660\u0660\u0660 \u0644.\u0644.'), ('more_than_fifty', '\u0623\u0643\u062b\u0631 \u0645\u0646 \u0665\u0665\u066c\u0660\u0660\u0660 \u0644.\u0644.')], max_length=100, null=True, verbose_name='\u0643\u0645 \u064a\u062c\u0646\u064a \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0627\u0644\u0639\u0645\u0644 \u0641\u064a \u0627\u0644\u0627\u0633\u0628\u0648\u0639\u061f'),
        ),
    ]
