# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0141_auto_20200724_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='How well did the child meet the learning outcomes?'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='parent_learning_support_rate',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='How do you rate the parents learning support provided to the child through this Remote learning phase?'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='remote_learning_engagement',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='Frequency of Child Engagement in remote learning?'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='How well did the child meet the learning outcomes?'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='parent_learning_support_rate',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='How do you rate the parents learning support provided to the child through this Remote learning phase?'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='remote_learning_engagement',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='Frequency of Child Engagement in remote learning?'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='How well did the child meet the learning outcomes?'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='parent_learning_support_rate',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='How do you rate the parents learning support provided to the child through this Remote learning phase?'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='remote_learning_engagement',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='Frequency of Child Engagement in remote learning?'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='How well did the child meet the learning outcomes?'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='parent_learning_support_rate',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='How do you rate the parents learning support provided to the child through this Remote learning phase?'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='remote_learning_engagement',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='Frequency of Child Engagement in remote learning?'),
        ),
    ]
