# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-29 10:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0144_auto_20200729_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='follow_up_done',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Was any follow-up done to ensure messages were well received, understood and adopted?'),
        ),
        migrations.AddField(
            model_name='bln',
            name='follow_up_done',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Was any follow-up done to ensure messages were well received, understood and adopted?'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='follow_up_done',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Was any follow-up done to ensure messages were well received, understood and adopted?'),
        ),
        migrations.AddField(
            model_name='rs',
            name='follow_up_done',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Was any follow-up done to ensure messages were well received, understood and adopted?'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('no_barriers', '\u0644\u0627 \u064a\u0648\u062c\u062f'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='barriers_single',
            field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('no_barriers', '\u0644\u0627 \u064a\u0648\u062c\u062f'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='The main barriers affecting the daily attendance and performance'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0627\u0644\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='covid_message_how_often',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='gender_participate',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0643\u0644 \u0645\u0646 \u0627\u0644\u0641\u062a\u064a\u0627\u062a \u0648\u0627\u0644\u0641\u062a\u064a\u0627\u0646 \u0645\u0646 \u0646\u0641\u0633 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0641\u064a \u0627\u0644\u0641\u0635\u0644 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0648\u062a\u0645\u0643\u0646\u0648\u0627 \u0645\u0646 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0627\u0644\u0647\u0627\u062a\u0641/\u0627\u0644\u062c\u0647\u0627\u0632\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='gender_participate_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0634\u0631\u062d'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0642\u064a\u064a\u0645 \u0642\u062f\u0631\u0629 \u0627\u0644\u0637\u0641\u0644  \u0641\u064a \u0641\u0647\u0645 \u0627\u0644\u0645\u0646\u0647\u062c \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0627\u0644\u0645\u0639\u062a\u0645\u062f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='parent_learning_support_rate',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0642\u064a\u0645 \u062f\u0639\u0645 \u0627\u0623\u0647\u0644 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u062a\u0642\u062f\u064a\u0645 \u0627\u0644\u0645\u0633\u0627\u0639\u062f\u0629 \u0627\u0644\u0645\u0637\u0644\u0648\u0628\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='phone_owner',
            field=models.CharField(choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='pss_kit',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0639\u062f\u0629 \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='reliable_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627'), ('sometimes', 'Sometimes')], max_length=10, null=True, verbose_name='\u0647\u0644  \u062e\u062f\u0645\u0629 \u0625\u0646\u062a\u0631\u0646\u062a \u0645\u062a\u0648\u0641\u0631\u0629 \u0644\u0644\u0623\u0647\u0644 \u0641\u064a \u0645\u0646\u0637\u0642\u062a\u0647\u0645 \u0623\u062b\u0646\u0627\u0621 \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='remote_learning_engagement',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0645\u0639\u062f\u0644 \u0627\u0646\u062e\u0631\u0627\u0637 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='second_phone_owner',
            field=models.CharField(blank=True, choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('no_barriers', '\u0644\u0627 \u064a\u0648\u062c\u062f'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='barriers_single',
            field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('no_barriers', '\u0644\u0627 \u064a\u0648\u062c\u062f'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='The main barriers affecting the daily attendance and performance'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0627\u0644\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_message_how_often',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='gender_participate',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0643\u0644 \u0645\u0646 \u0627\u0644\u0641\u062a\u064a\u0627\u062a \u0648\u0627\u0644\u0641\u062a\u064a\u0627\u0646 \u0645\u0646 \u0646\u0641\u0633 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0641\u064a \u0627\u0644\u0641\u0635\u0644 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0648\u062a\u0645\u0643\u0646\u0648\u0627 \u0645\u0646 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0627\u0644\u0647\u0627\u062a\u0641/\u0627\u0644\u062c\u0647\u0627\u0632\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='gender_participate_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0634\u0631\u062d'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0642\u064a\u064a\u0645 \u0642\u062f\u0631\u0629 \u0627\u0644\u0637\u0641\u0644  \u0641\u064a \u0641\u0647\u0645 \u0627\u0644\u0645\u0646\u0647\u062c \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0627\u0644\u0645\u0639\u062a\u0645\u062f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='parent_learning_support_rate',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0642\u064a\u0645 \u062f\u0639\u0645 \u0627\u0623\u0647\u0644 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u062a\u0642\u062f\u064a\u0645 \u0627\u0644\u0645\u0633\u0627\u0639\u062f\u0629 \u0627\u0644\u0645\u0637\u0644\u0648\u0628\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='phone_owner',
            field=models.CharField(choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='pss_kit',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0639\u062f\u0629 \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='reliable_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627'), ('sometimes', 'Sometimes')], max_length=10, null=True, verbose_name='\u0647\u0644  \u062e\u062f\u0645\u0629 \u0625\u0646\u062a\u0631\u0646\u062a \u0645\u062a\u0648\u0641\u0631\u0629 \u0644\u0644\u0623\u0647\u0644 \u0641\u064a \u0645\u0646\u0637\u0642\u062a\u0647\u0645 \u0623\u062b\u0646\u0627\u0621 \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='remote_learning_engagement',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0645\u0639\u062f\u0644 \u0627\u0646\u062e\u0631\u0627\u0637 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='second_phone_owner',
            field=models.CharField(blank=True, choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('no_barriers', '\u0644\u0627 \u064a\u0648\u062c\u062f'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='barriers_single',
            field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('no_barriers', '\u0644\u0627 \u064a\u0648\u062c\u062f'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='The main barriers affecting the daily attendance and performance'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0627\u0644\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_message_how_often',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='gender_participate',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0643\u0644 \u0645\u0646 \u0627\u0644\u0641\u062a\u064a\u0627\u062a \u0648\u0627\u0644\u0641\u062a\u064a\u0627\u0646 \u0645\u0646 \u0646\u0641\u0633 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0641\u064a \u0627\u0644\u0641\u0635\u0644 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0648\u062a\u0645\u0643\u0646\u0648\u0627 \u0645\u0646 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0627\u0644\u0647\u0627\u062a\u0641/\u0627\u0644\u062c\u0647\u0627\u0632\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='gender_participate_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0634\u0631\u062d'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0642\u064a\u064a\u0645 \u0642\u062f\u0631\u0629 \u0627\u0644\u0637\u0641\u0644  \u0641\u064a \u0641\u0647\u0645 \u0627\u0644\u0645\u0646\u0647\u062c \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0627\u0644\u0645\u0639\u062a\u0645\u062f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='parent_learning_support_rate',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0642\u064a\u0645 \u062f\u0639\u0645 \u0627\u0623\u0647\u0644 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u062a\u0642\u062f\u064a\u0645 \u0627\u0644\u0645\u0633\u0627\u0639\u062f\u0629 \u0627\u0644\u0645\u0637\u0644\u0648\u0628\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='phone_owner',
            field=models.CharField(choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='pss_kit',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0639\u062f\u0629 \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='reliable_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627'), ('sometimes', 'Sometimes')], max_length=10, null=True, verbose_name='\u0647\u0644  \u062e\u062f\u0645\u0629 \u0625\u0646\u062a\u0631\u0646\u062a \u0645\u062a\u0648\u0641\u0631\u0629 \u0644\u0644\u0623\u0647\u0644 \u0641\u064a \u0645\u0646\u0637\u0642\u062a\u0647\u0645 \u0623\u062b\u0646\u0627\u0621 \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='remote_learning_engagement',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0645\u0639\u062f\u0644 \u0627\u0646\u062e\u0631\u0627\u0637 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='second_phone_owner',
            field=models.CharField(blank=True, choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='phone_owner',
            field=models.CharField(choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='second_phone_owner',
            field=models.CharField(blank=True, choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('no_barriers', '\u0644\u0627 \u064a\u0648\u062c\u062f'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='barriers_single',
            field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('transportation', '\u0627\u0644\u0646\u0642\u0644\u064a\u0627\u062a  '), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u0628\u062f\u064a\u0644 \u0645\u0643\u0627\u0646 \u0627\u0644\u0633\u0643\u0646'), ('Moved back to Syria', '\u0627\u0646\u062a\u0642\u0644 \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0627\u0633\u0627\u0633\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629/\u062d\u0645\u0644'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('no_barriers', '\u0644\u0627 \u064a\u0648\u062c\u062f'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='The main barriers affecting the daily attendance and performance'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0627\u0644\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_message_how_often',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='gender_participate',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0643\u0644 \u0645\u0646 \u0627\u0644\u0641\u062a\u064a\u0627\u062a \u0648\u0627\u0644\u0641\u062a\u064a\u0627\u0646 \u0645\u0646 \u0646\u0641\u0633 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0641\u064a \u0627\u0644\u0641\u0635\u0644 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0648\u062a\u0645\u0643\u0646\u0648\u0627 \u0645\u0646 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0627\u0644\u0647\u0627\u062a\u0641/\u0627\u0644\u062c\u0647\u0627\u0632\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='gender_participate_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0634\u0631\u062d'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0642\u064a\u064a\u0645 \u0642\u062f\u0631\u0629 \u0627\u0644\u0637\u0641\u0644  \u0641\u064a \u0641\u0647\u0645 \u0627\u0644\u0645\u0646\u0647\u062c \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0627\u0644\u0645\u0639\u062a\u0645\u062f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='parent_learning_support_rate',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0642\u064a\u0645 \u062f\u0639\u0645 \u0627\u0623\u0647\u0644 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u062a\u0642\u062f\u064a\u0645 \u0627\u0644\u0645\u0633\u0627\u0639\u062f\u0629 \u0627\u0644\u0645\u0637\u0644\u0648\u0628\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pss_kit',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0639\u062f\u0629 \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='reliable_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627'), ('sometimes', 'Sometimes')], max_length=10, null=True, verbose_name='\u0647\u0644  \u062e\u062f\u0645\u0629 \u0625\u0646\u062a\u0631\u0646\u062a \u0645\u062a\u0648\u0641\u0631\u0629 \u0644\u0644\u0623\u0647\u0644 \u0641\u064a \u0645\u0646\u0637\u0642\u062a\u0647\u0645 \u0623\u062b\u0646\u0627\u0621 \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='remote_learning_engagement',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', 'Less than 25%')], max_length=100, null=True, verbose_name='\u0645\u0639\u062f\u0644 \u0627\u0646\u062e\u0631\u0627\u0637 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
    ]
