# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-29 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0145_auto_20200729_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='follow_up_done_with_who',
            field=models.CharField(blank=True, choices=[('child', 'Child'), ('caregiver', 'Caregiver'), ('childand_or_caregiver', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=50, null=True, verbose_name='With who child and/or caregiver?'),
        ),
        migrations.AddField(
            model_name='bln',
            name='follow_up_done_with_who',
            field=models.CharField(blank=True, choices=[('child', 'Child'), ('caregiver', 'Caregiver'), ('childand_or_caregiver', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=50, null=True, verbose_name='With who child and/or caregiver?'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='follow_up_done_with_who',
            field=models.CharField(blank=True, choices=[('child', 'Child'), ('caregiver', 'Caregiver'), ('childand_or_caregiver', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=50, null=True, verbose_name='With who child and/or caregiver?'),
        ),
        migrations.AddField(
            model_name='rs',
            name='follow_up_done_with_who',
            field=models.CharField(blank=True, choices=[('child', 'Child'), ('caregiver', 'Caregiver'), ('childand_or_caregiver', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629/\u0627\u0644\u0639\u0631\u0628\u064a\u0629')], max_length=50, null=True, verbose_name='With who child and/or caregiver?'),
        ),
    ]
