# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0147_auto_20200729_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('every_2_to_3_days', 'Every 2-3 days'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('every_2_to_3_days', 'Every 2-3 days'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('every_2_to_3_days', 'Every 2-3 days'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('every_2_to_3_days', 'Every 2-3 days'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('every_2_to_3_days', 'Every 2-3 days'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('every_2_to_3_days', 'Every 2-3 days'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('every_2_to_3_days', 'Every 2-3 days'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('every_2_to_3_days', 'Every 2-3 days'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
    ]
