# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-03 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0148_auto_20200729_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', '\u064a\u0648\u0645\u064a\u0627\u064b'), ('every_2_to_3_days', '\u0643\u0644 \u064a\u0648\u0645\u064a\u0646 \u0627\u0648 \u062b\u0644\u0627\u062b'), ('weekly', '\u0643\u0644 \u0623\u0633\u0628\u0648\u0639'), ('biweekly', '\u0643\u0644 \u0627\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', '\u064a\u0648\u0645\u064a\u0627\u064b'), ('every_2_to_3_days', '\u0643\u0644 \u064a\u0648\u0645\u064a\u0646 \u0627\u0648 \u062b\u0644\u0627\u062b'), ('weekly', '\u0643\u0644 \u0623\u0633\u0628\u0648\u0639'), ('biweekly', '\u0643\u0644 \u0627\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', '\u0623\u0642\u0644 \u0645\u0646 25%')], max_length=100, null=True, verbose_name='\u0627\u0644\u0649 \u0627\u064a \u0645\u062f\u0649 \u062a\u0645\u0643\u0646 \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u062a\u062d\u0642\u064a\u0642 \u0646\u062a\u0627\u0626\u062c \u0627\u0644\u062a\u0639\u0644\u0645 \u0627\u0644\u0645\u0631\u062c\u0648\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', '\u064a\u0648\u0645\u064a\u0627\u064b'), ('every_2_to_3_days', '\u0643\u0644 \u064a\u0648\u0645\u064a\u0646 \u0627\u0648 \u062b\u0644\u0627\u062b'), ('weekly', '\u0643\u0644 \u0623\u0633\u0628\u0648\u0639'), ('biweekly', '\u0643\u0644 \u0627\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', '\u064a\u0648\u0645\u064a\u0627\u064b'), ('every_2_to_3_days', '\u0643\u0644 \u064a\u0648\u0645\u064a\u0646 \u0627\u0648 \u062b\u0644\u0627\u062b'), ('weekly', '\u0643\u0644 \u0623\u0633\u0628\u0648\u0639'), ('biweekly', '\u0643\u0644 \u0627\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', '\u0623\u0642\u0644 \u0645\u0646 25%')], max_length=100, null=True, verbose_name='\u0627\u0644\u0649 \u0627\u064a \u0645\u062f\u0649 \u062a\u0645\u0643\u0646 \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u062a\u062d\u0642\u064a\u0642 \u0646\u062a\u0627\u0626\u062c \u0627\u0644\u062a\u0639\u0644\u0645 \u0627\u0644\u0645\u0631\u062c\u0648\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', '\u064a\u0648\u0645\u064a\u0627\u064b'), ('every_2_to_3_days', '\u0643\u0644 \u064a\u0648\u0645\u064a\u0646 \u0627\u0648 \u062b\u0644\u0627\u062b'), ('weekly', '\u0643\u0644 \u0623\u0633\u0628\u0648\u0639'), ('biweekly', '\u0643\u0644 \u0627\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', '\u064a\u0648\u0645\u064a\u0627\u064b'), ('every_2_to_3_days', '\u0643\u0644 \u064a\u0648\u0645\u064a\u0646 \u0627\u0648 \u062b\u0644\u0627\u062b'), ('weekly', '\u0643\u0644 \u0623\u0633\u0628\u0648\u0639'), ('biweekly', '\u0643\u0644 \u0627\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', '\u0623\u0642\u0644 \u0645\u0646 25%')], max_length=100, null=True, verbose_name='\u0627\u0644\u0649 \u0627\u064a \u0645\u062f\u0649 \u062a\u0645\u0643\u0646 \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u062a\u062d\u0642\u064a\u0642 \u0646\u062a\u0627\u0626\u062c \u0627\u0644\u062a\u0639\u0644\u0645 \u0627\u0644\u0645\u0631\u062c\u0648\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', '\u064a\u0648\u0645\u064a\u0627\u064b'), ('every_2_to_3_days', '\u0643\u0644 \u064a\u0648\u0645\u064a\u0646 \u0627\u0648 \u062b\u0644\u0627\u062b'), ('weekly', '\u0643\u0644 \u0623\u0633\u0628\u0648\u0639'), ('biweekly', '\u0643\u0644 \u0627\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('daily', '\u064a\u0648\u0645\u064a\u0627\u064b'), ('every_2_to_3_days', '\u0643\u0644 \u064a\u0648\u0645\u064a\u0646 \u0627\u0648 \u062b\u0644\u0627\u062b'), ('weekly', '\u0643\u0644 \u0623\u0633\u0628\u0648\u0639'), ('biweekly', '\u0643\u0644 \u0627\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='meet_learning_outcomes',
            field=models.CharField(blank=True, choices=[('hundred', '100%'), ('seventy_five', '75%'), ('fifty', '50%'), ('twenty_five', '25%'), ('less_than_twenty_five', '\u0623\u0642\u0644 \u0645\u0646 25%')], max_length=100, null=True, verbose_name='\u0627\u0644\u0649 \u0627\u064a \u0645\u062f\u0649 \u062a\u0645\u0643\u0646 \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u062a\u062d\u0642\u064a\u0642 \u0646\u062a\u0627\u0626\u062c \u0627\u0644\u062a\u0639\u0644\u0645 \u0627\u0644\u0645\u0631\u062c\u0648\u0629\u061f'),
        ),
    ]
