# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0149_auto_20200803_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='reasons_not_engaged_other',
            field=models.TextField(blank=True, null=True, verbose_name='Please specify'),
        ),
        migrations.AddField(
            model_name='abln',
            name='remote_learning_reasons_not_engaged',
            field=models.CharField(blank=True, choices=[('child_relocated', 'Child relocated'), ('child_is_not_reachable', 'Child is not reachable'), ('child_did_not_fit_the_criteria', 'Child didn\u2019t fit the criteria (enrolled in previous FE)'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AddField(
            model_name='bln',
            name='reasons_not_engaged_other',
            field=models.TextField(blank=True, null=True, verbose_name='Please specify'),
        ),
        migrations.AddField(
            model_name='bln',
            name='remote_learning_reasons_not_engaged',
            field=models.CharField(blank=True, choices=[('child_relocated', 'Child relocated'), ('child_is_not_reachable', 'Child is not reachable'), ('child_did_not_fit_the_criteria', 'Child didn\u2019t fit the criteria (enrolled in previous FE)'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='reasons_not_engaged_other',
            field=models.TextField(blank=True, null=True, verbose_name='Please specify'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='remote_learning_reasons_not_engaged',
            field=models.CharField(blank=True, choices=[('child_relocated', 'Child relocated'), ('child_is_not_reachable', 'Child is not reachable'), ('child_did_not_fit_the_criteria', 'Child didn\u2019t fit the criteria (enrolled in previous FE)'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
        migrations.AddField(
            model_name='rs',
            name='reasons_not_engaged_other',
            field=models.TextField(blank=True, null=True, verbose_name='Please specify'),
        ),
        migrations.AddField(
            model_name='rs',
            name='remote_learning_reasons_not_engaged',
            field=models.CharField(blank=True, choices=[('child_relocated', 'Child relocated'), ('child_is_not_reachable', 'Child is not reachable'), ('child_did_not_fit_the_criteria', 'Child didn\u2019t fit the criteria (enrolled in previous FE)'), ('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
    ]
