# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0150_auto_20200803_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='remote_learning_reasons_not_engaged',
            field=models.CharField(blank=True, choices=[('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Was the child engaged in remote learning?'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='remote_learning_reasons_not_engaged',
            field=models.CharField(blank=True, choices=[('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Was the child engaged in remote learning?'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='remote_learning_reasons_not_engaged',
            field=models.CharField(blank=True, choices=[('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Was the child engaged in remote learning?'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='remote_learning_reasons_not_engaged',
            field=models.CharField(blank=True, choices=[('Other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='Was the child engaged in remote learning?'),
        ),
    ]
