# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0152_auto_20200803_1442'),
    ]

    operations = [

    ]
