# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-14 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0158_auto_20201012_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='main_caregiver_nationality_other',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='bln',
            name='main_caregiver_nationality_other',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
    ]
