# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0160_auto_20201020_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='participation',
            field=models.CharField(blank=True, choices=[('', '----------'), ('no_absence', '\u0644\u0627 \u063a\u064a\u0627\u0628'), ('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('15_25_days', '15 to 25 absence days'), ('more_than_25days', 'More than 25 absence days')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
        migrations.AlterField(
            model_name='bln',
            name='participation',
            field=models.CharField(blank=True, choices=[('', '----------'), ('no_absence', '\u0644\u0627 \u063a\u064a\u0627\u0628'), ('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('15_25_days', '15 to 25 absence days'), ('more_than_25days', 'More than 25 absence days')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='participation',
            field=models.CharField(blank=True, choices=[('', '----------'), ('no_absence', '\u0644\u0627 \u063a\u064a\u0627\u0628'), ('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('15_25_days', '15 to 25 absence days'), ('more_than_25days', 'More than 25 absence days')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
        migrations.AlterField(
            model_name='rs',
            name='participation',
            field=models.CharField(blank=True, choices=[('', '----------'), ('no_absence', '\u0644\u0627 \u063a\u064a\u0627\u0628'), ('less_than_5days', '\u0623\u0642\u0644 \u0645\u0646 5 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('5_10_days', '5-10 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('10_15_days', '10-15 \u0623\u064a\u0627\u0645 \u063a\u064a\u0627\u0628'), ('15_25_days', '15 to 25 absence days'), ('more_than_25days', 'More than 25 absence days')], max_length=100, null=True, verbose_name='\u0627\u0644\u0645\u0634\u0627\u0631\u0643\u0629  '),
        ),
    ]
