# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-28 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0162_auto_20201027_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='Followup_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='abln',
            name='Followup_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='abln',
            name='Followup_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AddField(
            model_name='abln',
            name='covid_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='abln',
            name='covid_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='abln',
            name='covid_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AddField(
            model_name='abln',
            name='parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='abln',
            name='pss_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='abln',
            name='pss_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='abln',
            name='pss_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AddField(
            model_name='bln',
            name='Followup_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='bln',
            name='Followup_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='bln',
            name='Followup_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AddField(
            model_name='bln',
            name='covid_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='bln',
            name='covid_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='bln',
            name='covid_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AddField(
            model_name='bln',
            name='parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='bln',
            name='pss_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='bln',
            name='pss_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='bln',
            name='pss_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='Followup_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='Followup_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='Followup_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='covid_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='covid_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='covid_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='pss_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='pss_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='pss_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AddField(
            model_name='rs',
            name='Followup_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='rs',
            name='Followup_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='rs',
            name='Followup_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AddField(
            model_name='rs',
            name='covid_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='rs',
            name='covid_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='rs',
            name='covid_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AddField(
            model_name='rs',
            name='parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='pss_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Attended PSS Session'),
        ),
        migrations.AddField(
            model_name='rs',
            name='pss_session_modality',
            field=models.CharField(blank=True, choices=[('online', 'Online via Whatsapp'), ('phone', 'Phone calls'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=100, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AddField(
            model_name='rs',
            name='pss_session_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PSS session number'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('graduated_to_abln_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('graduated_to_abln_next_round_same_level', '\u0625\u0643\u0645\u0627\u0644 \u0641\u064a \u0646\u0641\u0633 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0642\u0627\u062f\u0645\u0629'), ('graduated_to_abln_next_round_higher_level', '\u064a\u0631\u0641\u0639 \u0625\u0627\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0623\u0639\u0644\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0642\u0627\u062f\u0645\u0629'), ('referred_to_bln', ' \u0627\u0644\u0623\u062d\u0627\u0644\u0629 \u0645\u0646 ABLN \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c BLN'), ('referred_to_ybln', '\u0627\u0644\u0623\u062d\u0627\u0644\u0629 \u0625\u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u0645\u0631\u0627\u0647\u0642\u064a\u0646 (YBLN)'), ('referred_to_alp', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ALP'), ('referred_to_cbt', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c CBT'), ('dropout', '\u0627\u0644\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='round_complete',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u0627\u062a\u0645 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u062f\u0648\u0631\u0629 \u0628\u0646\u062c\u0627\u062d\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('graduated_to_bln_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('graduated_to_bln_next_round_same_level', '\u0625\u0643\u0645\u0627\u0644 \u0641\u064a \u0646\u0641\u0633 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0642\u0627\u062f\u0645\u0629'), ('graduated_to_bln_next_round_higher_level', '\u064a\u0631\u0641\u0639 \u0625\u0627\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0623\u0639\u0644\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0642\u0627\u062f\u0645\u0629'), ('referred_to_alp', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ALP'), ('referred_public_school', '\u0627\u0644\u0623\u062d\u0627\u0644\u0629 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('referred_to_tvet', '\u0627\u0644\u0623\u062d\u0627\u0644\u0629 \u0627\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0645\u0647\u0646\u064a \u0648 \u0627\u0644\u062a\u0642\u0646\u064a (TVET)'), ('referred_to_ybln', '\u0627\u0644\u0623\u062d\u0627\u0644\u0629 \u0625\u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u0645\u0631\u0627\u0647\u0642\u064a\u0646 (YBLN)'), ('dropout', '\u0627\u0644\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='round_complete',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u0627\u062a\u0645 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u062f\u0648\u0631\u0629 \u0628\u0646\u062c\u0627\u062d\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('graduated_to_formal_kg', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0631\u0648\u0636\u0629'), ('graduated_to_formal_level1', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0646\u0638\u0627\u0645\u064a - \u0627\u0644\u0635\u0641 \u0627\u0644\u0623\u0648\u0644'), ('referred_to_another_program', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0622\u062e\u0631 \u062e\u0644\u0627\u0644 \u0627\u0644\u062f\u0648\u0631\u0629'), ('dropout', 'Dropout from school'), ('repeat_level', '\u0625\u0639\u0627\u062f\u0629 \u0627\u0644\u0645\u0633\u062a\u0648\u0649'), ('graduated_next_round_higher_level', '\u064a\u0631\u0641\u0639 \u0625\u0627\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0623\u0639\u0644\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0642\u0627\u062f\u0645\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='round_complete',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u0627\u062a\u0645 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u062f\u0648\u0631\u0629 \u0628\u0646\u062c\u0627\u062d\u061f'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('graduated_to_abln_next_round_same_level', '\u0625\u0643\u0645\u0627\u0644 \u0641\u064a \u0646\u0641\u0633 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0642\u0627\u062f\u0645\u0629'), ('graduated_to_abln_next_round_higher_level', '\u064a\u0631\u0641\u0639 \u0625\u0627\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0623\u0639\u0644\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0642\u0627\u062f\u0645\u0629'), ('referred_to_bln', ' \u0627\u0644\u0623\u062d\u0627\u0644\u0629 \u0645\u0646 ABLN \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c BLN'), ('referred_to_ybln', '\u0627\u0644\u0623\u062d\u0627\u0644\u0629 \u0625\u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0627\u0644\u0645\u0631\u0627\u0647\u0642\u064a\u0646 (YBLN)'), ('referred_to_cbt', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c CBT')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='round_complete',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u0627\u062a\u0645 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u062f\u0648\u0631\u0629 \u0628\u0646\u062c\u0627\u062d\u061f'),
        ),
    ]
