# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0164_auto_20201028_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abln',
            old_name='Followup_session_modality',
            new_name='followup_session_modality',
        ),
        migrations.RenameField(
            model_name='abln',
            old_name='Followup_session_number',
            new_name='followup_session_number',
        ),
        migrations.RenameField(
            model_name='bln',
            old_name='Followup_session_modality',
            new_name='followup_session_modality',
        ),
        migrations.RenameField(
            model_name='bln',
            old_name='Followup_session_number',
            new_name='followup_session_number',
        ),
        migrations.RenameField(
            model_name='cbece',
            old_name='Followup_session_modality',
            new_name='followup_session_modality',
        ),
        migrations.RenameField(
            model_name='cbece',
            old_name='Followup_session_number',
            new_name='followup_session_number',
        ),
        migrations.RenameField(
            model_name='rs',
            old_name='Followup_session_modality',
            new_name='followup_session_modality',
        ),
        migrations.RenameField(
            model_name='rs',
            old_name='Followup_session_number',
            new_name='followup_session_number',
        ),
        migrations.RemoveField(
            model_name='abln',
            name='Followup_session_attended',
        ),
        migrations.RemoveField(
            model_name='bln',
            name='Followup_session_attended',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='Followup_session_attended',
        ),
        migrations.RemoveField(
            model_name='rs',
            name='Followup_session_attended',
        ),
        migrations.AddField(
            model_name='abln',
            name='followup_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='covid_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='pss_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='pss_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='pss_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pss_session_attended',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062e\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0625\u0644\u0649 \u062c\u0644\u0633\u0627\u062a \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a \u0648\u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651'),
        ),
    ]
