# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-29 20:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0173_auto_20201118_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abln',
            old_name='parent_attended',
            new_name='covid_parent_attended',
        ),
        migrations.RenameField(
            model_name='abln',
            old_name='parent_attended_other',
            new_name='covid_parent_attended_other',
        ),
        migrations.RenameField(
            model_name='bln',
            old_name='parent_attended',
            new_name='covid_parent_attended',
        ),
        migrations.RenameField(
            model_name='bln',
            old_name='parent_attended_other',
            new_name='covid_parent_attended_other',
        ),
        migrations.RenameField(
            model_name='cbece',
            old_name='parent_attended',
            new_name='covid_parent_attended',
        ),
        migrations.RenameField(
            model_name='cbece',
            old_name='parent_attended_other',
            new_name='covid_parent_attended_other',
        ),
        migrations.RenameField(
            model_name='rs',
            old_name='parent_attended',
            new_name='covid_parent_attended',
        ),
        migrations.RenameField(
            model_name='rs',
            old_name='parent_attended_other',
            new_name='covid_parent_attended_other',
        ),
        migrations.AddField(
            model_name='abln',
            name='followup_parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='abln',
            name='followup_parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='abln',
            name='pss_parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='abln',
            name='pss_parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='bln',
            name='followup_parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='bln',
            name='pss_parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='bln',
            name='pss_parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='followup_parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='pss_parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='pss_parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='followup_parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='pss_parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='pss_parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('availablity_electronic_device', '\u0639\u062f\u0645  \u0648\u062c\u0648\u062f \u0627\u0644\u062c\u0647\u0627\u0632 \u0627\u0644\u0643\u062a\u0631\u0648\u0646\u064a'), ('internet_connectivity', '\u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0634\u0628\u0643\u0629 \u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u063a\u064a\u064a\u0631 \u0627\u0642\u0627\u0645\u0629 \u0627\u0644\u0633\u0643\u0646 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('Moved back to Syria', '\u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0627\u0646\u062a\u0642\u0644\u062a \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='barriers_single',
            field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('availablity_electronic_device', '\u0639\u062f\u0645  \u0648\u062c\u0648\u062f \u0627\u0644\u062c\u0647\u0627\u0632 \u0627\u0644\u0643\u062a\u0631\u0648\u0646\u064a'), ('internet_connectivity', '\u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0634\u0628\u0643\u0629 \u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u063a\u064a\u064a\u0631 \u0627\u0642\u0627\u0645\u0629 \u0627\u0644\u0633\u0643\u0646 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('Moved back to Syria', '\u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0627\u0646\u062a\u0642\u0644\u062a \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='The main barriers affecting the daily attendance and performance'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('availablity_electronic_device', '\u0639\u062f\u0645  \u0648\u062c\u0648\u062f \u0627\u0644\u062c\u0647\u0627\u0632 \u0627\u0644\u0643\u062a\u0631\u0648\u0646\u064a'), ('internet_connectivity', '\u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0634\u0628\u0643\u0629 \u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u063a\u064a\u064a\u0631 \u0627\u0642\u0627\u0645\u0629 \u0627\u0644\u0633\u0643\u0646 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('Moved back to Syria', '\u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0627\u0646\u062a\u0642\u0644\u062a \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='barriers_single',
            field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('availablity_electronic_device', '\u0639\u062f\u0645  \u0648\u062c\u0648\u062f \u0627\u0644\u062c\u0647\u0627\u0632 \u0627\u0644\u0643\u062a\u0631\u0648\u0646\u064a'), ('internet_connectivity', '\u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0634\u0628\u0643\u0629 \u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u063a\u064a\u064a\u0631 \u0627\u0642\u0627\u0645\u0629 \u0627\u0644\u0633\u0643\u0646 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('Moved back to Syria', '\u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0627\u0646\u062a\u0642\u0644\u062a \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='The main barriers affecting the daily attendance and performance'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('availablity_electronic_device', '\u0639\u062f\u0645  \u0648\u062c\u0648\u062f \u0627\u0644\u062c\u0647\u0627\u0632 \u0627\u0644\u0643\u062a\u0631\u0648\u0646\u064a'), ('internet_connectivity', '\u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0634\u0628\u0643\u0629 \u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u063a\u064a\u064a\u0631 \u0627\u0642\u0627\u0645\u0629 \u0627\u0644\u0633\u0643\u0646 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('Moved back to Syria', '\u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0627\u0646\u062a\u0642\u0644\u062a \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='barriers_single',
            field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('availablity_electronic_device', '\u0639\u062f\u0645  \u0648\u062c\u0648\u062f \u0627\u0644\u062c\u0647\u0627\u0632 \u0627\u0644\u0643\u062a\u0631\u0648\u0646\u064a'), ('internet_connectivity', '\u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0634\u0628\u0643\u0629 \u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u063a\u064a\u064a\u0631 \u0627\u0642\u0627\u0645\u0629 \u0627\u0644\u0633\u0643\u0646 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('Moved back to Syria', '\u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0627\u0646\u062a\u0642\u0644\u062a \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='The main barriers affecting the daily attendance and performance'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='mid_test_barriers_single',
            field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('availablity_electronic_device', '\u0639\u062f\u0645  \u0648\u062c\u0648\u062f \u0627\u0644\u062c\u0647\u0627\u0632 \u0627\u0644\u0643\u062a\u0631\u0648\u0646\u064a'), ('internet_connectivity', '\u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0634\u0628\u0643\u0629 \u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u063a\u064a\u064a\u0631 \u0627\u0642\u0627\u0645\u0629 \u0627\u0644\u0633\u0643\u0646 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('Moved back to Syria', '\u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0627\u0646\u062a\u0642\u0644\u062a \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='The main barriers affecting the daily attendance and performance'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='barriers',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('cold_weather', '\u0627\u0644\u0637\u0642\u0633 \u0627\u0644\u0628\u0627\u0631\u062f'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family moved', '\u062a\u063a\u064a\u064a\u0631 \u0627\u0642\u0627\u0645\u0629 \u0627\u0644\u0633\u0643\u0646 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('Moved back to Syria', '\u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0627\u0646\u062a\u0642\u0644\u062a \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629')], max_length=100, null=True, verbose_name='The main barriers affecting the daily attendance and performance'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='barriers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('availablity_electronic_device', '\u0639\u062f\u0645  \u0648\u062c\u0648\u062f \u0627\u0644\u062c\u0647\u0627\u0632 \u0627\u0644\u0643\u062a\u0631\u0648\u0646\u064a'), ('internet_connectivity', '\u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0634\u0628\u0643\u0629 \u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u063a\u064a\u064a\u0631 \u0627\u0642\u0627\u0645\u0629 \u0627\u0644\u0633\u0643\u0646 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('Moved back to Syria', '\u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0627\u0646\u062a\u0642\u0644\u062a \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0627\u0644\u062d\u0648\u0627\u062c\u0632'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='barriers_single',
            field=models.CharField(blank=True, choices=[('Full time job to support family financially', '\u0627\u0644\u0639\u0645\u0644 \u0644\u0625\u0639\u0627\u0644\u0629 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0645\u0627\u062f\u064a\u0627\u064b'), ('seasonal_work', '\u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0645\u0648\u0633\u0645\u064a'), ('availablity_electronic_device', '\u0639\u062f\u0645  \u0648\u062c\u0648\u062f \u0627\u0644\u062c\u0647\u0627\u0632 \u0627\u0644\u0643\u062a\u0631\u0648\u0646\u064a'), ('internet_connectivity', '\u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0634\u0628\u0643\u0629 \u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a'), ('sickness', '\u0627\u0644\u0645\u0631\u0636'), ('security', '\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u0623\u0645\u0646\u064a'), ('family_moved', '\u062a\u063a\u064a\u064a\u0631 \u0627\u0642\u0627\u0645\u0629 \u0627\u0644\u0633\u0643\u0646 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('Moved back to Syria', '\u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0627\u0646\u062a\u0642\u0644\u062a \u0627\u0644\u0649 \u0633\u0648\u0631\u064a\u0627'), ('Enrolled in formal education', '\u0645\u0633\u062c\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('marriage engagement pregnancy', '\u0632\u0648\u0627\u062c/\u062e\u0637\u0648\u0628\u0629'), ('violence bullying', '  \u062a\u0646\u0645\u0631/\u0639\u0646\u0641 \u0636\u062f \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0642\u0628\u0644 \u0637\u0641\u0644 \u0623\u062e\u0631'), ('No interest in pursuing the programme/No value', '\u0639\u062f\u0645 \u0627\u0644\u0631\u063a\u0628\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645/ \u0644\u0627 \u0642\u064a\u0645\u0629'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='The main barriers affecting the daily attendance and performance'),
        ),
    ]
