# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-29 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0174_auto_20201129_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='abln',
            name='parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='bln',
            name='parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='bln',
            name='parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='parent_attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0648\u0644\u064a \u0623\u0645\u0631 \u0627\u0644\u0637\u0641\u0644 \u0623\u062c\u062a\u0645\u0627\u0639\u0627\u062a \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='parent_attended_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u0625\u0630\u0627 \u0643\u0627\u0646 \u0644\u0623\u0633\u0628\u0627\u0628 \u0623\u062e\u0631\u0649 \u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
    ]
