# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-29 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0175_auto_20201129_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abln',
            name='parent_attended',
        ),
        migrations.RemoveField(
            model_name='abln',
            name='parent_attended_other',
        ),
        migrations.RemoveField(
            model_name='bln',
            name='parent_attended',
        ),
        migrations.RemoveField(
            model_name='bln',
            name='parent_attended_other',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='parent_attended',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='parent_attended_other',
        ),
        migrations.RemoveField(
            model_name='rs',
            name='parent_attended',
        ),
        migrations.RemoveField(
            model_name='rs',
            name='parent_attended_other',
        ),
    ]
