# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-30 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0176_auto_20201129_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_barriers_other',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_barriers_single',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_basic_stationery',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_child_health_concern',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_child_health_examed',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_covid_session_attended',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_covid_session_modality',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_covid_session_number',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_family_visit_number',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_follow_up_result',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_follow_up_type',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_followup_session_attended',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_followup_session_modality',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_followup_session_number',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_house_visit_number',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_learning_result',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_parent_attended',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_parent_attended_other',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_parent_attended_visits',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_participation',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_phone_call_number',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_pss_session_attended',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_pss_session_modality',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_pss_session_number',
        ),
        migrations.RemoveField(
            model_name='cbece',
            name='mid_test_round_complete',
        ),
    ]
