# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-17 19:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0056_auto_20200414_1021'),
        ('clm', '0181_auto_20201210_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='rs',
            name='child_muac',
            field=models.CharField(blank=True, choices=[('', 'MUAC'), ('1', '<11.5 \u0633\u0645 (\u0633\u0648\u0621 \u0627\u0644\u062a\u063a\u0630\u064a\u0629 \u0627\u0644\u062d\u0627\u062f)'), ('2', '<12.5 \u0633\u0645 (\u0633\u0648\u0621 \u0627\u0644\u062a\u063a\u0630\u064a\u0629 \u0627\u0644\u0645\u0639\u062a\u062f\u0644)')], max_length=50, null=True, verbose_name='Child MUAC'),
        ),
        migrations.AddField(
            model_name='rs',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Cycle', verbose_name='\u0631\u0642\u0645'),
        ),
        migrations.AddField(
            model_name='rs',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='rs',
            name='main_caregiver',
            field=models.CharField(blank=True, choices=[('', '----------'), ('mother', '\u0627\u0644\u0623\u0645'), ('father', '\u0627\u0644\u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0647\u0648 \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631 \u0627\u0644\u0631\u0626\u064a\u0633\u064a'),
        ),
        migrations.AddField(
            model_name='rs',
            name='main_caregiver_nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Nationality', verbose_name='\u062c\u0646\u0633\u064a\u0629 \u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'),
        ),
        migrations.AddField(
            model_name='rs',
            name='miss_school_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u062a\u062d\u062f\u064a\u062f \u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0631\u0627\u0633\u0629'),
        ),
        migrations.AddField(
            model_name='rs',
            name='other_caregiver_relationship',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0645\u0627 \u0647\u064a \u0635\u0644\u0629 \u0627\u0644\u0642\u0631\u0627\u0628\u0629\u061f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='phone_owner',
            field=models.CharField(choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645\u061f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='round_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0628\u062f\u0627\u064a\u0629 \u0627\u0644\u062f\u0648\u0631\u0629 \u0641\u064a \u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
        migrations.AddField(
            model_name='rs',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0631\u0642\u0645 \u0627\u0644\u0647\u0627\u062a\u0641 \u0627\u0644\u062b\u0627\u0646\u0648\u064a'),
        ),
        migrations.AddField(
            model_name='rs',
            name='second_phone_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u062a\u0623\u0643\u064a\u062f \u0631\u0642\u0645 \u0627\u0644\u0647\u0627\u062a\u0641 \u0627\u0644\u062b\u0627\u0646\u0648\u064a'),
        ),
        migrations.AddField(
            model_name='rs',
            name='second_phone_owner',
            field=models.CharField(blank=True, choices=[('main_caregiver', '\u0648\u0644\u064a \u0627\u0644\u0623\u0645\u0631'), ('family member', '\u0623\u062d\u062f \u0627\u0641\u0631\u0627\u062f \u0627\u0644\u0639\u0627\u0626\u0644\u0629'), ('neighbors', '\u0627\u0644\u062c\u064a\u0631\u0627\u0646'), ('shawish', '\u0627\u0644\u0634\u0627\u0648\u064a\u0634')], max_length=100, null=True, verbose_name='\u0645\u0646 \u0627\u0644\u0634\u062e\u0635 \u0627\u0644\u0630\u064a \u064a\u062c\u064a\u0628 \u0639\u0644\u0649 \u0647\u0630\u0627 \u0627\u0644\u0631\u0642\u0645\u061f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='student_number_children',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True, verbose_name='\u062d\u062f\u062f \u0639\u062f\u062f \u0627\u0644\u0623\u0637\u0641\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='education_status',
            field=models.CharField(blank=True, choices=[('', '----------'), ('out of school', '\u0644\u0645 \u064a\u0633\u062c\u0644 \u0627\u0628\u062f\u0627 \u0641\u064a \u0627\u0644\u0645\u062f\u0631\u0633\u0629 \u0645\u0646 \u0642\u0628\u0644'), ('enrolled in formal education but did not continue', '\u0643\u0627\u0646 \u0645\u0633\u062c\u0644\u0627\u064b \u0641\u064a \u0645\u062f\u0631\u0633\u0629 \u0646\u0638\u0627\u0645\u064a\u0629 \u0648\u0644\u0645 \u064a\u0643\u0645\u0644'), ('enrolled in CBECE', '\u0643\u0627\u0646 \u0645\u0633\u062c\u0644\u0627\u064b \u0641\u064a \u0645\u062f\u0631\u0633\u0629 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a\u0629 \u0648\u0644\u0645 \u064a\u0643\u0645\u0644')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a \u0644\u0644\u0637\u0641\u0644 \u0639\u0646\u062f \u0627\u0644\u062a\u0633\u062c\u064a\u0644 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', '----------'), ('graduated_to_cbece_next_level', '\u0631\u0641\u0639 \u0625\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0627\u0644\u064a'), ('graduated_to_cbece_next_round_same_level', '\u0625\u0643\u0645\u0627\u0644 \u0641\u064a \u0646\u0641\u0633 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0642\u0627\u062f\u0645\u0629'), ('graduated_to_cbece_next_round_higher_level', '\u064a\u0631\u0641\u0639 \u0625\u0627\u0644\u0649 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0623\u0639\u0644\u0649 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629 \u0627\u0644\u0642\u0627\u062f\u0645\u0629 (\u0627\u0644\u0645\u0633\u062a\u0648\u0649 3)'), ('referred_to_alp', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ALP'), ('referred_public_school', '\u064a\u0631\u0641\u0639 \u0627\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a \u0627\u0644\u0635\u0641 \u0627\u0644\u0623\u0648\u0644'), ('referred_to_tvet', '\u0627\u0644\u0623\u062d\u0627\u0644\u0629 \u0627\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0645\u0647\u0646\u064a \u0648 \u0627\u0644\u062a\u0642\u0646\u064a (TVET)'), ('referred_to_ycbece', 'Referred to YCBECE'), ('dropout', '\u0627\u0644\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_arabic',
            field=models.FloatField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='\u0627\u0644\u0639\u0644\u0648\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_language',
            field=models.FloatField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='\u0627\u0644\u0639\u0644\u0648\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_math',
            field=models.FloatField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='\u0627\u0644\u0639\u0644\u0648\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test_science',
            field=models.FloatField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='\u0627\u0644\u0639\u0644\u0648\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_arabic',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_language',
            field=models.FloatField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name=' \u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0623\u062c\u0646\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_math',
            field=models.FloatField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='\u0627\u0644\u0631\u064a\u0627\u0636\u064a\u0627\u062a'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test_science',
            field=models.FloatField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='\u0627\u0644\u0639\u0644\u0648\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referral',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('from_same_ngo', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0627\u0644\u062c\u0645\u0639\u064a\u0629 \u0630\u0627\u062a\u0647\u0627'), ('from_other_ngo', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u063a\u064a\u0631\u062c\u0645\u0639\u064a\u0629'), ('form_official_reference', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0645\u0631\u062c\u0639 \u0631\u0633\u0645\u064a (\u0645\u062e\u062a\u0627\u0631\u060c \u0628\u0644\u062f\u064a\u0629\u060c \u0645\u062f\u064a\u0631 \u0645\u062f\u0631\u0633\u0629\u060c \u0625\u0644\u062e ..)'), ('from_host_community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0627\u0644\u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0645\u0636\u064a\u0641'), ('from_displaced_community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0646\u0627\u0632\u062d\u064a\u0646')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0645\u0646 \u0623\u064a\u0646 \u062a\u0645 \u0625\u062d\u0627\u0644\u0629 \u0627\u0644\u0637\u0641\u0644\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='registration_level',
            field=models.CharField(blank=True, choices=[('', '----------'), ('level_two', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062b\u0627\u0646\u064a'), ('level_three', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062b\u0627\u0644\u062b')], max_length=100, null=True, verbose_name='\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0633\u062c\u064a\u0644'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Referred by CP partner', ' \u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0634\u0631\u0643\u0627\u0621 \u062d\u0645\u0627\u064a\u0629 \u0627\u0644\u0637\u0641\u0644 CP partner'), ('Family walked in to NGO', '\u0645\u0646 \u0642\u0628\u0644 \u0627\u0647\u0644 \u0627\u0644\u0637\u0641\u0644 \u0645\u0628\u0627\u0634\u0631\u0629'), ('Referral from another NGO', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u062c\u0645\u0639\u064a\u0629 \u0623\u062e\u0631\u0649'), ('Referral from another Municipality', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0627\u0644\u0628\u0644\u062f\u064a\u0629 / \u0645\u0631\u062c\u0639 \u0631\u0633\u0645\u064a'), ('Direct outreach', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u062d\u0645\u0644\u0627\u062a \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u0627\u0644\u062c\u0645\u0639\u064a\u0629'), ('List database', ' \u0627\u062d\u0644\u0629 \u0639\u0646 \u0637\u0631\u064a\u0642 Profiling Database'), ('From hosted community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0627\u0644\u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0645\u0636\u064a\u0641'), ('From displaced community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0646\u0627\u0632\u062d\u064a\u0646')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u062d\u0627\u0644\u0629 \u0627\u0644\u0637\u0641\u0644  \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ABLN'),
        ),
    ]
