# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0182_auto_20201217_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='rs',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('grade1', 'Grade 1'), ('grade2', 'Grade 2'), ('grade3', 'Grade 3'), ('grade4', 'Grade 4'), ('grade5', 'Grade 5'), ('grade6', 'Grade 6'), ('grade7', 'Grade 7'), ('grade8', 'Grade 8'), ('grade9', 'Grade 9')], max_length=50, null=True, verbose_name='What was the child education level when first joining formal education in lebanon'),
        ),
        migrations.AddField(
            model_name='rs',
            name='source_join_fe',
            field=models.CharField(blank=True, choices=[('ALP', 'ALP'), ('Prep-ECE', 'Prep - ECE'), ('ABLN', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0628\u0631\u0646\u0627\u0645\u062c ABLN \u0625\u0627\u0644\u0649  BLN programme'), ('CBECE', 'CBECE'), ('BLN', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0628\u0631\u0646\u0627\u0645\u062c BLN \u0625\u0627\u0644\u0649  ABLN programme'), ('YBLN', 'YBLN'), ('FE_outside_lebanon', 'FE outside Lebanon')], max_length=50, null=True, verbose_name='From where did the child first come to join  FE'),
        ),
    ]
