# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-28 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0184_auto_20201223_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rs',
            name='grade_registration',
            field=models.CharField(blank=True, choices=[('', '----------'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=100, null=True, verbose_name=' \u0645\u0627 \u0647\u0648 \u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0644\u0644\u0637\u0641\u0644 \u0639\u0646\u062f \u0627\u0644\u062a\u0633\u062c\u064a\u0644 \u0644\u0623\u0648\u0644 \u0645\u0631\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a \u0641\u064a \u0644\u0628\u0646\u0627\u0646'),
        ),
    ]
