# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0186_auto_20201229_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rs',
            name='registered_in_school',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0633\u0645 \u0645\u062f\u0631\u0633\u0629 \u0627\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='shift',
            field=models.CharField(blank=True, choices=[('', '----------'), ('first', '\u062f\u0648\u0627\u0645 \u0635\u0628\u0627\u062d\u064a'), ('second', '\u062f\u0648\u0627\u0645 \u0628\u0639\u062f \u0627\u0644\u0638\u0647\u0631')], max_length=50, null=True, verbose_name='\u062f\u0648\u0627\u0645 \u0627\u0644\u062a\u0639\u0644\u064a\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Referral from school directors', 'Referral from school directors'), ('From Profiling Database (MEHE)', 'From Profiling Database (MEHE)'), ('Other Sources', 'Other Sources')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u062d\u0627\u0644\u0629 \u0627\u0644\u0637\u0641\u0644  \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ABLN'),
        ),
    ]
