# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0188_rs_source_of_identification_specify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rs',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', '----------'), ('graduated_to_rs_next_round_higher_level', 'Progress to FE higher grade next year'), ('referred_alp', '\u0623\u062d\u064a\u0644 \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ALP'), ('graduated_to_cbece_next_round_higher_level', '\u0627\u0644\u0623\u062d\u0627\u0644\u0629 \u0627\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0645\u0647\u0646\u064a \u0648 \u0627\u0644\u062a\u0642\u0646\u064a (TVET)'), ('graduated_to_rs_next_round_same_level', 'Repeat same grade next year'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Referral from school directors', ' \u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0645\u062f\u064a\u0631 \u0627\u0644\u0645\u062f\u0631\u0633\u0629'), ('From Profiling Database (MEHE)', 'From Profiling Database (MEHE)'), ('Other Sources', '\u0645\u0635\u0627\u062f\u0631 \u0623\u062e\u0631\u0649')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u062d\u0627\u0644\u0629 \u0627\u0644\u0637\u0641\u0644  \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ABLN'),
        ),
    ]
