# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-18 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0190_auto_20210112_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='rs',
            name='miss_school',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0633\u0631\u0628 \u0627\u0644\u0637\u0641\u0644 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='source_join_fe',
            field=models.CharField(blank=True, choices=[('ALP', 'ALP'), ('Prep-ECE', 'Prep - ECE'), ('ABLN', 'ABLN'), ('CBECE', 'CBECE'), ('BLN', 'BLN'), ('YBLN', 'YBLN'), ('FE_outside_lebanon', '\u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a \u062e\u0627\u0631\u062c \u0644\u0628\u0646\u0627\u0646'), ('FE__lebanon', '\u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a')], max_length=50, null=True, verbose_name=' \u0645\u0635\u062f\u0631 \u0625\u062d\u0627\u0644\u0629 \u0627\u0644\u0637\u0641\u0644 \u0639\u0646\u062f \u0627\u0644\u062a\u0633\u062c\u064a\u0644 \u0644\u0623\u0648\u0644 \u0645\u0631\u0629 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'),
        ),
    ]
