# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-10 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0192_rs_learning_result_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='FC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fc_type', models.CharField(blank=True, choices=[('subject1_pre', 'Subject1 Pre'), ('subject1_post', 'Subject1 Post'), ('subject2_pre', 'Subject2 Pre'), ('subject2_post', 'Subject2 Post')], max_length=50, null=True, verbose_name='FC Type')),
                ('facilitator_name', models.TextField(blank=True, null=True, verbose_name='Facilitator name')),
                ('subject_taught', models.TextField(blank=True, null=True, verbose_name='Subject taught')),
                ('date_of_monitoring', models.DateField(blank=True, null=True)),
                ('numbers_child_monitored', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True, verbose_name='Number of times the child has been monitored to date')),
                ('topic_covered', models.TextField(blank=True, null=True, verbose_name='Activities/ topic covered')),
                ('materials_needed', models.TextField(blank=True, null=True, verbose_name='Materials needed for the lesson (teaching/ learning)')),
                ('materials_needed_available', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did the child have these learning materials available for the lesson?')),
                ('materials_needed_reason_no', models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628')),
                ('remote_learning', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Was the child involved in remote learning?')),
                ('share_expectations_caregiver', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did you share the expectations with their caregiver for the weekly engagement in learning?')),
                ('share_expectations_no_reason', models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0633\u0628\u0628')),
                ('child_engaged_lesson', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Was the child engaged in the lesson and understood the content?')),
                ('child_engaged_lesson_explain', models.TextField(blank=True, null=True, verbose_name='How was this verified?')),
                ('child_participate_others', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did the child participate with others on time?')),
                ('child_participate_others_no_explain', models.TextField(blank=True, null=True, verbose_name='Please explain Why')),
                ('child_expected_work_independently', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Was the child expected to work independently?')),
                ('child_meet_lesson_objectives', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did the child meet the previous lesson objectives?')),
                ('child_meet_lesson_objectives_verified', models.TextField(blank=True, null=True, verbose_name='How was this verified?')),
                ('homework_after_lesson', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Was there any homework given after the lesson?')),
                ('homework_after_lesson_explain', models.TextField(blank=True, null=True, verbose_name='Please explain')),
                ('homework_score', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True, verbose_name='(if applicable) What score did the child receive on the homework?')),
                ('homework_score_explain', models.TextField(blank=True, null=True, verbose_name='How was the Grading and Feedback on the homework given?')),
                ('parents_supporting_student', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Were parents supporting the student through this lesson?')),
                ('parents_supporting_student_explain', models.TextField(blank=True, null=True, verbose_name='Please explain')),
                ('child_complete_printed_package', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='(if applicable) Did the child complete the printed package for the week?')),
                ('number_child_participate_online', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True, verbose_name='How many times did this child participate in online classes this week?')),
                ('how_make_sure_child_access_online', models.TextField(blank=True, null=True, verbose_name='How did you make sure that the child was able to login/access the online lessons?')),
                ('followup_not_join_online', models.TextField(blank=True, null=True, verbose_name='How do you follow up if the child does not join / engage in online learning?')),
                ('times_voice_contact_child_caregiver', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True, verbose_name='How many times do you have voice contact with the child/caregiver per week?')),
                ('child_coping_home_learning', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Is the child coping with home-based learning? ')),
                ('child_caregiver_challenges', models.TextField(blank=True, null=True, verbose_name='What challenges does this child face? child/caregiver?')),
                ('actions_before_next_class', models.TextField(blank=True, null=True, verbose_name='Actions_before_next_class')),
                ('actions_before_next_class_how', models.TextField(blank=True, null=True, verbose_name='actions_before_next_class_how')),
                ('girls_boys_participate_access_device', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='(if applicable) Did both girls and boys in the same family participate in the class and have access to the phone/ device?')),
                ('girls_boys_participate_explain', models.TextField(blank=True, null=True, verbose_name='Please explain')),
                ('how_often_contact_caregivers', models.CharField(blank=True, choices=[('daily', '\u064a\u0648\u0645\u064a\u0627\u064b'), ('two_three_per_week', '2-3 times a week'), ('weekly', '\u0643\u0644 \u0623\u0633\u0628\u0648\u0639'), ('biweekly', '\u0643\u0644 \u0627\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b'), ('not_in_touch', 'Have not kept in touch with parents / caregivers.')], max_length=50, null=True, verbose_name='How often do you keep in touch with parents /caregivers of this child since the learning center closed?')),
                ('how_contact_caregivers', models.CharField(blank=True, choices=[('Phone_calls', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0623\u062a\u0635\u0627\u0644 \u0627\u0644\u0647\u0627\u062a\u0641\u064a'), ('WhatsApp', 'WhatsApp'), ('text_whatsApp_messages', 'Text messages / WhatsApp messages '), ('other', '\u0622\u062e\u0631')], max_length=50, null=True, verbose_name='How do you keep in touch with parents / caregivers?')),
                ('how_keep_touch_caregivers_specify', models.TextField(blank=True, null=True, verbose_name='Please Specify')),
                ('child_awareness_prevention_covid19', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Has the child been reached with awareness messaging on Covid-19 and prevention measures?')),
                ('followup_done_messages', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Was any follow-up done with the child to ensure message(s) received and understood?')),
                ('followup_followup_explain', models.TextField(blank=True, null=True, verbose_name='Please Specify')),
                ('child_practice_basic_handwashing', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Does this child practice basic handwashing? ')),
                ('child_practice_basic_handwashing_explain', models.TextField(blank=True, null=True, verbose_name='Please Specify')),
                ('child_have_pss_wellbeing', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Does the child have any PSS/ wellbeing needs?')),
                ('child_have_pss_wellbeing_explain', models.TextField(blank=True, null=True, verbose_name='Please Specify')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Additional notes/ specific challenges/ follow up action/ referrals etc.')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'FC',
                'verbose_name_plural': 'FC',
            },
        ),
    ]
