# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-10 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0193_fc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FC',
        ),
    ]
