# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-10 21:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0195_abln_fc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln_fc',
            name='actions_before_next_class_how',
            field=models.TextField(blank=True, null=True, verbose_name='how'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='date_of_monitoring',
            field=models.DateField(blank=True, null=True, verbose_name='Date of monitoring'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='how_contact_caregivers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Phone_calls', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0623\u062a\u0635\u0627\u0644 \u0627\u0644\u0647\u0627\u062a\u0641\u064a'), ('WhatsApp', 'WhatsApp'), ('text_whatsApp_messages', 'Text messages / WhatsApp messages '), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='How do you keep in touch with parents / caregivers?'),
        ),
    ]
