# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-12 13:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0197_auto_20210211_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abln_fc',
            name='abln',
        ),
        migrations.AddField(
            model_name='abln_fc',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.ABLN', verbose_name='\u0627\u0644\u062a\u0633\u062c\u064a\u0644'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('', '----------'), ('daily', '\u064a\u0648\u0645\u064a\u064b\u0651\u0627'), ('every_2_to_3_days', '\u0645\u0631\u0651\u062a\u064a\u0646 \u0623\u0648 \u062b\u0644\u0627\u062b \u0645\u0631\u0651\u0627\u062a \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639'), ('weekly', '\u0623\u0633\u0628\u0648\u0639\u064a\u064b\u0651\u0627'), ('biweekly', '\u0643\u0644\u0651 \u0623\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('', '----------'), ('daily', '\u064a\u0648\u0645\u064a\u064b\u0651\u0627'), ('every_2_to_3_days', '\u0645\u0631\u0651\u062a\u064a\u0646 \u0623\u0648 \u062b\u0644\u0627\u062b \u0645\u0631\u0651\u0627\u062a \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639'), ('weekly', '\u0623\u0633\u0628\u0648\u0639\u064a\u064b\u0651\u0627'), ('biweekly', '\u0643\u0644\u0651 \u0623\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='covid_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='followup_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='pss_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='actions_before_next_class',
            field=models.TextField(blank=True, null=True, verbose_name='\u0645\u0627 \u0647\u064a \u0627\u0644\u062e\u0637\u0648\u0627\u062a \u0627\u0644\u0645\u062d\u062f\u0651\u062f\u0629 \u0627\u0644\u0651\u062a\u064a \u064a\u062c\u0628 \u0627\u062a\u0651\u062e\u0627\u0630\u0647\u0627 \u0645\u0639 \u0627\u0644\u0637\u0651\u0641\u0644 \u0642\u0628\u0644 \u0627\u0644\u0628\u062f\u0621 \u0628\u0627\u0644\u0635\u0651\u0641\u0651 \u0627\u0644\u062a\u0651\u0627\u0644\u064a\u061f \u0643\u064a\u0641\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='\u0645\u0644\u0627\u062d\u0638\u0627\u062a \u0625\u0636\u0627\u0641\u064a\u0651\u0629 / \u062a\u062d\u062f\u0651\u064a\u0627\u062a \u0645\u0639\u064a\u0651\u0646\u0629 / \u0639\u0645\u0644\u064a\u0651\u0629 \u0645\u062a\u0627\u0628\u0639\u0629 / \u0627\u0644\u0625\u062d\u0627\u0644\u0629 \u0625\u0644\u062e'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_awareness_prevention_covid19',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645\u0651 \u062d\u0635\u0648\u0644 \u0627\u0644\u0637\u0651\u0641\u0644 \u0639\u0644\u0649 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0651\u0648\u0639\u064a\u0629 \u0648\u0637\u0631\u0642 \u0627\u0644\u0648\u0642\u0627\u064a\u0629 \u0645\u0646 \u0643\u0648\u0641\u064a\u062f 19\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_caregiver_challenges',
            field=models.TextField(blank=True, null=True, verbose_name='\u0645\u0627 \u0647\u064a \u0627\u0644\u062a\u0651\u062d\u062f\u0651\u064a\u0627\u062a \u0627\u0644\u0651\u062a\u064a \u064a\u0648\u0627\u062c\u0647\u0647\u0627 \u0627\u0644\u0637\u0651\u0641\u0644 / \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_complete_printed_package',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='(\u0625\u0630\u0627 \u0643\u0627\u0646 \u0645\u0645\u0643\u0646\u064b\u0627) \u0647\u0644 \u0623\u062a\u0645 \u0627\u0644\u0637\u0651\u0641\u0644 \u0627\u0644\u062d\u0632\u0645\u0629 \u0627\u0644\u0645\u0637\u0628\u0648\u0639\u0629 \u0644\u0647\u0630\u0627 \u0627\u0644\u062f\u0651\u0631\u0633\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_coping_home_learning',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0627\u0644\u0637\u0651\u0641\u0644 \u0642\u0627\u062f\u0631\u064c \u0639\u0644\u0649 \u0645\u0648\u0627\u0643\u0628\u0629 \u0627\u0644\u062a\u0651\u0639\u0644\u0651\u0645 \u0627\u0644\u0645\u0646\u0632\u0644\u064a\u0651\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_engaged_lesson',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0641\u0627\u0639\u0644 \u0627\u0644\u0637\u0651\u0641\u0644 \u0645\u0639 \u0627\u0644\u062f\u0651\u0631\u0633 \u0648\u0641\u0647\u0645 \u0627\u0644\u0645\u062d\u062a\u0648\u0649\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_engaged_lesson_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0645\u0651 \u0627\u0644\u062a\u0651\u062d\u0642\u0651\u0642 \u0645\u0646 \u0630\u0644\u0643\u061f (\u0645\u062b\u0644\u064f\u0627 \u0623\u064a\u0651 \u0623\u0633\u0644\u0648\u0628 \u062a\u0642\u064a\u064a\u0645\u064a\u0651 \u0627\u0633\u062a\u064f\u062e\u062f\u0650\u0645)'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_expected_work_independently',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0643\u0627\u0646 \u0645\u062a\u0648\u0642\u0651\u0639\u064b\u0627 \u0645\u0646 \u0627\u0644\u0637\u0651\u0641\u0644 \u0623\u0646 \u064a\u0639\u0645\u0644 \u0628\u0627\u0633\u062a\u0642\u0644\u0627\u0644\u064a\u0651\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_have_pss_wellbeing',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0627 \u0647\u064a \u0627\u0644\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u0627\u0644\u0645\u062d\u062f\u0651\u062f\u0629 \u0644\u0647\u0630\u0627 \u0627\u0644\u0637\u0651\u0641\u0644 \u0641\u064a\u0645\u0627 \u064a\u062a\u0639\u0644\u0651\u0642 \u0628\u0627\u0644\u062f\u0651\u0639\u0645 \u0627\u0644\u0646\u0651\u0641\u0633\u064a\u0651 \u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651 \u0648\u0627\u0644\u0631\u0651\u0641\u0627\u0647\u064a\u0651\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_have_pss_wellbeing_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_meet_lesson_objectives',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062d\u0642\u0642 \u0627\u0644\u0637\u0641\u0644 \u0623\u0647\u062f\u0627\u0641 \u0627\u0644\u062f\u0631\u0633 \u0627\u0644\u0633\u0627\u0628\u0642\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_meet_lesson_objectives_verified',
            field=models.TextField(blank=True, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0645\u0651 \u0627\u0644\u062a\u0651\u062d\u0642\u0651\u0642 \u0645\u0646 \u0630\u0644\u0643\u061f (\u0645\u062b\u0644\u064f\u0627 \u0623\u064a\u0651 \u0623\u0633\u0644\u0648\u0628 \u062a\u0642\u064a\u064a\u0645\u064a\u0651 \u0627\u0633\u062a\u064f\u062e\u062f\u0650\u0645)'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_participate_others',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0651\u0641\u0644 \u0645\u0639 \u0627\u0644\u0622\u062e\u0631\u064a\u0646 \u0641\u064a \u0627\u0644\u0648\u0642\u062a \u0627\u0644\u0645\u062d\u062f\u0651\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_participate_others_no_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0631\u0651\u062c\u0627\u0621 \u062a\u0648\u0636\u064a\u062d \u0644\u0645\u0627\u0630\u0627\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_practice_basic_handwashing',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u064a\u0645\u0627\u0631\u0633 \u0647\u0630\u0627 \u0627\u0644\u0637\u0651\u0641\u0644 \u063a\u0633\u0644 \u0627\u0644\u064a\u062f\u064a\u0646 \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u0651\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_practice_basic_handwashing_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='date_of_monitoring',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0625\u0639\u0637\u0627\u0621 \u0627\u0644\u062f\u0651\u0631\u0633 (\u0627\u0644\u064a\u0648\u0645\u060c \u0627\u0644\u0634\u0651\u0647\u0631\u060c \u0627\u0644\u0633\u0651\u0646\u0629)'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='facilitator_name',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0645\u0639\u0644\u0651\u0645/\u0629\u0651'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='followup_done_messages',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645\u0651\u062a \u0627\u0644\u0645\u062a\u0627\u0628\u0639\u0629 \u0645\u0639 \u0627\u0644\u0637\u0651\u0641\u0644 \u0644\u0644\u062a\u0651\u0623\u0643\u0651\u062f \u0645\u0646 \u062d\u0635\u0648\u0644\u0647 \u0639\u0644\u0649 \u0627\u0644\u0631\u0651\u0633\u0627\u0626\u0644 \u0648\u0641\u0647\u0645\u0647\u0627\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='followup_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='followup_not_join_online',
            field=models.TextField(blank=True, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u062a\u0627\u0628\u0639 \u0625\u0630\u0627 \u0644\u0645 \u064a\u0646\u0636\u0645\u0651 \u0627\u0644\u0637\u0651\u0641\u0644 /\u064a\u0634\u0627\u0631\u0643 \u0641\u064a \u0627\u0644\u062a\u0651\u0639\u0644\u064a\u0645 \u0639\u0646 \u0628\u064f\u0639\u062f\u061f\t'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='girls_boys_participate_access_device',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='(\u0625\u0630\u0627 \u0643\u0627\u0646 \u0645\u0645\u0643\u0646\u064b\u0627) \u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0623\u0637\u0641\u0627\u0644 \u0627\u0644\u0630\u0651\u0643\u0648\u0631 \u0648\u0627\u0644\u0625\u0646\u0627\u062b \u0644\u0646\u0641\u0633 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0641\u064a \u0627\u0644\u0635\u0651\u0641\u0648\u0641 \u0648\u0627\u0633\u062a\u0637\u0627\u0639\u0648\u0627 \u0627\u0644\u0648\u0635\u0648\u0644 \u0625\u0644\u0649 \u0627\u0644\u0647\u0627\u062a\u0641 / \u0627\u0644\u062c\u0647\u0627\u0632\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='girls_boys_participate_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='homework_after_lesson',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645\u0651 \u0625\u0639\u0637\u0627\u0621 \u0648\u0627\u062c\u0628 \u0645\u0646\u0632\u0644\u064a\u0651 \u0628\u0639\u062f \u0627\u0644\u062f\u0651\u0631\u0633\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='homework_after_lesson_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='homework_score',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True, verbose_name='(\u0625\u0630\u0627 \u0643\u0627\u0646 \u0645\u0645\u0643\u0646\u064b\u0627) \u0645\u0627 \u0627\u0644\u0639\u0644\u0627\u0645\u0629 \u0627\u0644\u0651\u062a\u064a \u062d\u0635\u0644 \u0639\u0644\u064a\u0647\u0627 \u0627\u0644\u0637\u0651\u0641\u0644 \u0645\u0646 \u062d\u0644\u0651 \u0627\u0644\u0648\u0627\u062c\u0628 \u0627\u0644\u0645\u0646\u0632\u0644\u064a\u0651\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='homework_score_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0645\u0651\u062a \u0639\u0645\u0644\u064a\u0651\u0629 \u0648\u0636\u0639 \u0627\u0644\u0639\u0644\u0627\u0645\u0627\u062a \u0648\u0625\u0639\u0637\u0627\u0621 \u0627\u0644\u062a\u0651\u063a\u0630\u064a\u0629 \u0627\u0644\u0631\u0651\u0627\u062c\u0639\u0629 \u0644\u0644\u0637\u0651\u0641\u0644 \u0641\u064a\u0645\u0627 \u064a\u062a\u0639\u0644\u0651\u0642 \u0628\u0627\u0644\u0648\u0627\u062c\u0628 \u0627\u0644\u0645\u0646\u0632\u0644\u064a\u0651\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='how_contact_caregivers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Phone_calls', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('WhatsApp', '\u0631\u0633\u0627\u0626\u0644 \u0635\u0648\u062a\u064a\u0651\u0629 \u0639\u0628\u0631 \u0627\u0644\u0648\u0627\u062a\u0633 \u0623\u0628'), ('text_whatsApp_messages', '\u0631\u0633\u0627\u0626\u0644 \u0645\u0643\u062a\u0648\u0628\u0629 / \u0639\u0628\u0631 \u0627\u0644\u0648\u0627\u062a\u0633 \u0623\u0628'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='\u0643\u064a\u0641 \u062a\u062d\u0627\u0641\u0638 \u0639\u0644\u0649 \u0627\u0644\u062a\u0651\u0648\u0627\u0635\u0644 \u0645\u0639 \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='how_keep_touch_caregivers_specify',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='how_make_sure_child_access_online',
            field=models.TextField(blank=True, null=True, verbose_name='(\u0625\u0630\u0627 \u0643\u0627\u0646 \u0645\u0645\u0643\u0646\u064b\u0627) \u0643\u064a\u0641 \u062a\u0623\u0643\u0651\u062f\u062a \u0645\u0646 \u0623\u0646\u0651 \u0627\u0644\u0637\u0651\u0641\u0644 \u064a\u0633\u062a\u0637\u064a\u0639 \u062a\u0633\u062c\u064a\u0644 \u0627\u0644\u062f\u0651\u062e\u0648\u0644 / \u0627\u0644\u0648\u0635\u0648\u0644 \u0625\u0644\u0649 \u0627\u0644\u062f\u0651\u0631\u0633 \u0639\u0628\u0631 \u0627\u0644\u0625\u0646\u062a\u0631\u0646\u062a\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='how_often_contact_caregivers',
            field=models.CharField(blank=True, choices=[('daily', '\u064a\u0648\u0645\u064a\u064b\u0651\u0627'), ('two_three_per_week', ' \u0645\u0631\u0651\u062a\u064a\u0646 \u0623\u0648 \u062b\u0644\u0627\u062b \u0645\u0631\u0651\u0627\u062a \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639'), ('weekly', '\u0623\u0633\u0628\u0648\u0639\u064a\u064b\u0651\u0627'), ('biweekly', '\u0643\u0644\u0651 \u0623\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b'), ('not_in_touch', '\u0644\u0645 \u0646\u062d\u0627\u0641\u0638 \u0639\u0644\u0649 \u0627\u0644\u062a\u0651\u0648\u0627\u0635\u0644 \u0645\u0639 \u0627\u0644\u0623\u0647\u0644')], max_length=50, null=True, verbose_name='\u0643\u0645 \u0645\u0631\u0651\u0629 \u0641\u064a \u0627\u0644\u063a\u0627\u0644\u0628 \u064a\u062a\u0645\u0651 \u0627\u0644\u0645\u062d\u0627\u0641\u0638\u0629 \u0639\u0644\u0649 \u0627\u0644\u062a\u0651\u0648\u0627\u0635\u0644 \u0645\u0639 \u0623\u0647\u0644 \u0647\u0630\u0627 \u0627\u0644\u0637\u0651\u0641\u0644 \u0644\u062a\u0642\u062f\u064a\u0645 \u0627\u0644\u062a\u0651\u0648\u0639\u064a\u0629 / \u0627\u0644\u062f\u0651\u0639\u0645 \u0627\u0644\u0646\u0651\u0641\u0633\u064a\u0651 \u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651 / \u0625\u0644\u062e'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='materials_needed',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0645\u0648\u0627\u062f\u0651 \u0627\u0644\u0645\u0637\u0644\u0648\u0628\u0629 \u0644\u0644\u062f\u0651\u0631\u0633 (\u0627\u0644\u062a\u0651\u0639\u0644\u064a\u0645 / \u0627\u0644\u062a\u0651\u0639\u0644\u0651\u0645): \u0647\u0644 \u062a\u0648\u0641\u0651\u0631\u062a \u0647\u0630\u0647 \u0627\u0644\u0645\u0648\u0627\u062f\u0651 \u0644\u0644\u0637\u0651\u0641\u0644 \u0644\u062d\u0635\u0648\u0644 \u0627\u0644\u062a\u0651\u0639\u0644\u0651\u0645\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='materials_needed_available',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0648\u0641\u0651\u0631\u062a \u0647\u0630\u0647 \u0627\u0644\u0645\u0648\u0627\u062f\u0651 \u0644\u0644\u0637\u0651\u0641\u0644 \u0644\u062d\u0635\u0648\u0644 \u0627\u0644\u062a\u0651\u0639\u0644\u0651\u0645\u061f\u0627'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='number_child_participate_online',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True, verbose_name='\u0643\u0645 \u064a\u0648\u0645\u064b\u0627 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0651\u0641\u0644 \u0641\u064a \u0635\u0641\u0648\u0641 \u0627\u0644\u062a\u0651\u0639\u0644\u0651\u0645 \u0639\u0646 \u0628\u064f\u0639\u062f \u0644\u0647\u0630\u0627 \u0627\u0644\u0623\u0633\u0628\u0648\u0639\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='numbers_child_monitored',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True, verbose_name='\u0639\u062f\u062f \u0627\u0644\u0645\u0631\u0651\u0627\u062a \u0627\u0644\u0651\u062a\u064a \u0627\u0633\u062a\u064f\u062e\u062f\u0650\u0645\u062a \u0641\u064a\u0647\u0627 \u0647\u0630\u0647 \u0627\u0644\u0644\u0651\u0627\u0626\u062d\u0629 \u0644\u062a\u0642\u064a\u064a\u0645 \u0627\u0644\u0637\u0651\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='parents_supporting_student',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0642\u0627\u0645 \u0627\u0644\u0623\u0647\u0644 \u0628\u062f\u0639\u0645 \u0627\u0644\u062a\u0651\u0644\u0645\u064a\u0630 \u062e\u0644\u0627\u0644 \u0647\u0630\u0627 \u0627\u0644\u062f\u0651\u0631\u0633\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='parents_supporting_student_explain',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='share_expectations_caregiver',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645\u0651\u062a \u0645\u0634\u0627\u0631\u0643\u0629 \u0623\u0647\u062f\u0627\u0641 \u0627\u0644\u062a\u0651\u0639\u0644\u0651\u0645 / \u0645\u0627 \u0647\u0648 \u0645\u062a\u0648\u0642\u0651\u0639 \u0645\u0646 \u0627\u0644\u0627\u0646\u062e\u0631\u0627\u0637 \u0641\u064a \u0627\u0644\u062a\u0651\u0639\u0644\u0651\u0645 \u0644\u0647\u0630\u0627 \u0627\u0644\u0623\u0633\u0628\u0648\u0639 \u0645\u0639 \u0627\u0644\u0623\u0647\u0644\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='subject_taught',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0645\u0627\u062f\u0651\u0629 \u0627\u0644\u0645\u064f\u0639\u0637\u0627\u0629 \u0639\u0646\u062f \u0647\u0630\u0647 \u0627\u0644\u0645\u0644\u0627\u062d\u0638\u0629'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='times_voice_contact_child_caregiver',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], null=True, verbose_name='\u0643\u0645 \u0645\u0631\u0651\u0629\u064b \u064a\u062a\u0645\u0651 \u0627\u0644\u0627\u062a\u0651\u0635\u0627\u0644 \u0635\u0648\u062a\u064a\u064b\u0651\u0627 \u0628\u0627\u0644\u0637\u0651\u0641\u0644 / \u0628\u0627\u0644\u0623\u0647\u0644 \u062e\u0644\u0627\u0644 \u0623\u0633\u0628\u0648\u0639\u061f '),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='topic_covered',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0646\u0651\u0634\u0627\u0637\u0627\u062a / \u0627\u0644\u0645\u0648\u0627\u0636\u064a\u0639 \u0627\u0644\u0645\u064f\u0639\u0637\u0627\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('', '----------'), ('daily', '\u064a\u0648\u0645\u064a\u064b\u0651\u0627'), ('every_2_to_3_days', '\u0645\u0631\u0651\u062a\u064a\u0646 \u0623\u0648 \u062b\u0644\u0627\u062b \u0645\u0631\u0651\u0627\u062a \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639'), ('weekly', '\u0623\u0633\u0628\u0648\u0639\u064a\u064b\u0651\u0627'), ('biweekly', '\u0643\u0644\u0651 \u0623\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('', '----------'), ('daily', '\u064a\u0648\u0645\u064a\u064b\u0651\u0627'), ('every_2_to_3_days', '\u0645\u0631\u0651\u062a\u064a\u0646 \u0623\u0648 \u062b\u0644\u0627\u062b \u0645\u0631\u0651\u0627\u062a \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639'), ('weekly', '\u0623\u0633\u0628\u0648\u0639\u064a\u064b\u0651\u0627'), ('biweekly', '\u0643\u0644\u0651 \u0623\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='followup_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='pss_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('', '----------'), ('daily', '\u064a\u0648\u0645\u064a\u064b\u0651\u0627'), ('every_2_to_3_days', '\u0645\u0631\u0651\u062a\u064a\u0646 \u0623\u0648 \u062b\u0644\u0627\u062b \u0645\u0631\u0651\u0627\u062a \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639'), ('weekly', '\u0623\u0633\u0628\u0648\u0639\u064a\u064b\u0651\u0627'), ('biweekly', '\u0643\u0644\u0651 \u0623\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('', '----------'), ('daily', '\u064a\u0648\u0645\u064a\u064b\u0651\u0627'), ('every_2_to_3_days', '\u0645\u0631\u0651\u062a\u064a\u0646 \u0623\u0648 \u062b\u0644\u0627\u062b \u0645\u0631\u0651\u0627\u062a \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639'), ('weekly', '\u0623\u0633\u0628\u0648\u0639\u064a\u064b\u0651\u0627'), ('biweekly', '\u0643\u0644\u0651 \u0623\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='followup_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='pss_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_message_how_often',
            field=models.CharField(blank=True, choices=[('', '----------'), ('daily', '\u064a\u0648\u0645\u064a\u064b\u0651\u0627'), ('every_2_to_3_days', '\u0645\u0631\u0651\u062a\u064a\u0646 \u0623\u0648 \u062b\u0644\u0627\u062b \u0645\u0631\u0651\u0627\u062a \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639'), ('weekly', '\u0623\u0633\u0628\u0648\u0639\u064a\u064b\u0651\u0627'), ('biweekly', '\u0643\u0644\u0651 \u0623\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_parents_message_how_often',
            field=models.CharField(blank=True, choices=[('', '----------'), ('daily', '\u064a\u0648\u0645\u064a\u064b\u0651\u0627'), ('every_2_to_3_days', '\u0645\u0631\u0651\u062a\u064a\u0646 \u0623\u0648 \u062b\u0644\u0627\u062b \u0645\u0631\u0651\u0627\u062a \u0641\u064a \u0627\u0644\u0623\u0633\u0628\u0648\u0639'), ('weekly', '\u0623\u0633\u0628\u0648\u0639\u064a\u064b\u0651\u0627'), ('biweekly', '\u0643\u0644\u0651 \u0623\u0633\u0628\u0648\u0639\u064a\u0646'), ('monthly', '\u0634\u0647\u0631\u064a\u0627\u064b')], max_length=50, null=True, verbose_name=' \u0643\u0645 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='followup_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pss_session_modality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('online', '\u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u062a\u0635\u0627\u0644 Whatsapp'), ('phone', '\u0627\u062a\u0651\u0635\u0627\u0644 \u0647\u0627\u062a\u0641\u064a\u0651'), ('offline', ' \u0639\u0646 \u0637\u0631\u064a\u0642 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u0628\u0627\u0634\u0631(\u0644\u064a\u0633 \u0639\u0628\u0631 \u0627\u0644\u0623\u0646\u062a\u0631\u0646\u062a)')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
    ]
