# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-22 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0198_auto_20210212_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln_fc',
            name='child_have_pss_wellbeing',
            field=models.TextField(blank=True, null=True, verbose_name='\u0647\u0627 \u0647\u064a \u0627\u0644\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u0627\u0644\u0645\u062d\u062f\u0651\u062f\u0629 \u0644\u0647\u0630\u0627 \u0627\u0644\u0637\u0651\u0641\u0644 \u0641\u064a\u0645\u0627 \u064a\u062a\u0639\u0644\u0651\u0642 \u0628\u0627\u0644\u062f\u0651\u0639\u0645 \u0627\u0644\u0646\u0651\u0641\u0633\u064a\u0651 \u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651 \u0648\u0627\u0644\u0631\u0651\u0641\u0627\u0647\u064a\u0651\u0629\u061f'),
        ),
    ]
