# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-03-09 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0202_abln_fc_date_start_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln_fc',
            name='number_child_participate_online',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=100, null=True, verbose_name=' \u0646\u0648\u0639 \u0627\u0644\u0628\u0631\u0646\u0627\u0645\u062c'),
        ),
    ]
