# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-03-09 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0203_auto_20210309_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_meet_lesson_objectives',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_meet_lesson_objectives_verified',
        ),
        migrations.AddField(
            model_name='abln_fc',
            name='child_expected_work_independently_verified',
            field=models.TextField(blank=True, null=True, verbose_name='\u0643\u064a\u0641 \u062a\u0645\u0651 \u0627\u0644\u062a\u0651\u062d\u0642\u0651\u0642 \u0645\u0646 \u0630\u0644\u0643\u061f (\u0645\u062b\u0644\u064f\u0627 \u0623\u064a\u0651 \u0623\u0633\u0644\u0648\u0628 \u062a\u0642\u064a\u064a\u0645\u064a\u0651 \u0627\u0633\u062a\u064f\u062e\u062f\u0650\u0645)'),
        ),
    ]
