# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-03-31 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0205_abln_fc_remote_learning_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Site / Center',
                'verbose_name_plural': 'Sites / Centers',
            },
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='child_have_pss_wellbeing',
            field=models.TextField(blank=True, null=True, verbose_name='\u0645\u0627 \u0647\u064a \u0627\u0644\u0627\u062d\u062a\u064a\u0627\u062c\u0627\u062a \u0627\u0644\u0645\u062d\u062f\u0651\u062f\u0629 \u0644\u0647\u0630\u0627 \u0627\u0644\u0637\u0651\u0641\u0644 \u0641\u064a\u0645\u0627 \u064a\u062a\u0639\u0644\u0651\u0642 \u0628\u0627\u0644\u062f\u0651\u0639\u0645 \u0627\u0644\u0646\u0651\u0641\u0633\u064a\u0651 \u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0651 \u0648\u0627\u0644\u0631\u0651\u0641\u0627\u0647\u064a\u0651\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='date_start_online',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0628\u062f\u0621 \u0627\u0644\u062a\u0651\u0639\u0644\u0651\u0645 \u0639\u0646 \u0628\u064f\u0639\u062f \u0627\u0644\u062e\u0627\u0635\u0651 \u0628\u0627\u0644\u0637\u0651\u0641\u0644'),
        ),
        migrations.AddField(
            model_name='abln',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Center', verbose_name='Site / Center'),
        ),
        migrations.AddField(
            model_name='bln',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Center', verbose_name='Site / Center'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Center', verbose_name='Site / Center'),
        ),
        migrations.AddField(
            model_name='rs',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Center', verbose_name='Site / Center'),
        ),
    ]
