# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-03-31 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0206_auto_20210331_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='rims_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RIMS Case Number'),
        ),
        migrations.AddField(
            model_name='bln',
            name='rims_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RIMS Case Number'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='rims_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RIMS Case Number'),
        ),
        migrations.AddField(
            model_name='rs',
            name='rims_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RIMS Case Number'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Center', verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0645\u0648\u0642\u0639/\u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Center', verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0645\u0648\u0642\u0639/\u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Center', verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0645\u0648\u0642\u0639/\u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Center', verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0645\u0648\u0642\u0639/\u0627\u0644\u0645\u0631\u0643\u0632'),
        ),
    ]
