# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-05-10 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0208_auto_20210402_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='learning_result_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='bln',
            name='learning_result_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='learning_result_other',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
    ]
