# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-05-10 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0211_merge_20210510_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='child_received_books',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received books'),
        ),
        migrations.AddField(
            model_name='abln',
            name='child_received_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received internet'),
        ),
        migrations.AddField(
            model_name='abln',
            name='child_received_printout',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received printout'),
        ),
        migrations.AddField(
            model_name='bln',
            name='child_received_books',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received books'),
        ),
        migrations.AddField(
            model_name='bln',
            name='child_received_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received internet'),
        ),
        migrations.AddField(
            model_name='bln',
            name='child_received_printout',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received printout'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='child_received_books',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received books'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='child_received_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received internet'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='child_received_printout',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received printout'),
        ),
        migrations.AddField(
            model_name='rs',
            name='child_received_books',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received books'),
        ),
        migrations.AddField(
            model_name='rs',
            name='child_received_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received internet'),
        ),
        migrations.AddField(
            model_name='rs',
            name='child_received_printout',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='child received printout'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='rims_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0631\u0642\u0645 \u0645\u0644\u0641 RIMS'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='rims_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0631\u0642\u0645 \u0645\u0644\u0641 RIMS'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='rims_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0631\u0642\u0645 \u0645\u0644\u0641 RIMS'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='rims_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0631\u0642\u0645 \u0645\u0644\u0641 RIMS'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='rims_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0631\u0642\u0645 \u0645\u0644\u0641 RIMS'),
        ),
    ]
