# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-05-11 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0212_auto_20210510_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0645\u0637\u0628\u0648\u0639\u0627\u062a \u0627\u0636\u0627\u0641\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='abln',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0628\u0627\u0642\u0629 \u0627\u0646\u062a\u0631\u0646\u062a'),
        ),
        migrations.AddField(
            model_name='abln',
            name='referal_other_specify',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='abln',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0643\u062a\u0628'),
        ),
        migrations.AddField(
            model_name='bln',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0645\u0637\u0628\u0648\u0639\u0627\u062a \u0627\u0636\u0627\u0641\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='bln',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0628\u0627\u0642\u0629 \u0627\u0646\u062a\u0631\u0646\u062a'),
        ),
        migrations.AddField(
            model_name='bln',
            name='referal_other_specify',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='bln',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0643\u062a\u0628'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0645\u0637\u0628\u0648\u0639\u0627\u062a \u0627\u0636\u0627\u0641\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0628\u0627\u0642\u0629 \u0627\u0646\u062a\u0631\u0646\u062a'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='referal_other_specify',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0643\u062a\u0628'),
        ),
        migrations.AddField(
            model_name='rs',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0645\u0637\u0628\u0648\u0639\u0627\u062a \u0627\u0636\u0627\u0641\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='rs',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0628\u0627\u0642\u0629 \u0627\u0646\u062a\u0631\u0646\u062a'),
        ),
        migrations.AddField(
            model_name='rs',
            name='referal_other_specify',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='rs',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0643\u062a\u0628'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='child_received_books',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0643\u062a\u0628'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='child_received_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0628\u0627\u0642\u0629 \u0627\u0646\u062a\u0631\u0646\u062a'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='child_received_printout',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0645\u0637\u0628\u0648\u0639\u0627\u062a \u0627\u0636\u0627\u0641\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='child_received_books',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0643\u062a\u0628'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='child_received_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0628\u0627\u0642\u0629 \u0627\u0646\u062a\u0631\u0646\u062a'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='child_received_printout',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0645\u0637\u0628\u0648\u0639\u0627\u062a \u0627\u0636\u0627\u0641\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='child_received_books',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0643\u062a\u0628'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='child_received_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0628\u0627\u0642\u0629 \u0627\u0646\u062a\u0631\u0646\u062a'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='child_received_printout',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0645\u0637\u0628\u0648\u0639\u0627\u062a \u0627\u0636\u0627\u0641\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='child_received_books',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0643\u062a\u0628'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='child_received_internet',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0628\u0627\u0642\u0629 \u0627\u0646\u062a\u0631\u0646\u062a'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='child_received_printout',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062d\u0635\u0644  \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0645\u0637\u0628\u0648\u0639\u0627\u062a \u0627\u0636\u0627\u0641\u064a\u0629'),
        ),
    ]
