# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-05-11 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0213_auto_20210511_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal health'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal other'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referal_other_specify',
            field=models.TextField(blank=True, null=True, verbose_name='referal other specify'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal wash'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal health'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal other'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referal_other_specify',
            field=models.TextField(blank=True, null=True, verbose_name='referal other specify'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal wash'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal health'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal other'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referal_other_specify',
            field=models.TextField(blank=True, null=True, verbose_name='referal other specify'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal wash'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal health'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal other'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referal_other_specify',
            field=models.TextField(blank=True, null=True, verbose_name='referal other specify'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='referal wash'),
        ),
    ]
