# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-05-20 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0214_auto_20210511_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abln_fc',
            name='actions_before_next_class',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='actions_before_next_class_how',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_awareness_prevention_covid19',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_caregiver_challenges',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_complete_printed_package',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_coping_home_learning',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_engaged_lesson',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_engaged_lesson_explain',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_expected_work_independently_verified',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_have_pss_wellbeing',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_have_pss_wellbeing_explain',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_participate_others_no_explain',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_practice_basic_handwashing',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_practice_basic_handwashing_explain',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='date_start_online',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='followup_done_messages',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='followup_explain',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='followup_not_join_online',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='girls_boys_participate_access_device',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='girls_boys_participate_explain',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='homework_after_lesson_explain',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='homework_score',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='homework_score_explain',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='how_contact_caregivers',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='how_keep_touch_caregivers_specify',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='how_make_sure_child_access_online',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='how_often_contact_caregivers',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='materials_needed',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='materials_needed_reason_no',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='number_child_participate_online',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='numbers_child_monitored',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='parents_supporting_student_explain',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='remote_learning_reason',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='share_expectations_caregiver',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='share_expectations_no_reason',
        ),
        migrations.RemoveField(
            model_name='abln_fc',
            name='times_voice_contact_child_caregiver',
        ),
        migrations.AlterField(
            model_name='abln',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c Health'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0623\u062e\u0631'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c Wash'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c Health'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0623\u062e\u0631'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c Wash'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c Health'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0623\u062e\u0631'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c Wash'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referal_health',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c Health'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referal_other',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c \u0623\u062e\u0631'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='referal_wash',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u062a\u062d\u0648\u064a\u0644 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c Wash'),
        ),
    ]
