# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-01-17 12:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0218_auto_20220117_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inclusion',
            name='child_dropout_other',
        ),
        migrations.AddField(
            model_name='inclusion',
            name='child_dropout_specify',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
    ]
