# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-01-17 13:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0219_auto_20220117_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusion',
            name='caregiver_trained_parental_engagement',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Mother Only', 'Mother Only'), ('Father Only', 'Father Only'), ('Both Mother and Father', 'Both Mother and Father'), ('None', '\u0644\u0627\u0634\u064a\u0621'), ('Other', '\u0622\u062e\u0631'), ('Not begun yet', 'Not begun yet')], max_length=100, null=True, verbose_name='Have the Caregivers been trained on the Parental Engagement Curriculum? '),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='child_dropout',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Has the child dropped out of the program?'),
        ),
    ]
