# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-01-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0222_auto_20220119_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln_fc',
            name='fc_type',
            field=models.CharField(blank=True, choices=[('pre-arabic', 'Pre Arabic'), ('pre-math', 'Pre Math'), ('post-arabic', 'Post Arabic'), ('post-math', 'Post Math'), ('arabic', '\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('math', '\u0627\u0644\u0631\u064a\u0627\u0636\u064a\u0627\u062a')], max_length=50, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644'),
        ),
        migrations.AlterField(
            model_name='bln_fc',
            name='fc_type',
            field=models.CharField(blank=True, choices=[('pre-arabic', 'Pre Arabic'), ('pre-math', 'Pre Math'), ('pre-language', 'Pre Language'), ('post-arabic', 'Post Arabic'), ('post-math', 'Post Math'), ('post-language', 'Post Language'), ('arabic', '\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('language', 'Language'), ('math', '\u0627\u0644\u0631\u064a\u0627\u0636\u064a\u0627\u062a')], max_length=50, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644'),
        ),
        migrations.AlterField(
            model_name='cbece_fc',
            name='fc_type',
            field=models.CharField(blank=True, choices=[('pre-arabic', 'Pre Arabic'), ('pre-math', 'Pre Math'), ('pre-language', 'Pre Language'), ('post-arabic', 'Post Arabic'), ('post-math', 'Post Math'), ('post-language', 'Post Language'), ('arabic', '\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('language', 'Language'), ('math', '\u0627\u0644\u0631\u064a\u0627\u0636\u064a\u0627\u062a')], max_length=50, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644'),
        ),
        migrations.AlterField(
            model_name='rs_fc',
            name='fc_type',
            field=models.CharField(blank=True, choices=[('pre-arabic', 'Pre Arabic'), ('pre-math', 'Pre Math'), ('pre-language', 'Pre Language'), ('pre-science', 'Pre Science'), ('pre-biology', 'Pre Biology'), ('pre-chemistry', 'Pre Chemistry'), ('pre-physics', 'Pre Physics'), ('post-arabic', 'Post Arabic'), ('post-math', 'Post Math'), ('post-language', 'Post Language'), ('post-science', 'Post Science'), ('post-biology', 'Post Biology'), ('post-chemistry', 'Post Chemistry'), ('post-physics', 'Post Physics'), ('arabic', '\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('language', 'Language'), ('math', '\u0627\u0644\u0631\u064a\u0627\u0636\u064a\u0627\u062a')], max_length=50, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644'),
        ),
    ]
