# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-02-04 11:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0227_auto_20220128_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='akelius_program',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('Center', 'Center'), ('Home', '\u0627\u0644\u0631\u0626\u064a\u0633\u064a\u0629'), ('All', '\u0627\u0644\u0643\u0644')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Did the child use Akelius program'),
        ),
        migrations.AddField(
            model_name='bln',
            name='akelius_program',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('Center', 'Center'), ('Home', '\u0627\u0644\u0631\u0626\u064a\u0633\u064a\u0629'), ('All', '\u0627\u0644\u0643\u0644')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Did the child use Akelius program'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='akelius_program',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('Center', 'Center'), ('Home', '\u0627\u0644\u0631\u0626\u064a\u0633\u064a\u0629'), ('All', '\u0627\u0644\u0643\u0644')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Did the child use Akelius program'),
        ),
        migrations.AddField(
            model_name='outreach',
            name='akelius_program',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('Center', 'Center'), ('Home', '\u0627\u0644\u0631\u0626\u064a\u0633\u064a\u0629'), ('All', '\u0627\u0644\u0643\u0644')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Did the child use Akelius program'),
        ),
        migrations.AddField(
            model_name='rs',
            name='akelius_program',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('Center', 'Center'), ('Home', '\u0627\u0644\u0631\u0626\u064a\u0633\u064a\u0629'), ('All', '\u0627\u0644\u0643\u0644')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Did the child use Akelius program'),
        ),
    ]
