# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-02-04 12:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0228_auto_20220204_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='akelius_program',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('child using Akelius in Center', 'child using Akelius in Center'), ('child using Akelius at Home', 'child using Akelius at Home'), ('Child is not using Akelius at all', 'Child is not using Akelius at all')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Did the child use Akelius program'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='akelius_program',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('child using Akelius in Center', 'child using Akelius in Center'), ('child using Akelius at Home', 'child using Akelius at Home'), ('Child is not using Akelius at all', 'Child is not using Akelius at all')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Did the child use Akelius program'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='akelius_program',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('child using Akelius in Center', 'child using Akelius in Center'), ('child using Akelius at Home', 'child using Akelius at Home'), ('Child is not using Akelius at all', 'Child is not using Akelius at all')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Did the child use Akelius program'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='akelius_program',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('child using Akelius in Center', 'child using Akelius in Center'), ('child using Akelius at Home', 'child using Akelius at Home'), ('Child is not using Akelius at all', 'Child is not using Akelius at all')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Did the child use Akelius program'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='akelius_program',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('child using Akelius in Center', 'child using Akelius in Center'), ('child using Akelius at Home', 'child using Akelius at Home'), ('Child is not using Akelius at all', 'Child is not using Akelius at all')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Did the child use Akelius program'),
        ),
    ]
