# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-02-17 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0232_auto_20220216_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abln_fc',
            name='child_performance_evaluation',
        ),
        migrations.RemoveField(
            model_name='bln_fc',
            name='child_performance_evaluation',
        ),
        migrations.RemoveField(
            model_name='cbece_fc',
            name='child_performance_evaluation',
        ),
        migrations.RemoveField(
            model_name='rs_fc',
            name='child_performance_evaluation',
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='lesson_modality',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Online', 'Online'), ('Present', '\u062d\u0627\u0636\u0631'), ('Blended', 'Blended')], max_length=100, null=True, verbose_name='\u0627\u0644\u062f\u0631\u0633 \u0627\u0644\u062d\u0627\u0644\u064a'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='steps_acquire_competency',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Re-explain', 'Re-explain'), ('Extra Howmework', 'Extra Howmework'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0645\u0627 \u0647\u064a \u0627\u0644\u062e\u0637\u0648\u0627\u062a \u0627\u0644\u062a\u0627\u0644\u064a\u0629 \u0644\u0645\u0633\u0627\u0639\u062f\u0629 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0627\u0643\u062a\u0633\u0627\u0628 \u0627\u0644\u0643\u0641\u0627\u064a\u0629 \u0627\u0644\u0645\u0633\u062a\u0647\u062f\u0641\u0629'),
        ),
        migrations.AlterField(
            model_name='bln_fc',
            name='lesson_modality',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Online', 'Online'), ('Present', '\u062d\u0627\u0636\u0631'), ('Blended', 'Blended')], max_length=100, null=True, verbose_name='\u0627\u0644\u062f\u0631\u0633 \u0627\u0644\u062d\u0627\u0644\u064a'),
        ),
        migrations.AlterField(
            model_name='bln_fc',
            name='steps_acquire_competency',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Re-explain', 'Re-explain'), ('Extra Howmework', 'Extra Howmework'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0645\u0627 \u0647\u064a \u0627\u0644\u062e\u0637\u0648\u0627\u062a \u0627\u0644\u062a\u0627\u0644\u064a\u0629 \u0644\u0645\u0633\u0627\u0639\u062f\u0629 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0627\u0643\u062a\u0633\u0627\u0628 \u0627\u0644\u0643\u0641\u0627\u064a\u0629 \u0627\u0644\u0645\u0633\u062a\u0647\u062f\u0641\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece_fc',
            name='lesson_modality',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Online', 'Online'), ('Present', '\u062d\u0627\u0636\u0631'), ('Blended', 'Blended')], max_length=100, null=True, verbose_name='\u0627\u0644\u062f\u0631\u0633 \u0627\u0644\u062d\u0627\u0644\u064a'),
        ),
        migrations.AlterField(
            model_name='cbece_fc',
            name='steps_acquire_competency',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Re-explain', 'Re-explain'), ('Extra Howmework', 'Extra Howmework'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0645\u0627 \u0647\u064a \u0627\u0644\u062e\u0637\u0648\u0627\u062a \u0627\u0644\u062a\u0627\u0644\u064a\u0629 \u0644\u0645\u0633\u0627\u0639\u062f\u0629 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0627\u0643\u062a\u0633\u0627\u0628 \u0627\u0644\u0643\u0641\u0627\u064a\u0629 \u0627\u0644\u0645\u0633\u062a\u0647\u062f\u0641\u0629'),
        ),
        migrations.AlterField(
            model_name='rs_fc',
            name='fc_type',
            field=models.CharField(blank=True, choices=[('pre-arabic', 'Pre Arabic'), ('pre-math', 'Pre Math'), ('pre-language', 'Pre Language'), ('pre-science', 'Pre Science'), ('pre-biology', 'Pre Biology'), ('pre-chemistry', 'Pre Chemistry'), ('pre-physics', 'Pre Physics'), ('post-arabic', 'Post Arabic'), ('post-math', 'Post Math'), ('post-language', 'Post Language'), ('post-science', 'Post Science'), ('post-biology', 'Post Biology'), ('post-chemistry', 'Post Chemistry'), ('post-physics', 'Post Physics'), ('arabic', '\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('language', 'Language'), ('math', '\u0627\u0644\u0631\u064a\u0627\u0636\u064a\u0627\u062a'), ('science', '\u0627\u0644\u0639\u0644\u0648\u0645'), ('biology', '\u0639\u0644\u0648\u0645 \u0627\u0644\u062d\u064a\u0627\u0629'), ('chemistry', '\u0643\u064a\u0645\u064a\u0627\u0621'), ('physics', 'Physics')], max_length=50, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0639\u0645\u0644'),
        ),
        migrations.AlterField(
            model_name='rs_fc',
            name='lesson_modality',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Online', 'Online'), ('Present', '\u062d\u0627\u0636\u0631'), ('Blended', 'Blended')], max_length=100, null=True, verbose_name='\u0627\u0644\u062f\u0631\u0633 \u0627\u0644\u062d\u0627\u0644\u064a'),
        ),
        migrations.AlterField(
            model_name='rs_fc',
            name='steps_acquire_competency',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Re-explain', 'Re-explain'), ('Extra Howmework', 'Extra Howmework'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name='\u0645\u0627 \u0647\u064a \u0627\u0644\u062e\u0637\u0648\u0627\u062a \u0627\u0644\u062a\u0627\u0644\u064a\u0629 \u0644\u0645\u0633\u0627\u0639\u062f\u0629 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0627\u0643\u062a\u0633\u0627\u0628 \u0627\u0644\u0643\u0641\u0627\u064a\u0629 \u0627\u0644\u0645\u0633\u062a\u0647\u062f\u0641\u0629'),
        ),
    ]
