# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-14 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0238_auto_20220303_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridging',
            name='child_complete_year',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did the child fully complete the school year?'),
        ),
        migrations.AddField(
            model_name='bridging',
            name='community_Liaison_follow_up',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Was the community Liaison at school level involved in follow up on child absence or drop out?'),
        ),
        migrations.AddField(
            model_name='bridging',
            name='community_liaison_specify',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='bridging',
            name='receiving_social_assistance',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Is the child receiving social assistance?'),
        ),
        migrations.AddField(
            model_name='bridging',
            name='receiving_transportation_support',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Is the Child Receiving Transportation Support?'),
        ),
        migrations.AddField(
            model_name='bridging',
            name='using_digital_platform',
            field=models.CharField(blank=True, choices=[('yes_akelius)', 'Yes (Akelius)'), ('yes_learning_passport)', 'Yes (Learning Passport)'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='Is the Child Using a digital platform (Akelius or  Learning Passport)'),
        ),
    ]
