# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-04-22 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0239_auto_20220414_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='child_complete_year',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0627\u062a\u0645 \u0627\u0644\u0637\u0641\u0644 \u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062f\u0631\u0627\u0633\u064a\u0629 \u0628\u0646\u062c\u0627\u062d?'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='community_Liaison_follow_up',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0627\u0644\u0645\u062c\u062a\u0645\u0639\u064a \u0639\u0644\u0649 \u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0645\u062f\u0631\u0633\u0629 \u0641\u064a \u0645\u062a\u0627\u0628\u0639\u0629 \u063a\u064a\u0627\u0628 \u0627\u0644\u0637\u0641\u0644 \u0623\u0648 \u062a\u0633\u0631\u0628\u0647'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='receiving_social_assistance',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u064a\u062a\u0644\u0642\u0649 \u0627\u0644\u0637\u0641\u0644 \u0645\u0633\u0627\u0639\u062f\u0629 \u0627\u062c\u062a\u0645\u0627\u0639\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='receiving_transportation_support',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u064a\u062a\u0644\u0642\u0649 \u0627\u0644\u0637\u0641\u0644 \u0628\u062f\u0644 \u0627\u0644\u0645\u0648\u0627\u0635\u0644\u0627\u062a\u061f'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='registration_level',
            field=models.CharField(blank=True, choices=[('', '----------'), ('level_one', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0623\u0648\u0644'), ('level_two', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062b\u0627\u0646\u064a'), ('level_three', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062b\u0627\u0644\u062b'), ('level_four', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0631\u0627\u0628\u0639'), ('level_five', 'Level five'), ('level_six', 'Level six')], max_length=100, null=True, verbose_name='\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0633\u062c\u064a\u0644'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='using_digital_platform',
            field=models.CharField(blank=True, choices=[('yes_akelius)', 'Yes (Akelius)'), ('yes_learning_passport)', 'Yes (Learning Passport)'), ('no', '\u0643\u0644\u0627')], max_length=100, null=True, verbose_name='(Learning passport, Akelius) \u0647\u0644 \u064a\u0633\u062a\u062e\u062f\u0645 \u0627\u0644\u0637\u0641\u0644 \u0645\u0646\u0635\u0629 \u0631\u0642\u0645\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
    ]
