# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-13 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0124_auto_20220303_1520'),
        ('clm', '0242_auto_20220513_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridging',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='School Namel'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='community_Liaison_follow_up',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0642\u0627\u0645 \u0645\u0648\u0638\u0641 \u0627\u0644\u062a\u0648\u0627\u0635\u0644  \u0628\u0627\u0644\u0625\u062a\u0635\u0627\u0644 \u0648 \u0645\u062a\u0627\u0628\u0639\u0629 \u063a\u064a\u0627\u0628 \u0627\u0644\u0637\u0641\u0644 \u0627\u0648 \u062a\u0633\u0631\u0628\u0647 \u0645\u0646 \u0627\u0644\u0645\u062f\u0631\u0633\u0629'),
        ),
    ]
