# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-24 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0243_auto_20220513_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridging',
            name='child_complete_year',
        ),
        migrations.AlterField(
            model_name='bridging',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('graduated_to_Bridging_next_level', 'Graduated to the next level SBP'), ('graduated_to_Bridging_next_round_same_level', 'Graduated to the next round, same level SBP'), ('referred_public_school', '\u064a\u0631\u0641\u0639 \u0627\u0644\u0649 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0631\u0633\u0645\u064a'), ('dropout', '\u0627\u0644\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062f\u0648\u0631\u0629'), ('other', '\u0622\u062e\u0631')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0645\u062f\u0631\u0633\u0629'),
        ),
    ]
