# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-31 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0245_auto_20220527_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': "'Learning result",
            },
        ),
        migrations.RemoveField(
            model_name='bridging',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='bridging',
            name='section',
        ),
        migrations.AlterField(
            model_name='bridging',
            name='registration_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.RegistrationLevel', verbose_name='\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0633\u062c\u064a\u0644'),
        ),
    ]
