# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0247_auto_20220602_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='covid_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0627\u0644\u0637\u0641\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='covid_parents_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0645\u0642\u062f\u0645 \u0627\u0644\u0631\u0639\u0627\u064a\u0629 /\u0627\u0644\u0627\u0647\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='follow_up_done',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0625\u062c\u0631\u0627\u0621 \u0623\u064a \u0645\u062a\u0627\u0628\u0639\u0629 \u0644\u0636\u0645\u0627\u0646 \u062a\u0644\u0642\u064a \u0627\u0644\u0631\u0633\u0627\u0626\u0644 \u0648\u0641\u0647\u0645\u0647\u0627 \u0648\u0627\u0639\u062a\u0645\u0627\u062f\u0647\u0627 \u0628\u0634\u0643\u0644 \u062c\u064a\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='gender_participate',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0643\u0644 \u0645\u0646 \u0627\u0644\u0641\u062a\u064a\u0627\u062a \u0648\u0627\u0644\u0641\u062a\u064a\u0627\u0646 \u0645\u0646 \u0646\u0641\u0633 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0641\u064a \u0627\u0644\u0641\u0635\u0644 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0648\u062a\u0645\u0643\u0646\u0648\u0627 \u0645\u0646 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0627\u0644\u0647\u0627\u062a\u0641/\u0627\u0644\u062c\u0647\u0627\u0632\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='pss_kit',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0639\u062f\u0629 \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a\u061f'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0627\u0644\u0637\u0641\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='covid_parents_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0645\u0642\u062f\u0645 \u0627\u0644\u0631\u0639\u0627\u064a\u0629 /\u0627\u0644\u0627\u0647\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='follow_up_done',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0625\u062c\u0631\u0627\u0621 \u0623\u064a \u0645\u062a\u0627\u0628\u0639\u0629 \u0644\u0636\u0645\u0627\u0646 \u062a\u0644\u0642\u064a \u0627\u0644\u0631\u0633\u0627\u0626\u0644 \u0648\u0641\u0647\u0645\u0647\u0627 \u0648\u0627\u0639\u062a\u0645\u0627\u062f\u0647\u0627 \u0628\u0634\u0643\u0644 \u062c\u064a\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='gender_participate',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0643\u0644 \u0645\u0646 \u0627\u0644\u0641\u062a\u064a\u0627\u062a \u0648\u0627\u0644\u0641\u062a\u064a\u0627\u0646 \u0645\u0646 \u0646\u0641\u0633 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0641\u064a \u0627\u0644\u0641\u0635\u0644 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0648\u062a\u0645\u0643\u0646\u0648\u0627 \u0645\u0646 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0627\u0644\u0647\u0627\u062a\u0641/\u0627\u0644\u062c\u0647\u0627\u0632\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='pss_kit',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0639\u062f\u0629 \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a\u061f'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='covid_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0627\u0644\u0637\u0641\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='covid_parents_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0645\u0642\u062f\u0645 \u0627\u0644\u0631\u0639\u0627\u064a\u0629 /\u0627\u0644\u0627\u0647\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='follow_up_done',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0625\u062c\u0631\u0627\u0621 \u0623\u064a \u0645\u062a\u0627\u0628\u0639\u0629 \u0644\u0636\u0645\u0627\u0646 \u062a\u0644\u0642\u064a \u0627\u0644\u0631\u0633\u0627\u0626\u0644 \u0648\u0641\u0647\u0645\u0647\u0627 \u0648\u0627\u0639\u062a\u0645\u0627\u062f\u0647\u0627 \u0628\u0634\u0643\u0644 \u062c\u064a\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='gender_participate',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0643\u0644 \u0645\u0646 \u0627\u0644\u0641\u062a\u064a\u0627\u062a \u0648\u0627\u0644\u0641\u062a\u064a\u0627\u0646 \u0645\u0646 \u0646\u0641\u0633 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0641\u064a \u0627\u0644\u0641\u0635\u0644 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0648\u062a\u0645\u0643\u0646\u0648\u0627 \u0645\u0646 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0627\u0644\u0647\u0627\u062a\u0641/\u0627\u0644\u062c\u0647\u0627\u0632\u061f'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='pss_kit',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0639\u062f\u0629 \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a\u061f'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0627\u0644\u0637\u0641\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='covid_parents_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0645\u0642\u062f\u0645 \u0627\u0644\u0631\u0639\u0627\u064a\u0629 /\u0627\u0644\u0627\u0647\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='follow_up_done',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0625\u062c\u0631\u0627\u0621 \u0623\u064a \u0645\u062a\u0627\u0628\u0639\u0629 \u0644\u0636\u0645\u0627\u0646 \u062a\u0644\u0642\u064a \u0627\u0644\u0631\u0633\u0627\u0626\u0644 \u0648\u0641\u0647\u0645\u0647\u0627 \u0648\u0627\u0639\u062a\u0645\u0627\u062f\u0647\u0627 \u0628\u0634\u0643\u0644 \u062c\u064a\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='gender_participate',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0643\u0644 \u0645\u0646 \u0627\u0644\u0641\u062a\u064a\u0627\u062a \u0648\u0627\u0644\u0641\u062a\u064a\u0627\u0646 \u0645\u0646 \u0646\u0641\u0633 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0641\u064a \u0627\u0644\u0641\u0635\u0644 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0648\u062a\u0645\u0643\u0646\u0648\u0627 \u0645\u0646 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0627\u0644\u0647\u0627\u062a\u0641/\u0627\u0644\u062c\u0647\u0627\u0632\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='pss_kit',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0639\u062f\u0629 \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a\u061f'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='covid_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0627\u0644\u0637\u0641\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='covid_parents_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0645\u0642\u062f\u0645 \u0627\u0644\u0631\u0639\u0627\u064a\u0629 /\u0627\u0644\u0627\u0647\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='follow_up_done',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0625\u062c\u0631\u0627\u0621 \u0623\u064a \u0645\u062a\u0627\u0628\u0639\u0629 \u0644\u0636\u0645\u0627\u0646 \u062a\u0644\u0642\u064a \u0627\u0644\u0631\u0633\u0627\u0626\u0644 \u0648\u0641\u0647\u0645\u0647\u0627 \u0648\u0627\u0639\u062a\u0645\u0627\u062f\u0647\u0627 \u0628\u0634\u0643\u0644 \u062c\u064a\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='gender_participate',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0643\u0644 \u0645\u0646 \u0627\u0644\u0641\u062a\u064a\u0627\u062a \u0648\u0627\u0644\u0641\u062a\u064a\u0627\u0646 \u0645\u0646 \u0646\u0641\u0633 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0641\u064a \u0627\u0644\u0641\u0635\u0644 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0648\u062a\u0645\u0643\u0646\u0648\u0627 \u0645\u0646 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0627\u0644\u0647\u0627\u062a\u0641/\u0627\u0644\u062c\u0647\u0627\u0632\u061f'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='pss_kit',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0639\u062f\u0629 \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a\u061f'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='basic_stationery',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u062c\u0645\u064a\u0639 \u0627\u0644\u0645\u0648\u0627\u062f \u0648\u0627\u0644\u0645\u0648\u0627\u0631\u062f \u0627\u0644\u062a\u064a \u064a\u062d\u062a\u0627\u062c\u0647\u0627 (\u0642\u0631\u0637\u0627\u0633\u064a\u0629 \u060c \u0643\u062a\u0628 \u060c \u062d\u0632\u0645\u0629 \u062a\u0639\u0644\u064a\u0645\u064a\u0629)\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0627\u0644\u0637\u0641\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='covid_parents_message',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0645\u0642\u062f\u0645 \u0627\u0644\u0631\u0639\u0627\u064a\u0629 /\u0627\u0644\u0627\u0647\u0644 \u0645\u0628\u0627\u0634\u0631\u0629\u064b \u0645\u0646 \u062e\u0644\u0627\u0644 \u0631\u0633\u0627\u0626\u0644 \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u062d\u0648\u0644 Covid-19 \u0648\u062a\u062f\u0627\u0628\u064a\u0631 \u0627\u0644\u0648\u0642\u0627\u064a\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='follow_up_done',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062a\u0645 \u0625\u062c\u0631\u0627\u0621 \u0623\u064a \u0645\u062a\u0627\u0628\u0639\u0629 \u0644\u0636\u0645\u0627\u0646 \u062a\u0644\u0642\u064a \u0627\u0644\u0631\u0633\u0627\u0626\u0644 \u0648\u0641\u0647\u0645\u0647\u0627 \u0648\u0627\u0639\u062a\u0645\u0627\u062f\u0647\u0627 \u0628\u0634\u0643\u0644 \u062c\u064a\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='gender_participate',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0643\u0644 \u0645\u0646 \u0627\u0644\u0641\u062a\u064a\u0627\u062a \u0648\u0627\u0644\u0641\u062a\u064a\u0627\u0646 \u0645\u0646 \u0646\u0641\u0633 \u0627\u0644\u0639\u0627\u0626\u0644\u0629 \u0641\u064a \u0627\u0644\u0641\u0635\u0644 \u0627\u0644\u062a\u0639\u0644\u064a\u0645\u064a \u0648\u062a\u0645\u0643\u0646\u0648\u0627 \u0645\u0646 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0627\u0644\u0647\u0627\u062a\u0641/\u0627\u0644\u062c\u0647\u0627\u0632\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pss_kit',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name=' \u0647\u0644 \u062d\u0635\u0644 \u0627\u0644\u0637\u0641\u0644 \u0639\u0644\u0649 \u0639\u062f\u0629 \u0627\u0644\u062f\u0639\u0645 \u0627\u0644\u0646\u0641\u0633\u064a\u061f'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u0634\u0627\u0631\u0643 \u0627\u0644\u0637\u0641\u0644 \u0641\u064a \u0627\u0644\u062a\u0639\u0644\u0645 \u0639\u0646 \u0628\u0639\u062f\u061f'),
        ),
    ]
