# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-07 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0249_mscc'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscc',
            name='center_p_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Center P-code'),
        ),
    ]
