# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-07 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0250_mscc_center_p_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscc',
            name='center_type',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Municipality', 'Municipality'), ('Collective Settlement', 'Collective Settlement'), ('Informal Settlement', 'Informal Settlement'), ('Welfare Center', 'Welfare Center'), ('Collective Settlement', 'Collective Settlement')], max_length=100, null=True, verbose_name='Center Type'),
        ),
    ]
