# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-20 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0251_merge_20230110_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalquestionnaire',
            options={'ordering': ['id'], 'verbose_name': 'General Questionnaire', 'verbose_name_plural': 'General Questionnaire'},
        ),
    ]
