# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-07 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0251_mscc_center_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscc',
            name='source_of_identification',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Dirassa', 'Dirassa'), ('Awarness Session', '\u0627\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u062d\u0645\u0644\u0627\u062a \u0627\u0644\u062a\u0648\u0639\u064a\u0629 \u0627\u0644\u062c\u0645\u0639\u064a\u0629'), ('Childs parents', 'Childs parents'), ('From Hosted Community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0627\u0644\u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0645\u0636\u064a\u0641'), ('Sector Partners referral (CP, Education, Health, Wash, Youth, Palestenian program...) ', 'Sector Partners referral (CP, Education, Health, Wash, Youth, Palestenian program...) '), ('From Profiling Database', '\u0625\u062d\u0627\u0644\u0629 \u0639\u0646 \u0637\u0631\u064a\u0642 Profiling Database'), ('From Other NGO', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u062c\u0645\u0639\u064a\u0629 \u0623\u062e\u0631\u0649'), ('From Displaced Community', '\u0625\u062d\u0627\u0644\u0629 \u0645\u0646 \u0642\u0628\u0644 \u0645\u062c\u062a\u0645\u0639 \u0627\u0644\u0646\u0627\u0632\u062d\u064a\u0646'), ('Referred by the municipality/Other formal sources', 'Referred by the municipality/Other formal sources'), ('Other Sources', '\u0645\u0635\u0627\u062f\u0631 \u0623\u062e\u0631\u0649')], max_length=100, null=True, verbose_name='\u0645\u0635\u062f\u0631 \u0627\u062d\u0627\u0644\u0629 \u0627\u0644\u0637\u0641\u0644  \u0625\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ABLN'),
        ),
    ]
