# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-17 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0250_auto_20230109_2159'),
        ('clm', '0250_auto_20230109_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalquestionnaire',
            options={'ordering': ['id'], 'verbose_name': 'General Questionnaire', 'verbose_name_plural': 'General Questionnaire'},
        ),
    ]
