# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-07 20:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0252_auto_20221007_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mscc',
            options={'ordering': ['-id'], 'verbose_name': 'MSCC', 'verbose_name_plural': 'MSCC'},
        ),
        migrations.AddField(
            model_name='mscc',
            name='cash_support_programmes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('Haddi', 'Haddi'), ('Education Cash assistance', 'Education Cash assistance'), ('UNHCR cash assistance', 'UNHCR cash assistance'), ('WFP cash assistance', 'WFP cash assistance')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Cash support programmes that child is already benefitting from'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='packages_received',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('Early Childhood Development', 'Early Childhood Development'), ('Education', '\u062a\u0631\u0628\u064a\u0629'), ('Child Protection/Psychosocial support', 'Child Protection/Psychosocial support'), ('Youth Empowerment and engagement', 'Youth Empowerment and engagement'), ('Health and Nutrition', 'Health and Nutrition'), ('Parental and Caregiver Support', 'Parental and Caregiver Support'), ('Social Cash Assistance', 'Social Cash Assistance')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Packages received/to be provided to child under MSCC'),
        ),
    ]
