# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-02-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0252_auto_20230120_1501'),
        ('clm', '0252_auto_20230117_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridging',
            name='residence_type',
            field=models.CharField(blank=True, choices=[('', 'Residence Type'), ('Informal settlement', 'Informal settlement - \u0645\u062e\u064a\u0645'), ('House', 'House - \u0645\u0646\u0632\u0644'), ('Collective shelter', 'Collective shelter - \u0645\u062c\u0645\u0639 \u0633\u0643\u0646\u064a  ')], max_length=100, null=True, verbose_name='Residence Type'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='have_labour_single_selection',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=100, null=True, verbose_name='Does the child participate in work?'),
        ),
    ]
