# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0253_auto_20221007_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscc',
            name='education_status',
            field=models.CharField(blank=True, choices=[('', '----------'), ('out of school', '\u0644\u0645 \u064a\u0633\u062c\u0644 \u0627\u0628\u062f\u0627 \u0641\u064a \u0627\u0644\u0645\u062f\u0631\u0633\u0629 \u0645\u0646 \u0642\u0628\u0644'), ('Was registered in formal school but didnt continue', 'Was registered in formal school but didnt continue'), ('Was registered in non formal program and was referred to MSCC', 'Was registered in non formal program and was referred to MSCC'), ('Was registered in non formal program but did not continue', 'Was registered in non formal program but did not continue'), ('Was enrolled in TVET Programs', 'Was enrolled in TVET Programse')], max_length=100, null=True, verbose_name='\u0627\u0644\u0648\u0636\u0639 \u0627\u0644\u062f\u0631\u0627\u0633\u064a \u0644\u0644\u0637\u0641\u0644 \u0639\u0646\u062f \u0627\u0644\u062a\u0633\u062c\u064a\u0644 \u0641\u064a \u0627\u0644\u062f\u0648\u0631\u0629'),
        ),
    ]
