# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-25 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0255_auto_20221025_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscc',
            name='enrollement_reason',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='What is the reason for the adolescent enrollement in the programme?'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='pre_tests_administered',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Were pre-tests administered to assess adolescents level?'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='previous_community_initiative',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Was the adolescent part of any previous community based initiative?'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='volunteering_experience',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Does the adolescent have any volunteering experience?'),
        ),
    ]
