# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0255_bridging_child_outreach'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridging',
            name='consent_parents',
            field=models.FileField(blank=True, null=True, upload_to='uploads/child', verbose_name='Consent from parents'),
        ),
    ]
