# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-30 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0256_auto_20221025_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscc',
            name='adolescent_attendance',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Full attendance', 'Full attendance'), ('Absence for less than 5 days', 'Absence for less than 5 days'), ('Absence for more than 5 days', 'Absence for more than 5 days'), ('Dropout', ' \u0645\u062a\u0633\u0631\u0628 \u0645\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645')], max_length=200, null=True, verbose_name='Adolescent attendance'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='adolescent_dropout_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dropout Date'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='adolescent_dropout_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for dropout'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='community_initiatives_specify',
            field=models.TextField(blank=True, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='life_skills_completed',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did the adolescent complete the life skills package?'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='participate_community_initiatives',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did the adolescent participate/come up in community based initiatives?'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='participate_volunteering',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did the adolescent participate in any volunteering opportunity during the course of the program?'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='receive_passing_grade',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did the adolescent receive a passing grade for the tests?'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='social_course',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did the adolescent benefit from any social innovation/entrepreneurship course?'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='test_diagnostic_done',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did the adolescent undertake any Post Diagnostic tests?'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='volunteering_specify',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Printed workbook', 'Printed workbook'), ('Tablets', 'Tablets'), ('Access to digital content (learning Passport) ', 'Access to digital content (learning Passport) '), ('Other', '\u0622\u062e\u0631')], max_length=200, null=True, verbose_name='What training material was provided?'),
        ),
        migrations.AddField(
            model_name='mscc',
            name='yfs_course_completed',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Did the adolescent complete the YFS course?'),
        ),
        migrations.AlterField(
            model_name='mscc',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', ' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'), ('Transition to FE', 'Transition to FE'), ('Repeat the school year', 'Repeat the school year'), ('Refer to a UNICEF Youth Programme (skills tranining, CBT, GIL)', 'Refer to a UNICEF Youth Programme (skills tranining, CBT, GIL)'), ('Transition to TVET', 'Transition to TVET'), ('Internship or volunteering opportunity', 'Internship or volunteering opportunity')], max_length=100, null=True, verbose_name=' \u0646\u062a\u064a\u062c\u0629 \u0627\u0644\u062a\u0639\u0644\u0645'),
        ),
    ]
