# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-31 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0256_bridging_consent_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridging',
            name='consent_parents',
            field=models.FileField(blank=True, null=True, upload_to='uploads/student', verbose_name='Consent from parents'),
        ),
    ]
