# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-10-30 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0257_auto_20221030_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscc',
            name='training_material',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Printed workbook', 'Printed workbook'), ('Tablets', 'Tablets'), ('Access to digital content (learning Passport) ', 'Access to digital content (learning Passport) '), ('Other', '\u0622\u062e\u0631')], max_length=200, null=True, verbose_name='What training material was provided?'),
        ),
        migrations.AlterField(
            model_name='mscc',
            name='volunteering_specify',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Outreach', 'Outreach'), ('Data entry', 'Data entry'), ('Admin work', 'Admin work'), ('Awareness raising sessions', 'Awareness raising sessions'), ('Empowerment and leadership', 'Empowerment and leadership'), ('Other', '\u0622\u062e\u0631')], max_length=200, null=True, verbose_name='Please specify the volunteering opportunity'),
        ),
    ]
