# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0257_auto_20230331_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridging',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', '----------'), ('graduated_to_Bridging_next_level', 'Graduated to the next level SBP'), ('graduated_to_Bridging_next_round_same_level', 'Graduated to the next round, same level SBP'), ('referred_public_school', 'Referred to public school'), ('dropout', 'Dropout, referral not possible'), ('other', 'Other')], max_length=100, null=True, verbose_name='Learning result'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='residence_type',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Informal settlement', 'Informal settlement - \u0645\u062e\u064a\u0645'), ('House', 'House - \u0645\u0646\u0632\u0644'), ('Collective shelter', 'Collective shelter - \u0645\u062c\u0645\u0639 \u0633\u0643\u0646\u064a  ')], max_length=100, null=True, verbose_name='Residence Type'),
        ),
    ]
