# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-29 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0258_auto_20230428_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridging',
            name='education_status',
            field=models.CharField(blank=True, choices=[('', '----------'), ('No Registered in any school before', 'Not Registered in any school before'), ('Was registered in BLN program', 'Was registered in BLN program'), ('Was registered in formal school and didnt continue', 'Was registered in formal school and didnt continue'), ('Was registered in CBECE program', 'Was registered in CBECE program'), ('Was registered in ALP program and didnt continue', 'Was registered in ALP program and didnt continue')], max_length=100, null=True, verbose_name='Education status'),
        ),
    ]
