# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-06 14:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0259_auto_20230529_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='have_labour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='have_labour_single_selection',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=100, null=True, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='have_labour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='have_labour_single_selection',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=100, null=True, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='have_labour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='have_labour_single_selection',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=100, null=True, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='have_labour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='have_labour_single_selection',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=100, null=True, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='have_labour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='have_labour_single_selection',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=100, null=True, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='have_labour',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=50, null=True), blank=True, null=True, size=None, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='have_labour_single_selection',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - All day', 'Yes - All day')], max_length=100, null=True, verbose_name='Does the child participate in work?'),
        ),
    ]
