# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-07-11 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0260_auto_20230606_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('5 USD or Less', '5 USD or Less'), ('5-20 USD', '5-20 USD'), ('20-50 USD', '20-50 USD'), ('50-100 USD', '50-100 USD'), ('More than 100 USD', 'More than 100 USD')], max_length=100, null=True, verbose_name='What is the income of the child per week?'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('5 USD or Less', '5 USD or Less'), ('5-20 USD', '5-20 USD'), ('20-50 USD', '20-50 USD'), ('50-100 USD', '50-100 USD'), ('More than 100 USD', 'More than 100 USD')], max_length=100, null=True, verbose_name='What is the income of the child per week?'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('5 USD or Less', '5 USD or Less'), ('5-20 USD', '5-20 USD'), ('20-50 USD', '20-50 USD'), ('50-100 USD', '50-100 USD'), ('More than 100 USD', 'More than 100 USD')], max_length=100, null=True, verbose_name='What is the income of the child per week?'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('5 USD or Less', '5 USD or Less'), ('5-20 USD', '5-20 USD'), ('20-50 USD', '20-50 USD'), ('50-100 USD', '50-100 USD'), ('More than 100 USD', 'More than 100 USD')], max_length=100, null=True, verbose_name='What is the income of the child per week?'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('5 USD or Less', '5 USD or Less'), ('5-20 USD', '5-20 USD'), ('20-50 USD', '20-50 USD'), ('50-100 USD', '50-100 USD'), ('More than 100 USD', 'More than 100 USD')], max_length=100, null=True, verbose_name='What is the income of the child per week?'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('5 USD or Less', '5 USD or Less'), ('5-20 USD', '5-20 USD'), ('20-50 USD', '20-50 USD'), ('50-100 USD', '50-100 USD'), ('More than 100 USD', 'More than 100 USD')], max_length=100, null=True, verbose_name='What is the income of the child per week?'),
        ),
    ]
