# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-07-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0261_auto_20230711_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='caretaker_birthday_day',
            field=models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30), (b'31', 31)], default=0, max_length=2, null=True, verbose_name='Caregiver birthday day'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='caretaker_birthday_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=0, max_length=2, null=True, verbose_name='Caregiver birthday month'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='caretaker_birthday_year',
            field=models.CharField(blank=True, choices=[(b'1940', 1940), (b'1941', 1941), (b'1942', 1942), (b'1943', 1943), (b'1944', 1944), (b'1945', 1945), (b'1946', 1946), (b'1947', 1947), (b'1948', 1948), (b'1949', 1949), (b'1950', 1950), (b'1951', 1951), (b'1952', 1952), (b'1953', 1953), (b'1954', 1954), (b'1955', 1955), (b'1956', 1956), (b'1957', 1957), (b'1958', 1958), (b'1959', 1959), (b'1960', 1960), (b'1961', 1961), (b'1962', 1962), (b'1963', 1963), (b'1964', 1964), (b'1965', 1965), (b'1966', 1966), (b'1967', 1967), (b'1968', 1968), (b'1969', 1969), (b'1970', 1970), (b'1971', 1971), (b'1972', 1972), (b'1973', 1973), (b'1974', 1974), (b'1975', 1975), (b'1976', 1976), (b'1977', 1977), (b'1978', 1978), (b'1979', 1979), (b'1980', 1980), (b'1981', 1981), (b'1982', 1982), (b'1983', 1983), (b'1984', 1984), (b'1985', 1985), (b'1986', 1986), (b'1987', 1987), (b'1988', 1988), (b'1989', 1989), (b'1990', 1990), (b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004)], default=0, max_length=4, null=True, verbose_name='Caregiver birthday year'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='caretaker_first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver First Name'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='caretaker_last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Last Name'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Middle Name'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Mother Name'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='caretaker_birthday_day',
            field=models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30), (b'31', 31)], default=0, max_length=2, null=True, verbose_name='Caregiver birthday day'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='caretaker_birthday_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=0, max_length=2, null=True, verbose_name='Caregiver birthday month'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='caretaker_birthday_year',
            field=models.CharField(blank=True, choices=[(b'1940', 1940), (b'1941', 1941), (b'1942', 1942), (b'1943', 1943), (b'1944', 1944), (b'1945', 1945), (b'1946', 1946), (b'1947', 1947), (b'1948', 1948), (b'1949', 1949), (b'1950', 1950), (b'1951', 1951), (b'1952', 1952), (b'1953', 1953), (b'1954', 1954), (b'1955', 1955), (b'1956', 1956), (b'1957', 1957), (b'1958', 1958), (b'1959', 1959), (b'1960', 1960), (b'1961', 1961), (b'1962', 1962), (b'1963', 1963), (b'1964', 1964), (b'1965', 1965), (b'1966', 1966), (b'1967', 1967), (b'1968', 1968), (b'1969', 1969), (b'1970', 1970), (b'1971', 1971), (b'1972', 1972), (b'1973', 1973), (b'1974', 1974), (b'1975', 1975), (b'1976', 1976), (b'1977', 1977), (b'1978', 1978), (b'1979', 1979), (b'1980', 1980), (b'1981', 1981), (b'1982', 1982), (b'1983', 1983), (b'1984', 1984), (b'1985', 1985), (b'1986', 1986), (b'1987', 1987), (b'1988', 1988), (b'1989', 1989), (b'1990', 1990), (b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004)], default=0, max_length=4, null=True, verbose_name='Caregiver birthday year'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='caretaker_first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver First Name'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='caretaker_last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Last Name'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Middle Name'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Mother Name'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='caretaker_birthday_day',
            field=models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30), (b'31', 31)], default=0, max_length=2, null=True, verbose_name='Caregiver birthday day'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='caretaker_birthday_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=0, max_length=2, null=True, verbose_name='Caregiver birthday month'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='caretaker_birthday_year',
            field=models.CharField(blank=True, choices=[(b'1940', 1940), (b'1941', 1941), (b'1942', 1942), (b'1943', 1943), (b'1944', 1944), (b'1945', 1945), (b'1946', 1946), (b'1947', 1947), (b'1948', 1948), (b'1949', 1949), (b'1950', 1950), (b'1951', 1951), (b'1952', 1952), (b'1953', 1953), (b'1954', 1954), (b'1955', 1955), (b'1956', 1956), (b'1957', 1957), (b'1958', 1958), (b'1959', 1959), (b'1960', 1960), (b'1961', 1961), (b'1962', 1962), (b'1963', 1963), (b'1964', 1964), (b'1965', 1965), (b'1966', 1966), (b'1967', 1967), (b'1968', 1968), (b'1969', 1969), (b'1970', 1970), (b'1971', 1971), (b'1972', 1972), (b'1973', 1973), (b'1974', 1974), (b'1975', 1975), (b'1976', 1976), (b'1977', 1977), (b'1978', 1978), (b'1979', 1979), (b'1980', 1980), (b'1981', 1981), (b'1982', 1982), (b'1983', 1983), (b'1984', 1984), (b'1985', 1985), (b'1986', 1986), (b'1987', 1987), (b'1988', 1988), (b'1989', 1989), (b'1990', 1990), (b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004)], default=0, max_length=4, null=True, verbose_name='Caregiver birthday year'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='caretaker_first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver First Name'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='caretaker_last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Last Name'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Middle Name'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Mother Name'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='school_contacted_caretaker',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Have the child caregivers been contacted by the School Community Laison'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='caretaker_birthday_day',
            field=models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30), (b'31', 31)], default=0, max_length=2, null=True, verbose_name='Caregiver birthday day'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='caretaker_birthday_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=0, max_length=2, null=True, verbose_name='Caregiver birthday month'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='caretaker_birthday_year',
            field=models.CharField(blank=True, choices=[(b'1940', 1940), (b'1941', 1941), (b'1942', 1942), (b'1943', 1943), (b'1944', 1944), (b'1945', 1945), (b'1946', 1946), (b'1947', 1947), (b'1948', 1948), (b'1949', 1949), (b'1950', 1950), (b'1951', 1951), (b'1952', 1952), (b'1953', 1953), (b'1954', 1954), (b'1955', 1955), (b'1956', 1956), (b'1957', 1957), (b'1958', 1958), (b'1959', 1959), (b'1960', 1960), (b'1961', 1961), (b'1962', 1962), (b'1963', 1963), (b'1964', 1964), (b'1965', 1965), (b'1966', 1966), (b'1967', 1967), (b'1968', 1968), (b'1969', 1969), (b'1970', 1970), (b'1971', 1971), (b'1972', 1972), (b'1973', 1973), (b'1974', 1974), (b'1975', 1975), (b'1976', 1976), (b'1977', 1977), (b'1978', 1978), (b'1979', 1979), (b'1980', 1980), (b'1981', 1981), (b'1982', 1982), (b'1983', 1983), (b'1984', 1984), (b'1985', 1985), (b'1986', 1986), (b'1987', 1987), (b'1988', 1988), (b'1989', 1989), (b'1990', 1990), (b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004)], default=0, max_length=4, null=True, verbose_name='Caregiver birthday year'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='caretaker_first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver First Name'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='caretaker_last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Last Name'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Middle Name'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Mother Name'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='caretaker_birthday_day',
            field=models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30), (b'31', 31)], default=0, max_length=2, null=True, verbose_name='Caregiver birthday day'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='caretaker_birthday_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=0, max_length=2, null=True, verbose_name='Caregiver birthday month'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='caretaker_birthday_year',
            field=models.CharField(blank=True, choices=[(b'1940', 1940), (b'1941', 1941), (b'1942', 1942), (b'1943', 1943), (b'1944', 1944), (b'1945', 1945), (b'1946', 1946), (b'1947', 1947), (b'1948', 1948), (b'1949', 1949), (b'1950', 1950), (b'1951', 1951), (b'1952', 1952), (b'1953', 1953), (b'1954', 1954), (b'1955', 1955), (b'1956', 1956), (b'1957', 1957), (b'1958', 1958), (b'1959', 1959), (b'1960', 1960), (b'1961', 1961), (b'1962', 1962), (b'1963', 1963), (b'1964', 1964), (b'1965', 1965), (b'1966', 1966), (b'1967', 1967), (b'1968', 1968), (b'1969', 1969), (b'1970', 1970), (b'1971', 1971), (b'1972', 1972), (b'1973', 1973), (b'1974', 1974), (b'1975', 1975), (b'1976', 1976), (b'1977', 1977), (b'1978', 1978), (b'1979', 1979), (b'1980', 1980), (b'1981', 1981), (b'1982', 1982), (b'1983', 1983), (b'1984', 1984), (b'1985', 1985), (b'1986', 1986), (b'1987', 1987), (b'1988', 1988), (b'1989', 1989), (b'1990', 1990), (b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004)], default=0, max_length=4, null=True, verbose_name='Caregiver birthday year'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='caretaker_first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver First Name'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='caretaker_last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Last Name'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Middle Name'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Mother Name'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='caretaker_birthday_day',
            field=models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30), (b'31', 31)], default=0, max_length=2, null=True, verbose_name='Caregiver birthday day'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='caretaker_birthday_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=0, max_length=2, null=True, verbose_name='Caregiver birthday month'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='caretaker_birthday_year',
            field=models.CharField(blank=True, choices=[(b'1940', 1940), (b'1941', 1941), (b'1942', 1942), (b'1943', 1943), (b'1944', 1944), (b'1945', 1945), (b'1946', 1946), (b'1947', 1947), (b'1948', 1948), (b'1949', 1949), (b'1950', 1950), (b'1951', 1951), (b'1952', 1952), (b'1953', 1953), (b'1954', 1954), (b'1955', 1955), (b'1956', 1956), (b'1957', 1957), (b'1958', 1958), (b'1959', 1959), (b'1960', 1960), (b'1961', 1961), (b'1962', 1962), (b'1963', 1963), (b'1964', 1964), (b'1965', 1965), (b'1966', 1966), (b'1967', 1967), (b'1968', 1968), (b'1969', 1969), (b'1970', 1970), (b'1971', 1971), (b'1972', 1972), (b'1973', 1973), (b'1974', 1974), (b'1975', 1975), (b'1976', 1976), (b'1977', 1977), (b'1978', 1978), (b'1979', 1979), (b'1980', 1980), (b'1981', 1981), (b'1982', 1982), (b'1983', 1983), (b'1984', 1984), (b'1985', 1985), (b'1986', 1986), (b'1987', 1987), (b'1988', 1988), (b'1989', 1989), (b'1990', 1990), (b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004)], default=0, max_length=4, null=True, verbose_name='Caregiver birthday year'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='caretaker_first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver First Name'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='caretaker_last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Last Name'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Middle Name'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Mother Name'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='caretaker_birthday_day',
            field=models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30), (b'31', 31)], default=0, max_length=2, null=True, verbose_name='Caregiver birthday day'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='caretaker_birthday_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=0, max_length=2, null=True, verbose_name='Caregiver birthday month'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='caretaker_birthday_year',
            field=models.CharField(blank=True, choices=[(b'1940', 1940), (b'1941', 1941), (b'1942', 1942), (b'1943', 1943), (b'1944', 1944), (b'1945', 1945), (b'1946', 1946), (b'1947', 1947), (b'1948', 1948), (b'1949', 1949), (b'1950', 1950), (b'1951', 1951), (b'1952', 1952), (b'1953', 1953), (b'1954', 1954), (b'1955', 1955), (b'1956', 1956), (b'1957', 1957), (b'1958', 1958), (b'1959', 1959), (b'1960', 1960), (b'1961', 1961), (b'1962', 1962), (b'1963', 1963), (b'1964', 1964), (b'1965', 1965), (b'1966', 1966), (b'1967', 1967), (b'1968', 1968), (b'1969', 1969), (b'1970', 1970), (b'1971', 1971), (b'1972', 1972), (b'1973', 1973), (b'1974', 1974), (b'1975', 1975), (b'1976', 1976), (b'1977', 1977), (b'1978', 1978), (b'1979', 1979), (b'1980', 1980), (b'1981', 1981), (b'1982', 1982), (b'1983', 1983), (b'1984', 1984), (b'1985', 1985), (b'1986', 1986), (b'1987', 1987), (b'1988', 1988), (b'1989', 1989), (b'1990', 1990), (b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004)], default=0, max_length=4, null=True, verbose_name='Caregiver birthday year'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='caretaker_first_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver First Name'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='caretaker_last_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Last Name'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='caretaker_middle_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Middle Name'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='caretaker_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver Mother Name'),
        ),
    ]
