# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-10-17 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0262_auto_20230712_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridging',
            options={'ordering': ['student__first_name', 'student__father_name', 'student__last_name'], 'verbose_name': 'Bridging', 'verbose_name_plural': 'Bridging'},
        ),
    ]
