# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-04-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0264_auto_20240118_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridging',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Date'),
        ),
    ]
