# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-06-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0267_bridging_mid_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='parent_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record'),
        ),
        migrations.AddField(
            model_name='abln',
            name='parent_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record confirm'),
        ),
        migrations.AddField(
            model_name='bln',
            name='parent_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record'),
        ),
        migrations.AddField(
            model_name='bln',
            name='parent_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record confirm'),
        ),
        migrations.AddField(
            model_name='bridging',
            name='parent_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record'),
        ),
        migrations.AddField(
            model_name='bridging',
            name='parent_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record confirm'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='parent_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='parent_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record confirm'),
        ),
        migrations.AddField(
            model_name='outreach',
            name='parent_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record'),
        ),
        migrations.AddField(
            model_name='outreach',
            name='parent_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record confirm'),
        ),
        migrations.AddField(
            model_name='rs',
            name='parent_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record'),
        ),
        migrations.AddField(
            model_name='rs',
            name='parent_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record confirm'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Lebanese Extract of Record', 'Lebanese Extract of Record'), ('Other nationality', 'Other nationality'), ('Child have no ID', 'Child have no ID')], max_length=100, null=True, verbose_name='Child ID type'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Lebanese Extract of Record', 'Lebanese Extract of Record'), ('Other nationality', 'Other nationality'), ('Child have no ID', 'Child have no ID')], max_length=100, null=True, verbose_name='Child ID type'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Lebanese Extract of Record', 'Lebanese Extract of Record'), ('Other nationality', 'Other nationality'), ('Child have no ID', 'Child have no ID')], max_length=100, null=True, verbose_name='Child ID type'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Lebanese Extract of Record', 'Lebanese Extract of Record'), ('Other nationality', 'Other nationality'), ('Child have no ID', 'Child have no ID')], max_length=100, null=True, verbose_name='Child ID type'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Lebanese Extract of Record', 'Lebanese Extract of Record'), ('Other nationality', 'Other nationality'), ('Child have no ID', 'Child have no ID')], max_length=100, null=True, verbose_name='Child ID type'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='id_type',
            field=models.CharField(blank=True, choices=[('UNHCR Registered', 'UNHCR Registered'), ('UNHCR Recorded', 'UNHCR Recorded'), ('Syrian national ID', 'Syrian national ID'), ('Palestinian national ID', 'Palestinian national ID'), ('Lebanese national ID', 'Lebanese national ID'), ('Lebanese Extract of Record', 'Lebanese Extract of Record'), ('Other nationality', 'Other nationality'), ('Child have no ID', 'Child have no ID')], max_length=100, null=True, verbose_name='Child ID type'),
        ),
    ]
