# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-29 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0268_auto_20240607_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridging',
            name='dropout_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dropout date'),
        ),
    ]
