# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-09-23 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0269_bridging_dropout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridging',
            name='using_digital_platform',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes_akelius)', 'Yes (Akelius)'), ('yes_learning_passport)', 'Yes (Learning Passport)'), ('no', 'No')], max_length=100, null=True, verbose_name='Is the Child Using a digital platform (Akelius or  Learning Passport)'),
        ),
    ]
