# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-10-24 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0271_auto_20241016_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridging',
            name='learning_result',
            field=models.CharField(blank=True, choices=[('', '----------'), ('graduated_to_Bridging_next_level', 'Progress to the next Dirasa level'), ('graduated_to_Bridging_next_round_same_level', 'Repeat the same Dirasa level'), ('dropout', 'Drop out'), ('referred_public_school', 'Referred to formal education'), ('other', 'Referred to another pathway')], max_length=100, null=True, verbose_name='Learning result'),
        ),
    ]
