# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-02-27 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0274_auto_20250210_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='abln',
            name='individual_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese Extract of Record of the child'),
        ),
        migrations.AddField(
            model_name='abln',
            name='individual_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confirm Lebanese Extract of Record of the child'),
        ),
        migrations.AddField(
            model_name='bln',
            name='individual_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese Extract of Record of the child'),
        ),
        migrations.AddField(
            model_name='bln',
            name='individual_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confirm Lebanese Extract of Record of the child'),
        ),
        migrations.AddField(
            model_name='bridging',
            name='enrolled_formal_education',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Was this child enrolled in Formal Education last year and dropped out due to lack of documentation?'),
        ),
        migrations.AddField(
            model_name='bridging',
            name='individual_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese Extract of Record of the child'),
        ),
        migrations.AddField(
            model_name='bridging',
            name='individual_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confirm Lebanese Extract of Record of the child'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='individual_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese Extract of Record of the child'),
        ),
        migrations.AddField(
            model_name='cbece',
            name='individual_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confirm Lebanese Extract of Record of the child'),
        ),
        migrations.AddField(
            model_name='outreach',
            name='individual_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese Extract of Record of the child'),
        ),
        migrations.AddField(
            model_name='outreach',
            name='individual_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confirm Lebanese Extract of Record of the child'),
        ),
        migrations.AddField(
            model_name='rs',
            name='individual_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lebanese Extract of Record of the child'),
        ),
        migrations.AddField(
            model_name='rs',
            name='individual_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confirm Lebanese Extract of Record of the child'),
        ),
    ]
