# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-05-20 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0276_auto_20250514_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridging',
            name='registration_level',
            field=models.CharField(blank=True, choices=[('', '----------'), ('level_one', 'Level one'), ('level_two', 'Level two'), ('level_three', 'Level three'), ('level_four', 'Level four'), ('level_five', 'Level five'), ('level_six', 'Level six'), ('grade_one', 'Grade one'), ('grade_two', 'Grade two'), ('grade_three', 'Grade three'), ('grade_four', 'Grade four'), ('grade_five', 'Grade five'), ('grade_six', 'Grade six'), ('grade_seven', 'Grade seven'), ('grade_eight', 'Grade eight'), ('grade_nine', 'Grade nine')], max_length=100, null=True, verbose_name='Registration level'),
        ),
    ]
