# Generated by Django 5.2.3 on 2025-09-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0278_auto_20250626_1644'),
        ('locations', '0026_auto_20250701_1656'),
        ('schools', '0158_auto_20250820_1259'),
        ('students', '0087_auto_20250626_1644'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='abln',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Cadaster'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.center', verbose_name='Site / Center'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.cycle', verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='cycle_completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Course completed successfully'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='abln',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.disability', verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='dropout_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='abln',
            name='enrolled_at_school',
            field=models.BooleanField(blank=True, default=False, verbose_name='Enrolled at School'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the father?'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='hh_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the mother?'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='main_caregiver_nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Main Caregiver Nationality'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='moved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='abln',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abln',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='post_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='abln',
            name='pre_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='abln',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clmround', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='abln',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='abln',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.abln', verbose_name='Enrollment'),
        ),
        migrations.AlterField(
            model_name='abln_fc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Cadaster'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.center', verbose_name='Site / Center'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.cycle', verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='cycle_completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Course completed successfully'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bln',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.disability', verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='dropout_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bln',
            name='enrolled_at_school',
            field=models.BooleanField(blank=True, default=False, verbose_name='Enrolled at School'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the father?'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='hh_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the mother?'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='main_caregiver_nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Main Caregiver Nationality'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='moved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bln',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bln',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='post_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bln',
            name='pre_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bln',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clmround', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='bln',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bln',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='bln_fc',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.bln', verbose_name='Enrollment'),
        ),
        migrations.AlterField(
            model_name='bln_fc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Cadaster'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.center', verbose_name='Site / Center'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.cycle', verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='cycle_completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Course completed successfully'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.disability', verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='dropout_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='enrolled_at_school',
            field=models.BooleanField(blank=True, default=False, verbose_name='Enrolled at School'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the father?'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='hh_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the mother?'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='main_caregiver_nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Main Caregiver Nationality'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='mid_test1',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='mid_test2',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='moved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='post_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='pre_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clmround', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school', verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bridging',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Cadaster'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.center', verbose_name='Site / Center'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.cycle', verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='cycle_completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Course completed successfully'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.disability', verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='dropout_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='enrolled_at_school',
            field=models.BooleanField(blank=True, default=False, verbose_name='Enrolled at School'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the father?'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='hh_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the mother?'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='main_caregiver_nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Main Caregiver Nationality'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='mid_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='moved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='post_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='pre_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clmround', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school', verbose_name='Attending in school'),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cbece',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='cbece_fc',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.cbece', verbose_name='Enrollment'),
        ),
        migrations.AlterField(
            model_name='cbece_fc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='center',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='center',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='current_cycle',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalquestionnaire',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Cadaster'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.disability', verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='main_caregiver_nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Main Caregiver Nationality'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clmround', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Cadaster'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.center', verbose_name='Site / Center'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.cycle', verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='cycle_completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Course completed successfully'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.disability', verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='dropout_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='enrolled_at_school',
            field=models.BooleanField(blank=True, default=False, verbose_name='Enrolled at School'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the father?'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='hh_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the mother?'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='main_caregiver_nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Main Caregiver Nationality'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='moved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='post_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='pre_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clmround', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Cadaster'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.center', verbose_name='Site / Center'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.cycle', verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='cycle_completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Course completed successfully'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rs',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.disability', verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='dropout_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rs',
            name='enrolled_at_school',
            field=models.BooleanField(blank=True, default=False, verbose_name='Enrolled at School'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the father?'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classroom', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='hh_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name='What is the educational level of the mother?'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='main_caregiver_nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Main Caregiver Nationality'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='moved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rs',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rs',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_motivation',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_reading',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_self_assessment',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rs',
            name='post_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_motivation',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_reading',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_self_assessment',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rs',
            name='pre_test',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rs',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clmround', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school', verbose_name='Attending in school'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='rs',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='rs',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='rs_fc',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.rs', verbose_name='Enrollment'),
        ),
        migrations.AlterField(
            model_name='rs_fc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rscycle',
            name='current_cycle',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rscycle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='selfperceptiongrades',
            name='answers',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Assessment answers'),
        ),
        migrations.AlterField(
            model_name='selfperceptiongrades',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.rs', verbose_name='Enrollment'),
        ),
        migrations.AlterField(
            model_name='selfperceptiongrades',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='site',
            name='current_cycle',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
