# Generated by Django 5.2.3 on 2026-03-13 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0280_alter_bridging_registration_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridging',
            name='education_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', '----------'),
                    ('No Registered in any school before', 'Not Registered in any school before'),
                    ('Was registered in BLN program', 'Was registered in BLN program'),
                    ('Internally Displaced, was enrolled in FE before the conflict',
                     'Internally Displaced, was enrolled in FE before the conflict'),
                    ('Internally Displaced, was enrolled in NFE before the conflict',
                     'Internally Displaced, was enrolled in NFE before the conflict'),
                    ('Internally Displaced, out of school (never been engaged in any type of learning)',
                     'Internally Displaced, out of school (never been engaged in any type of learning)'),
                    ('Was registered in formal school and didnt continue',
                     'Was registered in formal school and didnt continue'),
                    ('Was registered in CBECE program', 'Was registered in CBECE program'),
                    ('Was registered in ALP program and didnt continue',
                     'Was registered in ALP program and didnt continue'),
                ],
                max_length=100,
                null=True,
                verbose_name='Education status',
            ),
        ),
    ]
