# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0041_auto_20161101_1747'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0015_auto_20161101_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChildVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('service_provider', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registering_adult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='registrations.RegisteringAdult')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdVisitStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_found', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('household_visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.HouseholdVisit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MainReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64L, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Main Reason',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Service Type',
            },
        ),
        migrations.CreateModel(
            name='SpecificReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254L)),
                ('main_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhvisit.MainReason', verbose_name='Main Reason')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Specific Reason',
            },
        ),
        migrations.AddField(
            model_name='childvisit',
            name='household_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.HouseholdVisit'),
        ),
        migrations.AddField(
            model_name='childvisit',
            name='main_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.MainReason'),
        ),
        migrations.AddField(
            model_name='childvisit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childvisit',
            name='specific_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.SpecificReason'),
        ),
        migrations.AddField(
            model_name='childvisit',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student'),
        ),
        migrations.AddField(
            model_name='childservice',
            name='child_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.ChildVisit'),
        ),
        migrations.AddField(
            model_name='childservice',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.ServiceType'),
        ),
    ]
