# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0002_auto_20161104_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdVisitComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('household_visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_comment', to='hhvisit.HouseholdVisit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='childvisit',
            name='child_enrolled_in_another_school',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='childservice',
            name='child_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_visit_service', to='hhvisit.ChildVisit'),
        ),
    ]
