# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0004_auto_20161109_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='householdvisitteam',
            options={'ordering': ['name']},
        ),
    ]
