# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-13 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0005_auto_20161109_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childvisit',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='householdvisit',
            name='household_visit_team',
        ),
        migrations.AddField(
            model_name='childservice',
            name='service_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
