# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0006_auto_20161113_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdvisit',
            name='household_visit_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.HouseholdVisitTeam'),
        ),
    ]
