# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-08 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_merge'),
        ('hhvisit', '0008_auto_20161205_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMonitoringDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_monitoring', models.DateField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='studentAbsence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateTimeField()),
                ('dateTo', models.DateTimeField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='childattendancemonitoring',
            name='date',
        ),
        migrations.AddField(
            model_name='childattendancemonitoring',
            name='child_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.ChildVisit'),
        ),
        migrations.AddField(
            model_name='childattendancemonitoring',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='childattendancemonitoring',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='childattendancemonitoring',
            name='is_first_visit',
            field=models.BooleanField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childattendancemonitoring',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student'),
        ),
    ]
