# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-13 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0010_auto_20161215_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentAbsence',
        ),
    ]
