# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-27 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0011_delete_studentabsence'),
    ]

    operations = [
        migrations.AddField(
            model_name='childservice',
            name='service_provider_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='main_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.MainReason'),
        ),
        migrations.AlterField(
            model_name='childvisit',
            name='specific_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.SpecificReason'),
        ),
    ]
