# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0013_childvisit_child_absence_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_reason_other_specify', models.CharField(blank=True, max_length=255, null=True)),
                ('child_visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_visit_reason', to='hhvisit.ChildVisit')),
                ('main_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.MainReason')),
                ('specific_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hhvisit.SpecificReason')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
