# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-24 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0014_childreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdvisitattempt',
            name='household_not_found',
            field=models.BooleanField(default=False),
        ),
    ]
