# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-02 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0015_auto_20170224_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='childvisit',
            name='child_no_longer_living_in_the_pilot_area',
            field=models.BooleanField(default=False),
        ),
    ]
