# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-13 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0016_childvisit_child_no_longer_living_in_the_pilot_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='childreason',
            name='reason_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='childservice',
            name='service_date',
            field=models.DateField(null=True),
        ),
    ]
