# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-13 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0017_auto_20170413_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childreason',
            name='reason_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='childservice',
            name='service_date',
            field=models.DateTimeField(null=True),
        ),
    ]
