# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-13 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhvisit', '0018_auto_20170413_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainreason',
            name='name_arabic',
            field=models.CharField(max_length=64L, null=True),
        ),
        migrations.AddField(
            model_name='specificreason',
            name='name_arabic',
            field=models.CharField(max_length=64L, null=True),
        ),
    ]
