# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-10 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_auto_20190910_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='Automated_Nb',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Automated Nb'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='Financial_Nb',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Financial Nb'),
        ),
    ]
