# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-10 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20170731_2134'),
        ('staffs', '0005_auto_20190910_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='caza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_caza', to='locations.Location', verbose_name='Caza'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_district', to='locations.Location', verbose_name='\u0627\u0644\u0642\u0636\u0627\u0621'),
        ),
    ]
