# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-22 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student_registration.staffs.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20170731_2134'),
        ('staffs', '0006_auto_20190911_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='district',
        ),
        migrations.AddField(
            model_name='staffs',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_governorate', to='locations.Location', verbose_name='\u0627\u0644\u0645\u062d\u0627\u0641\u0638\u0629'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='profiles', validators=[student_registration.staffs.models.validate_file_size], verbose_name='Profile Picture'),
        ),
    ]
