# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-28 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student_registration.staffs.models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_auto_20190922_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['code'], 'verbose_name_plural': 'Bank'},
        ),
        migrations.AlterModelOptions(
            name='staffs',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name'], 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='staffs',
            name='Automated_Nb',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0627\u0644\u0631\u0642\u0645 \u0627\u0644\u0627\u0644\u064a'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='Financial_Nb',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0627\u0644\u0631\u0642\u0645 \u0627\u0644\u0645\u0627\u0644\u064a'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='MinisterApproval',
            field=models.CharField(blank=True, choices=[('Exceptional', '\u0645\u0648\u0627\u0641\u0642\u0629 \u0627\u0633\u062a\u062b\u0646\u0627\u0626\u064a\u0629'), ('AccordingToCond', '\u0645\u0648\u0627\u0641\u0642\u0629 \u0628\u062d\u0633\u0628 \u0627\u0644\u0634\u0631\u0648\u0637 \u0641\u064a \u0627\u0644\u0645\u0630\u0643\u0631\u0629'), ('CadreOrCont', '\u0645\u0644\u0627\u0643 \u0627\u0648 \u0645\u062a\u0639\u0627\u0642\u062f \u0648\u0641\u0642 \u0627\u0644\u0627\u0635\u0648\u0644')], max_length=150, null=True, verbose_name='\u0645\u0648\u0627\u0641\u0642\u0629 \u0627\u0644\u0648\u0632\u064a\u0631'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.Bank', verbose_name='\u0627\u0644\u0628\u0646\u0643'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='branch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0627\u0644\u0641\u0631\u0639'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='caza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_caza', to='locations.Location', verbose_name='\u0627\u0644\u0642\u0636\u0627\u0621'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.Certificate', verbose_name='\u0627\u0644\u0634\u0647\u0627\u062f\u0629'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='image',
            field=models.ImageField(blank=True, help_text='\u0627\u0644\u0635\u0648\u0631\u0629 \u0627\u0644\u0634\u062e\u0635\u064a\u0629', null=True, upload_to='profiles', validators=[student_registration.staffs.models.validate_file_size], verbose_name='\u0627\u0644\u0635\u0648\u0631\u0629 \u0627\u0644\u0634\u062e\u0635\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='type_of_employment',
            field=models.CharField(blank=True, choices=[('Cadre', '\u0645\u0644\u0627\u0643'), ('Contractual', 'Contractual'), ('Supporter', '\u0645\u0633\u062a\u0639\u0627\u0646 \u0628\u0647')], max_length=80, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0648\u0638\u064a\u0641\u0629'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.University', verbose_name='\u0625\u0633\u0645 \u0627\u0644\u062c\u0627\u0645\u0639\u0629'),
        ),
    ]
