# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-08 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import student_registration.staffs.models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_auto_20190928_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0631\u0642\u0645 \u0627\u0644\u062d\u0633\u0627\u0628 \u0627\u0644\u0628\u0646\u0643\u064a IBAN'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='image',
            field=models.ImageField(blank=True, help_text='\u0627\u0644\u0635\u0648\u0631\u0629 \u0627\u0644\u0634\u0645\u0633\u064a\u0629', null=True, upload_to='profiles', validators=[student_registration.staffs.models.validate_file_size], verbose_name='\u0627\u0644\u0635\u0648\u0631\u0629 \u0627\u0644\u0634\u0645\u0633\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='type_of_employment',
            field=models.CharField(blank=True, choices=[('Cadre', '\u0645\u0644\u0627\u0643'), ('Contractual', '\u0645\u062a\u0639\u0627\u0642\u062f'), ('Supporter', '\u0645\u0633\u062a\u0639\u0627\u0646 \u0628\u0647')], max_length=80, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0648\u0638\u064a\u0641\u0629'),
        ),
    ]
