# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-11-20 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0009_auto_20191008_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='Automated_Nb',
            new_name='automated_nb',
        ),
        migrations.RenameField(
            model_name='staffs',
            old_name='Financial_Nb',
            new_name='financial_nb',
        ),
    ]
