# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-11-22 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0011_auto_20191121_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='staff_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
