# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-21 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0012_staffs_staff_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='staff_seq',
        ),
    ]
