# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-17 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0017_auto_20200114_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='cert_origin',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name=' \u0627\u0644\u062c\u0646\u0633\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='speciality',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name=' \u0627\u0644\u062c\u0646\u0633\u064a\u0629'),
        ),
    ]
