# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-17 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0018_auto_20200117_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='bank_Base1',
            new_name='bank_base1',
        ),
        migrations.RenameField(
            model_name='staffs',
            old_name='bank_Base2',
            new_name='bank_base2',
        ),
    ]
