# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-27 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0019_auto_20200309_1204'),
        ('staffs', '0019_auto_20200317_1935'),
    ]

    operations = [
    ]
