# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0020_merge_20200327_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='caza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_caza', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0642\u0636\u0627\u0621'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_governorate', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0645\u062d\u0627\u0641\u0638\u0629'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='mother_fullname',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='\u0625\u0633\u0645 \u0627\u0644\u0623\u0645 \u0648 \u0634\u0647\u0631\u062a\u0647\u0627'),
        ),
    ]
