# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-29 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0021_staffs_pic_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled?'),
        ),
    ]
