# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-01 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0023_merge_20200414_1606'),
        ('staffs', '0023_auto_20200412_1029'),
    ]

    operations = [
    ]
