# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-06 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student_registration.staffs.models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0024_merge_20200501_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantyear',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staffs.Staffs', verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='automated_nb',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Automated Nb'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='bank_base1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staffs.Bank', verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='bank_base2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staffs.Bank', verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='birthday_day',
            field=models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30), (b'31', 31)], default=0, max_length=2, null=True, verbose_name='Birthday day'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='birthday_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=0, max_length=2, null=True, verbose_name='Birthday month'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='birthday_year',
            field=models.CharField(blank=True, choices=[(b'1990', 1990), (b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004), (b'2005', 2005), (b'2006', 2006), (b'2007', 2007), (b'2008', 2008), (b'2009', 2009), (b'2010', 2010), (b'2011', 2011), (b'2012', 2012), (b'2013', 2013), (b'2014', 2014), (b'2015', 2015), (b'2016', 2016), (b'2017', 2017), (b'2018', 2018), (b'2019', 2019), (b'2020', 2020), (b'2021', 2021), (b'2022', 2022), (b'2023', 2023), (b'2024', 2024), (b'2025', 2025), (b'2026', 2026), (b'2027', 2027), (b'2028', 2028), (b'2029', 2029), (b'2030', 2030), (b'2031', 2031), (b'2032', 2032), (b'2033', 2033), (b'2034', 2034), (b'2035', 2035), (b'2036', 2036), (b'2037', 2037), (b'2038', 2038), (b'2039', 2039), (b'2040', 2040), (b'2041', 2041), (b'2042', 2042), (b'2043', 2043), (b'2044', 2044), (b'2045', 2045), (b'2046', 2046), (b'2047', 2047), (b'2048', 2048), (b'2049', 2049)], default=0, max_length=4, null=True, verbose_name='Birthday year'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='branch_base1',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='branch_base2',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='caza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_caza', to='locations.Location', verbose_name='Caza'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='cert_origin',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.Certificate', verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='family_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('engaged', 'Engaged'), ('divorced', 'Divorced'), ('widower', 'Widower'), ('single', 'Single')], max_length=50, null=True, verbose_name='Family status'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='father_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Father name'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='financial_nb',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Financial Nb'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='first_education_year',
            field=models.CharField(blank=True, choices=[('2000/2001', '2000/2001'), ('2001/2002', '2001/2002'), ('2002/2003', '2002/2003'), ('2003/2004', '2003/2004'), ('2004/2005', '2004/2005'), ('2005/2006', '2005/2006'), ('2006/2007', '2006/2007'), ('2007/2008', '2007/2008'), ('2008/2009', '2008/2009'), ('2009/2010', '2009/2010'), ('2010/2011', '2010/2011'), ('2011/2012', '2011/2012'), ('2012/2013', '2012/2013'), ('2013/2014', '2013/2014'), ('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030'), ('2030/2031', '2030/2031'), ('2031/2032', '2031/2032'), ('2032/2033', '2032/2033'), ('2033/2034', '2033/2034'), ('2034/2035', '2034/2035'), ('2035/2036', '2035/2036'), ('2036/2037', '2036/2037'), ('2037/2038', '2037/2038'), ('2038/2039', '2038/2039'), ('2039/2040', '2039/2040'), ('2040/2041', '2040/2041'), ('2041/2042', '2041/2042'), ('2042/2043', '2042/2043'), ('2043/2044', '2043/2044'), ('2044/2045', '2044/2045'), ('2045/2046', '2045/2046'), ('2046/2047', '2046/2047'), ('2047/2048', '2047/2048'), ('2048/2049', '2048/2049'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Last Education year'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_governorate', to='locations.Location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='profiles', validators=[student_registration.staffs.models.validate_file_size], verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='ministerapproval',
            field=models.CharField(blank=True, choices=[('Exceptional', 'Exceptional Approved'), ('AccordingToCond', 'Consent According to Conditions'), ('CadreOrCont', 'Cadre / Contractual')], max_length=150, null=True, verbose_name='Minister Approved'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='mother_fullname',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Mother fullname'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='phone',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Place of birth'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='speciality',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='type_of_employment',
            field=models.CharField(blank=True, choices=[('Cadre', 'Cadre'), ('Contractual', 'Contractual'), ('Supporter', 'Supporter')], max_length=80, null=True, verbose_name='Type on Employment'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.University', verbose_name='University Name'),
        ),
    ]
