# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-04-03 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0024_auto_20200403_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='worklist',
        ),
        migrations.DeleteModel(
            name='Worklist',
        ),
    ]
