# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-04-09 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0027_auto_20200408_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='pic_iban2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Picture of the iban'),
        ),
    ]
