# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-04 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20161021_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='note',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
