# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-21 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20161207_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALPReferMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_grade', models.IntegerField(blank=True, null=True)),
                ('fail_refer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fail_refer_to', to='schools.ClassLevel')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel')),
                ('success_refer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='success_refer_to', to='schools.ClassLevel')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'ALP Refer Matrix',
            },
        ),
    ]
