# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-21 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_alprefermatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='alprefermatrix',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
