# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_alprefermatrix_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
