# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_educationyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationyear',
            options={'ordering': ['name'], 'verbose_name': 'Education Year'},
        ),
        migrations.AddField(
            model_name='educationyear',
            name='current_year',
            field=models.BooleanField(default=False),
        ),
    ]
