# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20170419_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_2nd_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='is_alp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='number_students_2nd_shift',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='number_students_alp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
