# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_school_in_use'),
        ('schools', '0013_auto_20170511_0928'),
    ]

    operations = [
    ]
