# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-08 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20170621_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='school',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='section',
        ),
        migrations.RemoveField(
            model_name='school',
            name='in_use',
        ),
    ]
