# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_educationallevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='educationallevel',
            name='note',
        ),
        migrations.AlterField(
            model_name='educationallevel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
