# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_auto_20170906_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='attendance_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
