# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0029_auto_20171111_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='academic_year_end',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0646\u062a\u0647\u0627\u0621 \u0627\u0639\u0645\u0627\u0644 \u0627\u0644\u062a\u062f\u0631\u064a\u0633 '),
        ),
        migrations.AlterField(
            model_name='school',
            name='academic_year_exam_end',
            field=models.DateField(blank=True, null=True, verbose_name='  \u062a\u0627\u0631\u064a\u062e \u0627\u0646\u062a\u0647\u0627\u0621 \u0627\u0644\u0639\u0627\u0645 \u0627\u0644\u062f\u0631\u0627\u0633\u064a - \u0636\u0645\u0646\u0627 \u0627\u0644\u0627\u0645\u062a\u062d\u0627\u0646\u0627\u062a '),
        ),
        migrations.AlterField(
            model_name='school',
            name='academic_year_start',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0628\u062f\u0621 \u0627\u0639\u0645\u0627\u0644 \u0627\u0644\u062a\u062f\u0631\u064a\u0633'),
        ),
        migrations.AlterField(
            model_name='school',
            name='certified_foreign_language',
            field=models.CharField(blank=True, choices=[('French', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629'), ('English', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629'), ('French & English', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629 + \u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629')], max_length=100, null=True, verbose_name=' \u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0627\u062c\u0646\u0628\u064a\u0629 \u0627\u0644\u0645\u0639\u062a\u0645\u062f\u0629 \u0644\u062f\u0648\u0627\u0645 \u0628\u0639\u062f \u0627\u0644\u0638\u0647\u0631'),
        ),
        migrations.AlterField(
            model_name='school',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0645\u0644\u0627\u062d\u0627\u0638\u0627\u062a'),
        ),
        migrations.AlterField(
            model_name='school',
            name='director_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0631\u0642\u0645 \u0627\u0644\u0647\u0627\u062a\u0641 \u0627\u0644\u062e\u0644\u064a\u0648\u064a \u0627\u0644\u062e\u0627\u0635 \u0628\u0627\u0644\u0645\u062f\u064a\u0631/\u0629'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' \u0627\u0644\u0628\u062f\u064a\u062f \u0627\u0644\u0627\u0644\u0643\u062a\u0631\u0648\u0646\u064a \u0627\u0644\u062e\u0627\u0635 \u0628\u0627\u0644\u0645\u062f\u0631\u0633\u0629 '),
        ),
        migrations.AlterField(
            model_name='school',
            name='field_coordinator_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0645\u0646\u0633\u0642 \u0627\u0644\u0645\u064a\u062f\u0627\u0646\u064a'),
        ),
        migrations.AlterField(
            model_name='school',
            name='weekend',
            field=models.CharField(blank=True, choices=[('Friday', '\u0627\u0644\u062c\u0645\u0639\u0629'), ('Saturday', '\u0627\u0644\u0633\u0628\u062a')], max_length=100, null=True, verbose_name=' \u0627\u0644\u0639\u0637\u0644\u0629 \u0627\u0644\u0627\u0633\u0628\u0648\u0639\u064a\u0629 \u0644\u062f\u0648\u0627\u0645 \u0628\u0639\u062f \u0627\u0644\u0636\u0647\u0631 '),
        ),
    ]
