# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-18 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_auto_20171114_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='attendance_from_beginning',
            field=models.BooleanField(default=False, verbose_name='Start attendance from the beginning'),
        ),
    ]
