# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0032_auto_20171123_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='academic_year_exam_end',
            field=models.DateField(blank=True, null=True, verbose_name='  \u062a\u0627\u0631\u064a\u062e \u0627\u0646\u062a\u0647\u0627\u0621 \u0627\u0644\u0639\u0627\u0645 \u0627\u0644\u062f\u0631\u0627\u0633\u064a - \u0636\u0645\u0646\u0627\u064b \u0627\u0644\u0627\u0645\u062a\u062d\u0627\u0646\u0627\u062a '),
        ),
    ]
