# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-14 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0035_auto_20180215_1432'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Coordinator',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=200, unique=True)),
        #     ],
        #     options={
        #         'ordering': ['name'],
        #         'verbose_name': 'Coordinator',
        #     },
        # ),
        # migrations.RemoveField(
        #     model_name='school',
        #     name='field_coordinator_name',
        # ),
        # migrations.AddField(
        #     model_name='school',
        #     name='coordinator',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Coordinator', verbose_name='coordinator'),
        # ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
    ]
