# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-20 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0035_auto_20180215_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.RemoveField(
            model_name='school',
            name='coordinator',
        ),
    ]
