# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-06-18 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0037_auto_20190328_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmround',
            name='current_round_abln',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clmround',
            name='current_round_bln',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clmround',
            name='current_round_cbece',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clmround',
            name='end_date_abln',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='end_date_bln',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='end_date_cbece',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='start_date_abln',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='start_date_bln',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='start_date_cbece',
            field=models.DateField(blank=True, null=True),
        ),
    ]
