# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-28 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0039_auto_20190619_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is closed'),
        ),
    ]
