# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-29 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_school_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='\u0645\u063a\u0644\u0642\u0629'),
        ),
    ]
