# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-05 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0043_class_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpassignmentmatrix',
            name='matrix_type',
            field=models.CharField(blank=True, choices=[('O', 'Old'), ('N', 'New')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='coefficient_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='with_arabic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='with_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='with_math',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='with_science',
            field=models.BooleanField(default=False),
        ),
    ]
