# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-05 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0044_auto_20200105_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='new_calculation',
            field=models.BooleanField(default=True),
        ),
    ]
