# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-17 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0047_auto_20200114_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpassignmentmatrix',
            name='matrix_type',
            field=models.CharField(blank=True, choices=[('O', 'Old'), ('N', '\u0623\u0636\u0641')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='\u0627\u0644\u0635\u0641'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='closed_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u0633\u0628\u0628 \u0627\u0644\u0627\u0642\u0641\u0627\u0644 '),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='\u0627\u0644\u0645\u062f\u0631\u0633\u0629'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='school_type',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0645\u062f\u0631\u0633\u0629'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section', verbose_name='\u0627\u0644\u0634\u0639\u0628\u0629'),
        ),
    ]
