# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-21 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0050_auto_20200321_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='c2_ar_remaining_de',
            new_name='c2_ara_remaining_de',
        ),
    ]
