# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-04-12 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0060_auto_20200325_0802'),
    ]

    operations = [



    ]
