# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-04-04 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0061_auto_20200325_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.DateField(blank=True, verbose_name='Public holidays')),
            ],
        ),
    ]
