# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-04-13 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0063_schl_subject_schl_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schl_Survey_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('de_implemented', models.BooleanField(default=False, verbose_name='Distance education implemented ?')),
                ('de_usedmethod_1', models.TextField(blank=True, null=True, verbose_name='The methods used during the distance education plan')),
                ('de_challenge_1', models.TextField(blank=True, null=True, verbose_name='The challenges during the distance education plan')),
                ('de_negativenotes_1', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_positivenotes_1', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_interactedstudents_1', models.TextField(blank=True, null=True, verbose_name='The number of interacted students  ')),
                ('de_usedmethod_2', models.TextField(blank=True, null=True, verbose_name='The methods used during the distance education plan')),
                ('de_challenge_2', models.TextField(blank=True, null=True, verbose_name='The challenges during the distance education plan')),
                ('de_negativenotes_2', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_positivenotes_2', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_interactedstudents_2', models.TextField(blank=True, null=True, verbose_name='The number of interacted students  ')),
                ('de_usedmethod_3', models.TextField(blank=True, null=True, verbose_name='The methods used during the distance education plan')),
                ('de_challenge_3', models.TextField(blank=True, null=True, verbose_name='The challenges during the distance education plan')),
                ('de_negativenotes_3', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_positivenotes_3', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_interactedstudents_3', models.TextField(blank=True, null=True, verbose_name='The number of interacted students  ')),
                ('de_usedmethod_4', models.TextField(blank=True, null=True, verbose_name='The methods used during the distance education plan')),
                ('de_challenge_4', models.TextField(blank=True, null=True, verbose_name='The challenges during the distance education plan')),
                ('de_negativenotes_4', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_positivenotes_4', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_interactedstudents_4', models.TextField(blank=True, null=True, verbose_name='The number of interacted students  ')),
                ('de_usedmethod_5', models.TextField(blank=True, null=True, verbose_name='The methods used during the distance education plan')),
                ('de_challenge_5', models.TextField(blank=True, null=True, verbose_name='The challenges during the distance education plan')),
                ('de_negativenotes_5', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_positivenotes_5', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_interactedstudents_5', models.TextField(blank=True, null=True, verbose_name='The number of interacted students  ')),
                ('de_usedmethod_6', models.TextField(blank=True, null=True, verbose_name='The methods used during the distance education plan')),
                ('de_challenge_6', models.TextField(blank=True, null=True, verbose_name='The challenges during the distance education plan')),
                ('de_negativenotes_6', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_positivenotes_6', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_interactedstudents_6', models.TextField(blank=True, null=True, verbose_name='The number of interacted students  ')),
                ('de_usedmethod_7', models.TextField(blank=True, null=True, verbose_name='The methods used during the distance education plan')),
                ('de_challenge_7', models.TextField(blank=True, null=True, verbose_name='The challenges during the distance education plan')),
                ('de_negativenotes_7', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_positivenotes_7', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_interactedstudents_7', models.TextField(blank=True, null=True, verbose_name='The number of interacted students  ')),
                ('de_usedmethod_8', models.TextField(blank=True, null=True, verbose_name='The methods used during the distance education plan')),
                ('de_challenge_8', models.TextField(blank=True, null=True, verbose_name='The challenges during the distance education plan')),
                ('de_negativenotes_8', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_positivenotes_8', models.TextField(blank=True, null=True, verbose_name='The negative notes ')),
                ('de_interactedstudents_8', models.TextField(blank=True, null=True, verbose_name='The number of interacted students  ')),
                ('nbstudents', models.IntegerField(blank=True, null=True)),
                ('de_nbstudents', models.IntegerField(blank=True, null=True)),
                ('nbteachers', models.IntegerField(blank=True, null=True)),
                ('de_nbteachers', models.IntegerField(blank=True, null=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='\u0627\u0644\u0635\u0641')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='\u0627\u0644\u0645\u062f\u0631\u0633\u0629')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='schl_subject',
            options={'verbose_name_plural': 'Subjects'},
        ),
    ]
