# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-04-07 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0063_school_nb_of_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='nb_of_students',
        ),
    ]
