# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-04-09 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0064_remove_school_nb_of_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('teachingdays_tillfeb', models.IntegerField(blank=True, null=True)),
                ('teachingdays_frommars', models.IntegerField(blank=True, null=True)),
                ('teachingdays_remaining', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='\u0627\u0644\u0635\u0641'),
        ),
        migrations.AddField(
            model_name='survey',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='\u0627\u0644\u0645\u062f\u0631\u0633\u0629'),
        ),
        migrations.AddField(
            model_name='survey',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Subject', verbose_name='Subject'),
        ),
    ]
