# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-15 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0068_auto_20200504_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmround',
            name='current_round_inclusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clmround',
            name='end_date_inclusion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='end_date_inclusion_edit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='start_date_inclusion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='start_date_inclusion_edit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
