# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-19 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0069_auto_20200515_1009'),
        ('schools', '0061_auto_20200412_1826'),
    ]

    operations = [
    ]
