# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-10 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0076_auto_20200707_2030'),
    ]

    operations = [

    ]
