# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-13 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0077_auto_20200710_1155'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='evaluationdt',
        #     name='classroom',
        # ),
        # migrations.RemoveField(
        #     model_name='evaluationdt',
        #     name='evaluation',
        # ),
        # migrations.RemoveField(
        #     model_name='evaluationdt',
        #     name='subject',
        # ),
        # migrations.DeleteModel(
        #     name='Subject',
        # ),
        # migrations.DeleteModel(
        #     name='EvaluationDt',
        # ),
    ]
