# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-23 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0080_auto_20200803_1432'),
    ]

    operations = [

    ]
