# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0070_merge_20200519_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmround',
            name='current_year',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
