# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-28 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0120_auto_20201223_1408'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='evaluationdt',
        #     name='classroom',
        # ),
        # migrations.RemoveField(
        #     model_name='evaluationdt',
        #     name='evaluation',
        # ),
        # migrations.RemoveField(
        #     model_name='evaluationdt',
        #     name='subject',
        # ),
        # migrations.DeleteModel(
        #     name='Subject',
        # ),
        migrations.AddField(
            model_name='clmround',
            name='current_round_rs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clmround',
            name='end_date_rs',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='end_date_rs_edit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='start_date_rs',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='start_date_rs_edit',
            field=models.DateField(blank=True, null=True),
        ),
        # migrations.DeleteModel(
        #     name='EvaluationDt',
        # ),
    ]
