# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-03-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0123_auto_20220209_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, verbose_name='School name'),
        ),
    ]
