# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-05-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0124_auto_20220303_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_first_shift',
            field=models.BooleanField(default=False, verbose_name='School is 1st shift?'),
        ),
    ]
