# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-06-02 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20191219_1302'),
        ('schools', '0125_school_is_first_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='CWD_accessible',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Is the school accessible for CWD?'),
        ),
        migrations.AddField(
            model_name='school',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0645\u0646\u0637\u0642\u0629 \u0639\u0642\u0627\u0631\u064a\u0629'),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0642\u0636\u0627\u0621'),
        ),
        migrations.AddField(
            model_name='school',
            name='empty_building',
            field=models.IntegerField(blank=True, null=True, verbose_name='Available empty building/closed campus'),
        ),
        migrations.AddField(
            model_name='school',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0631\u0643\u0632: \u0627\u0644\u0645\u062d\u0627\u0641\u0638\u0629'),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('', '----------'), ('level_one', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0623\u0648\u0644'), ('level_two', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062b\u0627\u0646\u064a'), ('level_three', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062b\u0627\u0644\u062b'), ('level_four', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0631\u0627\u0628\u0639'), ('level_five', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062e\u0627\u0645\u0633'), ('level_six', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0633\u0627\u062f\u0633')], max_length=100, null=True, verbose_name='Grade level'),
        ),
        migrations.AddField(
            model_name='school',
            name='internet_available',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Availability of Internet'),
        ),
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='number_children',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (excluding SBP)'),
        ),
        migrations.AddField(
            model_name='school',
            name='number_children_female',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (female)'),
        ),
        migrations.AddField(
            model_name='school',
            name='number_children_female_sbp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (female, SBP only)'),
        ),
        migrations.AddField(
            model_name='school',
            name='number_children_lebanese',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (Lebanese)'),
        ),
        migrations.AddField(
            model_name='school',
            name='number_children_lebanese_sbp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (Lebanese, SBP only)'),
        ),
        migrations.AddField(
            model_name='school',
            name='number_children_male',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (male)'),
        ),
        migrations.AddField(
            model_name='school',
            name='number_children_male_sbp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (male, SBP only)'),
        ),
        migrations.AddField(
            model_name='school',
            name='number_children_non_lebanese',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (non Lebanese)'),
        ),
        migrations.AddField(
            model_name='school',
            name='number_children_non_lebanese_sbp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (non Lebanese, SBP only)'),
        ),
        migrations.AddField(
            model_name='school',
            name='number_children_sbp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (SBP only)'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='School capacity'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_digital_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='School Digital Capacity'),
        ),
        migrations.AlterField(
            model_name='school',
            name='director_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0631\u0642\u0645 \u0647\u0627\u062a\u0641 \u0627\u0644\u0645\u062f\u0631\u0633\u0629'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_first_shift',
            field=models.BooleanField(default=True, verbose_name='School is 1st shift?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number',
            field=models.CharField(max_length=45, unique=True, verbose_name='School CERD Number'),
        ),
    ]
