# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-06-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0126_auto_20220602_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='empty_building',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Available empty building/closed campus'),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.FloatField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='School GPS (latitude)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.FloatField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='School GPS (longitude)'),
        ),
    ]
