# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-06-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0127_auto_20220602_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_first_shift',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='School is 1st shift?'),
        ),
    ]
