# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-06-02 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0128_auto_20220602_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='School GPS (latitude)'),
        ),
    ]
