# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-06-02 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0129_auto_20220602_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='School GPS (longitude)'),
        ),
    ]
