# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-10 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0121_auto_20201228_0925'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='evaluationdt',
        #     name='classroom',
        # ),
        # migrations.RemoveField(
        #     model_name='evaluationdt',
        #     name='evaluation',
        # ),
        # migrations.RemoveField(
        #     model_name='evaluationdt',
        #     name='subject',
        # ),
        # migrations.DeleteModel(
        #     name='Subject',
        # ),
        # migrations.DeleteModel(
        #     name='EvaluationDt',
        # ),
    ]
