# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-06-06 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0131_auto_20220606_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u062e\u0631 \u062a\u0639\u062f\u064a\u0644 \u0645\u0646 \u0642\u0628\u0644'),
        ),
        migrations.AddField(
            model_name='school',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
