# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-06 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0132_auto_20220606_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpassignmentmatrix',
            name='matrix_type',
            field=models.CharField(blank=True, choices=[('O', 'Old'), ('N', 'New')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='closed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Closed Date'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is closed'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='school_type',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='school type'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='implemented_de',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Have you implemented distance education ?'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='implemented_de_2',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Have you implemented distance education ?'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='implemented_de_3',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Have you implemented distance education ?'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='implemented_de_9',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Have you implemented distance education ?'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='implemented_de_prep',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, verbose_name='Have you implemented distance education ?'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='other_notes_de',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='schl_survey',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='schl_survey',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='schl_survey_class',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='schl_survey_class',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='CWD_accessible',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Is the school accessible for CWD?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='academic_year_end',
            field=models.DateField(blank=True, null=True, verbose_name='School year end date'),
        ),
        migrations.AlterField(
            model_name='school',
            name='academic_year_exam_end',
            field=models.DateField(blank=True, null=True, verbose_name='Exam end date'),
        ),
        migrations.AlterField(
            model_name='school',
            name='academic_year_start',
            field=models.DateField(blank=True, null=True, verbose_name='School year start date'),
        ),
        migrations.AlterField(
            model_name='school',
            name='attendance_range',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attendance day range'),
        ),
        migrations.AlterField(
            model_name='school',
            name='bank_Base1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staffs.Bank', verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='school',
            name='bank_Base2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staffs.Bank', verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='school',
            name='branch_base1',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='school',
            name='branch_base2',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='school',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='Cadaster'),
        ),
        migrations.AlterField(
            model_name='school',
            name='certified_foreign_language',
            field=models.CharField(blank=True, choices=[('French', 'French'), ('English', 'English'), ('French & English', 'French & English')], max_length=100, null=True, verbose_name='Certified foreign language'),
        ),
        migrations.AlterField(
            model_name='school',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='school',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Coordinator', verbose_name='coordinator'),
        ),
        migrations.AlterField(
            model_name='school',
            name='director_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School director name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='director_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School land phone number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='empty_building',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Available empty building/closed campus'),
        ),
        migrations.AlterField(
            model_name='school',
            name='fax_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School fax number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='school',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('', '----------'), ('level_one', 'Level one'), ('level_two', 'Level two'), ('level_three', 'Level three'), ('level_four', 'Level four'), ('level_five', 'Level five'), ('level_six', 'Level six')], max_length=100, null=True, verbose_name='Grade level'),
        ),
        migrations.AlterField(
            model_name='school',
            name='internet_available',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Availability of Internet'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_2nd_shift',
            field=models.BooleanField(default=False, verbose_name='School is 2nd shift?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_alp',
            field=models.BooleanField(default=False, verbose_name='School is ALP?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is closed'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_first_shift',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='School is 1st shift?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='it_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School IT name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='it_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School IT phone number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='land_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='School land phone number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='School location'),
        ),
        migrations.AlterField(
            model_name='school',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_students_2nd_shift',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expected number of students in 2nd shift'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_students_alp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expected number of students in ALP'),
        ),
        migrations.AlterField(
            model_name='school',
            name='weekend',
            field=models.CharField(blank=True, choices=[('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=100, null=True, verbose_name='School weekends'),
        ),
    ]
