# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-09-16 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0132_auto_20220606_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmround',
            name='current_round_mscc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clmround',
            name='end_date_mscc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='end_date_mscc_edit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='start_date_mscc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmround',
            name='start_date_mscc_edit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
