# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0136_auto_20230427_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='number_dirasa_children_disability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total number of Children With Disability (Dirasa only)'),
        ),
        migrations.AddField(
            model_name='school',
            name='number_total_children_disability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total number of Children With Disability (Excluding Dirasa)'),
        ),
        migrations.AddField(
            model_name='school',
            name='receive_supplies',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Did the school receive school supplies/stationery'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_children',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (excluding Dirasa)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_children_female_sbp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (female, Dirasa only)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_children_lebanese_sbp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (Lebanese, Dirasa only)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_children_male_sbp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (male, Dirasa only)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_children_non_lebanese_sbp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (non Lebanese, Dirasa only)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_children_sbp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of children enrolled (Dirasa only)'),
        ),
    ]
