# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0137_auto_20230428_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='CWD_accessible',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Is the school accessible for CWD?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='empty_building',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Available empty building/closed campus'),
        ),
        migrations.AlterField(
            model_name='school',
            name='internet_available',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Availability of Internet'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_first_shift',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='School is 1st shift?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='receive_supplies',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Did the school receive school supplies/stationery'),
        ),
    ]
