# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-05 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0141_auto_20230503_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Club Type',
            },
        ),
        migrations.AlterField(
            model_name='club',
            name='club_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClubType', verbose_name='Club Type'),
        ),
        migrations.AlterField(
            model_name='club',
            name='number_children',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Number of Children'),
        ),
    ]
