# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-10-17 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0144_auto_20230718_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='benefit_wfp_service',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Is the school benefiting from WFP services?'),
        ),
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Private School', 'Private School'), ('Private Free School', 'Private Free School')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='wfp_service_type',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Community Kitchen', 'Community Kitchen'), ('School Snacks', 'School Snacks')], max_length=10, null=True, verbose_name='Service Type?'),
        ),
    ]
