# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-02 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0146_auto_20231017_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='is_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='is_youth',
            field=models.BooleanField(default=False),
        ),
    ]
