# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-10-01 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0146_auto_20231017_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_bma',
            field=models.BooleanField(default=True, verbose_name='BMA school'),
        ),
    ]
