# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-09 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0147_auto_20240702_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerorganization',
            name='is_education',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='is_youth',
        ),
    ]
