# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-05-20 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0121_auto_20201228_0925'),
    ]


