# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-09 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0148_auto_20240709_1638'),
    ]


