# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-10-23 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0149_partnerorganization_schools'),
        ('schools', '0147_school_is_bma'),
    ]

    operations = [
    ]
