# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-01-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0150_merge_20241023_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmround',
            name='current_year_inclusion',
            field=models.BooleanField(default=False),
        ),
    ]
