# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-02-27 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0151_clmround_current_year_inclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='digital_learning_programme',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Does the school have a digital learning programme?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_digital_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of devices'),
        ),
    ]
