# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-05-14 19:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0152_auto_20250227_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='is_Kayany',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='registration_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Level one', 'Level one'), ('Level two', 'Level two'), ('Level three', 'Level three'), ('Level four', 'Level four'), ('Level five', 'Level five'), ('Level six', 'Level six'), ('grade_one', 'Grade one'), ('grade_two', 'Grade two'), ('grade_three', 'Grade three'), ('grade_four', 'Grade four'), ('grade_five', 'Grade five'), ('grade_six', 'Grade six')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Grade level'),
        ),
    ]
