# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-06-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0154_auto_20250520_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='monitoring_evaluation_focal_point_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Monitoring and Evaluation Focal Point Email'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='monitoring_evaluation_focal_point_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Monitoring and Evaluation Focal Point Name'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='monitoring_evaluation_focal_point_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Monitoring and Evaluation Focal Point Phone'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='program_manager_focal_point_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Program Manager Focal Point Email'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='program_manager_focal_point_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Program Manager Focal Point Name'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='program_manager_focal_point_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Program Manager Focal Point Phone'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Name'),
        ),
    ]
