# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-06-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0155_auto_20250610_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='is_youth',
            field=models.BooleanField(default=False),
        ),
    ]
