# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-06-26 16:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0156_partnerorganization_is_youth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='registration_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Level one', 'Level one'), ('Level two', 'Level two'), ('Level three', 'Level three'), ('Level four', 'Level four'), ('Level five', 'Level five'), ('Level six', 'Level six'), ('level_one_pm', 'Level one PM shift'), ('level_two_pm', 'Level two PM shift'), ('level_three_pm', 'Level three PM shift'), ('level_four_pm', 'Level four PM shift'), ('level_five_pm', 'Level five PM shift'), ('level_six_pm', 'Level six PM shift'), ('grade_one', 'Grade one'), ('grade_two', 'Grade two'), ('grade_three', 'Grade three'), ('grade_four', 'Grade four'), ('grade_five', 'Grade five'), ('grade_six', 'Grade six'), ('grade_seven', 'Grade seven'), ('grade_eight', 'Grade eight'), ('grade_nine', 'Grade nine')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Grade level'),
        ),
    ]
