# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-08-20 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0157_auto_20250626_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='is_unrwa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='is_unrwa',
            field=models.BooleanField(default=False),
        ),
    ]
