# Generated by Django 5.2.3 on 2025-09-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0027_alter_activityinfolocation_id_and_more'),
        ('schools', '0158_auto_20250820_1259'),
        ('staffs', '0026_auto_20250210_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpassignmentmatrix',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alpassignmentmatrix',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationlevel'),
        ),
        migrations.AlterField(
            model_name='alpassignmentmatrix',
            name='refer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refer_to', to='schools.educationlevel'),
        ),
        migrations.AlterField(
            model_name='alprefermatrix',
            name='fail_refer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fail_refer_to', to='schools.classlevel'),
        ),
        migrations.AlterField(
            model_name='alprefermatrix',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alprefermatrix',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationlevel'),
        ),
        migrations.AlterField(
            model_name='alprefermatrix',
            name='success_refer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_refer_to', to='schools.classlevel'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classroom', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationyear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, verbose_name='is closed'),
        ),
        migrations.AlterField(
            model_name='class_section',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.section', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clmround',
            name='current_round_abln',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clmround',
            name='current_round_bln',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clmround',
            name='current_round_bridging',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clmround',
            name='current_round_cbece',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clmround',
            name='current_round_inclusion',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clmround',
            name='current_round_outreach',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clmround',
            name='current_round_rs',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clmround',
            name='current_year_inclusion',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clmround',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clubtype', verbose_name='Club Type'),
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='club',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='communityinitiative',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='communityinitiative',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='communityinitiative',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='educationallevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='new_calculation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='with_arabic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='with_language',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='with_math',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='with_science',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='educationyear',
            name='current_year',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='educationyear',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationyear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='healthvisit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='healthvisit',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='healthvisit',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='bln_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clmround', verbose_name='BLN current round'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='cbece_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clmround', verbose_name='CB-ECE current round'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='is_Kayany',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='is_unrwa',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='is_youth',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='rs_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.clmround', verbose_name='RS current round'),
        ),
        migrations.AlterField(
            model_name='publicdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicholidays',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schl_subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schl_survey',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classroom', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='schl_survey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schl_survey',
            name='schl_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.schl_subject', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='schl_survey',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='schl_survey_class',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classroom', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='schl_survey_class',
            name='de_implemented',
            field=models.BooleanField(blank=True, default=False, verbose_name='Distance education implemented ?'),
        ),
        migrations.AlterField(
            model_name='schl_survey_class',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schl_survey_class',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='attendance_from_beginning',
            field=models.BooleanField(blank=True, default=False, verbose_name='Start attendance from the beginning'),
        ),
        migrations.AlterField(
            model_name='school',
            name='bank_Base1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staffs.bank', verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='school',
            name='bank_Base2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staffs.bank', verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='school',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Cadaster'),
        ),
        migrations.AlterField(
            model_name='school',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.coordinator', verbose_name='coordinator'),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='school',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_2nd_shift',
            field=models.BooleanField(blank=True, default=False, verbose_name='School is 2nd shift?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_alp',
            field=models.BooleanField(blank=True, default=False, verbose_name='School is ALP?'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_bma',
            field=models.BooleanField(blank=True, default=True, verbose_name='BMA school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, verbose_name='is closed'),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_unrwa',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='School location'),
        ),
        migrations.AlterField(
            model_name='school',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='school',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
