# Generated by Django 5.2.3 on 2025-10-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0160_partnerorganization_is_dirasa_is_bma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerorganization',
            old_name='is_bma',
            new_name='is_makani',
        ),
    ]
