# Generated by Django 5.2.3 on 2026-02-20 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0161_rename_is_bma_partnerorganization_is_makani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='registration_level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Level one', 'Level one'), ('Level two', 'Level two'), ('Level three', 'Level three'), ('grade_one', 'Grade one'), ('grade_two', 'Grade two'), ('grade_three', 'Grade three'), ('grade_four', 'Grade four'), ('grade_five', 'Grade five'), ('grade_six', 'Grade six'), ('grade_seven', 'Grade seven'), ('grade_eight', 'Grade eight'), ('grade_nine', 'Grade nine')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Grade level'),
        ),
    ]
