# Generated by Django 5.2.3 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0162_alter_school_registration_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='is_world_learning',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
