# Generated by Django 5.2.3 on 2026-05-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0163_partnerorganization_is_world_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='active_during_emergency',
            field=models.CharField(
                blank=True,
                choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')],
                max_length=10,
                null=True,
                verbose_name='Active during emergency',
            ),
        ),
    ]
