# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0002_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_locations_+', to='locations.Location'),
        ),
    ]
