# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20161021_1045'),
        ('users', '0004_auto_20160923_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schools',
            field=models.ManyToManyField(blank=True, to='schools.School'),
        ),
    ]
