# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-23 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_pilot_in_use'),
        ('users', '0006_remove_user_app_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='governante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location'),
        ),
    ]
