# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-09 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20221213_1620'),
        ('users', '0013_user_staff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Center'),
        ),
    ]
