# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-09 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0007_auto_20240709_1641'),
        ('users', '0014_user_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='youth_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Partner', verbose_name='Partner'),
        ),
    ]
