# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-08-09 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_youth_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='youth_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='youth.Partner', verbose_name='Youth Partner'),
        ),
    ]
