# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-06-10 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20250210_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='youth_partner',
        ),
    ]
