from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views
# from .views import BLN, CBECE, RS

urlpatterns = [

    url(
        regex=r'^index/$',
        view=views.CLMView.as_view(),
        name='index'
    ),

    url(
        regex=r'^bln-dashboard/$',
        view=views.BLNDashboardView.as_view(),
        name='bln_dashboard'
    ),

    url(
        regex=r'^rs-dashboard/$',
        view=views.RSDashboardView.as_view(),
        name='rs_dashboard'
    ),

    url(
        regex=r'^cbece-dashboard/$',
        view=views.CBECEDashboardView.as_view(),
        name='cbece_dashboard'
    ),

    url(
        regex=r'^bln-add/$',
        view=views.BLNAddView.as_view(),
        name='bln_add'
    ),
    url(
        regex=r'^bln-edit/(?P<pk>[\w.@+-]+)/$',
        view=views.BLNEditView.as_view(),
        name='bln_edit'
    ),
    url(
        regex=r'^bln-export/$',
        view=views.BLNExportViewSet.as_view(),
        name='bln_export'
    ),
    url(
        regex=r'^assessment-submission/$',
        view=views.AssessmentSubmission.as_view(),
        name='assessment_submission'
    ),
    url(
        regex=r'^bln-list/$',
        view=views.BLNListView.as_view(),
        name='bln_list'
    ),
    url(
        regex=r'^bln-referral/(?P<pk>[\w.@+-]+)/$',
        view=views.BLNReferralView.as_view(),
        name='bln_referral'
    ),
    url(
        regex=r'^bln-followup/(?P<pk>[\w.@+-]+)/$',
        view=views.BLNFollowupView.as_view(),
        name='bln_followup'
    ),
    url(
        regex=r'^rs-add/$',
        view=views.RSAddView.as_view(),
        name='rs_add'
    ),
    url(
        regex=r'^rs-edit/(?P<pk>[\w.@+-]+)/$',
        view=views.RSEditView.as_view(),
        name='rs_edit'
    ),
    url(
        regex=r'^rs-export/$',
        view=views.RSExportViewSet.as_view(),
        name='rs_export'
    ),
    url(
        regex=r'^rs-list/$',
        view=views.RSListView.as_view(),
        name='rs_list'
    ),

    url(
        regex=r'^cbece-add/$',
        view=views.CBECEAddView.as_view(),
        name='cbece_add'
    ),
    url(
        regex=r'^cbece-edit/(?P<pk>[\w.@+-]+)/$',
        view=views.CBECEEditView.as_view(),
        name='cbece_edit'
    ),
    url(
        regex=r'^cbece-export/$',
        view=views.CBECEExportViewSet.as_view(),
        name='cbece_export'
    ),
    url(
        regex=r'^cbece-list/$',
        view=views.CBECEListView.as_view(),
        name='cbece_list'
    ),

    url(
        regex=r'^abln-add/$',
        view=views.ABLNAddView.as_view(),
        name='abln_add'
    ),
    url(
        regex=r'^abln-edit/(?P<pk>[\w.@+-]+)/$',
        view=views.ABLNEditView.as_view(),
        name='abln_edit'
    ),
    url(
        regex=r'^abln-export/$',
        view=views.ABLNExportViewSet.as_view(),
        name='abln_export'
    ),
    url(
        regex=r'^abln-list/$',
        view=views.ABLNListView.as_view(),
        name='abln_list'
    ),
    url(
        regex=r'^abln-referral/(?P<pk>[\w.@+-]+)/$',
        view=views.ABLNReferralView.as_view(),
        name='abln_referral'
    ),
    url(
        regex=r'^abln-followup/(?P<pk>[\w.@+-]+)/$',
        view=views.ABLNFollowupView.as_view(),
        name='abln_followup'
    ),
    url(
        regex=r'^abln-post-assessment/(?P<pk>[\w.@+-]+)/$',
        view=views.ABLNPostAssessmentView.as_view(),
        name='abln_post_assessment'
    ),
    url(
        regex=r'^bln-post-assessment/(?P<pk>[\w.@+-]+)/$',
        view=views.BLNPostAssessmentView.as_view(),
        name='bln_post_assessment'
    ),
    url(
        regex=r'^cbece-post-assessment/(?P<pk>[\w.@+-]+)/$',
        view=views.CBECEPostAssessmentView.as_view(),
        name='cbece_post_assessment'
    ),
    url(
        regex=r'^cbece-referral/(?P<pk>[\w.@+-]+)/$',
        view=views.CBECEReferralView.as_view(),
        name='cbece_referral'
    ),
    url(
        regex=r'^cbece-followup/(?P<pk>[\w.@+-]+)/$',
        view=views.CBECEFollowupView.as_view(),
        name='cbece_followup'
    ),
    url(
        'load-districts/$',
        views.load_districts,
        name='load_districts'
    ),
    url(
        'search-clm-child/$',
        views.search_clm_child,
        name='search_clm_child'
    ),
    url(
        regex=r'^exec-abln-update/$',
        view=views.ExecABLNUpdateView.as_view(),
        name='exec_abln_update'
    ),
]
