# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_squashed_0010_auto_20160531_1744'),
        ('alp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='average_distance',
            field=models.CharField(blank=True, choices=[('<= 2.5km', '<= 2.5km'), ('> 2.5km', '> 2.5km'), ('> 10km', '> 10km')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Language'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Governorate'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.ClassLevel'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.PartnerOrganization'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.School'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student'),
        ),
    ]
