# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0006_outreach_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreach',
            name='governorate',
        ),
    ]
