# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-31 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0007_auto_20161027_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='alp_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alp.ALPRound'),
        ),
    ]
