# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0007_remove_outreach_governorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='last_class_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.ClassLevel'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.EducationLevel'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Location'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.PartnerOrganization'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.School'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student'),
        ),
    ]
