# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0008_auto_20160531_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outreach',
            options={'ordering': ['id']},
        ),
    ]
