# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alp', '0009_auto_20160606_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
