# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0010_auto_20161104_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='exam_result_arabic',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='exam_result_language',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='exam_result_math',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='exam_result_science',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
