# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0011_auto_20161107_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='not_enrolled_in_this_school',
            field=models.BooleanField(default=False),
        ),
    ]
