# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 11:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0011_auto_20160701_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='extra_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
