# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0012_outreach_not_enrolled_in_this_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='exam_not_exist_in_school',
            field=models.BooleanField(default=False),
        ),
    ]
