# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0013_auto_20160704_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreach',
            name='extra_fields',
        ),
    ]
