# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-07 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0016_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outreach',
            options={'ordering': ['id'], 'verbose_name': 'Pre Test'},
        ),
    ]
