# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0017_auto_20160715_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='day',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='month',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='year',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='education_level',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
