# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20160719_2149'),
        ('alp', '0018_auto_20160719_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='owner',
        ),
        migrations.AddField(
            model_name='registration',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Grade'),
        ),
        migrations.AddField(
            model_name='registration',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Section'),
        ),
    ]
