# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_classroom_school'),
        ('alp', '0022_remove_registration_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.ClassRoom'),
        ),
    ]
