# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-18 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0022_auto_20170216_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alp_enrollment', to='students.Student'),
        ),
    ]
