# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-22 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0023_auto_20170218_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='assigned_to_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel', verbose_name='Assigned to level'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel', verbose_name='Registered in level'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='registered_in_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel', verbose_name='Current level'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section', verbose_name='Current Section'),
        ),
    ]
