# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-04 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0024_auto_20170222_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='dropout_status',
            field=models.BooleanField(default=False),
        ),
    ]
