# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alp', '0025_auto_20160803_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='validation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='validation_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='validation_status',
            field=models.BooleanField(default=False),
        ),
    ]
