# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 07:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0026_auto_20160803_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='validation_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
