# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0026_auto_20170418_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alpround',
            options={'ordering': ['name'], 'verbose_name': 'ALP Round'},
        ),
    ]
