# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_educationlevel_school'),
        ('alp', '0027_auto_20160803_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.School'),
        ),
    ]
