# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-30 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0027_auto_20170419_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReEnrolled',
        ),
    ]
