# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-07 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0027_auto_20170503_2123'),
        ('alp', '0028_delete_reenrolled'),
    ]

    operations = [
    ]
