# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alp', '0029_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
