# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-08 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0031_auto_20170606_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracolumn',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='preferred_language',
        ),
        migrations.DeleteModel(
            name='ExtraColumn',
        ),
    ]
