# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-11 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0031_auto_20170606_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='exam_language',
            field=models.CharField(blank=True, choices=[('english', '\u0627\u0644\u0625\u0646\u062c\u0644\u064a\u0632\u064a\u0651\u0629'), ('french', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0651\u0629')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='post_exam_language',
            field=models.CharField(blank=True, choices=[('english', '\u0627\u0644\u0625\u0646\u062c\u0644\u064a\u0632\u064a\u0651\u0629'), ('french', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0651\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='assigned_to_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel', verbose_name='Pre-test result'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel', verbose_name='Entrance Test (Pre-Test)'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='refer_to_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassLevel', verbose_name='Post-test result'),
        ),
    ]
