# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-22 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0032_auto_20170711_1257'),
        ('alp', '0032_auto_20170708_1557'),
    ]

    operations = [
    ]
