# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-15 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0036_auto_20170915_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='exam_language',
            field=models.CharField(blank=True, choices=[('english', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629'), ('french', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0646\u0634\u0623 \u0645\u0646 \u0642\u0628\u0644'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='post_exam_language',
            field=models.CharField(blank=True, choices=[('english', '\u0627\u0644\u0627\u0646\u0643\u0644\u064a\u0632\u064a\u0629'), ('french', '\u0627\u0644\u0641\u0631\u0646\u0633\u064a\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alp_school', to='schools.School', verbose_name='\u0627\u0644\u0645\u062f\u0631\u0633\u0629'),
        ),
    ]
