# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0038_auto_20170927_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='exam_result_language',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0644\u063a\u0629 \u0627\u062c\u0646\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='post_exam_result_language',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u0644\u063a\u0629 \u0627\u062c\u0646\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='pre_test_room',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='\u063a\u0631\u0641\u0629 \u0627\u0645\u062a\u062d\u0627\u0646 \u0627\u0644\u062f\u062e\u0648\u0644'),
        ),
    ]
