# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0042_auto_20171102_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='\u0627\u0644\u0645\u0648\u0642\u0639/\u0645\u0631\u0643\u0632'),
        ),
    ]
