# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0044_auto_20171111_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='have_barcode',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u0644\u062f\u064a\u0647 \u0627\u0644\u0628\u0627\u0631\u0643\u0648\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_informal_edu_final_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassLevel', verbose_name='\u062a\u0641\u0627\u0635\u064a\u0644 \u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u062e\u0644\u0627\u0644 \u0622\u062e\u0631 \u062f\u0648\u0631\u0629  \u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_informal_edu_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alp.ALPRound', verbose_name=' \u062a\u0641\u0627\u0635\u064a\u0644 \u0622\u062e\u0631 \u062f\u0648\u0631\u0629  \u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='new_registry',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u064a\u062a\u0645 \u0627\u0644\u062a\u0633\u062c\u064a\u0644 \u0644\u0623\u0648\u0644 \u0645\u0631\u0629\u061f'),
        ),
    ]
