# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-08 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0052_auto_20190928_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpround',
            name='round_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Round end date'),
        ),
        migrations.AlterField(
            model_name='alpround',
            name='round_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Round start date'),
        ),
    ]
