# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-06 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0056_auto_20200414_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpround',
            name='round_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Round start date'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='assigned_to_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel', verbose_name='Pre-test result'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='exam_language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('french', 'French')], max_length=50, null=True, verbose_name='Exam language'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='exam_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='exam_result_arabic',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Arabic'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='exam_result_language',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Foreign Language'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='exam_result_math',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Math'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='exam_result_science',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Science'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='have_barcode',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='Have barcode with him?'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='Last Education level'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_education_year',
            field=models.CharField(blank=True, choices=[('2000/2001', '2000/2001'), ('2001/2002', '2001/2002'), ('2002/2003', '2002/2003'), ('2003/2004', '2003/2004'), ('2004/2005', '2004/2005'), ('2005/2006', '2005/2006'), ('2006/2007', '2006/2007'), ('2007/2008', '2007/2008'), ('2008/2009', '2008/2009'), ('2009/2010', '2009/2010'), ('2010/2011', '2010/2011'), ('2011/2012', '2011/2012'), ('2012/2013', '2012/2013'), ('2013/2014', '2013/2014'), ('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030'), ('2030/2031', '2030/2031'), ('2031/2032', '2031/2032'), ('2032/2033', '2032/2033'), ('2033/2034', '2033/2034'), ('2034/2035', '2034/2035'), ('2035/2036', '2035/2036'), ('2036/2037', '2036/2037'), ('2037/2038', '2037/2038'), ('2038/2039', '2038/2039'), ('2039/2040', '2039/2040'), ('2040/2041', '2040/2041'), ('2041/2042', '2041/2042'), ('2042/2043', '2042/2043'), ('2043/2044', '2043/2044'), ('2044/2045', '2044/2045'), ('2045/2046', '2045/2046'), ('2046/2047', '2046/2047'), ('2047/2048', '2047/2048'), ('2048/2049', '2048/2049'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Last Education year'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_informal_edu_final_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassLevel', verbose_name='Last informal education status'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_informal_edu_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel', verbose_name='Last informal education level'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_informal_edu_result',
            field=models.CharField(blank=True, choices=[('graduated', 'Graduated'), ('failed', 'Failed')], max_length=50, null=True, verbose_name='Last informal education result'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_informal_edu_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alp.ALPRound', verbose_name='Last informal education round'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_informal_edu_year',
            field=models.CharField(blank=True, choices=[('2000/2001', '2000/2001'), ('2001/2002', '2001/2002'), ('2002/2003', '2002/2003'), ('2003/2004', '2003/2004'), ('2004/2005', '2004/2005'), ('2005/2006', '2005/2006'), ('2006/2007', '2006/2007'), ('2007/2008', '2007/2008'), ('2008/2009', '2008/2009'), ('2009/2010', '2009/2010'), ('2010/2011', '2010/2011'), ('2011/2012', '2011/2012'), ('2012/2013', '2012/2013'), ('2013/2014', '2013/2014'), ('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030'), ('2030/2031', '2030/2031'), ('2031/2032', '2031/2032'), ('2032/2033', '2032/2033'), ('2033/2034', '2033/2034'), ('2034/2035', '2034/2035'), ('2035/2036', '2035/2036'), ('2036/2037', '2036/2037'), ('2037/2038', '2037/2038'), ('2038/2039', '2038/2039'), ('2039/2040', '2039/2040'), ('2040/2041', '2040/2041'), ('2041/2042', '2041/2042'), ('2042/2043', '2042/2043'), ('2043/2044', '2043/2044'), ('2044/2045', '2044/2045'), ('2045/2046', '2045/2046'), ('2046/2047', '2046/2047'), ('2047/2048', '2047/2048'), ('2048/2049', '2048/2049'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Last informal education year'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_year_result',
            field=models.CharField(blank=True, choices=[('graduated', 'Graduated'), ('failed', 'Failed')], max_length=50, null=True, verbose_name='Last Education result'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel', verbose_name='Entrance Test (Pre-Test)'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='new_registry',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='First time registered?'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='outreach_barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Outreach barcode'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='participated_in_alp',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='Participated in ALP'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='post_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='post_exam_language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('french', 'French')], max_length=50, null=True, verbose_name='Exam language'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='post_exam_result_arabic',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Arabic'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='post_exam_result_language',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Foreign Language'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='post_exam_result_math',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Math'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='post_exam_result_science',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Science'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='post_test_room',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Post test room'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='pre_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='pre_test_room',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Pre test room'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='refer_to_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassLevel', verbose_name='Post-test result'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='registered_in_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel', verbose_name='Current Level'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='registered_in_school',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('yes', 'Yes'), ('no', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='registered_in_unhcr',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('yes', 'Yes'), ('no', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alp_school', to='schools.School', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section', verbose_name='Current Section'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='student_outreached',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='Student outreached?'),
        ),
    ]
