# Generated by Django 5.2.3 on 2025-09-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0058_auto_20250210_1627'),
        ('locations', '0026_auto_20250701_1656'),
        ('schools', '0158_auto_20250820_1259'),
        ('students', '0087_auto_20250626_1644'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS students_alp_dob CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='alpround',
            name='current_post_test',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='alpround',
            name='current_pre_test',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='alpround',
            name='current_round',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='alpround',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='alp_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alp.alpround'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='assigned_to_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationlevel', verbose_name='Pre-test result'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classroom'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='dropout_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='enrolled_in_this_school',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='exam_not_exist_in_school',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='exam_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classlevel'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classroom', verbose_name='Last Education level'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_informal_edu_final_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classlevel', verbose_name='Last informal education status'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_informal_edu_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationlevel', verbose_name='Last informal education level'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_informal_edu_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alp.alpround', verbose_name='Last informal education round'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationlevel', verbose_name='Entrance Test (Pre-Test)'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='not_enrolled_in_this_school',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.partnerorganization'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='refer_to_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.classlevel', verbose_name='Post-test result'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='registered_in_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationlevel', verbose_name='Current Level'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alp_school', to='schools.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.section', verbose_name='Current Section'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alp_enrollment', to='students.student'),
        ),
    ]
