# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-09 12:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0002_auto_20221208_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='cash_support_programmes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Haddi', 'Haddi'), ('Education Cash assistance', 'Education Cash assistance'), ('UNHCR cash assistance', 'UNHCR cash assistance'), ('WFP cash assistance', 'WFP cash assistance')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Cash support programmes that child is already benefitting from'),
        ),
    ]
