# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-12 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0004_auto_20221209_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationassessment',
            old_name='barriers_single',
            new_name='barriers',
        ),
        migrations.AddField(
            model_name='educationassessment',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mscc.Registration'),
        ),
    ]
