# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-14 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0006_auto_20221213_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationassessment',
            name='post_modality_arabic',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Online Forms', 'Online Forms'), ('Phone call/WhatsApp', 'Phone call/WhatsApp'), ('Asking Parents', 'Asking Parents'), ('Offline (F2F)', 'Offline (F2F)')], max_length=50, null=True, verbose_name='Modality'),
        ),
        migrations.AlterField(
            model_name='educationassessment',
            name='post_modality_language',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Online Forms', 'Online Forms'), ('Phone call/WhatsApp', 'Phone call/WhatsApp'), ('Asking Parents', 'Asking Parents'), ('Offline (F2F)', 'Offline (F2F)')], max_length=50, null=True, verbose_name='Modality'),
        ),
        migrations.AlterField(
            model_name='educationassessment',
            name='post_modality_math',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Online Forms', 'Online Forms'), ('Phone call/WhatsApp', 'Phone call/WhatsApp'), ('Asking Parents', 'Asking Parents'), ('Offline (F2F)', 'Offline (F2F)')], max_length=50, null=True, verbose_name='Modality'),
        ),
        migrations.AlterField(
            model_name='educationassessment',
            name='pre_modality_arabic',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Online Forms', 'Online Forms'), ('Phone call/WhatsApp', 'Phone call/WhatsApp'), ('Asking Parents', 'Asking Parents'), ('Offline (F2F)', 'Offline (F2F)')], max_length=50, null=True, verbose_name='Modality'),
        ),
        migrations.AlterField(
            model_name='educationassessment',
            name='pre_modality_language',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Online Forms', 'Online Forms'), ('Phone call/WhatsApp', 'Phone call/WhatsApp'), ('Asking Parents', 'Asking Parents'), ('Offline (F2F)', 'Offline (F2F)')], max_length=50, null=True, verbose_name='Modality'),
        ),
        migrations.AlterField(
            model_name='educationassessment',
            name='pre_modality_math',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Online Forms', 'Online Forms'), ('Phone call/WhatsApp', 'Phone call/WhatsApp'), ('Asking Parents', 'Asking Parents'), ('Offline (F2F)', 'Offline (F2F)')], max_length=50, null=True, verbose_name='Modality'),
        ),
    ]
