# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-15 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0008_auto_20221215_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthnutritionservice',
            name='age_eat_solid_food',
            field=models.CharField(blank=True, choices=[('', '----------'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('7 months', '7 months'), ('8 months', '8 months'), ('9 months', '9 months'), ('10 months', '10 months'), ('11 months', '11 months'), ('12 months', '12 months'), ('13 months', '13 months'), ('14 months', '14 months'), ('15 months', '15 months'), ('16 months', '16 months'), ('17 months', '17 months'), ('18 months', '18 months'), ('19 months', '19 months'), ('20 months', '20 months'), ('21 months', '21 months'), ('22 months', '22 months'), ('23 months', '23 months'), ('24 months', '24 months')], max_length=50, null=True, verbose_name='If yes, at which age ?'),
        ),
    ]
