# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0009_auto_20221215_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupservice',
            name='follow_up_result',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Child returned to program', 'Child returned to program'), ('Child referred to specialized services', 'Child referred to specialized services'), ('Child referred to CP', 'Child referred to CP'), ('Child referred to Health programme', 'Child referred to Health programme'), ('Follow-up with parents', 'Follow-up with parents'), ('Dropout/No Interest', 'Dropout/No Interest')], max_length=100, null=True, verbose_name='Result of follow up'),
        ),
        migrations.AlterField(
            model_name='followupservice',
            name='meeting_modality',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Online via WhatsApp', 'Online via WhatsApp'), ('Phone calls', 'Phone calls'), ('Offline (F2F)', 'Offline (F2F)')], max_length=200, null=True, verbose_name='Please the modality used per each session'),
        ),
        migrations.AlterField(
            model_name='followupservice',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('', '----------'), ('PSS Session', 'PSS Session'), ('COVID health awareness session', 'COVID health awareness session')], max_length=50, null=True, verbose_name='Please indicate the types of meeting'),
        ),
    ]
