# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0010_auto_20221216_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='providedservices',
            name='service_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
