# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-22 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0011_providedservices_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='receive_needed_material',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Did the child receive all needed materials and resources (Stationery, Books, Learning bundle)?'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='recommended_learning_path',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Transition to Dirasa', 'Transition to Dirasa'), ('Repeat same level in next  school year', 'Repeat same level in next  school year'), ('Progress to FE', 'Progress to FE'), ('Referred to Specialized Education', 'Referred to Specialized Education'), ('Referred to TVET', 'Referred to TVET'), ('Drop out', 'Drop out'), ('Referred to YBLN', 'Referred to YBLN')], max_length=100, null=True, verbose_name='Based on the overall score, what is the recommended learning path/outcome?'),
        ),
    ]
