# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-09 21:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0012_auto_20221222_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationrsservice',
            name='support_needed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Foreign Languages', 'Foreign Languages'), ('Arabic', 'Arabic'), ('Math', 'Math'), ('Sciences', 'Sciences')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Needed support'),
        ),
    ]
