# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-10 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0013_auto_20230109_1130'),
        ('mscc', '0013_auto_20230109_2159'),
    ]

    operations = [
    ]
