# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-17 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0014_merge_20230110_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('undertake_post_diagnostic', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent undertake any Post Diagnotic tests?')),
                ('receive_passing_grade', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent receive a passing grade for the tests?')),
                ('complete_life_skills', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent complete the life skills package?')),
                ('participate_volunteering', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent participate in any volunteering opportunity during the course of the program?')),
                ('volunteering_opportunity', models.CharField(blank=True, choices=[('', '----------'), ('Outreach', 'Outreach'), ('Data entry', 'Data entry'), ('Admin work', 'Admin work'), ('Awareness raising sessions', 'Awareness raising sessions'), ('Empowerment and leadership', 'Empowerment and leadership'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Is yes, please specify the volunteering opportunity')),
                ('benefit_innovation_course', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent benefit from any social innovation/entrepreneurship course?')),
                ('compelete_yfs_course', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent compelete the YFS course?')),
                ('training_material', models.CharField(blank=True, choices=[('', '----------'), ('Printed workbook', 'Printed workbook'), ('Tablets', 'Tablets'), ('Access to digital content (learning Passport)', 'Access to digital content (learning Passport)'), ('Other', 'Other')], max_length=50, null=True, verbose_name='What training material was provided?')),
                ('future_path', models.CharField(blank=True, choices=[('', '----------'), ('Transition to FE', 'Transition to FE'), ('Repeat the school year', 'Repeat the school year'), ('Refer to a UNICEF Youth Programme (skills tranining, CBT, GIL...)', 'Refer to a UNICEF Youth Programme (skills tranining, CBT, GIL...)'), ('Transition to TVET', 'Transition to TVET'), ('Internship or volunteering opportunity', 'Internship or volunteering opportunity')], max_length=50, null=True, verbose_name='What is the recommended future path for the adolescent?')),
                ('participate_community_initiatives', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent participate/come up in community based initiatives?')),
                ('attendance', models.CharField(blank=True, choices=[('', '----------'), ('Full attendance', 'Full attendance'), ('Absence for less than 5 days', 'Absence for less than 5 days'), ('Absence for more than 5 days', 'Absence for more than 5 days'), ('Dropout', 'Dropout')], max_length=50, null=True, verbose_name='Adolescent attendance')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mscc.Registration')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Youth Assessment',
                'verbose_name_plural': 'Youth Assessments',
            },
        ),
        migrations.AlterField(
            model_name='healthnutritionservice',
            name='development_delays_identified',
            field=models.CharField(blank=True, choices=[('Mental', 'Mental'), ('Cognitive', 'Cognitive'), ('Neurological', 'Neurological'), ('No', 'No')], max_length=50, null=True, verbose_name='Any mental , cognitive or neurological development delays is being identified?'),
        ),
    ]
