# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-18 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_auto_20221213_1620'),
        ('students', '0071_idtype_active'),
        ('mscc', '0016_registration_student_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('registration_id', models.IntegerField(blank=True, null=True)),
                ('programme_type', models.CharField(blank=True, choices=[('BLN', 'BLN'), ('Bridging', 'Bridging'), ('ABLN', 'ABLN'), ('RS', 'RS'), ('CBECE', 'CBECE'), ('Inclusion', 'Inclusion')], max_length=100, null=True, verbose_name='Dropout')),
                ('programme_id', models.IntegerField(blank=True, null=True)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='child.Child', verbose_name='Child')),
                ('student_old', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student', verbose_name='Old Student')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Education History',
                'verbose_name_plural': 'Education Histories',
            },
        ),
    ]
