# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0019_auto_20230119_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='providedservices',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='category',
            field=models.CharField(blank=True, choices=[('Education', 'Education'), ('Youth', 'Youth'), ('Health & Nutrition', 'Health & Nutrition'), ('Child Protection', 'Child Protection'), ('Social Protection', 'Social Protection')], max_length=100, null=True, verbose_name='Category'),
        ),
    ]
