# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-07 09:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0022_auto_20230220_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='mscc_packages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Early Childhood  Development', 'Early Childhood  Development'), ('Education', 'Education'), ('Child Protection/Psychosocial support', 'Child Protection/Psychosocial support'), ('Youth Empowerment and engagement', 'Youth Empowerment and engagement'), ('Health and Nutrition', 'Health and Nutrition'), ('Parental and Caregiver Support', 'Parental and Caregiver Support'), ('Social Cash Assistance', 'Social Cash Assistance')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Packages received/to be provided to child under MSCC'),
        ),
        migrations.AlterField(
            model_name='healthnutritionservice',
            name='age_eat_solid_food',
            field=models.CharField(blank=True, choices=[('', '----------'), ('0 month', '1 months'), ('1 month', '1 months'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('7 months', '7 months'), ('8 months', '8 months'), ('9 months', '9 months'), ('10 months', '10 months'), ('11 months', '11 months'), ('12 months', '12 months'), ('13 months', '13 months'), ('14 months', '14 months'), ('15 months', '15 months'), ('16 months', '16 months'), ('17 months', '17 months'), ('18 months', '18 months'), ('19 months', '19 months'), ('20 months', '20 months'), ('21 months', '21 months'), ('22 months', '22 months'), ('23 months', '23 months'), ('24 months', '24 months')], max_length=50, null=True, verbose_name='If yes, at which age ?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='cash_support_programmes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Haddi', 'Haddi'), ('Education Cash assistance', 'Education Cash assistance'), ('UNHCR cash assistance', 'UNHCR cash assistance'), ('WFP cash assistance', 'WFP cash assistance')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Cash support programmes that child is already benefiting from'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='labour_type',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Agriculture', 'Agriculture'), ('Building', 'Building'), ('Manufacturing', 'Manufacturing'), ('Retail / Store', 'Retail / Store'), ('Begging', 'Begging'), ('Mechanic shop', 'Mechanic shop'), ('Other services', 'Other services')], max_length=100, null=True, verbose_name='What is the type of work?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('99,000 LBP or less', '99,000 LBP or less'), ('From 100,000 to 299,000', 'From 100,000 to 299,000'), ('From 300,000 to 499,000', 'From 300,000 to 499,000'), ('From 500,000 and More', 'From 500,000 and More')], max_length=100, null=True, verbose_name='What is the income of the child per week?'),
        ),
    ]
