# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-03 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0023_auto_20230303_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthnutritionservice',
            name='development_delays_identified',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Social/Emotional', 'Social/Emotional'), ('Language/Communication', 'Language/Communication'), ('Cognitive (learning thinking, problem solving)', 'Cognitive (learning thinking, problem solving)'), ('Movement/Physical development', 'Movement/Physical development')], max_length=50, null=True, verbose_name='Any delays in the development milestones  is being identified? (please to check the Integrated ECD milestones Cards based on the age of the child)'),
        ),
    ]
