# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0024_auto_20230303_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthnutritionservice',
            name='development_delays_identified',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Social/Emotional', 'Social/Emotional'), ('Language/Communication', 'Language/Communication'), ('Cognitive (learning thinking, problem solving)', 'Cognitive (learning thinking, problem solving)'), ('Movement/Physical development', 'Movement/Physical development')], max_length=100, null=True, verbose_name='Any delays in the development milestones  is being identified? (please to check the Integrated ECD milestones Cards based on the age of the child)'),
        ),
        migrations.AlterField(
            model_name='healthnutritionservice',
            name='muac_malnutrition_screening',
            field=models.CharField(blank=True, choices=[('', '----------'), ('MAM (MUAC >11.5 and <12.5 cm)', 'MAM (MUAC >11.5 and <12.5 cm)'), ('SAM (MUAC <11.5 cm)', 'SAM (MUAC <11.5 cm)'), ('SAM with Bilateral pitting oedema  (both feet puffy)', 'SAM with Bilateral pitting oedema  (both feet puffy)'), ('At risk of malnutrition (MUAC 12.5-13.5 cm)', 'At risk of malnutrition (MUAC 12.5-13.5 cm)')], max_length=100, null=True, verbose_name='MUAC malnutrition screening '),
        ),
    ]
