# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-14 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0027_auto_20230307_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupservice',
            name='caregiver_visit_number',
        ),
        migrations.RemoveField(
            model_name='followupservice',
            name='house_visit_number',
        ),
        migrations.RemoveField(
            model_name='followupservice',
            name='phone_call_number',
        ),
        migrations.AddField(
            model_name='followupservice',
            name='follow_up_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number'),
        ),
    ]
