# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-15 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0028_auto_20230314_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalservice',
            name='akelius_access',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Class', 'Class'), ('Home', 'Home'), ('Class & Home', 'Class & Home')], max_length=250, null=True, verbose_name='Access during'),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='akelius_change_learning',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Very Likely', 'Very Likely'), ('Likely', 'Likely'), ('Neutral', 'Neutral'), ('Not really', 'Not really')], max_length=250, null=True, verbose_name='As a teacher, are you noticing a change in attitude towards learning'),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='akelius_change_literacy',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Very Likely', 'Very Likely'), ('Likely', 'Likely'), ('Neutral', 'Neutral'), ('Not really', 'Not really')], max_length=250, null=True, verbose_name='As a teacher, are you noticing a change in motivation & output about Literacy'),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='akelius_change_math',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Very Likely', 'Very Likely'), ('Likely', 'Likely'), ('Neutral', 'Neutral'), ('Not really', 'Not really')], max_length=250, null=True, verbose_name='As a teacher, are you noticing a change in motivation & output about Math'),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='akelius_child_equipped',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally')], max_length=50, null=True, verbose_name='Is the child equipped at home to access the platforms (Based on Child and parents confirmation)'),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='akelius_sessions_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of sessions per week'),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='lp_access',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Class', 'Class'), ('Home', 'Home'), ('Class & Home', 'Class & Home')], max_length=250, null=True, verbose_name='Access during'),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='lp_change_learning',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Very Likely', 'Very Likely'), ('Likely', 'Likely'), ('Neutral', 'Neutral'), ('Not really', 'Not really')], max_length=250, null=True, verbose_name='As a teacher, are you noticing a change in attitude towards learning'),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='lp_change_literacy',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Very Likely', 'Very Likely'), ('Likely', 'Likely'), ('Neutral', 'Neutral'), ('Not really', 'Not really')], max_length=250, null=True, verbose_name='As a teacher, are you noticing a change in motivation & output about Literacy'),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='lp_change_math',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Very Likely', 'Very Likely'), ('Likely', 'Likely'), ('Neutral', 'Neutral'), ('Not really', 'Not really')], max_length=250, null=True, verbose_name='As a teacher, are you noticing a change in motivation & output about Math'),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='lp_child_equipped',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No'), ('Occasionally', 'Occasionally')], max_length=50, null=True, verbose_name='Is the child equipped at home to access the platforms (Based on Child and parents confirmation)'),
        ),
        migrations.AddField(
            model_name='digitalservice',
            name='lp_sessions_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of sessions per week'),
        ),
    ]
