# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0029_auto_20230315_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthNutritionReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Referred_development_delays', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Was the child Referred for any observed developmental delays as per the milestones cards to?')),
                ('development_delays', models.CharField(blank=True, choices=[('', '----------'), ('Primary Health care center', 'Primary Health care center'), ('Dispensary', 'Dispensary'), ('Hospital', 'Hospital'), ('Private clinic', 'Private clinic'), ('Organization', 'Organization')], max_length=100, null=True, verbose_name='if yes, please select')),
                ('referred_malnutrition', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Was the child Referred for malnutrition treatment center?')),
                ('malnutrition_treatment_center', models.CharField(blank=True, choices=[('', '----------'), ('MAM', 'MAM'), ('SAM', 'SAM'), ('At Risk of Malnutrition', 'At Risk of Malnutrition'), ('To Supplementary Feeding PHCC', 'To Supplementary Feeding PHCC'), ('To Treatment Center/ PHCC', 'To Treatment Center/ PHCC'), ('To Hospital', 'To Hospital'), ('To Organization', 'To Organization')], max_length=100, null=True, verbose_name='if yes, please select')),
                ('referred_anc_pnc', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Was a Pregnant lactating women/child with challenges on breastfeeding reffered to IYCF specialists?')),
                ('phc_center', models.TextField(blank=True, null=True, verbose_name='If yes (please add name of organization referred tor)')),
                ('referred_iycf', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Was a Children aged 6months to 59months with challenges on infant and young child feeding practice refeered to IYCF specialists and to receive Micronutrient supplements?')),
                ('iycf_organization', models.TextField(blank=True, null=True, verbose_name='If yes (please add name of organization referred tor)')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mscc.Registration')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Health & Nutrition Service',
                'verbose_name_plural': 'Health & Nutrition Services',
            },
        ),
    ]
