# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0030_healthnutritionreferral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthnutritionreferral',
            old_name='referred_iycf',
            new_name='infant_child_referred_iycf',
        ),
        migrations.RenameField(
            model_name='healthnutritionreferral',
            old_name='iycf_organization',
            new_name='women_child_referred_organization',
        ),
        migrations.AddField(
            model_name='healthnutritionreferral',
            name='infant_child_referred_organization',
            field=models.TextField(blank=True, null=True, verbose_name='If yes (please add name of organization referred to)'),
        ),
        migrations.AddField(
            model_name='healthnutritionreferral',
            name='women_child_referred_iycf',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Was a Pregnant lactating women/child with challenges on breastfeeding referred to IYCF specialists?'),
        ),
        migrations.AlterField(
            model_name='healthnutritionreferral',
            name='phc_center',
            field=models.TextField(blank=True, null=True, verbose_name='If yes (please add name the PHC center)'),
        ),
        migrations.AlterField(
            model_name='healthnutritionreferral',
            name='referred_anc_pnc',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Was a Pregnant lactating women/child referred  for ANC and PNC follow up  and to receive MMS (multivitamins) to PHC?'),
        ),
    ]
