# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-16 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0031_auto_20230316_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthnutritionreferral',
            options={'ordering': ['id'], 'verbose_name': 'Health & Nutrition Referral', 'verbose_name_plural': 'Health & Nutrition Referrals'},
        ),
    ]
