# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-16 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0032_auto_20230316_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthnutritionreferral',
            old_name='Referred_development_delays',
            new_name='referred_development_delays',
        ),
    ]
