# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0033_auto_20230316_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthnutritionservice',
            name='attended_health_nutrition_session',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Children attended health and nutrition session'),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='caregiver_counselling',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Did the caregiver receive one on one counselling?'),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='caregiver_ecd_counselling',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Did the caregiver attended ECD group counselling?'),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='child_immunization_screened',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Was the child immunization record screened'),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='child_malnutrition_screening',
            field=models.CharField(blank=True, choices=[('', '----------'), ('MAM (MUAC >11.5 and <12.5 cm)', 'MAM (MUAC >11.5 and <12.5 cm)'), ('SAM (MUAC <11.5 cm)', 'SAM (MUAC <11.5 cm)'), ('SAM with Bilateral pitting oedema  (both feet puffy)', 'SAM with Bilateral pitting oedema  (both feet puffy)'), ('At risk of malnutrition (MUAC 12.5-13.5 cm)', 'At risk of malnutrition (MUAC 12.5-13.5 cm)')], max_length=10, null=True, verbose_name='MUAC malnutrition screening '),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='child_screened_malnutrition',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Was the child screened for malnutrition using MUAC tapes?'),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='counselling_date',
            field=models.DateField(blank=True, null=True, verbose_name='If yes (please provide session date)'),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='ecd_counselling_date',
            field=models.DateField(blank=True, null=True, verbose_name='If yes (please provide session date)'),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='health_nutrition_session_date',
            field=models.DateField(blank=True, null=True, verbose_name='if yes to write the date of the session'),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='health_nutrition_session_title',
            field=models.TextField(blank=True, null=True, verbose_name='if yes to write the title of the session'),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='missing_vaccine',
            field=models.TextField(blank=True, null=True, verbose_name='if yes (please mention if any vaccine is missing)'),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='next_counselling_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Next session'),
        ),
        migrations.AddField(
            model_name='healthnutritionservice',
            name='next_ecd_counselling_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Next session'),
        ),
    ]
