# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0034_auto_20230320_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthnutritionservice',
            name='child_malnutrition_screening',
            field=models.CharField(blank=True, choices=[('', '----------'), ('MAM (MUAC >11.5 and <12.5 cm)', 'MAM (MUAC >11.5 and <12.5 cm)'), ('SAM (MUAC <11.5 cm)', 'SAM (MUAC <11.5 cm)'), ('SAM with Bilateral pitting oedema  (both feet puffy)', 'SAM with Bilateral pitting oedema  (both feet puffy)'), ('At risk of malnutrition (MUAC 12.5-13.5 cm)', 'At risk of malnutrition (MUAC 12.5-13.5 cm)')], max_length=100, null=True, verbose_name='MUAC malnutrition screening '),
        ),
    ]
