# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-24 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0035_auto_20230320_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationservice',
            name='education_program',
            field=models.CharField(blank=True, choices=[('', '----------'), ('BLN Level 1', 'BLN Level 1'), ('BLN Level 2', 'BLN Level 2'), ('BLN Level 2', 'BLN Level 3'), ('ABLN Level 1', 'ABLN Level 1'), ('ABLN Level 2', 'ABLN Level 2'), ('YBLN', 'YBLN'), ('YFNL', 'YFNL'), ('CBECE Level 1', 'CBECE Level 1'), ('CBECE Level 2', 'CBECE Level 2'), ('CBECE Level 3', 'CBECE Level 3'), ('RS Grade 7', 'RS Grade 7'), ('RS Grade 8', 'RS Grade 8'), ('RS Grade 9', 'RS Grade 9')], max_length=200, null=True, verbose_name='Education Program'),
        ),
        migrations.AlterField(
            model_name='educationservice',
            name='education_status',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Never registered in any formal school before', 'Never registered in any formal school before'), ("Was registered in formal school but didn't continue", "Was registered in formal school but didn't continue"), ('Was registered in non formal program and was referred to MSCC', 'Was registered in non formal program and was referred to MSCC'), ("Was registered in non formal program but didn't continue", "Was registered in non formal program but didn't continue"), ('Was enrolled in TVET Programs', 'Was enrolled in TVET Programs'), ('Wad Registered in Formal Education but not attending', 'Was Registered in Formal Education but not attending'), ('No', 'No')], max_length=200, null=True, verbose_name="Child's educational level when registering for the round"),
        ),
    ]
