# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-24 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0036_auto_20230324_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationprogrammeassessment',
            name='programme_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Education Programme Type'),
        ),
    ]
