# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0038_auto_20230327_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('refer_tvet', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the partner refer youth who are above 18 to the TVET centers')),
                ('refer_innovation', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the partner refer youth who are above 18 to the  innovation hubs GIL?')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mscc.Registration')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Youth Referral',
                'verbose_name_plural': 'Youth Referrals',
            },
        ),
    ]
