# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-04 10:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0039_youthreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogrammeassessment',
            name='school_test',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youthassessment',
            name='compelete_yfs_course',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Did the adolescent complete the YFS course?'),
        ),
    ]
