# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-04 14:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0041_auto_20230504_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recreational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('assessment', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mscc.Registration')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Recreational',
                'verbose_name_plural': 'Recreational',
            },
        ),
    ]
