# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-11 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0044_auto_20230509_2252'),
        ('mscc', '0043_auto_20230509_1608'),
    ]

    operations = [
    ]
