# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-16 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0045_merge_20230511_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationservice',
            name='education_status',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Never registered in any formal school before', 'Never registered in any formal school before'), ("Was registered in formal school but didn't continue", "Was registered in formal school but didn't continue"), ('Was registered in non formal program and was referred to MSCC', 'Was registered in non formal program and was referred to MSCC'), ("Was registered in non formal program but didn't continue", "Was registered in non formal program but didn't continue"), ('Was enrolled in TVET Programs', 'Was enrolled in TVET Programs'), ('Was Registered in Formal Education but not attending', 'Was Registered in Formal Education but not attending'), ('No', 'No')], max_length=200, null=True, verbose_name="Child's educational level when registering for the round"),
        ),
    ]
