# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-02 11:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0046_auto_20230516_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='labour_condition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('', '----------'), ('Carry heavy loads', 'Carry heavy loads'), ('Works in extreme cold, heat or humidity', 'Works in extreme cold, heat or humidity'), ('Exposed to dust, fume or gas', 'Exposed to dust, fume or gas'), ('Maneuvers dangerous tools such as knives or operating heavy machinery', 'Maneuvers dangerous tools such as knives or operating heavy machinery'), ('Required to work with chemicals, such as pesticides, glues and similar, or explosives', 'Required to work with chemicals, such as pesticides, glues and similar, or explosives')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='What is the work condition that the child is exposed to'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='have_labour',
            field=models.CharField(blank=True, choices=[('', '----------'), ('No', 'No'), ('Yes - Morning', 'Yes - Morning'), ('Yes - Afternoon', 'Yes - Afternoon'), ('Yes - Full Day', 'Yes - Full day'), ('Yes - Night Shift', 'Yes - Night Shift'), ('Yes - Morning & Night Shift', 'Yes - Morning & Night Shift'), ('Yes - Afternoon & Night Shift', 'Yes - Afternoon & Night Shift'), ('Yes - Full Day & Night Shift', 'Yes - Full Day & Night Shift')], max_length=100, null=True, verbose_name='Does the child participate in work?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='labour_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of working hours/week '),
        ),
        migrations.AlterField(
            model_name='registration',
            name='labour_type',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Agriculture', 'Agriculture'), ('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Retail / Store', 'Retail / Store'), ('Street Connected Work - includes vending and begging', 'Street Connected Work - includes vending and begging'), ('Household chores (includes domestic works and caring for siblings or their caregivers)', 'Household chores (includes domestic works and caring for siblings or their caregivers)'), ('Mechanic shop', 'Mechanic shop'), ('Other services', 'Other services')], max_length=100, null=True, verbose_name='What is the type of work?'),
        ),
    ]
