# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-02 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0047_auto_20230602_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='labour_hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of working hours/week '),
        ),
    ]
