# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-06 14:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0048_auto_20230602_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='labour_condition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Carry heavy loads', 'Carry heavy loads'), ('Works in extreme cold, heat or humidity', 'Works in extreme cold, heat or humidity'), ('Exposed to dust, fume or gas', 'Exposed to dust, fume or gas'), ('Maneuvers dangerous tools such as knives or operating heavy machinery', 'Maneuvers dangerous tools such as knives or operating heavy machinery'), ('Required to work with chemicals, such as pesticides, glues and similar, or explosives', 'Required to work with chemicals, such as pesticides, glues and similar, or explosives')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='What is the work condition that the child is exposed to?'),
        ),
    ]
