# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0049_auto_20230606_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationservice',
            name='class_section',
            field=models.CharField(blank=True, choices=[('', '----------'), ('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f')], max_length=50, null=True, verbose_name='Class Section'),
        ),
    ]
