# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-22 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0050_educationservice_class_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationservice',
            name='class_section',
            field=models.CharField(blank=True, choices=[('', '----------'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=50, null=True, verbose_name='Class Section'),
        ),
    ]
