# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-23 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0052_auto_20230623_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='labour_weekly_income',
            field=models.CharField(blank=True, choices=[('', '----------'), ('5 USD or Less', '5 USD or Less'), ('5-20 USD', '5-20 USD'), ('20-50 USD', '20-50 USD'), ('50-100 USD', '50-100 USD'), ('More than 100 USD', 'More than 100 USD')], max_length=100, null=True, verbose_name='What is the income of the child per week?'),
        ),
    ]
