# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-30 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0053_auto_20230623_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupservice',
            name='pfss_sessions',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Did they undertake FPSS sessions'),
        ),
        migrations.AddField(
            model_name='followupservice',
            name='pfss_sessions_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number number of sessions'),
        ),
        migrations.AddField(
            model_name='pssservice',
            name='child_know_seek_help',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Does the child know where to seek help or support in case he is exposed to violence, abuse, or exploitation?'),
        ),
        migrations.AddField(
            model_name='pssservice',
            name='child_protection_concern',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Nightmares', 'Nightmares'), ('Regressions', 'Regressions'), ('Distress', 'Distress'), ('Suicidal ideation', 'Suicidal ideation'), ('Bedwetting', 'Bedwetting'), ('Anger issues', 'Anger issues'), ('Isolation', 'Isolation')], max_length=100, null=True, verbose_name='Does the facilitator identify any child protection concern or has the caregiver expressed any of the below signs on their children?'),
        ),
        migrations.AddField(
            model_name='registration',
            name='partner_unique_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Partner unique child number'),
        ),
    ]
