# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-08-17 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0056_auto_20230808_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationservice',
            name='class_section',
            field=models.CharField(blank=True, choices=[('', '----------'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M')], max_length=50, null=True, verbose_name='Class Section'),
        ),
        migrations.AlterField(
            model_name='educationservice',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_service', to='mscc.Registration'),
        ),
    ]
