# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-09-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0058_auto_20230825_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='recommended_learning_path',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Transition to Dirasa', 'Transition to Dirasa'), ('Repeat same level in next  school year', 'Repeat same level in next  school year'), ('Progress to FE', 'Progress to FE'), ('Referred to Specialized Education', 'Referred to Specialized Education'), ('Referred to TVET', 'Referred to TVET'), ('Drop out', 'Drop out'), ('Referred to YBLN', 'Referred to YBLN'), ('Referred to CBECE Higher Level in next school year', 'Referred to CBECE Higher Level in next school year')], max_length=100, null=True, verbose_name='Based on the overall score, what is the recommended learning path/outcome?'),
        ),
    ]
