# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-10-03 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0059_auto_20230920_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationservice',
            name='class_section',
            field=models.CharField(blank=True, choices=[('', '----------'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=50, null=True, verbose_name='Class Section'),
        ),
    ]
