# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-01-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0060_auto_20231003_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('current_year', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Round',
            },
        ),
        migrations.AddField(
            model_name='educationservice',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mscc.Round', verbose_name='Round'),
        ),
        migrations.AddField(
            model_name='registration',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mscc.Round', verbose_name='Round'),
        ),
    ]
