# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-03-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0062_auto_20240118_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationservice',
            name='education_program',
            field=models.CharField(blank=True, choices=[('', '----------'), ('BLN Level 1', 'BLN Level 1'), ('BLN Level 2', 'BLN Level 2'), ('BLN Level 3', 'BLN Level 3'), ('ABLN Level 1', 'ABLN Level 1'), ('ABLN Level 2', 'ABLN Level 2'), ('YBLN Level 1', 'YBLN Level 1'), ('YBLN Level 2', 'YBLN Level 2'), ('YFS Level 1', 'YFS Level 1'), ('YFS Level 2', 'YFS Level 2'), ('CBECE Level 1', 'CBECE Level 1'), ('CBECE Level 2', 'CBECE Level 2'), ('CBECE Level 3', 'CBECE Level 3'), ('RS Grade 7', 'RS Grade 7'), ('RS Grade 8', 'RS Grade 8'), ('RS Grade 9', 'RS Grade 9'), ('ECD', 'ECD')], max_length=200, null=True, verbose_name='Education Program'),
        ),
        migrations.AlterField(
            model_name='healthnutritionservice',
            name='child_malnutrition_screening',
            field=models.CharField(blank=True, choices=[('', '----------'), ('No malnutrition screening', 'No malnutrition screening'), ('MAM (MUAC >11.5 and <12.5 cm)', 'MAM (MUAC >11.5 and <12.5 cm)'), ('SAM (MUAC <11.5 cm)', 'SAM (MUAC <11.5 cm)'), ('SAM with Bilateral pitting oedema  (both feet puffy)', 'SAM with Bilateral pitting oedema  (both feet puffy)'), ('At risk of malnutrition (MUAC 12.5-13.5 cm)', 'At risk of malnutrition (MUAC 12.5-13.5 cm)')], max_length=100, null=True, verbose_name='MUAC malnutrition screening '),
        ),
        migrations.AlterField(
            model_name='healthnutritionservice',
            name='muac_malnutrition_screening',
            field=models.CharField(blank=True, choices=[('', '----------'), ('No malnutrition screening', 'No malnutrition screening'), ('MAM (MUAC >11.5 and <12.5 cm)', 'MAM (MUAC >11.5 and <12.5 cm)'), ('SAM (MUAC <11.5 cm)', 'SAM (MUAC <11.5 cm)'), ('SAM with Bilateral pitting oedema  (both feet puffy)', 'SAM with Bilateral pitting oedema  (both feet puffy)'), ('At risk of malnutrition (MUAC 12.5-13.5 cm)', 'At risk of malnutrition (MUAC 12.5-13.5 cm)')], max_length=100, null=True, verbose_name='MUAC malnutrition screening '),
        ),
    ]
