# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-05-21 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0066_auto_20240502_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthkitservice',
            name='youth_trained_mental_health',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Is the youth trained on Mental health?'),
        ),
    ]
