# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-07-22 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0067_youthkitservice_youth_trained_mental_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='dropout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
