# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-08-27 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0068_referral_dropout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='export',
            field=models.BooleanField(default=False),
        ),
    ]
