# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-01-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0071_auto_20241212_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthnutritionservice',
            name='development_delays_identified',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Social/Emotional', 'Social/Emotional'), ('Language/Communication', 'Language/Communication'), ('Cognitive (learning thinking, problem solving)', 'Cognitive (learning thinking, problem solving)'), ('Movement/Physical development', 'Movement/Physical development'), ('No', 'No')], max_length=100, null=True, verbose_name='Any delays in the development milestones  is being identified? (please to check the Integrated ECD milestones Cards based on the age of the child)'),
        ),
    ]
