# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-05-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0074_auto_20250408_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='lego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('participating_lego_sessions', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Is the child participating in CBPSS LEGO sessions?')),
                ('participating_education_sessions', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Is the child participating in Education sessions supported by LEGO activities?')),
                ('participating_lego_play_sessions', models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True, verbose_name='Is the child participating in LEGO free-play sessions?')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mscc.Registration')),
            ],
            options={
                'verbose_name': 'LEGO',
                'ordering': ['id'],
                'verbose_name_plural': 'LEGO',
            },
        ),
    ]
