# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-07-03 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0079_auto_20250702_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationservice',
            name='catch_up_registered',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes-New Comers programme', 'Yes-New Comers programme'), ('Yes-Undocumented programme', 'Yes-Undocumented programme')], max_length=200, null=True, verbose_name='Is the child registered in catch-up program'),
        ),
    ]
