# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-09-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0080_auto_20250703_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pssservice',
            name='child_out_school_reasons',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Fear of bullying, discrimination or violence at school or on the way to school', 'Fear of bullying, discrimination or violence at school or on the way to school'), ('The child needs to work', 'The child needs to work'), ('The child needs to stay at home to support the family with chores', 'The child needs to stay at home to support the family with chores'), ('Disability', 'Disability'), ('N/A', 'N/A')], max_length=250, null=True, verbose_name='Reasons for a child being out of school'),
        ),
    ]
