# Generated by Django 5.2.3 on 2026-03-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0087_serviceprogramoption_is_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationservice',
            name='education_status',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Never registered in any formal school before', 'Never registered in any formal school before'), ("Was registered in formal school but didn't continue", "Was registered in formal school but didn't continue"), ('Was registered in non formal program and was referred to MSCC', 'Was registered in non formal program and was referred to MSCC'), ("Was registered in non formal program but didn't continue", "Was registered in non formal program but didn't continue"), ('Was enrolled in TVET Programs', 'Was enrolled in TVET Programs'), ('Was Registered in Formal Education but not attending', 'Was Registered in Formal Education but not attending'), ('Currently registered in Formal Education school', 'Currently registered in Formal Education school'), ('Currently registered in Formal Education school but not attending', 'Currently registered in Formal Education school but not attending'), ('Internally Displaced, was enrolled in FE before the conflict', 'Internally Displaced, was enrolled in FE before the conflict'), ('Internally Displaced, was enrolled in NFE before the conflict', 'Internally Displaced, was enrolled in NFE before the conflict'), ('Internally Displaced, out of school (never been engaged in any type of learning)', 'Internally Displaced, out of school (never been engaged in any type of learning)'), ('No', 'No')], max_length=200, null=True, verbose_name="Child's educational level when registering for the round"),
        ),
    ]
