# Generated by Django 5.2.3 on 2026-04-14 15:39

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0088_alter_educationservice_education_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProgrammeWLAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pre_test', models.JSONField(default=dict)),
                ('post_test', models.JSONField(default=dict)),
                ('programme_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Education Programme Type')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mscc.registration')),
            ],
            options={
                'verbose_name': 'WL BLN Assessment',
                'verbose_name_plural': 'WL BLN  Assessments',
                'ordering': ['id'],
            },
        ),
    ]
