# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_enrollment_last_informal_edu_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_school_type',
            field=models.CharField(blank=True, choices=[('out_the_country', 'Out of the country'), ('public_in_country', 'Public in the country'), ('private_in_country', 'Private in the country')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_result',
            field=models.CharField(blank=True, choices=[('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_year_result',
            field=models.CharField(blank=True, choices=[('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='result',
            field=models.CharField(blank=True, choices=[('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629')], max_length=50, null=True),
        ),
    ]
