# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-10 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_auto_20161027_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
