# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0009_auto_20170226_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='last_school_shift',
            field=models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second')], max_length=50, null=True),
        ),
    ]
