# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_alprefermatrix_age'),
        ('enrollments', '0011_auto_20170228_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrollments.Enrollment')),
                ('enrolment2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrollments.Enrollment')),
                ('school1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School')),
                ('school2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Student move',
            },
        ),
    ]
