# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-16 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_educationyear'),
        ('students', '0021_idtype_inuse'),
        ('enrollments', '0014_auto_20170319_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingStudentMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrollments.Enrollment', verbose_name='Enrollment')),
                ('school_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='From school')),
                ('school_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='To school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student', verbose_name='Student')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Student moves logs',
            },
        ),
    ]
