# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-19 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0015_loggingstudentmove'),
        ('enrollments', '0015_auto_20170418_1655'),
    ]

    operations = [
    ]
