# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20170419_1619'),
        ('enrollments', '0016_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear'),
        ),
    ]
