# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0022_auto_20170528_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_artistic',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='\u0627\u0644\u0645\u062c\u0627\u0644 \u0627\u0644\u0641\u0646\u064a'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_language',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='\u0644\u063a\u0629 \u0627\u062c\u0646\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_linguistic',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='\u0627\u0644\u0645\u062c\u0627\u0644 \u0627\u0644\u0644\u063a\u0648\u064a'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_mathematics',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='\u0627\u0644\u0645\u062c\u0627\u0644 \u0627\u0644\u0639\u0644\u0645\u064a/\u0631\u064a\u0627\u0636\u064a\u0627\u062a'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_physical',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='\u0645\u062c\u0627\u0644 \u0627\u0644\u0631\u064a\u0627\u0636\u0629 \u0627\u0644\u0628\u062f\u0646\u064a\u0629 \u0648\u0627\u0644\u062c\u0633\u062f\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_sciences',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='\u0627\u0644\u0645\u062c\u0627\u0644 \u0627\u0644\u0639\u0644\u0645\u064a/\u0639\u0644\u0648\u0645'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_sociology',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='\u0627\u0644\u0645\u062c\u0627\u0644 \u0627\u0644\u0627\u062c\u062a\u0645\u0627\u0639\u064a'),
        ),
    ]
