# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-29 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0025_auto_20170529_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_linguistic_ar',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='\u0627\u0644\u0645\u062c\u0627\u0644 \u0627\u0644\u0644\u063a\u0648\u064a/\u0639\u0631\u0628\u064a'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_linguistic_en',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='\u0627\u0644\u0645\u062c\u0627\u0644 \u0627\u0644\u063a\u0648\u064a/\u0644\u063a\u0629 \u0627\u062c\u0646\u0628\u064a\u0629'),
        ),
    ]
