# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-31 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0026_auto_20170529_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='exam_total',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0627\u0644\u0639\u0644\u0627\u0645\u0629 \u0627\u0644\u0646\u0647\u0627\u0626\u064a\u0629'),
        ),
    ]
