# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0027_auto_20170531_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result',
            field=models.CharField(blank=True, choices=[('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629'), ('uncompleted', '\u0627\u0643\u0645\u0627\u0644')], max_length=50, null=True, verbose_name='\u0648\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
    ]
