# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-08 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0028_auto_20170607_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='relation_to_adult',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='year',
        ),
    ]
