# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-22 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0029_auto_20170708_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='outreach_barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
