# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-28 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0031_enrollment_student_outreached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student_outreached',
            field=models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True),
        ),
    ]
