# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-01 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0032_auto_20170728_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='have_barcode',
            field=models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='old_or_new',
            field=models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
