# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0036_auto_20170809_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='exam_result_arabic_cmplt',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Arabic Term 2'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_result_final',
            field=models.CharField(blank=True, choices=[('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629'), ('uncompleted', '\u0627\u0643\u0645\u0627\u0644')], max_length=50, null=True, verbose_name='Final Student status'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_result_language_cmplt',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Foreign language Term 2'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_result_math_cmplt',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Arabic Term 2'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='exam_total_cmplt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Grade Term 2'),
        ),
    ]
