# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0038_auto_20170904_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629'), ('uncompleted', '\u0627\u0643\u0645\u0627\u0644')], max_length=50, null=True, verbose_name='\u0648\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_final',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629'), ('uncompleted', '\u0627\u0643\u0645\u0627\u0644')], max_length=50, null=True, verbose_name='Final Student status'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_school_shift',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('first', '\u062f\u0648\u0627\u0645 \u0635\u0628\u0627\u062d\u064a'), ('second', '\u062f\u0648\u0627\u0645 \u0628\u0639\u062f \u0627\u0644\u0638\u0647\u0631'), ('alp', 'ALP')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_school_type',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('out_the_country', '\u0645\u062f\u0631\u0633\u0629 \u062e\u0627\u0631\u062c \u0644\u0628\u0646\u0627\u0646'), ('public_in_country', '\u0645\u062f\u0631\u0633\u0629 \u0631\u0633\u0645\u064a\u0629 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('private_in_country', '\u0645\u062f\u0631\u0633\u0629 \u062e\u0627\u0635\u0629 \u0641\u064a \u0644\u0628\u0646\u0627\u0646')], max_length=50, null=True),
        ),
    ]
