# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0039_auto_20170913_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_result',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_year_result',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='participated_in_alp',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='result',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629')], max_length=50, null=True),
        ),
    ]
