# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_merge_20170913_2010'),
        ('schools', '0023_auto_20170913_1241'),
        ('enrollments', '0040_auto_20170913_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingProgramMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='From school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student', verbose_name='Student')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Student moves from ALP',
                'verbose_name_plural': 'Student moves from ALP',
            },
        ),
    ]
