# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0041_loggingprogrammove'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingprogrammove',
            name='eligibility',
            field=models.BooleanField(default=True),
        ),
    ]
