# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_auto_20170913_1241'),
        ('enrollments', '0042_loggingprogrammove_eligibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggingprogrammove',
            old_name='school',
            new_name='school_from',
        ),
        migrations.AddField(
            model_name='loggingprogrammove',
            name='school_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='To school'),
        ),
    ]
