# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-15 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0043_auto_20170914_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_math_cmplt',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Math Term 2'),
        ),
    ]
