# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0047_auto_20170915_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_language',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Foreign Language'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_language_cmplt',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Foreign Language'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name=' \u0623\u0639\u0644\u0649 \u0645\u0633\u062a\u0648\u0649 \u062a\u0639\u0644\u064a\u0645 \u0648\u0635\u0644 \u0625\u0644\u064a\u0647 \u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_education_year',
            field=models.CharField(blank=True, choices=[('2000/2001', '2000/2001'), ('2001/2002', '2001/2002'), ('2002/2003', '2002/2003'), ('2003/2004', '2003/2004'), ('2004/2005', '2004/2005'), ('2005/2006', '2005/2006'), ('2006/2007', '2006/2007'), ('2007/2008', '2007/2008'), ('2008/2009', '2008/2009'), ('2009/2010', '2009/2010'), ('2010/2011', '2010/2011'), ('2011/2012', '2011/2012'), ('2012/2013', '2012/2013'), ('2013/2014', '2013/2014'), ('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('n/a', 'N/A')], max_length=10, null=True, verbose_name=' \u0622\u062e\u0631 \u0633\u0646\u0629 \u062f\u0631\u0627\u0633\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_final_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassLevel', verbose_name='\u0645\u0639\u0644\u0648\u0645\u0627\u062a \u0633\u0627\u0628\u0642\u0629 \u0644\u0644\u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a \u0644\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel', verbose_name=' \u0623\u0639\u0644\u0649 \u0645\u0633\u062a\u0648\u0649 \u062a\u0639\u0644\u064a\u0645 \u0648\u0635\u0644 \u0625\u0644\u064a\u0647 \u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_result',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629')], max_length=50, null=True, verbose_name='\u0645\u0639\u0644\u0648\u0645\u0627\u062a \u0633\u0627\u0628\u0642\u0629 \u0644\u0644\u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a \u0644\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alp.ALPRound', verbose_name='\u0645\u0639\u0644\u0648\u0645\u0627\u062a \u0633\u0627\u0628\u0642\u0629 \u0644\u0644\u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a \u0644\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_year',
            field=models.CharField(blank=True, choices=[('2000/2001', '2000/2001'), ('2001/2002', '2001/2002'), ('2002/2003', '2002/2003'), ('2003/2004', '2003/2004'), ('2004/2005', '2004/2005'), ('2005/2006', '2005/2006'), ('2006/2007', '2006/2007'), ('2007/2008', '2007/2008'), ('2008/2009', '2008/2009'), ('2009/2010', '2009/2010'), ('2010/2011', '2010/2011'), ('2011/2012', '2011/2012'), ('2012/2013', '2012/2013'), ('2013/2014', '2013/2014'), ('2014/2015', '2014/2015'), ('2015/2016', '2015/2016')], max_length=10, null=True, verbose_name='\u0645\u0639\u0644\u0648\u0645\u0627\u062a \u0633\u0627\u0628\u0642\u0629 \u0644\u0644\u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a \u0644\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='Last school'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_school_shift',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('first', '\u062f\u0648\u0627\u0645 \u0635\u0628\u0627\u062d\u064a'), ('second', '\u062f\u0648\u0627\u0645 \u0628\u0639\u062f \u0627\u0644\u0638\u0647\u0631'), ('alp', 'ALP')], max_length=50, null=True, verbose_name='Last school shift'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_school_type',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('out_the_country', '\u0645\u062f\u0631\u0633\u0629 \u062e\u0627\u0631\u062c \u0644\u0628\u0646\u0627\u0646'), ('public_in_country', '\u0645\u062f\u0631\u0633\u0629 \u0631\u0633\u0645\u064a\u0629 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('private_in_country', '\u0645\u062f\u0631\u0633\u0629 \u062e\u0627\u0635\u0629 \u0641\u064a \u0644\u0628\u0646\u0627\u0646')], max_length=50, null=True, verbose_name='Last school type'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_year_result',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629')], max_length=50, null=True, verbose_name='\u0622\u062e\u0631 \u0646\u062a\u064a\u062c\u0629 \u062d\u0635\u0644 \u0639\u0644\u064a\u0647\u0627 '),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='participated_in_alp',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u0627\u0646\u062a\u0633\u0628 \u0645\u0646 \u0642\u0628\u0644 \u0627\u0644\u0649 \u0628\u0631\u0646\u0627\u0645\u062c ALP'),
        ),
        migrations.AlterField(
            model_name='loggingstudentmove',
            name='enrolment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrollments.Enrollment', verbose_name='\u0627\u0644\u062a\u0633\u062c\u064a\u0644'),
        ),
        migrations.AlterField(
            model_name='loggingstudentmove',
            name='school_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='\u0627\u0644\u0649 \u0645\u062f\u0631\u0633\u0629 '),
        ),
        migrations.AlterField(
            model_name='loggingstudentmove',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student', verbose_name='\u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
    ]
