# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0052_auto_20171002_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='\u062d\u0630\u0641'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='dropout_status',
            field=models.BooleanField(default=False, verbose_name='\u0648\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_language',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='\u0644\u063a\u0629 \u0627\u062c\u0646\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_language_cmplt',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='\u0644\u063a\u0629 \u0627\u062c\u0646\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='have_barcode',
            field=models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u0644\u062f\u064a\u0629 \u0627\u0644\u0628\u0627\u0631\u0643\u0648\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='\u0627\u0644\u0645\u062f\u0631\u0633\u0629 \u0627\u0644\u0633\u0627\u0628\u0642\u0629'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_school_shift',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('first', '\u062f\u0648\u0627\u0645 \u0635\u0628\u0627\u062d\u064a'), ('second', '\u062f\u0648\u0627\u0645 \u0628\u0639\u062f \u0627\u0644\u0638\u0647\u0631'), ('alp', 'ALP')], max_length=50, null=True, verbose_name='\u062f\u0648\u0627\u0645 \u0627\u0644\u0645\u062f\u0631\u0633\u0629'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_school_type',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('out_the_country', '\u0645\u062f\u0631\u0633\u0629 \u062e\u0627\u0631\u062c \u0644\u0628\u0646\u0627\u0646'), ('public_in_country', '\u0645\u062f\u0631\u0633\u0629 \u0631\u0633\u0645\u064a\u0629 \u0641\u064a \u0644\u0628\u0646\u0627\u0646'), ('private_in_country', '\u0645\u062f\u0631\u0633\u0629 \u062e\u0627\u0635\u0629 \u0641\u064a \u0644\u0628\u0646\u0627\u0646')], max_length=50, null=True, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0645\u062f\u0631\u0633\u0629'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='moved',
            field=models.BooleanField(default=False, verbose_name='\u0627\u0646\u062a\u0642\u0644\u061f'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='new_registry',
            field=models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u064a\u062a\u0645 \u0627\u0644\u062a\u0633\u062c\u0644 \u0644\u0627\u0648\u0644 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='outreach_barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0631\u0642\u0645 \u0627\u0644\u0628\u0627\u0631\u0643\u0648\u062f'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0633\u062c\u064a\u0644'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_outreached',
            field=models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u062a\u0645 \u0627\u0644\u062a\u0648\u0627\u0635\u0644 \u0645\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u0645\u0646 \u0642\u0628\u0644\u061f'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_gradings', to='enrollments.Enrollment'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_language',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='\u0644\u063a\u0629 \u0627\u062c\u0646\u0628\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_term',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0627\u0644\u0641\u0635\u0644 '),
        ),
        migrations.AlterField(
            model_name='loggingstudentmove',
            name='school_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='\u0627\u0644\u0645\u062f\u0631\u0633\u0629 \u0627\u0644\u0633\u0627\u0628\u0642\u0629'),
        ),
    ]
