# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-05 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0055_auto_20171102_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['student__first_name']},
        ),
    ]
