# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0059_enrollment_number_in_previous_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='have_barcode',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u0644\u062f\u064a\u0647 \u0627\u0644\u0628\u0627\u0631\u0643\u0648\u062f\u061f'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_education_year',
            field=models.CharField(blank=True, choices=[('2000/2001', '2000/2001'), ('2001/2002', '2001/2002'), ('2002/2003', '2002/2003'), ('2003/2004', '2003/2004'), ('2004/2005', '2004/2005'), ('2005/2006', '2005/2006'), ('2006/2007', '2006/2007'), ('2007/2008', '2007/2008'), ('2008/2009', '2008/2009'), ('2009/2010', '2009/2010'), ('2010/2011', '2010/2011'), ('2011/2012', '2011/2012'), ('2012/2013', '2012/2013'), ('2013/2014', '2013/2014'), ('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030'), ('2030/2031', '2030/2031'), ('2031/2032', '2031/2032'), ('2032/2033', '2032/2033'), ('2033/2034', '2033/2034'), ('2034/2035', '2034/2035'), ('2035/2036', '2035/2036'), ('2036/2037', '2036/2037'), ('2037/2038', '2037/2038'), ('2038/2039', '2038/2039'), ('2039/2040', '2039/2040'), ('2040/2041', '2040/2041'), ('2041/2042', '2041/2042'), ('2042/2043', '2042/2043'), ('2043/2044', '2043/2044'), ('2044/2045', '2044/2045'), ('2045/2046', '2045/2046'), ('2046/2047', '2046/2047'), ('2047/2048', '2047/2048'), ('2048/2049', '2048/2049'), ('na', 'N/A')], max_length=10, null=True, verbose_name=' \u0622\u062e\u0631 \u0633\u0646\u0629 \u062f\u0631\u0627\u0633\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_final_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassLevel', verbose_name='\u062a\u0641\u0627\u0635\u064a\u0644 \u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0644\u0645\u064a\u0630 \u062e\u0644\u0627\u0644 \u0622\u062e\u0631 \u062f\u0648\u0631\u0629  \u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alp.ALPRound', verbose_name=' \u062a\u0641\u0627\u0635\u064a\u0644 \u0622\u062e\u0631 \u062f\u0648\u0631\u0629  \u062a\u0639\u0644\u064a\u0645 \u063a\u064a\u0631 \u0646\u0638\u0627\u0645\u064a'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='new_registry',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u064a\u062a\u0645 \u0627\u0644\u062a\u0633\u062c\u064a\u0644 \u0644\u0623\u0648\u0644 \u0645\u0631\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='number_in_previous_school',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='  \u0627\u0644\u0631\u0642\u0645 \u0627\u0644\u062a\u0633\u0644\u0633\u0644\u064a \u0641\u064a \u0627\u0644\u0645\u062f\u0631\u0633\u0629 \u0627\u0644\u0633\u0627\u0628\u0642\u0629'),
        ),
    ]
