# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-16 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0060_auto_20171114_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingprogrammove',
            name='potential_move',
            field=models.BooleanField(default=False),
        ),
    ]
