# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-13 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0061_loggingprogrammove_potential_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='age_max_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='age_min_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
