# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-24 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0063_auto_20171218_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingstudentmove',
            name='moved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Moved date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='number_in_previous_school',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='  \u0631\u0642\u0645 \u0627\u0644\u0627\u0641\u0627\u062f\u0629'),
        ),
    ]
