# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-24 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0064_auto_20171224_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_moved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last moved date'),
        ),
    ]
