# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-24 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0067_enrollment_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_absent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='last_attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
