# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-25 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0068_auto_20180224_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disabled',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('enrollments.enrollment',),
        ),
    ]
