# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-07 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0070_auto_20180307_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='dropout_status',
            field=models.BooleanField(default=False, verbose_name='Dropout?'),
        ),
    ]
