# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-29 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0072_auto_20180323_1504'),
        ('enrollments', '0073_auto_20180329_0935'),
    ]

    operations = [
    ]
