# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-09 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0051_auto_20180413_1223'),
        ('enrollments', '0075_auto_20180405_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingprogrammove',
            name='alp_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alp.ALPRound'),
        ),
        migrations.AlterField(
            model_name='loggingprogrammove',
            name='school_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='From school'),
        ),
    ]
