# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-04-09 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0078_auto_20190328_1416'),
        ('enrollments', '0078_auto_20190402_2122'),
    ]

    operations = [
    ]
