# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-19 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0080_auto_20190521_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='dropout_date',
            field=models.DateField(blank=True, null=True, verbose_name=' \u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0633\u0631\u0628 '),
        ),
    ]
