# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-12 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0081_duplicatestd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicatestd',
            name='user',
        ),
        migrations.AddField(
            model_name='duplicatestd',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='\u0627\u0646\u0634\u0623 \u0645\u0646 \u0642\u0628\u0644'),
        ),
    ]
