# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-08-12 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0082_auto_20190812_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatestd',
            name='sysdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
