# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-11 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0039_auto_20190619_1028'),
        ('enrollments', '0083_auto_20190812_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatestd',
            name='Level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassLevel', verbose_name='Class Level'),
        ),
        migrations.AddField(
            model_name='duplicatestd',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='\u0627\u0644\u0635\u0641 \u0627\u0644\u062d\u0627\u0644\u064a'),
        ),
        migrations.AddField(
            model_name='duplicatestd',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Coordinator', verbose_name='Coordinator'),
        ),
        migrations.AddField(
            model_name='duplicatestd',
            name='current_year',
            field=models.CharField(default=2019, max_length=10),
        ),
        migrations.AddField(
            model_name='duplicatestd',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duplicatestd',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section', verbose_name='\u0627\u0644\u0634\u0639\u0628\u0629 \u0627\u0644\u062d\u0627\u0644\u064a\u0629'),
        ),
    ]
