# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-19 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0084_auto_20190911_1704'),
        ('enrollments', '0081_auto_20190819_1002'),
    ]

    operations = [
    ]
