# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-28 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0085_merge_20190919_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duplicatestd',
            options={'verbose_name': 'Duplicated Students'},
        ),
        migrations.AlterField(
            model_name='duplicatestd',
            name='Level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassLevel', verbose_name='\u0627\u0644\u0645\u0633\u062a\u0648\u0649 '),
        ),
        migrations.AlterField(
            model_name='duplicatestd',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Coordinator', verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0645\u0646\u0633\u0642 \u0627\u0644\u0645\u064a\u062f\u0627\u0646\u064a'),
        ),
    ]
