# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-12-17 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0053_auto_20191008_1151'),
        ('enrollments', '0089_duplicatestd_education_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatestd',
            name='alp_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alp.ALPRound'),
        ),
    ]
