# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0047_auto_20200114_0918'),
        ('enrollments', '0092_auto_20200105_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Document Nunber'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='document_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear', verbose_name='Document Year'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrollments.DocumentType', verbose_name='Document Type'),
        ),
    ]
