# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-16 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0093_auto_20200116_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['id'], 'verbose_name': 'Document Type', 'verbose_name_plural': 'Documents Type'},
        ),
    ]
