# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-16 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0094_auto_20200116_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='document_number',
            new_name='documentnumber',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='document_type',
            new_name='documenttype',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='document_year',
            new_name='documentyear',
        ),
    ]
