# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-17 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import student_registration.enrollments.models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0095_auto_20200116_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='document_lastyear',
            field=models.ImageField(blank=True, help_text='\u0635\u0648\u0631\u0629 \u0639\u0646 \u0627\u0644\u062a\u0639\u0644\u064a\u0645 \u0627\u0644\u0633\u0627\u0628\u0642', null=True, upload_to='enr/doc', validators=[student_registration.enrollments.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='documentnumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0631\u0642\u0645 \u0627\u0644\u0645\u0633\u062a\u0646\u062f'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='documenttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrollments.DocumentType', verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629 \u0627\u0644\u062e\u0627\u0635\u0629 \u0628\u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='documentyear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear', verbose_name='\u0633\u0646\u0629 \u0627\u0644\u062a\u0635\u062f\u064a\u0642'),
        ),
    ]
