# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0098_remove_documenttype_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='justificationnumber',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Justification Number'),
        ),
    ]
