# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-01-31 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0100_documenttype_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='signature_cert_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
