# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-02-16 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0101_enrollment_signature_cert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='justificationnumber',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='\u0627\u0644\u0645\u0639\u0644\u0648\u0645\u0627\u062a \u0627\u0644\u0634\u062e\u0635\u064a\u0629 \u0644\u0644\u0637\u0641\u0644'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='signature_cert_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0635\u062f\u064a\u0642'),
        ),
    ]
