# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-03 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0102_auto_20200216_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_justified',
            field=models.BooleanField(default=True),
        ),
    ]
