# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-03 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0104_auto_20200303_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='justified_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Justified Date'),
        ),
    ]
