# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-04 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0105_enrollment_justified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='justified_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Justified by'),
        ),
    ]
