# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-20 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0103_auto_20200309_1204'),
        ('enrollments', '0106_enrollment_justified_by'),
    ]

    operations = [
    ]
