# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-27 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0107_auto_20200317_1935'),
        ('enrollments', '0107_merge_20200320_2135'),
    ]

    operations = [
    ]
