# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0108_merge_20200327_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='justified_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Justified by'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='justified_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Justified Date'),
        ),
    ]
