# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-06 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student_registration.enrollments.models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0111_auto_20220805_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatestd',
            name='Level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassLevel', verbose_name='Class Level'),
        ),
        migrations.AlterField(
            model_name='duplicatestd',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='Current Class'),
        ),
        migrations.AlterField(
            model_name='duplicatestd',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Coordinator', verbose_name='Coordinator'),
        ),
        migrations.AlterField(
            model_name='duplicatestd',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='duplicatestd',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='duplicatestd',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section', verbose_name='Current Section'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='Current Class'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='document_lastyear',
            field=models.ImageField(blank=True, help_text='picture of previous education', null=True, upload_to='enr/doc', validators=[student_registration.enrollments.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='documentnumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Document Nunber'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='documenttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrollments.DocumentType', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='documentyear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear', verbose_name='Document Year'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='dropout_date',
            field=models.DateField(blank=True, null=True, verbose_name='dropout date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='dropout_status',
            field=models.BooleanField(default=False, verbose_name='Dropout?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear', verbose_name='Education year'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_last_year',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('second', 'Yes - in 2nd shift'), ('first', 'Yes - in 1st shift'), ('private', 'Yes - in private school'), ('other', 'Yes - in another type of school')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', 'Graduated'), ('failed', 'Failed'), ('uncompleted', 'Uncompleted')], max_length=50, null=True, verbose_name='Student status'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_arabic',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Arabic'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_arabic_cmplt',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Arabic'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_artistic',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Artistic field'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_bio',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Biology'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_chemistry',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Chemistry'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_education',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_final',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', 'Graduated'), ('failed', 'Failed'), ('uncompleted', 'Uncompleted')], max_length=50, null=True, verbose_name='Final Student status'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_geo',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Geography'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_history',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_language',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Foreign Language'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_language_cmplt',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Foreign Language'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_linguistic_ar',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Linguistic field/Arabic'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_linguistic_en',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Linguistic field/Foreign language'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_math',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Math'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_math_cmplt',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Math'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_mathematics',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Scientific domain/Mathematics'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_physic',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Physic'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_physical',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Physical field'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_science',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Science'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_sciences',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Scientific domain/Sciences'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_result_sociology',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Sociology field'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_total',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Grade'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='exam_total_cmplt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Grade'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='have_barcode',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='Have barcode with him?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='justificationnumber',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Justification Number'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom', verbose_name='Last Education level'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_education_year',
            field=models.CharField(blank=True, choices=[('2000/2001', '2000/2001'), ('2001/2002', '2001/2002'), ('2002/2003', '2002/2003'), ('2003/2004', '2003/2004'), ('2004/2005', '2004/2005'), ('2005/2006', '2005/2006'), ('2006/2007', '2006/2007'), ('2007/2008', '2007/2008'), ('2008/2009', '2008/2009'), ('2009/2010', '2009/2010'), ('2010/2011', '2010/2011'), ('2011/2012', '2011/2012'), ('2012/2013', '2012/2013'), ('2013/2014', '2013/2014'), ('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026'), ('2026/2027', '2026/2027'), ('2027/2028', '2027/2028'), ('2028/2029', '2028/2029'), ('2029/2030', '2029/2030'), ('2030/2031', '2030/2031'), ('2031/2032', '2031/2032'), ('2032/2033', '2032/2033'), ('2033/2034', '2033/2034'), ('2034/2035', '2034/2035'), ('2035/2036', '2035/2036'), ('2036/2037', '2036/2037'), ('2037/2038', '2037/2038'), ('2038/2039', '2038/2039'), ('2039/2040', '2039/2040'), ('2040/2041', '2040/2041'), ('2041/2042', '2041/2042'), ('2042/2043', '2042/2043'), ('2043/2044', '2043/2044'), ('2044/2045', '2044/2045'), ('2045/2046', '2045/2046'), ('2046/2047', '2046/2047'), ('2047/2048', '2047/2048'), ('2048/2049', '2048/2049'), ('na', 'N/A')], max_length=10, null=True, verbose_name='Last Education year'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_final_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassLevel', verbose_name='Last informal education status'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel', verbose_name='Last informal education level'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_result',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', 'Graduated'), ('failed', 'Failed')], max_length=50, null=True, verbose_name='Last informal education result'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alp.ALPRound', verbose_name='Last informal education round'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_informal_edu_year',
            field=models.CharField(blank=True, choices=[('2000/2001', '2000/2001'), ('2001/2002', '2001/2002'), ('2002/2003', '2002/2003'), ('2003/2004', '2003/2004'), ('2004/2005', '2004/2005'), ('2005/2006', '2005/2006'), ('2006/2007', '2006/2007'), ('2007/2008', '2007/2008'), ('2008/2009', '2008/2009'), ('2009/2010', '2009/2010'), ('2010/2011', '2010/2011'), ('2011/2012', '2011/2012'), ('2012/2013', '2012/2013'), ('2013/2014', '2013/2014'), ('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021')], max_length=10, null=True, verbose_name='Last informal education year'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_moved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last moved date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='Last school'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_school_shift',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('first', 'First shift'), ('second', 'Second shift')], max_length=50, null=True, verbose_name='Last school shift'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_school_type',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('out_the_country', 'School out of the country'), ('public_in_country', 'Public school in the country'), ('private_in_country', 'Private school in the country'), ('CB_ECE', 'CB ECE')], max_length=50, null=True, verbose_name='Last school type'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_year_result',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', 'Graduated'), ('failed', 'Failed')], max_length=50, null=True, verbose_name='Last Education result'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='moved',
            field=models.BooleanField(default=False, verbose_name='Moved?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='new_registry',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='First time registered?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='number_in_previous_school',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Serial number in previous school'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='outreach_barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Outreach barcode'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='participated_in_alp',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='Participated in ALP'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='registered_in_unhcr',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='result',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', 'Graduated'), ('failed', 'Failed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ndshift_school', to='schools.School', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section', verbose_name='Current Section'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='signature_cert_date',
            field=models.DateField(blank=True, null=True, verbose_name='Signature Date'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_outreached',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True, verbose_name='Student outreached?'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result',
            field=models.CharField(blank=True, choices=[('na', 'n/a'), ('graduated', 'Graduated'), ('failed', 'Failed'), ('uncompleted', 'Uncompleted')], max_length=50, null=True, verbose_name='Student status'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_arabic',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Arabic'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_artistic',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Artistic field'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_bio',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Biology'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_chemistry',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Chemistry'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_education',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_geo',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Geography'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_history',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_language',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Foreign language'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_linguistic_ar',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Linguistic field/Arabic'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_linguistic_en',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Linguistic field/Foreign language'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_math',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Math'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_mathematics',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Scientific domain/Mathematics'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_physic',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Physic'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_physical',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Physical field'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_science',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Science'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_sciences',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Scientific domain/Sciences'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_result_sociology',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Sociology field'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_term',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='enrollmentgrading',
            name='exam_total',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Total Grade'),
        ),
        migrations.AlterField(
            model_name='loggingstudentmove',
            name='enrolment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='enrollments.Enrollment', verbose_name='Enrollment'),
        ),
        migrations.AlterField(
            model_name='loggingstudentmove',
            name='moved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Moved date'),
        ),
        migrations.AlterField(
            model_name='loggingstudentmove',
            name='school_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='From school'),
        ),
        migrations.AlterField(
            model_name='loggingstudentmove',
            name='school_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School', verbose_name='To school'),
        ),
        migrations.AlterField(
            model_name='loggingstudentmove',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student', verbose_name='Student'),
        ),
    ]
