# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-30 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0114_merge_20230111_1023'),
        ('enrollments', '0114_merge_20230110_2115'),
    ]

    operations = [
    ]
