# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-31 13:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_status', models.CharField(blank=True, choices=[('granted', 'Granted'), ('denied', 'Denied'), ('granted_referral', 'Granted for the referral')], max_length=50, null=True)),
                ('interview_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('residence_type', models.CharField(blank=True, choices=[(1, 'Informal Settlement'), (2, 'House or Apartment'), (3, 'Garage, Store or other')], max_length=50, null=True)),
                ('p_code', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_children', models.CharField(blank=True, max_length=45, null=True)),
                ('barcode_number', models.CharField(blank=True, max_length=45, null=True)),
                ('social_worker_name', models.CharField(blank=True, max_length=200, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('governorate', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, max_length=200, null=True)),
                ('interview_date', models.CharField(blank=True, max_length=200, null=True)),
                ('children', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
