# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='residence_type',
            field=models.CharField(blank=True, choices=[('informal_s', 'Informal Settlement'), ('house_appart', 'House or Apartment'), ('garage_store_other', 'Garage, Store or other')], max_length=50, null=True),
        ),
    ]
