# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0003_child'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={},
        ),
        migrations.AddField(
            model_name='child',
            name='barcode_subset',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
