# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0004_auto_20170803_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='outreach.HouseHold'),
        ),
    ]
