# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-04 11:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0004_auto_20170803_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('current_year', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Outreach Year',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='consent_child_protection',
            field=models.CharField(blank=True, choices=[('Yes', '\u0646\u0639\u0645'), ('No', '\u0643\u0644\u0627')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='current_situation',
            field=models.CharField(blank=True, choices=[('1', 'Education system 1'), ('2', 'Education system 2'), ('3', 'Education system 3'), ('4', 'Education system 4'), ('5', 'Education system 5'), ('6', 'Education system 6'), ('7', 'Education system 7')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='disability_comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='disability_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='disability_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Walking', 'Walking'), ('Seeing', 'Seeing'), ('Hearing', 'Hearing'), ('Speaking', 'Speaking'), ('Self_Care', 'Self Care'), ('Learning', 'Learning'), ('Interacting', 'Interacting'), ('Other', '\u0622\u062e\u0631')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='child',
            name='formal_education_shift',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('First', '\u062f\u0648\u0627\u0645 \u0635\u0628\u0627\u062d\u064a'), ('Second', '\u062f\u0648\u0627\u0645 \u0628\u0639\u062f \u0627\u0644\u0638\u0647\u0631'), ('ECE', 'ECE'), ('TVET', 'TVET')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='formal_education_type',
            field=models.CharField(blank=True, choices=[('1', 'Formal education 1'), ('2', 'Formal education 2'), ('3', 'Formal education 3'), ('4', 'Formal education 4')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='outreach.HouseHold'),
        ),
        migrations.AddField(
            model_name='child',
            name='informal_education_type',
            field=models.CharField(blank=True, choices=[('ALP', 'ALP'), ('BLN', 'BLN'), ('CBECE', 'CB-ECE'), ('SALP', 'SALP')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='last_education_year',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='last_informal_education',
            field=models.CharField(blank=True, choices=[('ALP', 'ALP'), ('BLN', 'BLN'), ('CB-ECE', 'CB-ECE'), ('SALP', 'SALP'), ('Prep.ALP', 'Prep.ALP'), ('Special_EDU_Dis', 'Special_EDU_Dis')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='last_public_school_location',
            field=models.CharField(blank=True, choices=[('Leb', 'Lebanon'), ('Syr', 'Syria'), ('Irq', 'Iraq'), ('Other', '\u0622\u062e\u0631')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='not_enrolled_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Reason 1'), ('2', 'Reason 2'), ('3', 'Reason 3'), ('4', 'Reason 4'), ('5', 'Reason 5'), ('6', 'Reason 6'), ('7', 'Reason 7'), ('8', 'Reason 8'), ('9', 'Reason 9'), ('10', 'Reason 10'), ('11', 'Reason 11'), ('12', 'Reason 12'), ('13', 'Reason 13'), ('14', 'Reason 14'), ('15', 'Reason 15'), ('16', 'Reason 16'), ('17', 'Reason 17'), ('18', 'Reason 18')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='child',
            name='other_disability_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referral_reason',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('ALP', 'ALP'), ('BLN', 'BLN'), ('CBECE', 'CB-ECE'), ('SALP', 'SALP')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='child',
            name='referred_org',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referred_org_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referred_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referred_school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='retention_support',
            field=models.CharField(blank=True, choices=[('1', 'Retention Support 1'), ('2', 'Retention Support 2'), ('3', 'Retention Support 3'), ('4', 'Retention Support 4'), ('5', 'Retention Support 5'), ('6', 'Retention Support 6')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='work_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
