# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-08 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0005_auto_20170804_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='interview_status',
            field=models.CharField(blank=True, choices=[('1', 'Granted'), ('2', 'Denied'), ('3', 'Granted for the referral')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='residence_type',
            field=models.CharField(blank=True, choices=[('1', 'Informal Settlement'), ('2', 'House or Apartment'), ('3', 'Garage, Store or other')], max_length=50, null=True),
        ),
    ]
