# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-09 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0006_auto_20170808_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='registered_in_unhcr',
            field=models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True),
        ),
    ]
