# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0005_child_household'),
        ('outreach', '0007_auto_20170809_1613'),
    ]

    operations = [
    ]
