# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-15 18:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0010_auto_20170915_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='family_status',
            field=models.CharField(blank=True, choices=[('married', '\u0645\u062a\u0632\u0648\u062c'), ('engaged', '\u0645\u0631\u062a\u0628\u0637'), ('divorced', '\u0645\u0637\u0644\u0642'), ('widower', '\u0627\u0631\u0645\u0644\u0629'), ('single', '\u0627\u0639\u0632\u0628')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='not_enrolled_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Reason 1'), ('2', '\u0627\u0644\u0633\u0628\u0628'), ('3', 'Reason 3'), ('4', 'Reason 4'), ('5', 'Reason 5'), ('6', 'Reason 6'), ('7', 'Reason 7'), ('8', 'Reason 8'), ('9', 'Reason 9'), ('10', 'Reason 10'), ('11', 'Reason 11'), ('12', 'Reason 12'), ('13', 'Reason 13'), ('14', 'Reason 14'), ('15', 'Reason 15'), ('16', 'Reason 16'), ('17', 'Reason 17'), ('18', 'Reason 18')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
    ]
