# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-27 10:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0011_auto_20170915_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='\u0627\u0644\u0639\u0646\u0648\u0627\u0646'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birthday_day',
            field=models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30), (b'31', 31)], default=0, max_length=2, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0648\u0644\u0627\u062f\u0629 - \u0627\u0644\u064a\u0648\u0645'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birthday_month',
            field=models.CharField(blank=True, choices=[('1', '\u0643\u0627\u0646\u0648\u0646 \u0627\u0644\u062b\u0627\u0646\u064a'), ('2', '\u0634\u0628\u0627\u0637'), ('3', '\u0622\u0630\u0627\u0631'), ('4', '\u0646\u064a\u0633\u0627\u0646'), ('5', '\u0623\u064a\u0627\u0631'), ('6', '\u062d\u0632\u064a\u0631\u0627\u0646'), ('7', '\u062a\u0645\u0648\u0632'), ('8', '\u0622\u0628'), ('9', '\u0623\u064a\u0644\u0648\u0644'), ('10', '\u062a\u0634\u0631\u064a\u0646 \u0627\u0644\u0623\u0648\u0644'), ('11', '\u062a\u0634\u0631\u064a\u0646 \u0627\u0644\u062b\u0627\u0646\u064a'), ('12', '\u0643\u0627\u0646\u0648\u0646 \u0627\u0644\u0623\u0648\u0644')], default=0, max_length=2, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0648\u0644\u0627\u062f\u0629 - \u0627\u0644\u0634\u0647\u0631'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birthday_year',
            field=models.CharField(blank=True, choices=[(b'1990', 1990), (b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004), (b'2005', 2005), (b'2006', 2006), (b'2007', 2007), (b'2008', 2008), (b'2009', 2009), (b'2010', 2010), (b'2011', 2011), (b'2012', 2012), (b'2013', 2013), (b'2014', 2014), (b'2015', 2015), (b'2016', 2016)], default=0, max_length=4, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0648\u0644\u0627\u062f\u0629 - \u0627\u0644\u0633\u0646\u0629'),
        ),
        migrations.AlterField(
            model_name='child',
            name='current_situation',
            field=models.CharField(blank=True, choices=[('1', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062f\u0631\u0627\u0633\u064a\u0629'), ('2', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062f\u0631\u0627\u0633\u064a\u0629'), ('3', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062f\u0631\u0627\u0633\u064a\u0629'), ('4', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062f\u0631\u0627\u0633\u064a\u0629'), ('5', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062f\u0631\u0627\u0633\u064a\u0629'), ('6', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062f\u0631\u0627\u0633\u064a\u0629'), ('7', '\u0627\u0644\u0633\u0646\u0629 \u0627\u0644\u062f\u0631\u0627\u0633\u064a\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='family_status',
            field=models.CharField(blank=True, choices=[('married', '\u0645\u062a\u0632\u0648\u062c'), ('engaged', '\u0645\u0631\u062a\u0628\u0637'), ('divorced', '\u0645\u0637\u0644\u0642'), ('widower', '\u0627\u0631\u0645\u0644\u0629'), ('single', '\u0627\u0639\u0632\u0628')], max_length=50, null=True, verbose_name='\u0648\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
        migrations.AlterField(
            model_name='child',
            name='father_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0627\u0628'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0627\u0644\u0627\u0633\u0645 \u0627\u0644\u0627\u0648\u0644'),
        ),
        migrations.AlterField(
            model_name='child',
            name='have_children',
            field=models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u0644\u062f\u064a\u0647 \u0627\u0637\u0641\u0627\u0644'),
        ),
        migrations.AlterField(
            model_name='child',
            name='id_number',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='\u0631\u0642\u0645 \u0627\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AlterField(
            model_name='child',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.IDType', verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0628\u0637\u0627\u0642\u0629'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0627\u0644\u0634\u0647\u0631\u0629'),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_fullname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0627\u0633\u0645 \u0627\u0644\u0623\u0645 \u0648\u0634\u0647\u0631\u062a\u0647\u0627 (\u0628\u0627\u0644\u0639\u0631\u0628\u064a)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Nationality', verbose_name='\u062c\u0646\u0633\u064a\u0629 \u0627\u0644\u0623\u0645'),
        ),
        migrations.AlterField(
            model_name='child',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Nationality', verbose_name=' \u0627\u0644\u062c\u0646\u0633\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='child',
            name='not_enrolled_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', '\u0627\u0644\u0633\u0628\u0628'), ('2', '\u0627\u0644\u0633\u0628\u0628'), ('3', '\u0627\u0644\u0633\u0628\u0628'), ('4', '\u0627\u0644\u0633\u0628\u0628'), ('5', '\u0627\u0644\u0633\u0628\u0628'), ('6', '\u0627\u0644\u0633\u0628\u0628'), ('7', '\u0627\u0644\u0633\u0628\u0628'), ('8', '\u0627\u0644\u0633\u0628\u0628'), ('9', '\u0627\u0644\u0633\u0628\u0628'), ('10', '\u0627\u0644\u0633\u0628\u0628'), ('11', '\u0627\u0644\u0633\u0628\u0628'), ('12', '\u0627\u0644\u0633\u0628\u0628'), ('13', 'Reason 13'), ('14', '\u0627\u0644\u0633\u0628\u0628'), ('15', '\u0627\u0644\u0633\u0628\u0628'), ('16', '\u0627\u0644\u0633\u0628\u0628'), ('17', '\u0627\u0644\u0633\u0628\u0628'), ('18', '\u0627\u0644\u0633\u0628\u0628')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='child',
            name='p_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='P-code'),
        ),
        migrations.AlterField(
            model_name='child',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u0627\u0644\u0647\u0627\u062a\u0641'),
        ),
        migrations.AlterField(
            model_name='child',
            name='phone_prefix',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u0643\u0648\u062f \u0627\u0644\u0631\u0642\u0645'),
        ),
        migrations.AlterField(
            model_name='child',
            name='registered_in_unhcr',
            field=models.CharField(blank=True, choices=[(1, '\u0646\u0639\u0645'), (0, '\u0643\u0644\u0627')], max_length=50, null=True, verbose_name='\u0645\u0633\u062c\u0644 \u0644\u062f\u0649 \u0627\u0644\u0645\u0641\u0648\u0636\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', '\u0630\u0643\u0631'), ('Female', '\u0627\u0646\u062b\u0649')], max_length=50, null=True, verbose_name='\u0627\u0644\u062c\u0646\u0633'),
        ),
    ]
