# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0014_auto_20171013_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='family_status',
            field=models.CharField(blank=True, choices=[('married', '\u0645\u062a\u0632\u0648\u062c / \u0645\u062a\u0632\u0648\u062c\u0629'), ('engaged', '\u0645\u062e\u0637\u0648\u0628 / \u0645\u062e\u0637\u0648\u0628\u0629'), ('divorced', '\u0645\u0637\u0644\u0642 / \u0645\u0637\u0644\u0642\u0629'), ('widower', '\u0627\u0631\u0645\u0644 / \u0627\u0631\u0645\u0644\u0629'), ('single', '\u0623\u0639\u0632\u0628 / \u0639\u0632\u0628\u0627\u0621')], max_length=50, null=True, verbose_name='\u0648\u0636\u0639 \u0627\u0644\u062a\u0644\u0645\u064a\u0630'),
        ),
    ]
