# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-06 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0016_auto_20171019_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='form_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='form_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
