# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-06 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0019_auto_20171107_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='p_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
