# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0026_auto_20171201_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
