# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0026_auto_20171201_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='std_phone',
            field=models.CharField(blank=True, max_length=74, null=True),
        ),
    ]
