# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-09-29 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0027_child_std_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='recordnumber',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
