# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-06 09:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0028_auto_20180228_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='formid_ind',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='last_edu_system',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='formal_education_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='referral_reason',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Referral_Reason 1'), ('2', 'Referral_Reason 2'), ('3', 'Referral_Reason 3'), ('4', 'Referral_Reason 4'), ('5', 'Referral_Reason 5'), ('6', 'Referral_Reason 6'), ('7', 'Referral_Reason 7'), ('8', 'Referral_Reason 8'), ('9', 'Referral_Reason 9'), ('10', 'Referral_Reason 10'), ('11', 'Referral_Reason 11'), ('12', 'Referral_Reason 12'), ('13', 'Referral_Reason 13'), ('14', 'Referral_Reason 14'), ('15', 'Referral_Reason 15')], max_length=50, null=True), blank=True, null=True, size=None),
        ),
    ]
