# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-06 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0029_auto_20180306_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='last_school_formal_year',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referred_org_bln',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referred_org_ece',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referred_school_alp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referred_school_first',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='referred_school_second',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
