# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-10-08 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0029_auto_20190929_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='recordnumber',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='\u0631\u0642\u0645 \u062a\u0633\u0644\u0633\u0644\u064a \u062e\u0627\u0635 \u0628\u0627\u0644\u062c\u0645\u0639\u064a\u0629'),
        ),
    ]
