# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-12 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_auto_20180228_1638'),
        ('outreach', '0030_auto_20180306_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Nationality', verbose_name=' \u0627\u0644\u062c\u0646\u0633\u064a\u0629'),
        ),
        migrations.AlterField(
            model_name='child',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outreach_children', to='outreach.HouseHold'),
        ),
    ]
