# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-13 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0032_child_education_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='education_level',
        ),
    ]
