# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-16 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0035_auto_20221216_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreachchild',
            name='address',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='birthday_day',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='birthday_month',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='birthday_year',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='created',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='have_children',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='mother_firstname',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='mother_fullname',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='mother_lastname',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='mother_nationality',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='number',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='number_part1',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='number_part2',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='p_code',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='phone_prefix',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='recordnumber',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='registered_in_unhcr',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='outreachchild',
            name='std_phone',
        ),
    ]
