# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-09 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0036_auto_20221216_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachchild',
            name='birthday_day',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='outreachchild',
            name='birthday_month',
            field=models.CharField(blank=True, choices=[('', '---------'), ('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default=0, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='outreachchild',
            name='birthday_year',
            field=models.CharField(blank=True, default=0, max_length=4, null=True),
        ),
    ]
