# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-02-24 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0037_auto_20230109_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachcaregiver',
            name='interview_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
