# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-09 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0039_auto_20230224_1857'),
        ('outreach', '0039_auto_20230307_0953'),
    ]

    operations = [
    ]
