# Generated by Django 5.2.3 on 2025-09-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0042_auto_20250210_1627'),
        ('students', '0087_auto_20250626_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutreachYear',
        ),
        migrations.AlterField(
            model_name='child',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='outreach.household'),
        ),
        migrations.AlterField(
            model_name='child',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.idtype', verbose_name='ID type'),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Mother nationality'),
        ),
        migrations.AlterField(
            model_name='child',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='household',
            name='children',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='outreachchild',
            name='outreach_caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='outreach.outreachcaregiver'),
        ),
    ]
