# Generated by Django 5.2.3 on 2025-10-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0043_delete_outreachyear_alter_child_household_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachcaregiver',
            name='first_phone_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outreachchild',
            name='cash_support_programmes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outreachchild',
            name='children_number_under18',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outreachchild',
            name='have_children',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outreachchild',
            name='have_sibling',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outreachchild',
            name='living_arrangement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outreachchild',
            name='mother_pregnant_expecting',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outreachchild',
            name='siblings_have_disability',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outreachchild',
            name='source_of_identification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
