# Generated by Django 5.2.3 on 2026-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0044_outreachcaregiver_first_phone_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='unicef_id_backup',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Unicef ID Backup'),
        ),
    ]
