# Generated by Django 5.2.7 on 2026-08-30 13:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0033_alter_center_type"),
        ("schools", "0166_alter_school_active_during_emergency"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolCenterLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasync_school_links",
                        to="locations.center",
                        verbose_name="Centre teachers are replicated to",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasync_center_link",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "School to centre link",
                "verbose_name_plural": "School to centre links",
                "ordering": ["school__name"],
            },
        ),
        migrations.CreateModel(
            name="SyncEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Event id",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("mscc.round", "Round"),
                            ("locations.center", "Center"),
                            ("mscc.teacher", "Teacher"),
                            ("mscc.registration", "Registration"),
                            ("mscc.education_service", "Child education situation"),
                            ("mscc.education_grading", "Grading"),
                            ("mscc.referral", "Referral"),
                            ("attendances.mscc_attendance", "Attendance"),
                            ("child.child", "Child"),
                        ],
                        db_index=True,
                        max_length=100,
                        verbose_name="Resource",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("upsert", "Create or update"), ("delete", "Delete")],
                        max_length=20,
                        verbose_name="Operation",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Record id"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Payload"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed, will retry"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Delivery attempts"
                    ),
                ),
                (
                    "next_attempt",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Not before"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, null=True, verbose_name="Last error"),
                ),
                (
                    "remote_detail",
                    models.TextField(
                        blank=True, null=True, verbose_name="Reply from BMA-NFE"
                    ),
                ),
                (
                    "remote_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Id in BMA-NFE",
                    ),
                ),
                (
                    "conflict",
                    models.BooleanField(
                        default=False, verbose_name="Overwrote a local edit in BMA-NFE"
                    ),
                ),
                (
                    "ignored_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Fields BMA-NFE does not store",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync event",
                "verbose_name_plural": "Sync events",
                "ordering": ["created", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt"],
                        name="datasync_sy_status_d15b0b_idx",
                    ),
                    models.Index(
                        fields=["resource", "source_id"],
                        name="datasync_sy_resourc_d1181e_idx",
                    ),
                ],
            },
        ),
    ]
