# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-27 04:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0042_auto_20171201_1630'),
        ('alp', '0051_auto_20180413_1223'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0037_auto_20190328_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('last_attendance_date', models.DateField(blank=True, null=True)),
                ('last_absent_date', models.DateField(blank=True, null=True)),
                ('absent_days', models.IntegerField(blank=True, null=True)),
                ('attended_days', models.IntegerField(blank=True, null=True)),
                ('total_absent_days', models.IntegerField(blank=True, null=True)),
                ('total_attended_days', models.IntegerField(blank=True, null=True)),
                ('reattend_date', models.DateField(blank=True, null=True)),
                ('validation_status', models.BooleanField(default=False)),
                ('last_modification_date', models.DateField(blank=True, null=True)),
                ('dropout_status', models.NullBooleanField(default=False)),
                ('disabled', models.NullBooleanField(default=False, verbose_name='disabled')),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('level_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('alp_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alp.ALPRound')),
                ('education_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absents', to='students.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.BooleanField(default=False)),
                ('attendance_date', models.DateField(blank=True, db_index=True, null=True)),
                ('validation_status', models.BooleanField(default=False)),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('absence_reason', models.CharField(blank=True, choices=[('sick', '\u0627\u0633\u0628\u0627\u0628 \u0635\u062d\u064a\u0629'), ('no_transport', '\u0645\u0634\u0643\u0644\u0629 \u0641\u064a \u0648\u0633\u0627\u0626\u0644 \u0627\u0644\u0646\u0642\u0644'), ('other', '\u0633\u0628\u0628 \u0622\u062e\u0631')], max_length=50, null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('public_holiday', '\u0639\u0637\u0644\u0629 \u0631\u0633\u0645\u064a\u0629'), ('school_holiday', '\u0639\u0637\u0644\u0629 \u0645\u062f\u0631\u0633\u064a\u0629'), ('strike', '\u0627\u0636\u0631\u0627\u0628'), ('weekly_holiday', '\u0639\u0637\u0644\u0629 \u0646\u0647\u0627\u064a\u0629 \u0627\u0644\u0627\u0633\u0628\u0648\u0639')], max_length=50, null=True)),
                ('students', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('total_enrolled', models.IntegerField(blank=True, null=True)),
                ('total_attended', models.IntegerField(blank=True, null=True)),
                ('total_absences', models.IntegerField(blank=True, null=True)),
                ('total_attended_male', models.IntegerField(blank=True, null=True)),
                ('total_attended_female', models.IntegerField(blank=True, null=True)),
                ('total_absent_male', models.IntegerField(blank=True, null=True)),
                ('total_absent_female', models.IntegerField(blank=True, null=True)),
                ('school_type', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('alp_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alp.ALPRound')),
                ('classlevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom')),
                ('education_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schools.School')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.Student')),
                ('validation_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendances by School by Day',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(blank=True, max_length=50, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('total_processed', models.IntegerField(default=0)),
                ('successful', models.BooleanField(default=False)),
                ('exception_message', models.TextField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('processed_date', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
            options={
                'ordering': ['processed_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendDt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('classlevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='BySchoolByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('highest_attendance_rate', models.BooleanField(default=False)),
                ('total_enrolled', models.IntegerField(blank=True, null=True)),
                ('total_attended', models.IntegerField(blank=True, null=True)),
                ('total_absences', models.IntegerField(blank=True, null=True)),
                ('total_attended_male', models.IntegerField(blank=True, null=True)),
                ('total_attended_female', models.IntegerField(blank=True, null=True)),
                ('total_absent_male', models.IntegerField(blank=True, null=True)),
                ('total_absent_female', models.IntegerField(blank=True, null=True)),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('validation_status', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceByStudent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('attendances.absentee',),
        ),
        migrations.CreateModel(
            name='AttendedDays',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('attendances.absentee',),
        ),
        migrations.AlterIndexTogether(
            name='attendance',
            index_together=set([('attendance_date', 'school')]),
        ),
    ]
