# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_auto_20160819_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('sick', 'Sick'), ('no_reason', 'No reason'), ('no_transport', 'No transport'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
