# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_auto_20160812_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School'),
        ),
    ]
