# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20161115_1824'),
        ('attendances', '0003_attendance_absence_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='classlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationLevel'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom'),
        ),
    ]
