# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-27 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_attendancedt_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancedt',
            name='attendance_date',
        ),
        migrations.AddField(
            model_name='attendancedt',
            name='levelname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
