# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-05-27 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_auto_20190527_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedt',
            name='attendance_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
