# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-13 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0005_byschoolbyday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='byschoolbyday',
            old_name='date',
            new_name='attendance_date',
        ),
    ]
