# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-28 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0010_byschoolbyday_validation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentee',
            name='last_absent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
