# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-04 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0011_absentee_last_absent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentee',
            name='dropout_status',
            field=models.BooleanField(default=False),
        ),
    ]
