# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-19 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0012_absentee_dropout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentee',
            name='dropout_status',
            field=models.NullBooleanField(default=False),
        ),
    ]
