# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_merge'),
        ('attendances', '0017_auto_20170419_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section'),
        ),
    ]
