# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0019_auto_20170908_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('public_holiday', 'Public Holiday'), ('school_holiday', 'School Holiday'), ('strike', 'Strike'), ('weekly_holiday', 'Weekly Holiday')], max_length=50, null=True),
        ),
    ]
