# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0022_auto_20171009_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendedDays',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('attendances.absentee',),
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['attendance_date'], 'verbose_name': 'Attendances by School by Day'},
        ),
        migrations.AddField(
            model_name='absentee',
            name='attended_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
