# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0023_auto_20171024_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceByStudent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('attendances.absentee',),
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendances by School by Day'},
        ),
    ]
