# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-09 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0027_auto_20180130_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentee',
            name='total_absent_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absentee',
            name='total_attended_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
