# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-12 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0028_auto_20180209_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentee',
            name='disabled',
            field=models.NullBooleanField(default=False, verbose_name='disabled'),
        ),
    ]
