# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0029_absentee_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentee',
            name='last_modification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
