# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-22 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alp', '0050_auto_20171218_1026'),
        ('schools', '0035_auto_20180215_1432'),
        ('attendances', '0031_auto_20180307_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentee',
            name='alp_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='alp.ALPRound'),
        ),
        migrations.AddField(
            model_name='absentee',
            name='education_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.EducationYear'),
        ),
        migrations.AddField(
            model_name='absentee',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='absentee',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
