# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-29 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0032_auto_20180322_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentee',
            name='level_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='absentee',
            name='section_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
