# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-06-08 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0056_auto_20200414_1021'),
        ('schools', '0132_auto_20220606_0932'),
        ('attendances', '0034_auto_20190528_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLMAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('registration_level', models.CharField(blank=True, choices=[('', '----------'), ('level_one', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0623\u0648\u0644'), ('level_two', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062b\u0627\u0646\u064a'), ('level_three', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062b\u0627\u0644\u062b'), ('level_four', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0631\u0627\u0628\u0639'), ('level_five', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062e\u0627\u0645\u0633'), ('level_six', '\u0627\u0644\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u0633\u0627\u062f\u0633')], max_length=100, null=True, verbose_name='\u0645\u0633\u062a\u0648\u0649 \u0627\u0644\u062a\u0633\u062c\u064a\u0644')),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('day_off', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Day off ?')),
                ('close_reason', models.CharField(blank=True, choices=[('public_holiday', '\u0639\u0637\u0644\u0629 \u0631\u0633\u0645\u064a\u0629'), ('school_holiday', '\u0639\u0637\u0644\u0629 \u0645\u062f\u0631\u0633\u064a\u0629'), ('strike', '\u0627\u0636\u0631\u0627\u0628'), ('weekly_holiday', '\u0639\u0637\u0644\u0629 \u0646\u0647\u0627\u064a\u0629 \u0627\u0644\u0627\u0633\u0628\u0648\u0639')], max_length=50, null=True, verbose_name='Day off reason')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School')),
            ],
            options={
                'ordering': ['attendance_date'],
                'verbose_name': 'Attendances by School by Day',
            },
        ),
        migrations.CreateModel(
            name='CLMAttendanceStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attended', models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='Student Attended?')),
                ('absence_reason', models.CharField(blank=True, choices=[('sick', '\u0627\u0633\u0628\u0627\u0628 \u0635\u062d\u064a\u0629'), ('no_transport', '\u0645\u0634\u0643\u0644\u0629 \u0641\u064a \u0648\u0633\u0627\u0626\u0644 \u0627\u0644\u0646\u0642\u0644'), ('other', '\u0633\u0628\u0628 \u0622\u062e\u0631')], max_length=50, null=True)),
                ('attendance_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='attendances.CLMAttendance')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student', verbose_name='\u0627\u0644\u062a\u0644\u0645\u064a\u0630')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Student Attendance',
            },
        ),
    ]
