# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-08-05 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0037_auto_20220630_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmattendancestudent',
            name='absence_reason_other',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u064a\u0631\u062c\u0649 \u0627\u0644\u062a\u062d\u062f\u064a\u062f'),
        ),
        migrations.AlterField(
            model_name='clmattendance',
            name='attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062d\u0636\u0648\u0631'),
        ),
        migrations.AlterField(
            model_name='clmattendance',
            name='day_off',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u064a\u0648\u0645 \u0639\u0637\u0644\u0629\u061f'),
        ),
        migrations.AlterField(
            model_name='clmattendancestudent',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('', '----------'), ('sick', '\u0627\u0633\u0628\u0627\u0628 \u0635\u062d\u064a\u0629'), ('no_transport', '\u0645\u0634\u0643\u0644\u0629 \u0641\u064a \u0648\u0633\u0627\u0626\u0644 \u0627\u0644\u0646\u0642\u0644'), ('other', '\u0633\u0628\u0628 \u0622\u062e\u0631')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clmattendancestudent',
            name='attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=10, null=True, verbose_name='\u0647\u0644 \u062d\u0636\u0631 \u0627\u0644\u0637\u0627\u0644\u0628'),
        ),
    ]
