# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-06 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0039_remove_clmattendancestudent_absence_reason_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmattendancestudent',
            name='absence_reason_other',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='specify'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('sick', 'Sick'), ('no_transport', 'No transport'), ('other', 'Other reason')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('public_holiday', 'Public Holiday'), ('school_holiday', 'School Holiday'), ('strike', 'Strike'), ('weekly_holiday', 'Weekly Holiday')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clmattendance',
            name='attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Attendance date'),
        ),
        migrations.AlterField(
            model_name='clmattendance',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('', '----------'), ('public_holiday', 'Public Holiday'), ('school_holiday', 'School Holiday'), ('strike', 'Strike'), ('weekly_holiday', 'Weekly Holiday'), ('roads_closed', 'Roads Closed')], max_length=50, null=True, verbose_name='Day off reason'),
        ),
        migrations.AlterField(
            model_name='clmattendance',
            name='day_off',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Day off ?'),
        ),
        migrations.AlterField(
            model_name='clmattendance',
            name='registration_level',
            field=models.CharField(blank=True, choices=[('', '----------'), ('level_one', 'Level one'), ('level_two', 'Level two'), ('level_three', 'Level three'), ('level_four', 'Level four'), ('level_five', 'Level five'), ('level_six', 'Level six')], max_length=100, null=True, verbose_name='Registration level'),
        ),
        migrations.AlterField(
            model_name='clmattendancestudent',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('', '----------'), ('sick', 'Sick'), ('no_transport', 'No transport'), ('other', 'Other reason')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clmattendancestudent',
            name='attended',
            field=models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Student Attended?'),
        ),
        migrations.AlterField(
            model_name='clmattendancestudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Student', verbose_name='Student'),
        ),
    ]
