# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_auto_20221213_1620'),
        ('locations', '0009_auto_20221213_1620'),
        ('attendances', '0040_auto_20221206_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSCCAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attendance_date', models.DateField(blank=True, null=True, verbose_name='Attendance date')),
                ('day_off', models.CharField(blank=True, choices=[('', '----------'), ('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Day off ?')),
                ('close_reason', models.CharField(blank=True, choices=[('', '----------'), ('public_holiday', 'Public Holiday'), ('school_holiday', 'School Holiday'), ('strike', 'Strike'), ('weekly_holiday', 'Weekly Holiday'), ('roads_closed', 'Roads Closed')], max_length=50, null=True, verbose_name='Day off reason')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Center', verbose_name='Center')),
            ],
            options={
                'ordering': ['attendance_date'],
                'verbose_name': 'Attendances by School by Day',
            },
        ),
        migrations.CreateModel(
            name='MSCCAttendanceStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attended', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Student Attended?')),
                ('absence_reason', models.CharField(blank=True, choices=[('', '----------'), ('sick', 'Sick'), ('no_transport', 'No transport'), ('other', 'Other reason')], max_length=50, null=True)),
                ('absence_reason_other', models.CharField(blank=True, max_length=500, null=True, verbose_name='specify')),
                ('attendance_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='attendances.MSCCAttendance')),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='child.Child', verbose_name='Child')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Student Attendance',
            },
        ),
    ]
