# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0041_msccattendance_msccattendancestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msccattendance',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Public Holiday', 'Public Holiday'), ('School Holiday', 'School Holiday'), ('Strike', 'Strike'), ('Weekly Holiday', 'Weekly Holiday'), ('Roads Closed', 'Roads Closed')], max_length=50, null=True, verbose_name='Day off reason'),
        ),
        migrations.AlterField(
            model_name='msccattendancestudent',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Sick', 'Sick'), ('No transport', 'No transport'), ('Other', 'Other'), ('Unspecified', 'Unspecified')], max_length=50, null=True),
        ),
    ]
