# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-01-23 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_auto_20221213_1620'),
        ('attendances', '0042_auto_20230120_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSCCAttendanceChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attended', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Student Attended?')),
                ('absence_reason', models.CharField(blank=True, choices=[('', '----------'), ('Sick', 'Sick'), ('No transport', 'No transport'), ('Other', 'Other'), ('Unspecified', 'Unspecified')], max_length=50, null=True)),
                ('absence_reason_other', models.CharField(blank=True, max_length=500, null=True, verbose_name='specify')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Student Attendance',
            },
        ),
        migrations.RemoveField(
            model_name='msccattendancestudent',
            name='attendance_day',
        ),
        migrations.RemoveField(
            model_name='msccattendancestudent',
            name='child',
        ),
        migrations.AlterModelOptions(
            name='msccattendance',
            options={'ordering': ['attendance_date'], 'verbose_name': 'Attendances by Day'},
        ),
        migrations.DeleteModel(
            name='MSCCAttendanceStudent',
        ),
        migrations.AddField(
            model_name='msccattendancechild',
            name='attendance_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='attendances.MSCCAttendance'),
        ),
        migrations.AddField(
            model_name='msccattendancechild',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='child.Child', verbose_name='Child'),
        ),
    ]
