# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0044_auto_20230207_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msccattendancechild',
            name='attendance_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_child', to='attendances.MSCCAttendance'),
        ),
    ]
