# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-04 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0046_clmabsencerecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmabsencerecords',
            name='round_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
