# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-04 12:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0047_clmabsencerecords_round_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLMStudentAbsences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('registration_id', models.IntegerField(blank=True, null=True)),
                ('round_id', models.IntegerField(blank=True, null=True)),
                ('student_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registation_level', models.CharField(blank=True, max_length=50, null=True)),
                ('absence_days', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('consecutive_absence_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Student Absences',
            },
        ),
        migrations.CreateModel(
            name='CLMStudentTotalAbsence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('registration_id', models.IntegerField(blank=True, null=True)),
                ('round_id', models.IntegerField(blank=True, null=True)),
                ('student_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registation_level', models.CharField(blank=True, max_length=50, null=True)),
                ('total_absence_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Student Total Absence',
            },
        ),
        migrations.DeleteModel(
            name='CLMAbsenceRecords',
        ),
    ]
