# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0048_auto_20230404_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmstudentabsences',
            name='absence_starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
