# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-06 14:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0050_clmstudentabsences_absence_ending_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clmstudentabsences',
            name='absence_days',
        ),
        migrations.AddField(
            model_name='clmstudentabsences',
            name='absence_dates',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
