# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0053_auto_20230529_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='msccattendance',
            name='class_section',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Public Holiday', 'Public Holiday'), ('School Holiday', 'School Holiday'), ('Strike', 'Strike'), ('Weekly Holiday', 'Weekly Holiday'), ('Roads Closed', 'Roads Closed')], max_length=50, null=True, verbose_name='Class Section'),
        ),
        migrations.AddField(
            model_name='msccattendance',
            name='education_program',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Public Holiday', 'Public Holiday'), ('School Holiday', 'School Holiday'), ('Strike', 'Strike'), ('Weekly Holiday', 'Weekly Holiday'), ('Roads Closed', 'Roads Closed')], max_length=200, null=True, verbose_name='Education Program'),
        ),
    ]
