# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-07-20 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0055_clmattendance_round_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmstudentabsences',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmstudentabsences',
            name='school_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmstudenttotalattendance',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clmstudenttotalattendance',
            name='school_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
