# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-08-17 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0056_auto_20230720_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clmattendance',
            options={'ordering': ['attendance_date'], 'verbose_name': 'Dirasa Attendance'},
        ),
        migrations.AlterModelOptions(
            name='clmattendancestudent',
            options={'ordering': ['id'], 'verbose_name': 'Dirasa Student Attendance'},
        ),
        migrations.AlterModelOptions(
            name='clmstudentabsences',
            options={'ordering': ['id'], 'verbose_name': 'Dirasa Student Absences'},
        ),
        migrations.AlterModelOptions(
            name='clmstudenttotalattendance',
            options={'ordering': ['id'], 'verbose_name': 'Dirasa Student Total Attendance'},
        ),
        migrations.AlterModelOptions(
            name='msccattendance',
            options={'ordering': ['attendance_date'], 'verbose_name': 'Makani Attendance'},
        ),
        migrations.AlterModelOptions(
            name='msccattendancechild',
            options={'ordering': ['id'], 'verbose_name': 'Makani Child Attendance'},
        ),
    ]
