# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-10-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mscc', '0060_auto_20231003_0958'),
        ('attendances', '0057_auto_20230817_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='msccattendancechild',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mscc.Registration', verbose_name='Registration'),
        ),
    ]
