# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-09-12 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clm', '0269_bridging_dropout_date'),
        ('attendances', '0058_msccattendancechild_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmattendancestudent',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Bridging', verbose_name='Registration'),
        ),
    ]
