# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-09-19 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0060_auto_20240913_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='msccattendance',
            name='round_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
