# Generated by Django 5.2.3 on 2026-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0065_alter_absentee_alp_round_alter_absentee_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clmattendance',
            name='registration_level',
            field=models.CharField(blank=True, choices=[('', '----------'), ('level_one', 'Level one'), ('level_two', 'Level two'), ('level_three', 'Level three'), ('grade_one', 'Grade one'), ('grade_two', 'Grade two'), ('grade_three', 'Grade three'), ('grade_four', 'Grade four'), ('grade_five', 'Grade five'), ('grade_six', 'Grade six'), ('grade_seven', 'Grade seven'), ('grade_eight', 'Grade eight'), ('grade_nine', 'Grade nine')], max_length=100, null=True, verbose_name='Registration level'),
        ),
    ]
