# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='type',
            new_name='gateway',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('name', 'gateway', 'p_code')]),
        ),
    ]
