# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_location_pilot_in_use'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
            ],
        ),
    ]
