# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-19 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20170731_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name_en',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='name_en',
            field=models.CharField(blank=True, max_length=145, null=True),
        ),
    ]
