# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-08 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='location',
        ),
        migrations.AddField(
            model_name='center',
            name='cadaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='Cadaster'),
        ),
        migrations.AddField(
            model_name='center',
            name='caza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='Caza'),
        ),
        migrations.AddField(
            model_name='center',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location', verbose_name='Governorate'),
        ),
        migrations.AddField(
            model_name='center',
            name='p_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='P-Code'),
        ),
        migrations.AddField(
            model_name='center',
            name='type',
            field=models.CharField(blank=True, choices=[('Municipality', 'Municipality'), ('Collective Settlement', 'Collective Settlement'), ('Informal Settlement', 'Informal Settlement'), ('Welfare Center', 'Welfare Center'), ('Collective Settlement', 'Collective Settlement')], max_length=100, null=True, verbose_name='Type'),
        ),
    ]
