# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20221208_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='type',
            field=models.CharField(blank=True, choices=[('Municipality', 'Municipality'), ('Collective Settlement', 'Collective Settlement'), ('Informal Settlement', 'Informal Settlement'), ('Welfare Center', 'Welfare Center')], max_length=100, null=True, verbose_name='Type'),
        ),
    ]
