# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-03-15 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20221213_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='type',
            field=models.CharField(blank=True, choices=[('Municipality', 'Municipality'), ('Collective Settlement', 'Collective Settlement'), ('Informal Settlement', 'Informal Settlement'), ('Welfare Center', 'Welfare Center'), ('Community Hub', 'Community Hub')], max_length=100, null=True, verbose_name='Type'),
        ),
    ]
