# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-04-26 10:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20230315_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='provided_packages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Education', 'Education'), ('Youth', 'Youth'), ('Health & Nutrition', 'Health & Nutrition'), ('Child Protection', 'Child Protection'), ('Social Protection', 'Social Protection')], max_length=100, null=True), blank=True, null=True, size=None, verbose_name='Provided Services'),
        ),
    ]
