# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-09-20 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0012_auto_20230920_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='center',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='center',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified by'),
        ),
        migrations.AddField(
            model_name='center',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='center',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Center GPS (latitude)'),
        ),
        migrations.AlterField(
            model_name='center',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Center GPS (longitude)'),
        ),
    ]
