# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-10-09 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_center_cwd_accessible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='cwd_accessible',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Is the center accessible for CWD'),
        ),
    ]
