# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-10-10 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0144_auto_20230718_1437'),
        ('locations', '0016_auto_20231009_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center_partner', to='schools.PartnerOrganization', verbose_name='Partner'),
        ),
    ]
