# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-10-18 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_auto_20231017_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstaff',
            name='attach_CV',
        ),
        migrations.RemoveField(
            model_name='programstaff',
            name='attach_Diploma',
        ),
        migrations.AddField(
            model_name='programstaff',
            name='attach_cv',
            field=models.FileField(blank=True, null=True, upload_to='uploads/program_staff', verbose_name='CV Attachment'),
        ),
        migrations.AddField(
            model_name='programstaff',
            name='attach_diploma',
            field=models.FileField(blank=True, null=True, upload_to='uploads/program_staff', verbose_name='Diploma Attachment'),
        ),
    ]
