# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-10-18 16:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_auto_20231018_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstaff',
            name='subject',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Education', 'Education'), ('Child Protection', 'Child Protection'), ('Health and Nutrition', 'Health and Nutrition'), ('Youth', 'Youth'), ('Digital', 'Digital')], max_length=200, null=True), blank=True, null=True, size=None, verbose_name='Subject'),
        ),
    ]
