# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-03-13 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0020_auto_20231018_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programstaff',
            options={'ordering': ['facilitator_name'], 'verbose_name': 'ProgramStaff', 'verbose_name_plural': 'ProgramStaffs'},
        ),
    ]
