# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-08-16 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_auto_20240313_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInfoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('name_en', models.CharField(blank=True, max_length=254, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('p_code', models.CharField(blank=True, max_length=32, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.ActivityInfoLocation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.LocationType', verbose_name='Location Type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='activityinfolocation',
            unique_together=set([('name', 'type', 'p_code')]),
        ),
    ]
