# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-10-04 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0022_center_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='is_active',
            field=models.NullBooleanField(default=False, verbose_name='is active'),
        ),
    ]
