# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-10-23 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0023_auto_20241004_1140'),
        ('locations', '0022_auto_20240816_1634'),
    ]

    operations = [
    ]
