from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views, education_view, services_view

urlpatterns = [

    url(
        regex=r'^Child-Add/$',
        view=views.MainAddView.as_view(),
        name='child_add'
    ),
    url(
        regex=r'^Child-Edit/(?P<pk>[\w.@+-]+)/$',
        view=views.MainEditView.as_view(),
        name='child_edit'
    ),
    # url(
    #     regex=r'^export/$',
    #     view=views.ExportViewSet.as_view(),
    #     name='export'
    # ),
    url(
        regex=r'^List/$',
        view=views.MainListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^Services/Education-Assessment-Add/(?P<registry>[\w.@+-]+)/$',
        view=education_view.EducationAssessmentFormView.as_view(),
        name='service_education_assessment_add'
    ),
    url(
        regex=r'^Services/Education-Assessment-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=education_view.EducationAssessmentFormView.as_view(),
        name='service_education_assessment_edit'
    ),
    url(
        regex=r'^Services/Diagnostic-Assessment-Add/(?P<registry>[\w.@+-]+)/$',
        view=education_view.DiagnosticAssessmentFormView.as_view(),
        name='service_diagnostic_assessment_add'
    ),
    url(
        regex=r'^Services/Diagnostic-Assessment-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=education_view.DiagnosticAssessmentFormView.as_view(),
        name='service_diagnostic_assessment_edit'
    ),
    url(
        regex=r'^Services/Education-Add/(?P<registry>[\w.@+-]+)/$',
        view=education_view.EducationServiceFormView.as_view(),
        name='service_education_add'
    ),
    url(
        regex=r'^Services/Education-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=education_view.EducationServiceFormView.as_view(),
        name='service_education_edit'
    ),
    url(
        regex=r'^Services/RS-Add/(?P<registry>[\w.@+-]+)/$',
        view=education_view.EducationRSServiceFormView.as_view(),
        name='service_education_rs_add'
    ),
    url(
        regex=r'^Services/RS-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=education_view.EducationRSServiceFormView.as_view(),
        name='service_education_rs_edit'
    ),
    url(
        regex=r'^Child-Profile/(?P<pk>[\w.@+-]+)/$',
        view=views.ProfileView.as_view(),
        name='child_profile'
    ),
    url(
        regex=r'^Services/Inclusion-Add/(?P<registry>[\w.@+-]+)/$',
        view=services_view.InclusionFormView.as_view(),
        name='service_inclusion_add'
    ),
    url(
        regex=r'^Services/Inclusion-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=services_view.InclusionFormView.as_view(),
        name='service_inclusion_edit'
    ),
    url(
        regex=r'^Services/Digital-Add/(?P<registry>[\w.@+-]+)/$',
        view=services_view.DigitalFormView.as_view(),
        name='service_digital_add'
    ),
    url(
        regex=r'^Services/Digital-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=services_view.DigitalFormView.as_view(),
        name='service_digital_edit'
    ),
    url(
        regex=r'^Services/Health-Nutrition-Add/(?P<registry>[\w.@+-]+)/(?P<age>[\w.@+-]+)/$',
        view=services_view.HealthNutritionFormView.as_view(),
        name='service_health_nutrition_add'
    ),
    url(
        regex=r'^Services/Health-Nutrition-Edit/(?P<registry>[\w.@+-]+)/(?P<age>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=services_view.HealthNutritionFormView.as_view(),
        name='service_health_nutrition_edit'
    ),
    url(
        regex=r'^Services/PSS-Add/(?P<registry>[\w.@+-]+)/$',
        view=services_view.PSSFormView.as_view(),
        name='service_pss_add'
    ),
    url(
        regex=r'^Services/PSS-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=services_view.PSSFormView.as_view(),
        name='service_pss_edit'
    ),
    url(
        regex=r'^Services/Youth-Kit-Add/(?P<registry>[\w.@+-]+)/$',
        view=services_view.YouthKitServiceFormView.as_view(),
        name='service_youth_kit_add'
    ),
    url(
        regex=r'^Services/Youth-Kit-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=services_view.YouthKitServiceFormView.as_view(),
        name='service_youth_kit_edit'
    ),
    url(
        regex=r'^Services/Follow-Up-Add/(?P<registry>[\w.@+-]+)/$',
        view=services_view.FollowUpFormView.as_view(),
        name='service_follow_up_add'
    ),
    url(
        regex=r'^Services/Follow-Up-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=services_view.FollowUpFormView.as_view(),
        name='service_follow_up_edit'
    ),
    url(
        regex=r'^Services/Youth-Assessment-Add/(?P<registry>[\w.@+-]+)/$',
        view=services_view.YouthAssessmentFormView.as_view(),
        name='service_youth_assessment_add'
    ),
    url(
        regex=r'^Services/Youth-Assessment-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=services_view.YouthAssessmentFormView.as_view(),
        name='service_youth_assessment_edit'
    ),
    url(
        'Outreach-Child-Search/$',
        views.outreach_child_search,
        name='outreach_child_search'
    ),
    url(
        'Outreach-Child/$',
        views.outreach_child,
        name='outreach_child'
    ),
    url(
        regex=r'^Referral-Add/(?P<registry>[\w.@+-]+)/$',
        view=views.ReferralFormView.as_view(),
        name='referral_add'
    ),
    url(
        regex=r'^Referral-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=views.ReferralFormView.as_view(),
        name='referral_edit'
    ),
    url(
        'Old-Child-Search/$',
        views.old_child_search,
        name='old_child_search'
    ),
    url(
        'Old-Child/$',
        views.old_child,
        name='old_child'
    ),
]
