# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-27 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_age'),
        ('registrations', '0002_auto_20160819_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=45L, unique=True)),
                ('number', models.CharField(max_length=45L, unique=True)),
                ('extension', models.CharField(max_length=45L, unique=True)),
                ('type', models.CharField(blank=True, choices=[('first', 'first'), ('second', 'second'), ('other', 'Other')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteringAdult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(blank=True, max_length=64L, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64L, null=True)),
                ('father_name', models.CharField(blank=True, max_length=64L, null=True)),
                ('full_name', models.CharField(blank=True, max_length=225L, null=True)),
                ('mother_fullname', models.CharField(blank=True, max_length=64L, null=True)),
                ('mother_firstname', models.CharField(blank=True, max_length=64L, null=True)),
                ('mother_lastname', models.CharField(blank=True, max_length=64L, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('birthday_year', models.CharField(blank=True, choices=[(b'1990', 1990), (b'1991', 1991), (b'1992', 1992), (b'1993', 1993), (b'1994', 1994), (b'1995', 1995), (b'1996', 1996), (b'1997', 1997), (b'1998', 1998), (b'1999', 1999), (b'2000', 2000), (b'2001', 2001), (b'2002', 2002), (b'2003', 2003), (b'2004', 2004), (b'2005', 2005), (b'2006', 2006), (b'2007', 2007), (b'2008', 2008), (b'2009', 2009), (b'2010', 2010), (b'2011', 2011), (b'2012', 2012), (b'2013', 2013), (b'2014', 2014), (b'2015', 2015), (b'2016', 2016), (b'2017', 2017), (b'2018', 2018), (b'2019', 2019), (b'2020', 2020), (b'2021', 2021), (b'2022', 2022), (b'2023', 2023), (b'2024', 2024), (b'2025', 2025), (b'2026', 2026), (b'2027', 2027), (b'2028', 2028), (b'2029', 2029), (b'2030', 2030), (b'2031', 2031), (b'2032', 2032), (b'2033', 2033), (b'2034', 2034), (b'2035', 2035), (b'2036', 2036), (b'2037', 2037), (b'2038', 2038), (b'2039', 2039), (b'2040', 2040), (b'2041', 2041), (b'2042', 2042), (b'2043', 2043), (b'2044', 2044), (b'2045', 2045), (b'2046', 2046), (b'2047', 2047), (b'2048', 2048), (b'2049', 2049), (b'2050', 2050)], max_length=4, null=True)),
                ('birthday_month', models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12)], max_length=2, null=True)),
                ('birthday_day', models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30), (b'31', 31), (b'32', 32)], max_length=2, null=True)),
                ('age', models.CharField(blank=True, max_length=4L, null=True)),
                ('phone', models.CharField(blank=True, max_length=64L, null=True)),
                ('id_number', models.CharField(blank=True, max_length=45L, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=45L, null=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending')], max_length=50, null=True)),
                ('previously_registered', models.BooleanField(default=False)),
                ('relation_to_child', models.CharField(choices=[('head', 'Household Head'), ('spouse', 'Spouse'), ('parent', 'Farther/Mother'), ('relative', 'Other Relative'), ('other', 'Other non-Relative')], max_length=50)),
                ('wfp_case_number', models.CharField(blank=True, max_length=50, null=True)),
                ('csc_case_number', models.CharField(blank=True, max_length=50, null=True)),
                ('card_issue_requested', models.BooleanField(default=False)),
                ('child_enrolled_in_this_school', models.PositiveIntegerField()),
                ('child_enrolled_in_other_schools', models.PositiveIntegerField()),
                ('id_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.IDType')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Nationality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='enrolled_last_year',
            field=models.CharField(blank=True, choices=[('no', '\u0644\u0627'), ('second', 'Yes - in 2nd shift'), ('first', 'Yes - in 1st shift'), ('private', 'Yes - in private school'), ('other', 'Yes - in another type of school')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='relation_to_adult',
            field=models.CharField(blank=True, choices=[('child', 'Son/Daughter'), ('grandchild', 'Grandchild'), ('nibling', 'Niece/Nephew'), ('relative', 'Other Relative'), ('other', 'Other non-Relative')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='adult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='registrations.RegisteringAdult'),
        ),
    ]
