# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('registrations', '0004_registration_registering_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School'),
        ),
    ]
