# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_registeringadult_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='primary_phone_answered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='secondary_phone_ansewered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
