# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20160830_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeringadult',
            old_name='secondary_phone_ansewered',
            new_name='secondary_phone_answered',
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
