# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_auto_20160830_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeringadult',
            name='child_enrolled_in_other_schools',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
