# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_auto_20160831_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeringadult',
            old_name='relation_to_child',
            new_name='relation_to_householdhead',
        ),
    ]
