# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_auto_20160901_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeringadult',
            name='child_enrolled_in_this_school',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='relation_to_householdhead',
            field=models.CharField(blank=True, choices=[('head', 'Household Head'), ('spouse', 'Spouse'), ('parent', 'Farther/Mother'), ('relative', 'Other Relative'), ('other', 'Other non-Relative')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='status',
            field=models.BooleanField(),
        ),
    ]
