# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_auto_20160901_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeringadult',
            name='number',
            field=models.CharField(blank=True, max_length=45L, null=True),
        ),
    ]
