# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_auto_20160901_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='previously_registered_status',
            field=models.BooleanField(default=False),
        ),
    ]
