# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_registeringadult_previously_registered_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeringadult',
            name='primary_phone_answered',
            field=models.CharField(blank=True, choices=[('me', 'Me personally'), ('relay', 'Someone who always relays the message to me'), ('notrelay', 'Someone who may not relay the message to me')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='relation_to_householdhead',
            field=models.CharField(blank=True, choices=[('head', 'I am the household head'), ('spouse', 'Spouse'), ('parent', 'Father/Mother'), ('relative', 'Other Relative'), ('other', 'Other non-Relative')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='secondary_phone_answered',
            field=models.CharField(blank=True, choices=[('me', 'Me personally'), ('relay', 'Someone who always relays the message to me'), ('notrelay', 'Someone who may not relay the message to me')], max_length=50, null=True),
        ),
    ]
