# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_auto_20160905_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='out_of_school_tow_years',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='related_to_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
