# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('registrations', '0017_auto_20160916_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='enrolled_last_year_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='enrolled_last_year_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School'),
        ),
    ]
