# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_auto_20160916_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='enrolled_last_year_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registering_adult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='registrations.RegisteringAdult'),
        ),
    ]
