# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_auto_20160916_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='previously_registered_number',
            field=models.CharField(blank=True, max_length=45L, null=True),
        ),
    ]
