# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20160920_2201'),
        ('registrations', '0020_registeringadult_previously_registered_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='mother_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Nationality'),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Nationality'),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='primary_phone_answered',
            field=models.CharField(blank=True, choices=[('me', '\u0623\u0646\u0627 \u0634\u062e\u0635\u064a\u0627'), ('relay', '\u0634\u062e\u0635 \u062f\u0627\u0626\u0645\u0627 \u064a\u0648\u0635\u0644 \u0627\u0644\u0631\u0633\u0627\u0644\u0629 \u0644\u064a'), ('notrelay', '\u0634\u062e\u0635 \u0645\u0627 \u0642\u062f \u0644\u0627 \u064a\u0648\u0635\u0644 \u0627\u0644\u0631\u0633\u0627\u0644\u0629 \u0644\u064a')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='relation_to_householdhead',
            field=models.CharField(blank=True, choices=[('head', '\u0623\u0646\u0627 \u0631\u0628 \u0627\u0644\u0623\u0633\u0631\u0629'), ('spouse', '\u0627\u0644\u0632\u0648\u062c\u0629'), ('parent', '\u0627\u0644\u0623\u0645/\u0627\u0644\u0623\u0628'), ('relative', '\u0623\u0642\u0627\u0631\u0628'), ('other', '\u0644\u064a\u0633 \u0645\u0646 \u0627\u0644\u0623\u0642\u0627\u0631\u0628')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='secondary_phone_answered',
            field=models.CharField(blank=True, choices=[('me', '\u0623\u0646\u0627 \u0634\u062e\u0635\u064a\u0627'), ('relay', '\u0634\u062e\u0635 \u062f\u0627\u0626\u0645\u0627 \u064a\u0648\u0635\u0644 \u0627\u0644\u0631\u0633\u0627\u0644\u0629 \u0644\u064a'), ('notrelay', '\u0634\u062e\u0635 \u0645\u0627 \u0642\u062f \u0644\u0627 \u064a\u0648\u0635\u0644 \u0627\u0644\u0631\u0633\u0627\u0644\u0629 \u0644\u064a')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', '\u0630\u0643\u0631'), ('Female', '\u0627\u0646\u062b\u0649')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='enrolled_last_year',
            field=models.CharField(blank=True, choices=[('no', '\u0643\u0644\u0627'), ('second', '\u0646\u0639\u0645 - \u0641\u064a \u062f\u0648\u0627\u0645 \u0628\u0639\u062f \u0627\u0644\u0638\u0647\u0631'), ('first', '\u0646\u0639\u0645 - \u0641\u064a \u062f\u0648\u0627\u0645 \u0627\u0644\u0635\u0628\u0627\u062d\u064a'), ('private', '\u0646\u0639\u0645 - \u0641\u064a \u0645\u062f\u0631\u0633\u0629 \u062e\u0627\u0635\u0629'), ('other', '\u0646\u0639\u0645 - \u0641\u064a \u0646\u0648\u0639 \u0622\u062e\u0631 \u0645\u0646 \u0627\u0644\u0645\u062f\u0627\u0631\u0633')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='relation_to_adult',
            field=models.CharField(blank=True, choices=[('child', '\u0627\u0628\u0646/\u0627\u0628\u0646\u0629'), ('grandchild', '\u062d\u0641\u064a\u062f'), ('nibling', '\u0627\u0628\u0646\u0629/\u0625\u0628\u0646 \u0623\u062e\u064a'), ('relative', '\u0623\u0642\u0627\u0631\u0628'), ('other', '\u0644\u064a\u0633 \u0645\u0646 \u0627\u0644\u0623\u0642\u0627\u0631\u0628')], max_length=50, null=True),
        ),
    ]
