# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0022_auto_20160930_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_year_result',
            field=models.CharField(blank=True, choices=[('graduated', 'Graduated'), ('failed', 'Failed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='result',
            field=models.CharField(blank=True, choices=[('graduated', 'Graduated'), ('failed', 'Failed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.ClassRoom'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Grade'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Section'),
        ),
    ]
