# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20161002_2337'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
        ('registrations', '0023_registration_enrolled_in_this_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(blank=True, max_length=64L, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64L, null=True)),
                ('father_name', models.CharField(blank=True, max_length=64L, null=True)),
                ('unhcr_id', models.CharField(max_length=15L)),
                ('number_of_children', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15L)),
                ('alternate_phone_number', models.CharField(max_length=15L)),
                ('village', models.CharField(max_length=50L)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.Location')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
