# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0024_waitinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=15L, null=True),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15L, null=True),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='unhcr_id',
            field=models.CharField(blank=True, max_length=15L, null=True),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='village',
            field=models.CharField(blank=True, max_length=50L, null=True),
        ),
    ]
