# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0024_merge'),
        ('registrations', '0025_auto_20161012_2244'),
    ]

    operations = [
    ]
