# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-15 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0027_auto_20161013_1543'),
        ('registrations', '0026_auto_20161014_1635'),
    ]

    operations = [
    ]
