# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20161020_1312'),
        ('registrations', '0028_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='phone_prefix',
            field=models.CharField(blank=True, max_length=10L, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='registered_in_unhcr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.ClassRoom'),
        ),
    ]
