# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0038_auto_20161021_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='participated_in_alp',
            field=models.CharField(blank=True, choices=[('yes', '\u0646\u0639\u0645'), ('no', '\u0643\u0644\u0627')], max_length=50, null=True),
        ),
    ]
