# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0039_auto_20161021_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='last_informal_edu_result',
            field=models.CharField(blank=True, choices=[('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_year_result',
            field=models.CharField(blank=True, choices=[('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='result',
            field=models.CharField(blank=True, choices=[('graduated', '\u0646\u0627\u062c\u062d/\u0629'), ('failed', '\u0645\u0639\u064a\u062f/\u0629')], max_length=50, null=True),
        ),
    ]
