# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0040_auto_20161027_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255L, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.CharField(blank=True, max_length=255L, null=True)),
                ('wfp_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['wfp_date'],
            },
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='old_id_number',
            field=models.CharField(blank=True, max_length=45L, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='old_id_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statuslog',
            name='adult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='registrations.RegisteringAdult'),
        ),
        migrations.AddField(
            model_name='statuslog',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='registrations.MessageType'),
        ),
    ]
