# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-05 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0045_auto_20161205_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_list_number', models.IntegerField(blank=True, null=True)),
                ('payment_amount', models.IntegerField(blank=True, null=True)),
                ('payment_month', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='batch_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='card_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_adult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='registrations.RegisteringAdult'),
        ),
    ]
