# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20161207_1610'),
        ('registrations', '0048_registeringadult_old_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_changed_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='school_changed_to_verify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School'),
        ),
    ]
