# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-08 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0049_auto_20170207_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='card_last_four_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
