# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-09 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0050_registeringadult_card_last_four_digits'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryChangedReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64L, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Main Reason',
            },
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_changed_father_name',
            field=models.CharField(blank=True, max_length=64L, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_changed_first_name',
            field=models.CharField(blank=True, max_length=64L, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_changed_last_name',
            field=models.CharField(blank=True, max_length=64L, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_changed_relation_to_householdhead',
            field=models.CharField(blank=True, choices=[('head', '\u0623\u0646\u0627 \u0631\u0628 \u0627\u0644\u0623\u0633\u0631\u0629'), ('spouse', '\u0627\u0644\u0632\u0648\u062c\u0629'), ('parent', '\u0627\u0644\u0623\u0645/\u0627\u0644\u0623\u0628'), ('relative', '\u0623\u0642\u0627\u0631\u0628'), ('other', '\u0644\u064a\u0633 \u0645\u0646 \u0627\u0644\u0623\u0642\u0627\u0631\u0628')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_changed_same_as_caller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_changed_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='registrations.BeneficiaryChangedReason'),
        ),
    ]
