# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-09 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0052_registeringadult_card_distribution_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64L, unique=True)),
                ('complaint_type', models.CharField(blank=True, choices=[('card', 'ATM Card'), ('payment', 'Payment')], max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Main Reason',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('complaint_note', models.TextField(blank=True, null=True)),
                ('complaint_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='registrations.ComplaintCategory')),
                ('complaint_adult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='registrations.RegisteringAdult')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
