# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0055_auto_20170209_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_adult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registrations.RegisteringAdult'),
        ),
    ]
