# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0058_auto_20170213_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registeringadult',
            name='beneficiary_changed_birthday_day',
            field=models.CharField(blank=True, choices=[(b'1', 1), (b'2', 2), (b'3', 3), (b'4', 4), (b'5', 5), (b'6', 6), (b'7', 7), (b'8', 8), (b'9', 9), (b'10', 10), (b'11', 11), (b'12', 12), (b'13', 13), (b'14', 14), (b'15', 15), (b'16', 16), (b'17', 17), (b'18', 18), (b'19', 19), (b'20', 20), (b'21', 21), (b'22', 22), (b'23', 23), (b'24', 24), (b'25', 25), (b'26', 26), (b'27', 27), (b'28', 28), (b'29', 29), (b'30', 30)], default=0, max_length=2, null=True),
        ),
    ]
