# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0059_auto_20170214_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_changed_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
