# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-15 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0060_registeringadult_beneficiary_changed_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='household_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
