# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-15 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0063_auto_20170215_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='omplaint_status',
            new_name='complaint_status',
        ),
    ]
