# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-17 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0058_auto_20170216_1125'),
        ('registrations', '0067_auto_20170216_1601'),
    ]

    operations = [
    ]
