# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0069_auto_20170217_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_bank_date_of_incident',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_bank_phone_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_bank_service_requested',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_bank_time_of_incident',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
