# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0070_auto_20170220_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_specify_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
