# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-20 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0071_registeringadult_beneficiary_specify_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_bank_time_of_incident',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_bank_date_of_incident',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
