# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-21 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_idtype_inuse'),
        ('registrations', '0072_auto_20170220_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_student_refused_entrance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='students.Student'),
        ),
    ]
