# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0073_complaint_complaint_student_refused_entrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_Other_type_specify',
            field=models.TextField(blank=True, null=True),
        ),
    ]
