# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-07 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0077_auto_20170307_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='registrations.ComplaintCategory'),
        ),
    ]
