# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-10 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0078_complaint_complaint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdnotfound',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='householdnotfound',
            name='primary_phone_answered',
            field=models.CharField(blank=True, choices=[('me', '\u0623\u0646\u0627 \u0634\u062e\u0635\u064a\u0627'), ('relay', '\u0634\u062e\u0635 \u062f\u0627\u0626\u0645\u0627 \u064a\u0648\u0635\u0644 \u0627\u0644\u0631\u0633\u0627\u0644\u0629 \u0644\u064a'), ('notrelay', '\u0634\u062e\u0635 \u0645\u0627 \u0642\u062f \u0644\u0627 \u064a\u0648\u0635\u0644 \u0627\u0644\u0631\u0633\u0627\u0644\u0629 \u0644\u064a')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='householdnotfound',
            name='relation_to_householdhead',
            field=models.CharField(blank=True, choices=[('head', '\u0623\u0646\u0627 \u0631\u0628 \u0627\u0644\u0623\u0633\u0631\u0629'), ('spouse', '\u0627\u0644\u0632\u0648\u062c\u0629'), ('parent', '\u0627\u0644\u0623\u0645/\u0627\u0644\u0623\u0628'), ('relative', '\u0623\u0642\u0627\u0631\u0628'), ('other', '\u0644\u064a\u0633 \u0645\u0646 \u0627\u0644\u0623\u0642\u0627\u0631\u0628')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='householdnotfound',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='householdnotfound',
            name='secondary_phone_answered',
            field=models.CharField(blank=True, choices=[('me', '\u0623\u0646\u0627 \u0634\u062e\u0635\u064a\u0627'), ('relay', '\u0634\u062e\u0635 \u062f\u0627\u0626\u0645\u0627 \u064a\u0648\u0635\u0644 \u0627\u0644\u0631\u0633\u0627\u0644\u0629 \u0644\u064a'), ('notrelay', '\u0634\u062e\u0635 \u0645\u0627 \u0642\u062f \u0644\u0627 \u064a\u0648\u0635\u0644 \u0627\u0644\u0631\u0633\u0627\u0644\u0629 \u0644\u064a')], max_length=50, null=True),
        ),
    ]
