# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0079_auto_20170310_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotEligibleReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64L, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Main Reason',
            },
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='no_logner_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='no_logner_eligible_specify',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='no_logner_eligible_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='registrations.NotEligibleReason'),
        ),
    ]
