# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-22 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0081_registeringadult_no_logner_eligible_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_changed_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_changed_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
