# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-22 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0082_auto_20170322_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeringadult',
            name='beneficiary_changed_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
