# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-22 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0083_auto_20170322_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='school_changed_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='school_changed_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=50, null=True),
        ),
    ]
