# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0085_auto_20170323_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='beneficiary_changed_date_requested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='duplicate_card_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='household_suspended_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='no_logner_eligible_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='phone_update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
