# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-24 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0087_auto_20170419_1619'),
        ('registrations', '0089_auto_20170419_1023'),
    ]

    operations = [
    ]
