# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-03 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0089_auto_20170419_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintcategory',
            name='complaint_type',
            field=models.CharField(blank=True, choices=[('distribution', 'CARD DISTRIBUTION'), ('card', 'CARD'), ('payment', 'PAYMENT'), ('school', 'SCHOOL-RELATED'), ('reinstate', 'REINSTATE BENEFICIARY'), ('remove', 'reinstate beneficiary'), ('bank', 'BANK'), ('other', 'OTHER'), ('student', 'Missing Student')], max_length=50, null=True),
        ),
    ]
