# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0090_auto_20170503_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdnotfound',
            name='id_number_duplicate',
            field=models.CharField(blank=True, max_length=45L, null=True),
        ),
        migrations.AddField(
            model_name='missingchild',
            name='id_number_duplicate',
            field=models.CharField(blank=True, max_length=45L, null=True),
        ),
        migrations.AddField(
            model_name='registeringadult',
            name='id_number_duplicate',
            field=models.CharField(blank=True, max_length=45L, null=True),
        ),
    ]
