# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0091_auto_20170509_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeringadult',
            name='red_case_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
