# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-11 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0091_merge'),
        ('registrations', '0092_registeringadult_red_case_number'),
    ]

    operations = [
    ]
