# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-18 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0093_registeringadult_household_suspended_reason'),
        ('registrations', '0093_merge'),
    ]

    operations = [
    ]
