# Generated by Django 5.2.7 on 2026-10-01 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("child", "0020_child_unicef_id_new"),
        ("locations", "0033_alter_center_type"),
        ("mscc", "0103_referral_public_school"),
        ("schools", "0167_publicschool"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlagSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "absence_streak",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="Flag A1: class days absent in a row"
                    ),
                ),
                (
                    "attendance_window_days",
                    models.PositiveSmallIntegerField(
                        default=28,
                        help_text="Flag A2: the period of the attendance rate, in calendar days",
                    ),
                ),
                (
                    "attendance_min_days",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="Flag A2: class days recorded in that period before the rate counts",
                    ),
                ),
                (
                    "attendance_rate_below",
                    models.PositiveSmallIntegerField(
                        default=70,
                        help_text="Flag A2: attendance rate under this percentage",
                    ),
                ),
                (
                    "drop_recent_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        help_text="Flag A3: the recent period, in calendar days",
                    ),
                ),
                (
                    "drop_previous_days",
                    models.PositiveSmallIntegerField(
                        default=28,
                        help_text="Flag A3: the period before it, in calendar days",
                    ),
                ),
                (
                    "drop_points",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Flag A3: drop of the attendance rate, in percentage points",
                    ),
                ),
                (
                    "service_weeks",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="Flag S1: weeks after joining the round for the required services",
                    ),
                ),
                (
                    "followup_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="Follow-up expected within this many days of a flag (centre summaries)",
                    ),
                ),
                (
                    "all_present_min_children",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="An attendance sheet with at least this many children, all present, is treated as not filled in: it counts neither as present nor absent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flag settings",
                "verbose_name_plural": "Flag settings",
            },
        ),
        migrations.CreateModel(
            name="CenterSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(help_text="first day of the month")),
                ("figures", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="locations.center",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="schools.partnerorganization",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="mscc.round",
                    ),
                ),
            ],
            options={
                "ordering": ["-month", "center__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("center", "round", "month"),
                        name="wellbeing_summary_month",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("A1", "Absent several class days in a row"),
                            ("A2", "Low attendance"),
                            ("A3", "Attendance dropped"),
                            ("S1", "Required service not received"),
                            ("D1", "Dropout without follow-up"),
                            ("H1", "Malnutrition screened, not referred"),
                            ("H2", "Developmental delay identified, not referred"),
                            ("P1", "Protection concern recorded, not referred"),
                            ("L1", "No learning progress between tests"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("followed_up", "Followed up"),
                            ("resolved", "Resolved by itself"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                (
                    "urgent",
                    models.BooleanField(
                        default=False,
                        help_text="e.g. suicidal ideation or severe malnutrition",
                    ),
                ),
                (
                    "priority",
                    models.BooleanField(
                        default=False,
                        help_text="the child also works, lives without parents or has a disability",
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="why the flag was raised, in words"),
                ),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "as_of",
                    models.DateField(
                        help_text="date of the latest data behind the flag"
                    ),
                ),
                ("opened_on", models.DateField()),
                ("last_seen_on", models.DateField()),
                ("followed_up_on", models.DateField(blank=True, null=True)),
                ("follow_up_type", models.CharField(blank=True, max_length=40)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "reached_returning",
                                "Child/caregiver reached: child is returning or continuing",
                            ),
                            (
                                "reached_support",
                                "Child/caregiver reached: extra support planned at the centre",
                            ),
                            (
                                "referred",
                                "Referred to a specialised service (CP, health, other)",
                            ),
                            (
                                "already_handled",
                                "Already handled (referral or follow-up done, not recorded)",
                            ),
                            ("not_reached", "Could not reach the child or caregiver"),
                            ("dropped_out", "Child has left the programme"),
                            ("not_needed", "Not needed: the data was wrong"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("resolved_on", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="locations.center",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="child.child",
                    ),
                ),
                (
                    "followed_up_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="schools.partnerorganization",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="mscc.registration",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="mscc.round",
                    ),
                ),
            ],
            options={
                "ordering": ["-urgent", "-priority", "opened_on", "id"],
                "indexes": [
                    models.Index(
                        fields=["center", "status"],
                        name="wellbeing_f_center__c0c2fd_idx",
                    ),
                    models.Index(
                        fields=["partner", "status"],
                        name="wellbeing_f_partner_2879e3_idx",
                    ),
                    models.Index(
                        fields=["registration", "kind"],
                        name="wellbeing_f_registr_b12361_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("registration", "kind"),
                        name="wellbeing_one_open_flag_per_kind",
                    )
                ],
            },
        ),
    ]
