# Generated by Django 5.2.7 on 2026-10-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellbeing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flag",
            name="followed_up_by_name",
            field=models.CharField(
                blank=True,
                help_text="who recorded the follow-up in NeuroDB",
                max_length=150,
            ),
        ),
    ]
