# Generated by Django 5.2.7 on 2026-10-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellbeing", "0002_follow_up_by_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="WellbeingRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "center_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="empty: every centre"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("requested_by", models.CharField(blank=True, max_length=150)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("totals", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-requested_at",),
            },
        ),
    ]
