# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-06-25 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adolescent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescent',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Registered youth Home Address'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clm.Disability', verbose_name='Does the youth have any disability or special need?'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='id_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.IDType', verbose_name='Youth ID type'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='individual_case_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Youth individual ID'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='individual_case_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Youth individual ID confirm'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='main_caregiver',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Mother', 'Mother'), ('Father', 'Father'), ('Other', 'Other')], max_length=100, null=True, verbose_name='who is the youth primary caregiver?'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Youth Lebanese ID number'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Youth Lebanese ID number'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='other_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID number of the youth'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='other_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID number of the youth confirm'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='sop_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Youth Palestinian ID number'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='sop_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Youth Palestinian ID number confirm'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='syrian_national_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Youth Syrian ID number'),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='syrian_national_number_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Youth Syrian ID number confirm'),
        ),
    ]
