# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-04-30 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescent', '0003_auto_20250217_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescent',
            name='unicef_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
