# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-05-29 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescent', '0004_adolescent_unicef_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescent',
            name='unrwa_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UNRWA Case number'),
        ),
    ]
