# Generated by Django 5.2.3 on 2026-02-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adolescent', '0006_alter_adolescent_cadaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescent',
            name='unicef_id_backup',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
