from __future__ import absolute_import, unicode_literals

from django.urls import re_path

from . import views, program_view, services_view

app_name = 'youth'

urlpatterns = [

    re_path(
        r'^child-add/$',
        view=views.MainAddView.as_view(),
        name='child_add'
    ),
    re_path(
        r'^child-edit/(?P<pk>[\w.@+-]+)/$',
        view=views.MainEditView.as_view(),
        name='child_edit'
    ),
    re_path(
        r'^child-mark-delete/(?P<pk>[\w.@+-]+)/$',
        view=views.main_mark_delete_view,
        name='child_mark_deleted'
    ),
    re_path(
        r'^export/$',
        view=views.export_data,
        name='export'
    ),
    re_path(
        r'^export-pd/$',
        view=views.export_pd_data,
        name='export_pd'
    ),
    re_path(
        r'^list/$',
        view=views.MainListView.as_view(),
        name='list'
    ),
    re_path(
        r'^pd-list/$',
        view=views.PDListView.as_view(),
        name='pd_list'
    ),
    re_path(
        r'^pd-add/$',
        view=views.PDListView.as_view(),
        name='pd_add'
    ),
    re_path(
        r'^program/enrolled-programs-add/(?P<registry>[\w.@+-]+)/$',
        view=program_view.EnrolledProgramsFormView.as_view(),
        name='program_enrolled_programs_add'
    ),
    re_path(
        r'^program/enrolled-programs-edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=program_view.EnrolledProgramsFormView.as_view(),
        name='program_enrolled_programs_edit'
    ),
    re_path(
        r'^program/program-document-add/$',
        view=program_view.ProgramDocumentFormView.as_view(),
        name='program_program_document_add'
    ),
    re_path(
        r'^program/program-document-edit/(?P<pk>[\w.@+-]+)/$',
        view=program_view.ProgramDocumentFormView.as_view(),
        name='program_program_document_edit'
    ),
    re_path(
        r'^child-profile/(?P<pk>[\w.@+-]+)/$',
        view=views.ProfileView.as_view(),
        name='child_profile'
    ),
    re_path(
        r'^Services/Youth-Assessment-Add/(?P<registry>[\w.@+-]+)/$',
        view=services_view.YouthAssessmentFormView.as_view(),
        name='service_youth_assessment_add'
    ),
    re_path(
        r'^Services/Youth-Assessment-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=services_view.YouthAssessmentFormView.as_view(),
        name='service_youth_assessment_edit'
    ),
    re_path(
        r'^outreach-child-search/$',
        views.outreach_child_search,
        name='outreach_child_search'
    ),
    re_path(
        r'^outreach-child/$',
        views.outreach_child,
        name='outreach_child'
    ),
    re_path(
        r'^old-child-search/$',
        views.old_child_search,
        name='old_child_search'
    ),
    re_path(
        r'^get-old-child-data/$',
        views.old_child_data,
        name='old_child_data'
    ),
    re_path(
        r'^child-duplication-check/$',
        views.child_duplication_check,
        name='child_duplication_check'
    ),
    re_path(
        r'^quick-search/$',
        views.quick_search,
        name='quick_search'
    ),
    re_path(
        r'^child-profile-preview/$',
        view=views.ChildProfilePreview.as_view(),
        name='child_profile_preview'
    ),
    re_path(
        r'^child-registration-cancel/(?P<pk>[\w.@+-]+)/$',
        view=views.main_registration_cancel_view,
        name='child_registration_cancel'
    ),
    re_path(
        'load-districts/$',
        views.load_districts,
        name='load_districts'
    ),
    re_path(
        'load-cadasters/$',
        views.load_cadasters,
        name='load_cadasters'
    ),

    re_path(
        'load-program-document/$',
        views.load_program_document,
        name='load_program_document'
    ),
    re_path(
        'load-master-program/$',
        views.load_master_program,
        name='load_master_program'
    ),
    re_path(
        'load-subr-program/$',
        views.load_sub_program,
        name='load_sub_program'
    ),
    re_path(
        r'^Program/Program-Document-Indicators/(?P<program_document_id>[\w.@+-]+)/$',
        view=views.program_document_indicators_view,
        name='program_document_indicators'
    ),
    re_path(
        r'^Program/Program-Document-Indicator-List/(?P<program_document_id>[\w.@+-]+)/$',
        view=views.program_document_indicator_list_view,
        name='program_document_indicator_list'
    ),
    re_path(
        r'^Program/Program-Document-Indicators-Save/$',
        view=views.save_indicators,
        name='program_document_indicators_save'
    ),

]
