from __future__ import absolute_import, unicode_literals

from django.urls import re_path

from . import views, program_view, services_view

app_name = 'youth'

urlpatterns = [

    re_path(
        r'^Child-Add/$',
        view=views.MainAddView.as_view(),
        name='child_add'
    ),
    re_path(
        r'^Child-Edit/(?P<pk>[\w.@+-]+)/$',
        view=views.MainEditView.as_view(),
        name='child_edit'
    ),
    re_path(
        r'^Child-Mark-Delete/(?P<pk>[\w.@+-]+)/$',
        view=views.MainMarkDeleteView,
        name='child_mark_deleted'
    ),
    re_path(
        r'^export/$',
        view=views.export_data,
        name='export'
    ),
    re_path(
        r'^export-pd/$',
        view=views.export_pd_data,
        name='export_pd'
    ),
    re_path(
        r'^List/$',
        view=views.MainListView.as_view(),
        name='list'
    ),
    re_path(
        r'^PD-List/$',
        view=views.PDListView.as_view(),
        name='pd_list'
    ),
    re_path(
        r'^PD-Add/$',
        view=views.PDListView.as_view(),
        name='pd_add'
    ),
    re_path(
        r'^Program/Enrolled-Programs-Add/(?P<registry>[\w.@+-]+)/$',
        view=program_view.EnrolledProgramsFormView.as_view(),
        name='program_enrolled_programs_add'
    ),
    re_path(
        r'^Program/Enrolled-Programs-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=program_view.EnrolledProgramsFormView.as_view(),
        name='program_enrolled_programs_edit'
    ),
    re_path(
        r'^Program/Program-Document-Add/$',
        view=program_view.ProgramDocumentFormView.as_view(),
        name='program_program_document_add'
    ),
    re_path(
        r'^Program/Program-Document-Edit/(?P<pk>[\w.@+-]+)/$',
        view=program_view.ProgramDocumentFormView.as_view(),
        name='program_program_document_edit'
    ),
    re_path(
        r'^Child-Profile/(?P<pk>[\w.@+-]+)/$',
        view=views.ProfileView.as_view(),
        name='child_profile'
    ),
    re_path(
        r'^Services/Youth-Assessment-Add/(?P<registry>[\w.@+-]+)/$',
        view=services_view.YouthAssessmentFormView.as_view(),
        name='service_youth_assessment_add'
    ),
    re_path(
        r'^Services/Youth-Assessment-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=services_view.YouthAssessmentFormView.as_view(),
        name='service_youth_assessment_edit'
    ),
    re_path(
        'Outreach-Child-Search/$',
        views.outreach_child_search,
        name='outreach_child_search'
    ),
    re_path(
        'Outreach-Child/$',
        views.outreach_child,
        name='outreach_child'
    ),
    re_path(
        'Old-Child-Search/$',
        views.old_child_search,
        name='old_child_search'
    ),
    re_path(
        'Get-Old-Child-Data/$',
        views.old_child_data,
        name='old_child_data'
    ),
    re_path(
        'Child-Duplication-Check/$',
        views.child_duplication_check,
        name='child_duplication_check'
    ),
    re_path(
        'Quick-Search/$',
        views.quick_search,
        name='quick_search'
    ),
    re_path(
        'Child-Profile-Preview/$',
        view=views.ChildProfilePreview.as_view(),
        name='child_profile_preview'
    ),
    re_path(
        r'^Child-Registration-Cancel/(?P<pk>[\w.@+-]+)/$',
        view=views.MainRegistrationCancelView,
        name='child_registration_cancel'
    ),
    re_path(
        'load-districts/$',
        views.load_districts,
        name='load_districts'
    ),
    re_path(
        'load-cadasters/$',
        views.load_cadasters,
        name='load_cadasters'
    ),

    re_path(
        'load-program-document/$',
        views.load_program_document,
        name='load_program_document'
    ),
    re_path(
        'load-master-program/$',
        views.load_master_program,
        name='load_master_program'
    ),
    re_path(
        'load-subr-program/$',
        views.load_sub_program,
        name='load_sub_program'
    ),
]
