from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views, education_view, services_view

urlpatterns = [

    url(
        regex=r'^Child-Add/$',
        view=views.MainAddView.as_view(),
        name='child_add'
    ),
    url(
        regex=r'^Child-Edit/(?P<pk>[\w.@+-]+)/$',
        view=views.MainEditView.as_view(),
        name='child_edit'
    ),
    url(
        regex=r'^New-Round/(?P<pk>[\w.@+-]+)/$',
        view=views.NewRoundView.as_view(),
        name='new_round'
    ),
    url(
        regex=r'^New-Round-Redirect/$',
        view=views.NewRoundRedirectView.as_view(),
        name='new_round_redirect'
    ),
    url(
        regex=r'^Child-Mark-Delete/(?P<pk>[\w.@+-]+)/$',
        view=views.MainMarkDeleteView,
        name='child_mark_deleted'
    ),
    url(
        regex=r'^export/$',
        view=views.export_data,
        name='export'
    ),
    url(
        regex=r'^List/$',
        view=views.MainListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^PD-List/$',
        view=views.PDListView.as_view(),
        name='pd_list'
    ),
    url(
        regex=r'^PD-Add/$',
        view=views.PDListView.as_view(),
        name='pd_add'
    ),
    url(
        regex=r'^Services/Enrolled-Programs-Add/(?P<registry>[\w.@+-]+)/$',
        view=education_view.EnrolledProgramsFormView.as_view(),
        name='service_enrolled_programs_add'
    ),
    url(
        regex=r'^Services/Enrolled-Programs-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=education_view.EnrolledProgramsFormView.as_view(),
        name='service_enrolled_programs_edit'
    ),
    url(
        regex=r'^Child-Profile/(?P<pk>[\w.@+-]+)/$',
        view=views.ProfileView.as_view(),
        name='child_profile'
    ),
    url(
        regex=r'^Services/Youth-Assessment-Add/(?P<registry>[\w.@+-]+)/$',
        view=services_view.YouthAssessmentFormView.as_view(),
        name='service_youth_assessment_add'
    ),
    url(
        regex=r'^Services/Youth-Assessment-Edit/(?P<registry>[\w.@+-]+)/(?P<pk>[\w.@+-]+)/$',
        view=services_view.YouthAssessmentFormView.as_view(),
        name='service_youth_assessment_edit'
    ),
    url(
        'Outreach-Child-Search/$',
        views.outreach_child_search,
        name='outreach_child_search'
    ),
    url(
        'Outreach-Child/$',
        views.outreach_child,
        name='outreach_child'
    ),
    url(
        'Old-Child-Search/$',
        views.old_child_search,
        name='old_child_search'
    ),
    url(
        'Get-Old-Child-Data/$',
        views.old_child_data,
        name='old_child_data'
    ),
    url(
        'Child-Duplication-Check/$',
        views.child_duplication_check,
        name='child_duplication_check'
    ),
    url(
        'Quick-Search/$',
        views.quick_search,
        name='quick_search'
    ),
    url(
        'Child-Profile-Preview/$',
        view=views.ChildProfilePreview.as_view(),
        name='child_profile_preview'
    ),
    url(
        regex=r'^Child-Registration-Cancel/(?P<pk>[\w.@+-]+)/$',
        view=views.MainRegistrationCancelView,
        name='child_registration_cancel'
    ),
]
