# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-08 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='first_phone_owner',
            field=models.CharField(choices=[('', '----------'), ('Phone Main Caregiver', 'Phone Main Caregiver'), ('Family Member', 'Family Member'), ('Neighbors', 'Neighbors'), ('Shawish', 'Shawish')], max_length=100, null=True, verbose_name='Who will be answering the phone?'),
        ),
        migrations.AlterField(
            model_name='child',
            name='id_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.IDType', verbose_name='Child ID type'),
        ),
        migrations.AlterField(
            model_name='child',
            name='second_phone_owner',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Phone Main Caregiver', 'Phone Main Caregiver'), ('Family Member', 'Family Member'), ('Neighbors', 'Neighbors'), ('Shawish', 'Shawish')], max_length=100, null=True, verbose_name='Who will be answering the phone'),
        ),
    ]
