# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0070_auto_20221206_1532'),
        ('child', '0002_auto_20221208_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='main_caregiver_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.Nationality', verbose_name='Caregiver Nationality'),
        ),
        migrations.AddField(
            model_name='child',
            name='main_caregiver_nationality_other',
            field=models.TextField(blank=True, null=True, verbose_name='Please specify'),
        ),
    ]
