# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2022-12-12 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_auto_20221208_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Married', 'Married'), ('Engaged', 'Engaged'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Single', 'Single')], max_length=50, null=True, verbose_name='Child\u2019s Marital Status'),
        ),
    ]
