# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-02-07 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_auto_20221213_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='child',
            name='have_children',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Does the child have children?'),
        ),
    ]
