# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-05-05 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_auto_20230207_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='fe_unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formal Education unique student ID'),
        ),
    ]
