# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-02 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0008_auto_20230602_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='children_number_under18',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=0, null=True, verbose_name='Number of children (under 18) living in the household'),
        ),
    ]
