# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-06-14 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0009_auto_20230602_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='children_number_under18',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of children (under 18) living in the household'),
        ),
    ]
