# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-08-08 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0011_auto_20230808_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='living_arrangement',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Unaccompanied', 'Unaccompanied'), ('Separated', 'Separated'), ('Living with one caregivers', 'Living with one caregivers'), ('Living with caregivers', 'Living with caregivers'), ('Child headed household ', 'Child headed household ')], max_length=50, null=True, verbose_name='Child\u2019s Living Arrangement'),
        ),
    ]
