# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-08-25 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0012_auto_20230808_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='pregnant_expecting_children',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Is the child pregnant or expecting children?'),
        ),
        migrations.AlterField(
            model_name='child',
            name='caregiver_mother_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Caregiver  Mother Full Name'),
        ),
        migrations.AlterField(
            model_name='child',
            name='living_arrangement',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Unaccompanied', 'Unaccompanied'), ('Separated', 'Separated'), ('Living with one caregivers', 'Living with one caregivers'), ('Living with caregivers', 'Living with caregivers'), ('Child headed household ', 'Child headed household'), ('Married and living with extended family', 'Married and living with extended family')], max_length=50, null=True, verbose_name='Child\u2019s Living Arrangement'),
        ),
    ]
