# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2023-08-30 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0013_auto_20230825_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='pregnant_expecting_children',
        ),
        migrations.AlterField(
            model_name='child',
            name='have_children',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Yes', 'Yes'), ('No', 'No'), ('Child pregnant or expecting children', 'Child pregnant or expecting children')], max_length=50, null=True, verbose_name='Does the child have children?'),
        ),
    ]
