# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2024-06-07 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0014_auto_20230830_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent_extract_record',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent_extract_record_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Lebanese Extract of Record confirm'),
        ),
    ]
