# Generated by Django 5.2.3 on 2025-09-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0018_auto_20250430_2102'),
        ('clm', '0278_auto_20250626_1644'),
        ('schools', '0158_auto_20250820_1259'),
        ('students', '0087_auto_20250626_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='cash_programmes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='child',
            name='disability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clm.disability', verbose_name='Does the child have any disability or special need?'),
        ),
        migrations.AlterField(
            model_name='child',
            name='father_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name="What is the father's educational level?"),
        ),
        migrations.AlterField(
            model_name='child',
            name='id_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.idtype', verbose_name='Child ID type'),
        ),
        migrations.AlterField(
            model_name='child',
            name='main_caregiver_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Caregiver Nationality'),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schools.educationallevel', verbose_name="What is the father's educational level?"),
        ),
        migrations.AlterField(
            model_name='child',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.nationality', verbose_name='Nationality'),
        ),
    ]
