# Generated by Django 5.2.3 on 2026-02-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0019_alter_child_cash_programmes_alter_child_disability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='unicef_id_backup',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Unicef ID Backup'),
        ),
    ]
