# Generated by Django 5.2.7 on 2026-10-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0020_child_unicef_id_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/mscc/profile_pictures",
                verbose_name="Profile picture",
            ),
        ),
    ]
